### ISSUE TITLE
Support retroarch shader presets

### ISSUE THREAD

**Issue by AaronBPaden** [dosbox-staging/dosbox-staging#100]
This is a nice to have for sometime after SDL 2 support is done. Pcem supports it, and I can say playing dos games with a nice CRT shader is a pretty sweet alternative for those of us who don't actually want to lug around the real thing. :)

**Comment by dreamer** [comment]
Definitely; several DOSBox forks exist dedicated *only* to bringing in nice shaders, so this is definitely a desired feature - it would also allow us to remove ugly rgb* and tv* scalers, as similar but nicer and more performant effects would be enabled via shaders. So far all forks seem to use GLSL (and this seems to be supported by SDL2 - but I haven't looked in details yet - esp, if those shared apply only to output=opengl, or can they be made available to output=texture somehow). Ideally, it would be nice if we could co-operate with developers maintaining their own forks to work together on this...

**Comment by dreamer** [comment]
OK, upstream shader support got just merged into the master branch, but it does not affect this issue - we still want to support GLSL shaders and shader presets in a retroarch format.

**Comment by kcgen** [comment]
Directly supporting retroarch shaders will only be possible by migrating from SDL2 to Retroarch.  If this every happens, then this will be an implied feature.

Otherwise if retroarch-equivalent shaders are desired, then those shaders will need to be ported - which is something outside the scope of the project. 

Closing, as currently it's not supportable or out-of-scope so long as we're on an SDL2 path.

**Comment by GranMinigun** [comment]
Some research and discussion suggested that implementing RA-style shader pipeline is possible. Reopening.

**Comment by johnnovak** [comment]
Closing with won't do as I'm not planning to implement the RA pipeline. I'm planning to do our much more focused, DOSBox specific thing.
