### ISSUE TITLE
How can I lock the mouse in the window?

### ISSUE THREAD

**Issue by Toadfield** [dosbox-staging/dosbox-staging#1000]
I tried to play quake but the problem is that when I try to move the mouse it always goes out of the window.

**Comment by kcgen** [comment]
Hi @Toadfield ,

This is called `seamless` mouse mode, which Staging defaults to using.  

Edit your config file, by running `dosbox.exe -editconf`.  In there, you can set your **capture_mouse** setting to use `onstart` instead of `seamless`. 

Then you can unlock your mouse with a middle click or ctrl+F10.

Also note that going fullscreen, with Alt+Enter, with always lock your mouse - even with seamless. So that's an option too. 

You might find many more options that you prefer over the defaults as well.

**Comment by kcgen** [comment]
(answered; closing)

**Comment by MasterO2** [comment]
@Toadfield 

Regarding Quake 1, download [Quakespasm](http://quakespasm.sourceforge.net/download.htm) and run Quake 1 in that.

Additionally, for any other DOS FPS-es from that era, find a sourceport and play them in those.

https://github.com/dosbox-staging/dosbox-staging/wiki/Sourceport-Links-for-Classic-DOS-First-Person-Shooters

**Comment by Toadfield** [comment]
@kcgen thanks
> Then you can unlock your mouse with a middle click or ctrl+F10.

Is there a way to change the hotkey for that?
Cause I want to use middle click as a button ingame and I would like it more to use something like Super+F10 more to enable/disable seemless.
> Also note that going fullscreen, with Alt+Enter, with always locks your mouse - even with seamless.

I prefer to use the borderless fullscreen option that kde supports more than actual fullscreen.
@MasterO2 
I know that it is a better idea to use a sourceport if the game I want to play got one,I just tried Quake to test the performance of 3dfx emulation (I had much lags even though my gpu and cpu didn't had much usage for some reason,is this cause dosbox is not good enough to emulate it properly or why?).
Btw I like [Quakespasm-spiked](https://fte.triptohell.info/moodles/qss/) more than Quakespasm,cause it has some really good features like extra particle effects and that mods can change the hud look,it is Quakespasm-spiked,but with more features.

**Comment by kcgen** [comment]
Inside your conf file, read about using the `middlegame` setting instead of `middlerelease`. 

If you would prefer a different hotkey to lock and unlock the mouse, you will need to use the key mapper to reassign this function.

  I suggest reading about the mapper first, as it takes a bit of understanding before it becomes intuitive (atleast that was the case for myself). 

https://www.dosbox.com/wiki/Mapper

And you might find other people writing up howto's on various forums. I'm not in front of my PC so cannot send exact steps.
