### ISSUE TITLE
How is the performance and accuracy between this fork and other dosbox forks?

### ISSUE THREAD

**Issue by Toadfield** [dosbox-staging/dosbox-staging#1002]
The normal dosbox didn't get many major updates,so that is no option.
But there are other dosbox forks,like dosbox-x.
So which dosbox fork has the best performance and accuracy?
Cause the only reason I tried this fork instead of dosbox-x is cause I have a graphic bug on dosbox-x.

**Comment by kcgen** [comment]
There's good working happening in all three!

The upstream DOSBox developers continue to refine the core emulation, which is extremely important and invaluable work. They've also merged large improvements like the x86-64 bit dynamic core and OpenGL Shaders.  These refinements and additions are often imported into DOSBox-X and Staging.  Work also flows between X and Staging, and vice-versa.  

DOSBox-X focuses on being the most accurate and all-purpose DOSBox environment - applications and gaming alike, and is surely the most feature-packed of all the forks.  If you have a graphical issue, I would suggest reporting on their project page. 

You can read about Staging's goals and our release notes here: https://github.com/dosbox-staging/dosbox-staging.  Hope that helps :-)

**Comment by kcgen** [comment]
@Toadfield, @Wengier also mentioned via email that he's been focusing on the non-gaming aspect of DOSBox-X such as DOS demos/applications, Windows 9x, and hardware-centric improvements - plus features like save-states and 3dfx, which DOSBox Staging doesn't yet support.

Thanks for this helpful clarification @Wengier, and for progressing all of these features in DOSBox-X !

**Comment by Wengier** [comment]
Yes, as @kcgen said there's good working happening in all three DOSBox versions. And there are good communications between the projects too. We had a Venn diagram in an earlier email for different DOSBox versions, and for DOSBox-X things like DOS demos/applications, hardware-centric stuff, and gaming features like save-states and 3dfx are mentioned. For me personally I mainly worked on DOS applications, DOS shell, Windows 9x, PC-98, in addition to features like 3dfx and save states not yet supported by DOSBox Staging since that Venn diagram.

**Comment by Drag0nFly** [comment]
@kcgen, @Wengier – Just to chime in quickly here as this is an interesting topic - my preferred DosBox so far when it comes to games and demos has indeed been Dosbox-staging (although many demos obviously are lacking, such as Future Crew's 2nd Reality – mainly since it used every trick in the “x86-asm book” back then;). Others also do not run well (glitches or hangs in the middle, such as Triton's Crystal Dream II)

I did not know of yet another fork, _DosBox-X_, until I saw it mentioned here. It sounds like this might yield better performance, and is definitely something I'd want to try.

Frankly, I already found that navigating the various variants gave the impression of being somewhat of a jungle. I'm on **rpi4**, btw., and the current options were “lr-dosbox” (easily the worst I've tried, performance and stability-wise), “dosbox-sdl2” (runs quite ok), and “dosbox-staging” (again, the one which yielded best performance and usability _so far_, IMO) and plain-old “dosbox”. These were all tested in their current versions as of ~3mo ago and compiled from source.

Is the Venn diagram still available somewhere for a direct feature and performance comparison? – or even better, personal experience with any of these wrt. demos (and also games) would be highly appreciated. I've experiemented with numerous dosbox.conf settings (especially relating to Gravis Ultrasound) and compiler options to make things run as smooth as possible; keeping in mind that the rpi4 obviously is a challenge for achieving this, but still...

**Comment by kcgen** [comment]
Thanks @Drag0nFly.

> many demos obviously are lacking

In general, if you hit issues please report them one-per-game/demo -- but part of the fun w/ DOSBox is trying all the options it gives you to find a working configuration (especially for trick demos). 

The DOS era spanned 30 years of hardware development, so if its software were people, the first generation expected to be riding a cart-and-buggy, while the last era expected to by flying a space shuttle.  DOSBox's defaults try to be suitable for the majority of programs - but it's not a guaranteed one-size-fits-all. 

Here are working `dosbox.conf` files I've put together for both demos. Feel to free use them as a basis to try other demos :-)  

## Future Crew's 2nd Reality

Drop this config along side `SECOND.EXE` and use a release-build of Staging.
It should play through perfectly, even on your Pi.

``` ini
[sdl]
fullscreen = true
capture_mouse = nomouse middlerelease
output = texturenb

[dosbox]
machine = vgaonly
memsize = 8
startup_verbosity = quiet

[render]
aspect = true

[cpu]
core    = dynamic
cycles  = 20000

[midi]
mididevice = none

[sblaster]
sbtype = none

[gus]
gus     = true
gusdma  = 6

[speaker]
pcspeaker=false
tandy=off
disney=false

[dos]
xms = false
ems = true
umb = false

[autoexec]
@echo off
mount c . > NUL
c:
autotype -w 2 enter
second.exe
```


## Triton's Crystal Dream II

Drop this config along side `CD2.EXE` and test it on your desktop PC first with a relase-build of Staging.
It should play through perfectly. 
The demo needs a fast PC `cycles = 40000` as well as `core = normal` to ensure perfect video and audio rendering. This is probably too demanding for any current Pi to handle.

``` ini
[sdl]
fullscreen = true
capture_mouse = nomouse middlerelease
output = texturepp

[dosbox]
machine = vgaonly
memsize = 2
startup_verbosity = quiet

[render]
aspect = true

[cpu]
core    = normal
cycles  = 40000

[sblaster]
sbtype = none

[midi]
mididevice = none

[gus]
gus     = true
gusdma  = 6


[speaker]
pcspeaker=false
tandy=off
disney=false

[dos]
xms = true
ems = false
umb = false

[autoexec]
@echo off
mount c . > NUL
c:
autotype -w 2 enter
cd2
```

**Comment by kcgen** [comment]
> Is the Venn diagram still available somewhere for a direct feature and performance comparison

This was just a mental comparison we discussed, and wasn't published.  There is nothing contentious or negative in the comparison, but I just don't have the energy to write it all up here. 

> navigating the various variants gave the impression of being somewhat of a jungle

@dreamer keeps a running tally of them all here: https://github.com/dosbox-staging/dosbox-staging/wiki/DOSBox-forks

**Comment by Drag0nFly** [comment]
Thanks for that very detailed answer @kcgen. 👍  I'll be sure to test out those dosbox.conf files with the demos (currently I've been employing a “one-size-fits-all” solution, as I was a little hazy as how the configs were handled, and which options were available for each DosBox flavor, etc.) ;)

And yes, I did test a large number of "cycles" settings (both in-demo and before startup) when last running Crystal Dream II numerous times; all of which were suboptimal, as the various parts of the demo either slowed down or or it entered a “confused” state due to the fluctuating speeds. (It was also the hardest to get running with the other flavors, and had graphical/color issues with lr-dosbox as I recall...)

Np about the diagram, it was just in case it was already there. :)

**Comment by Wengier** [comment]
I think the "demos" covered previously particularly refer to demoscence productions. Demoscence productions are often the test cases for accuracy emulations in DOSBox-X. But if you prefer performance rather than accuracy, than another fork including DOSBox Staging is perhaps more recommended for you.

**Comment by kcgen** [comment]
Suggest we close this.
