### ISSUE TITLE
Multiple Midi devices

### ISSUE THREAD

**Issue by ronoverdrive** [dosbox-staging/dosbox-staging#1003]
Unless I'm missing it somewhere it would be nice to have multiple midi devices active within Dosbox-Staging. This project supports both mt32 and fluidsynth so it would be nice to be able to set them to separate IRQ for each one so we wouldn't have to switch config files or rely on external implementations of MUNT & Fluidsynth on the same IRQ.

ex. 

```
[midi]
mididevice = fluidsynth mt32

[fluidsynth]
fluidsynthirq = 300

[mt32]
mt32irq = 330
```

**Comment by kcgen** [comment]
Thanks for the question, @ronoverdrive.

This does seem convenient: it would let someone setup their conf file with both MIDI devices "once-and-for-all", and then carry on to configure all of their DOS games accordingly.

This would be possible if games were equally flexible - but unfortunately they're not. The original intelligent MPU-401 cards only supported the 330 base port, and [this could not be changed absent soldering and trace cutting on the cards.](http://nerdlypleasures.blogspot.com/2010/03/tutorial-how-to-get-roland-mt-32.html)

So we've got the scenario where _all_ MIDI games work on port 330 while a subset of those allow other ports. 

So for a large number of MIDI games, user would have swap around these settings depending if the game is using Roland or GM.  We would also have to take into account IRQs (and those conflicts), as well as what the game might assume. 

For example:

``` ini
[fluidsynth]
fluidsynthirq = 9
fluidsynthport = 300

[mt32]
mt32irq = 2
mt32port = 330
```

Given most games don't allow changing the MIDI IRQ, there would be a large risk that it sends IRQ calls to the wrong device.  So users would have to experiment and then flip those as well (or not).

``` ini
[fluidsynth]
fluidsynthirq = 2
fluidsynthport = 330

[mt32]
mt32irq = 9
mt32port = 300
```

And.. if they're flipping these things around in their primary conf file to satisfy game C, then game A and B will now be broken.

**Comment by ronoverdrive** [comment]
I understand where you're coming from, but there's another alternative: hotkey swap between Fluidsynth and MT32. Back in the day if you were made of money and had both a MT-32 and a GM/GS Midi synth they had switch boxes to switch between multiple synths. Maybe have a special key combo to swap between them?

**Comment by kcgen** [comment]
This brings up DOSBox's configuration design that, while powerful, is often a large hurdle for new users that prevents them from getting the most from their games.

In this example, here's what I recommend:
1. In your main configuration file, setup both `[fluidsynth]` and `[mt32]` to your most-preferred settings. 
2. Disable MIDI in your main configuration file. `mididevice = none`. 
3. For every MIDI MT-32 or FluidSynth game you have, create a `start.bat` (or edit it's current batch file):
    If the game uses General MIDI, add this to the start of that file:
    `mididevice fluidsynth`

    If the game uses a Roland MT-32 and CM-32L, add this:
    `mididevice mt32`

4. In step 1, I mentioned using "most-preferred" for a reason, because you might want to fine-tune your soundfont or Roland model on a per-game basis.  For these, you can apply those setting before setting your device preference.  For example:

    `soundfont path/to/preferred.sf2`
    `mididevice fluidsynth`

    And for MT-32:
    `model mt32`
    `mididevice mt32`

**Comment by kcgen** [comment]
> I understand where you're coming from, but there's another alternative: hotkey swap between Fluidsynth and MT32. Back in the day if you were made of money and had both a MT-32 and a GM/GS Midi synth they had switch boxes to switch between multiple synths. Maybe have a special key combo to swap between them?

This is an interesting idea!

I was thinking we could route the port-330 and IRQ content to the selected device on-the-fly, and then 'shutdown' or pause the other device. 

However, prior to playing the music, MIDI games typically perform a "large" sysex load up-front, followed by the music. This means that only the selected device at the time would 'get'  that initial sysex load.  So then if you switched devices mid-music, the other device would sound very wrong. (on top of that, MT32 and General MIDI also use different instrument banks).

Those money-bag MIDI users actually had a single MPU-401 card listening on 330 and then used a Y-splitter cable (or a breakout box) to send the same sysex content to all their MIDI devices at the same time.. then simply selected which device was allowed to play to their speakers via their audio mixer. 

So to do something the same, we'd have to run both FluidSynth and MT-32 at the same time, and then discard the audio output for which ever device isn't the active one.  This is possible, but it would burn up a lot of CPU time (FluidSynth and mt32emu are the two most CPU-intensive devices - each using roughly 600 up to 1200Mhz of one core).

**Comment by kcgen** [comment]
Even if we did all that, it still doesn't solve the issue that MT32/CM-32L and General MIDI use different instrument banks - so the music from the 'wrong' device would sound off or strange.

Where as the hotkey approach:
1. Relies on the user to switch over to the 'correct' device
2. Relies on the user knowing about this toggle-approach
3. Relies on the user either having keen enough ears to catch the musical flaws (and switch over) or keep some record of which game users which device. 
4. Even if all of the above are true, there's still the risk that the user experiences some initial incorrect audio during startup before they quickly switch over -- so the experience is harmed.  

So given the options, I would prefer users (and those packaging games for users) not use this approach -- because it's overall detrimental to the experience.  I would prefer users apply a single setting, from the get-go, straight into their game's startup configuration or batch file. This is a one-time task and guaranteed to be correct on game startup.

**Comment by kcgen** [comment]
Happy to chat more about this, but I think we've concluded that enabling multiple midi devices simultaneously or via toggle method would not be an overall improved experience. Thank you for bringing this up!

**Comment by johnnovak** [comment]
Duplicate of https://github.com/dosbox-staging/dosbox-staging/issues/1427

**Comment by johnnovak** [comment]
Yeah, the MIDI splitter box approach is good and I'm using that myself on real hardware, but it's only practical for multiple GM or multiple LA synth (MT-32) boxes. You need to specifically configure each game either for GM or Roland MT-32 as the instrument data, and maybe even the MIDI data in some games, will be very different.
