### ISSUE TITLE
"CTRL-ALT-F8	Start/Stop the recording of raw MIDI commands." is missing

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1099]
https://www.dosbox.com/wiki/Special_Keys
dosbox\docs\dosbox.1
...
.IP CTRL\-ALT\-F8
Start/Stop the recording of raw MIDI commands.
...

dosbox-staging\docs\dosbox.1
missing that line

and it also does not seem to work in staging

**Comment by kcgen** [comment]
This was deliberately changed under https://github.com/dosbox-staging/dosbox-staging/issues/585

@dreamer - is there a different hotkey we can use for MIDI recording?

@HW-Scanno has also expressed a need for this, and has actually produced some MIDI remixes using this feature (after manually mapping the feature).

We looked in Ctrl+F8, and it's surprisingly open on all OSes - perhaps we can use that?

**Comment by LowLevelMahn** [comment]
FYI why i need that feature: i try to record differences between original and reversed game sound driver

**Comment by LowLevelMahn** [comment]
would be also nice to have a command line parameter that captures the whole dosbox session

**Comment by kcgen** [comment]
We've got three different audio stream types.
With the current approach, each stream needs a separate hotkey.

What if "Record Audio" (Ctrl + F6) did that holistically? 
 - PCM samples
 - OPL instructions, if present
 - MIDI sysex, if present

With this approach, I'd only have to remember: _"Ctrl+F6 records my audio"._  and I'm done.
Likewise, a single command-line argument `--record-audio` could do the same.

@LowLevelMahn , @HW-Scanno -- what do you guys think?

**Comment by LowLevelMahn** [comment]
and do all streams end in the same file or different?

**Comment by kcgen** [comment]
> and do all streams end in the same file or different? i would say different - same as now but started with a single hotkey
> is that much more pressure for the CPU? (needs to be at least buffered or else the game will have laggy sound)

The plan would be have this mode write three seperate files. The nice thing about audio capture is that it happens in "game time", not "wall time", within the game loop, and is not affected by host-side performance.  

This mean that even if a host is busy or has competing workloads and DOSBox cannot keep up (use experience slow frame-rates and audio drop-outs), the recording side will will be unaffected by these anomalies because it writes data reliably every pass through the game loop.. however long that takes.

**Comment by LowLevelMahn** [comment]
and for the combined sound - if the game is using multiple outputs parallel (is that even possible?) one can use an extern recording tool

**Comment by Torinde** [comment]
Possibly related:
- #2973

**Comment by johnnovak** [comment]
> Possibly related:
> 
>     * [Include DOSBox-VGM patch #2973](https://github.com/dosbox-staging/dosbox-staging/issues/2973)

Not really—MIDI, audio, and OPL recording are three different things.

**Comment by johnnovak** [comment]
Hotkeys are documented on the wiki and the user manual is coming this year.

**Comment by nikitalita** [comment]
Ctrl-F6 does not record the midi; it just records the audio. What happened to this?

**Comment by johnnovak** [comment]
> Ctrl-F6 does not record the midi; it just records the audio. What happened to this?

@nikitalita 
Nothing. It's just unmapped, so you need to map it to the hotkey of your choosing in the keymapper.

It's been unmapped since 0.76.0 at least, I've just checked.

For that reason, we don't list the capture MIDI hotkey in out special keys wiki page:
https://github.com/dosbox-staging/dosbox-staging/wiki/Special-keys

I might make a change to map it by default, but then it's a niche feature.

**Comment by madbrain76** [comment]
I would say the MIDI recording feature definitely needs to be properly documented, the keyboard shortcut mapped by default, and that shortcut documented. So be it if there are some platform-specific shortcuts due to OS conflicts. A little ifdef in the code and extra sentence in the doc is not very harmful. Certainly not as much as having to do more manual work after install.

**Comment by johnnovak** [comment]
@madbrain76 Yeah, not niche feature for us, musicians, but it is for the majority of users 😏 

However, it's probably a good idea to map it by default anyway, you're right. Ctrl+Shift+F6 is free, then that could record MIDI, in addition to Ctrl+F6 for recording audio, which is already mapped.

It's a simple change, I'll just do in this or next week, then we'll document it as a default shortcut in the wiki so people won't miss it.

**Comment by madbrain76** [comment]
Thank you ! With the advent of soft MIDI synths, it might not be quite as much of a nice feature as it used to be. For sure it's not a high percentage of DOSBox users who own MIDI hardware. I no longer have an LAPC-1, CM-32L, or MT-32. Had all of them at some point, though never more than 2 at once. But stilll got my UM-880, Fantom XR, and VK-88.

**Comment by johnnovak** [comment]
> Thank you ! With the advent of soft MIDI synths, it might not be quite as much of a nice feature as it used to be. For sure it's not a high percentage of DOSBox users who own MIDI hardware. I no longer have an LAPC-1, CM-32L, or MT-32. Had all of them at some point, though never more than 2 at once. But stilll got my UM-880, Fantom XR, and VK-88.

Indeed, not many people have hardware synths, although surprisingly many retro enthusiast have quite a few.

I do have two SC-55 and Yamaha MU80 devices, check out the photos in this article I wrote (scroll a bit down for the pictures). Of course, the whole article is worth reading if you're interested, plus I think the recordings have turned out quite well :)

https://blog.johnnovak.net/2023/03/05/grand-ms-dos-gaming-general-midi-showdown/

**Comment by johnnovak** [comment]
I've added a default mapping for capturing the MIDI output as you suggested @madbrain76

**Comment by madbrain76** [comment]
@johnnovak , thank you !  How can I pick up this change ? I'm not building DOSbox staging myself at this time.

I looked for a way to manually add the mapping, but couldn't find one.

**Comment by johnnovak** [comment]
> @johnnovak , thank you ! How can I pick up this change ? I'm not building DOSbox staging myself at this time.

We publish a new dev build on every merged commit, so just download the latest from here:

https://www.dosbox-staging.org/releases/development-builds/


> I looked for a way to manually add the mapping, but couldn't find one.

- Ctrl+F1 to bring up the mapper
- Click on the **Rec. Midi** button
- Click on **Add Bind** (at the bottom), then press a key of your choosing (e.g., F6)
- Toggle Mod1, Mod2, and Mod3 in the bottom left corner.
- Hit **Save**

This is how it looks like when configured for Ctrl+Alt+F6 (I'm on macOS now, hence it shows Command + Option + F6).

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/ed0ff397-7135-4405-af37-331729a23e37">

**Comment by madbrain76** [comment]
@johnnovak I thought I put a comment late last night before going to sleep, but I must have forgotten to submit it, as I don't see it.
Yesterday, I couldn't figure out the 4th step - how to "toggle" mod1, mod2 and mod3. I think that requires some more detailed explanation on how to do this. I tried to click each one, but but when I clicked the next one, the first went from white to green. Also, I'm using a French AZERTY keyboard, and the key mapper showed a QWERTY. Not sure if there is a way to fix that. There are subtle differences like the AltGr key instead of Alt. Many letters are swapped, etc.
If it were me, I would prefer a config file with scan codes a million times over this GUI. Obviously I'm not a UI designed. But the UX was awful for me. Also, many Windows programs just let you enter the keys for the combo, one at a time, and then record them. Look at Display Fusion for example.
Anyway, I must messed up the mappings badly enough playing that UI, because now I'm stuck at the very first step - CTRL-F1 no longer brings up the key mapper.

**Comment by johnnovak** [comment]
> Yesterday, I couldn't figure out the 4th step - how to "toggle" mod1, mod2 and mod3. I think that requires some more detailed explanation on how to do this. I tried to click each one, but but when I clicked the next one, the first went from white to green. 

Interesting, never had that problem before. Maybe high-DPI related?

> Also, I'm using a French AZERTY keyboard, and the key mapper showed a QWERTY. Not sure if there is a way to fix that.

Actually, I don't know that either, but I can some French guys.

> If it were me, I would prefer a config file with scan codes a million times over this GUI. Obviously I'm not a UI designed. But the UX was awful for me. Also, many Windows programs just let you enter the keys for the combo, one at a time, and then record them. Look at Display Fusion for example.

No disagreements there, the mapper UI is crap, and all of us hate it 😆 We inherited it from the original DOSBox, and although we have patched it up slightly, it still sucks...

Absolutely, the new mapper will work as you described, will be much more flexible, and a lot more intuitive to use. It's just I need to implement a GUI framework (OSD) first, and then we'll burn the existing mapper to the ground and reimplement it from scratch on sane principles.

But, given this is a hobby project for me, that is years away.

> Anyway, I must messed up the mappings badly enough playing that UI, because now I'm stuck at the very first step - CTRL-F1 no longer brings up the key mapper.

Just delete your mapper file then you'll be back to the defaults. The mapper file gets saved to `C:\Users\%USERNAME%\AppData\Local\DOSBox\`, but you can get the exact name by looking for the following line in the logs:

```
MAPPER: Loaded 158 key bindings from '/Users/jnovak/Library/Preferences/DOSBox/mapper-sdl2-0.82.0-alpha.map'
```

Another way to delete it is to start dosbox with the `--erasemapper` command line param.

**Comment by johnnovak** [comment]
@madbrain76 My French connections are telling me the situation is hopeless with an AZERTY keyboard. DOSBox was just not built for non-US keyboard layouts in mind.

The general advice is to use `keyboardlayout=us` in the config, and either use a physical QWERTY US keyboard, or just live with the keycaps on the physical keyboard and the keys in the mapper showing different things.

Again, as mentioned, this can only be rectified with the total mapper rewrite.

**Comment by madbrain76** [comment]
After 28 years in the US I still don't own a QWERTY. Or even any laptop with one.

How is the output of the key mapper stored? Some sort of human readable format like XML or JSON or basic text file; or is it some dreadful binary format with a digital signature to prevent tampering ? Hopefully somewhere in between.

Anyway, I can set the OS layout to QWERTY temporarily.  I do need to fix the problem with CTRL+F1 no longer bringing the key mapper up. I may have accidentally mapped that key combo.

**Comment by johnnovak** [comment]
> After 28 years in the US I still don't own a QWERTY. Or even any laptop with one.
> 
> How is the output of the key mapper stored? Some sort of human readable format like XML or JSON or basic text file; or is it some dreadful binary format with a digital signature to prevent tampering ? Hopefully somewhere in between.
> 
> Anyway, I can set the OS layout to QWERTY temporarily. I do need to fix the problem with CTRL+F1 no longer bringing the key mapper up. I may have accidentally mapped that key combo.

Delete & recreate is the fastest, as I mentioned.

Have a look at the mapper file, the format should be easy to figure out.

**Comment by madbrain76** [comment]
> > Yesterday, I couldn't figure out the 4th step - how to "toggle" mod1, mod2 and mod3. I think that requires some more detailed explanation on how to do this. I tried to click each one, but but when I clicked the next one, the first went from white to green.
> 

That's because I misspoke . I meant to write "when I clicked the next one, the first went from green to white". Perhaps that's the intended behavior, but I I'm afraid I still don't understand it. Normally I don't rely on videos for technical documentation, but this may be one case where an exception is warranted. Still reading the rest of the posts in this thread - I missed while at the dentist earlier this afternoon.

> No disagreements there, the mapper UI is crap, and all of us hate it 😆 We inherited it from the original DOSBox, and although we have patched it up slightly, it still sucks...

I see. I wonder if there is some piece of open source code out there that does a better job and could be integrated given the proper license.

> The code is just horrible, everything is hardcoded, it's super hard to modify or extend, and just the whole approach is totally flawed. It needs a total rewrite and total rethinking of the new config file format as well.

Sorry to hear that.

> Absolutely, the new mapper will work as you described, will be much more flexible, and a lot more intuitive to use. It's just I need to implement a GUI framework (OSD) first, and then we'll burn the existing mapper to the ground and reimplement it from scratch on sane principles.

Does it even need to be GUI at all ? It could be a console app. Text-mode should suffice if all you are doing is inputting the keys, recording and displaying them. Sort of wizard/interview like UI. Keep it minimalist. The GUI of the current one just gets in the way.

> But, given this is a hobby project for me, that is years away.

I understand.

> Just delete your mapper file then you'll be back to the defaults. The mapper file gets saved to `C:\Users\%USERNAME%\AppData\Local\DOSBox\`, but you can get the exact name by looking for the following line in the logs:

FYI, There is a faster way to write this : %appdata%\..\local\dosbox .


> 
> ```
> MAPPER: Loaded 158 key bindings from '/Users/jnovak/Library/Preferences/DOSBox/mapper-sdl2-0.82.0-alpha.map'
> ```
> 
> Another way to delete it is to start dosbox with the `--erasemapper` command line param.

I will try it. But need to watch the hot tub as it's almost finished filling up. And then watch a movie with hubbie.
Will catch up with the rest of your posts later.

**Comment by madbrain76** [comment]
OK, my timer says I have 7 mins left to fill up. 

For posterity, this is the change that broke CTRL+F1 and thus the remapper no longer comes up. I have no idea how did it, but it was by clicking, not editing the file manually.

C:\Users\Julien Pierre\AppData\Local\DOSBox```
>fc mapper-sdl2-0.81.1.map mapper-sdl2-0.81.1.map.bad
Comparing files mapper-sdl2-0.81.1.map and MAPPER-SDL2-0.81.1.MAP.BAD
***** mapper-sdl2-0.81.1.map
hand_recwave "key 63 mod1"
hand_caprawmidi
hand_scrshot "key 62 mod1"
***** MAPPER-SDL2-0.81.1.MAP.BAD
hand_recwave "key 63 mod1"
hand_caprawmidi "key 65"
hand_scrshot "key 62 mod1"
*****

***** mapper-sdl2-0.81.1.map
jhat_0_0_1
mod_1 "key 224" "key 228"
mod_2 "key 226" "key 230"
mod_3 "key 227" "key 231"
***** MAPPER-SDL2-0.81.1.MAP.BAD
jhat_0_0_1
mod_1 "key 224 mod2" "key 228"
mod_2 "key 226 mod1 mod2" "key 230"
mod_3 "key 227 mod3" "key 231"
*****
```

**Comment by madbrain76** [comment]
I finally figured it out.
