### ISSUE TITLE
Install translations directory in linux with meson

### ISSUE THREAD

**Issue by IlyaIndigo** [dosbox-staging/dosbox-staging#1232]
How and where should the translation directory be installed?
It is not installed via %meson_install macro.
https://build.opensuse.org/package/show/home:13ilya/dosbox-staging

**Comment by kcgen** [comment]
The `translations` directory  is ideally copied (or symlinked) into the user's `~/.config/dosbox/` area (on Linux).  But I'm not sure how one would do that for a system-wide installation. 

Maybe you can place them in a /usr/share area for users to fetch from, if they want to use them?

When we switch to c++17 in October, we will have an easier way of detecting the install path to the executable, and can then load system-wide common data files (like these translations) directly from there instead of using the user's config path.

**Comment by IlyaIndigo** [comment]
I also think that they should be in "/usr/share/dosbox-staging/translations/ {ru,de,es,pl,???.lng".
But they should be prepared there, and most importantly dosbox-staging from itself should be able to read from there without copying to "~/.config", as it is now with soundfonds for fluidsynth ...
And also it must determine the locale and load (try to load) the corresponding language with "keyboardlayout = auto" (you can also read the system locale, for example, from $LANG (ru_RU.UTF-8)).
Without "keyboardlayout = ru", my language is not installed, even if I specify the path to the file (I see caracozyabs).
It's high time for C ++ 17!

I am very grateful to you for your many work and help!
Just sharing my thoughts on how this should work. :-)

**Comment by Burrito78** [comment]
@kcgen Can we close this?

**Comment by kcgen** [comment]
Thanks @Burrito78 - yes, the translations along with all of Staging's resources are `meson install`able and respects prefix and datadir targets.
