### ISSUE TITLE
Slideshow mode w/ Screamer 2 and Screamer Rally

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1297]
Slideshow mode is back at least in Screamer 2 and Screamer Rally on Pi. For the record a similar issue was discussed (and [fixed](https://github.com/dosbox-staging/dosbox-staging/commit/a554385cb3eca4228bc96abfc275dfc0ac29faf4)) for System Shock whenever using 640x400 video mode.

To reproduce:
1. on a Pi, run Screamer 2 (or Rally) in "hi-res 256 colours" mode > `START65L.EXE`
2. wait for the game to show the first logos and hit `enter` or `esc` which normally gets you to the main menu.
3. you'll see the screen will (very) slowly draws one line of pixels after the other until it gets to the bottom.
4. this slideshow will last for 2 or more minutes yet once in the main menu, game will play just fine from there

I've checked in the manual and the "hi-res 256 colours" mode means 640x400. 

**Note**: game runs fine with the other modes ("lo-res" 320x200 or "hi-res 65k colours").

**Comment by kcgen** [comment]
>     1. on a Pi, run Screamer 2 (or Rally) in "hi-res 256 colours" mode > `START65L.EXE`

@nemo93 , can you double check the exe name here - the "65L" to me maybe implies 65k colours, and low-resolution?

I added some logging to see what mode each executable is using:

| Executable  | Video Mode  | Res/Color  |
|---|---|---|
| `startl.exe`  | 13  |  "Standard VGA" 320x200 @ 256c  |
| `starth.exe`  |  101 |  VESA @ 640x480 @ 256c / 8bit |
| `start65l.exe`  | 111  | VESA 640x480 @ 65k/16bit |
| `start65h.exe`  | 111  | VESA 640x480 @ 65k/16bit |

(screenshots below, as references)

Because these involve VESA modes, my immediate thought is that the S3 patch might have changed these modes, so I went back to the 0.77.x sources, built them, and added the same logging. The game used the same modes, and even these modes in the code have the same timing properties. 

See the first couple hundreds lines:
```
 { 0x13
 ...
 { 0x101
  ...
 { 0x111
```

Latest: https://github.com/dosbox-staging/dosbox-staging/blob/main/src/ints/int10_modes.cpp
0.77x: https://github.com/dosbox-staging/dosbox-staging/blob/release/0.77.x/src/ints/int10_modes.cpp

So none of the new 24-bit modes are causing problems either - because they're not used.

We also didn't change the VESA refresh rate - it's still hardcoded at 70 Hz.

One change is the default memory size - which is now 4 MB.

Can you try 2 (default per upstream and 0.77x. and even 1 and 8, just for comparison)?

```ini
[dosbox]
vmemsize = 2 
```


---

![2021-10-04_09-31](https://user-images.githubusercontent.com/1557255/135889910-346ea02c-aa71-4838-b83a-47248bc9511a.png)
![2021-10-04_09-30](https://user-images.githubusercontent.com/1557255/135889912-474aacf4-9e32-4417-8722-d139f0f8e595.png)

![2021-10-04_09-32](https://user-images.githubusercontent.com/1557255/135889907-820df8f5-b57c-4834-8546-1370b9933669.png)
![2021-10-04_09-31_1](https://user-images.githubusercontent.com/1557255/135889909-8c472688-69dc-475a-b77e-b29b9659a27b.png)

**Comment by nemo93** [comment]
Thank you @kcgen for spending on this. I've pulled a fresh version compiled from latest `main` https://github.com/dosbox-staging/dosbox-staging/commit/c7b7dd5601a67026bdee97e557cd03627436d941. Then I'm adding a few screenshots to keep track of this quite odd issue:

[s2captures.zip](https://github.com/dosbox-staging/dosbox-staging/files/7285203/s2captures.zip)

I confirm running `START65L.EXE`. I referred to "hi-res 256 colours" mode as it's taken from the manual. I've tried many combos of `vmemsize` (including `vmemsize = 2`) , `machine`, `memsize` and `vesa_modes` with no luck. Also worth mentioning I'm **not** relying on DOS/32A for that game provided it conflicts with the... keyboard. Last I've tried to set a fixed amount of cycles (eg. `30000`) but still the issue persists.

Can't you reproduce that issue on your Pi3?

**Comment by kcgen** [comment]
@nemo93 , unfortunately everything is runnable on my Pi3, and the initial menus, logos, etc all popup fast and smooth with cycles max or 30k. 

The game is smoothest at 30k with the low res 256 exe, and others are slower as expected, but unfortunately I can reproduce this line by line slideshow menu issue. 

I don't use vsync, but even with it enabled didn't change anything.

Can you try maybe with vsync off, just to see if that changes anything in the menu?

**Comment by nemo93** [comment]
@kcgen I just tried with various "isos" of the game with same outcome. Same goes with `vsync on/off`. However things get back to normal whenever I load Univbe before the game (either Screamer 2 or Rally).

**Comment by kcgen** [comment]
This just in from @GranMinigun:
> The game keeps some settings in a config file, and every executable needs its own settings.
> Directly calling game's executables is discouraged. Configure the desired mode in the setup utility, then launch the game using S2.BAT / SR.BAT

After following this recommendation, I selected the high-color, low-resolution setting in `SETUP.EXE` first, then launched with `S2.bat`, and got:

![2021-10-05_10-29](https://user-images.githubusercontent.com/1557255/136081185-54115072-f4fe-45d3-bd6e-d496a95eb39e.png)

**Comment by kcgen** [comment]
The SETUP.EXE program itself has issues and is prone to staying black or crashing/freezing.
This is confirmed here: https://github.com/exoscoriae/eXoDOS/issues/2187

I've tested a startup sequence like this, and it works OK:

```
[autoexec]
mount c .
imgmount d cd/opus/cdrom.cue -t cdrom
mixer sb 50 cdaudio 200
mount a floppy -t floppy
c:
cd s2
cycles 50000
vsync false
del config\setup.cfg
setup
cycles max
vsync true
s2.bat
```

**Comment by Grounded0** [comment]
I can report that Screamer Rally works, sounds and looks beautiful both in hi res 65k colors and low res 65k colors. But it must be configured as such via SETUP and then you must run SR.BAT or its all excrement with weird aspect ratios.

**Comment by nemo93** [comment]
Thanks again for helping with that one and apologize for the time taken. I do confirm running the `S2.BAT` after running through the `SETUP`. I'm well aware of the [issue](https://github.com/dosbox-staging/dosbox-staging/wiki/Games-issues#screamer) with `SETUP` on all the Screamer games in general 😉 As this issue appears (only?) on Pi4 I went into a bisecting session which got me the "faulty" commit (`https://github.com/dosbox-staging/dosbox-staging/commit/634bb3c2799a78b168b5dbe5ddc23ff43261afbd`):

```
634bb3c2799a78b168b5dbe5ddc23ff43261afbd is the first bad commit
commit 634bb3c2799a78b168b5dbe5ddc23ff43261afbd
Author: kcgen <1557255+kcgen@users.noreply.github.com>
Date:   Fri Sep 10 14:37:03 2021 -0700

    Use original VGA SetClock algorithm with doubler flags

:040000 040000 7080f4e07a712750e3c3d8ad2f74b31ab0714cde f067bf940123720494abd47422d08ef0afab71f7 M      src
```

Before that commit indeed no issue with the games aforementioned and no need to load Univbe. Thanks again.

**Comment by kcgen** [comment]
Indeed, it does appear to be something sensitive about this on the Pi4 (we tested windows, mac, Linux, and Pi3 in all four modes).  But thanks to your bisecting, I will have a fix for you to try come AM.

**Comment by kcgen** [comment]
@nemo93 , when you have a chance, hopefully ` kc/fix-clock-calc-1` addresses this.
