### ISSUE TITLE
Display how many cycles Staging is actually using when cycles = max

### ISSUE THREAD

**Issue by MasterO2** [dosbox-staging/dosbox-staging#1335]
@kcgen 

When `cycles = max` is set, Dosbox Staging does not show how many CPU cycles are actually being used by the user's system when a program is executed.

Can the actual number of cycles being used, when `cycles = max` is set, be shown either in the `Dosbox Status Window` and/or on the top of the Dosbox Staging window when in windowed mode?

**Comment by arrowgent** [comment]
are there a lot of approximation updates for measuring that?
it would also need a test in place to calculate that measurement or change
i figure max CPU Cycles changes as your physical thread of the CPU gets Loaded, MHZ changes, etc.

configurable update cycle?  0=instant, 1second, 10 second update intervals?

is there an example of another dosbox having this feature for MAX = CPU Cycles?

**Comment by kcgen** [comment]
That's right @arrowgent ; the auto-cycle calculator is run up to 1000 times-per-second, however depending on conditions it may not run as frequently.  Here's the block of code:
https://github.com/dosbox-staging/dosbox-staging/blob/8a6ef3d00f70a347b4302876d9ad841416bb395b/src/dosbox.cpp#L221-L303

Getting this feature right would involve keeping a running average spanning some window of time, otherwise the visual output will be a blur.  Also, on some systems, perturbing the window itself can be expensive and 'blocking' (causing an brief interruption in audio).

**Comment by MasterO2** [comment]
How about update cycles in 10-second, 30-second, and 60-second intervals?

**Comment by GranMinigun** [comment]
I'd say, treat it like FPS counters. Sample n times per second, for a second, output every second. I don't see any use in exposing yet another configuration option.

**Comment by arrowgent** [comment]
is there any SDL2 feature that would be useful here?

glancing at the current MAX code you posted, it already does some kind of calculation?
from that you would just need to display that cycle on the title?
does MAX cycles currently do periodic checking?

thats a lot of IF statements for checking MAX cycles 😁 

interesting a limit of 2,000,000 cycles maximum.
was this number tested to break games, or just not be useful above that limit?
i figure a strong CPU and hardware would just constantly report 2million, making displaying MAX cycles fairly useless on those systems.

**Comment by Jkapp76** [comment]
I like this idea too.

BTW, I still test all the beta versions. And I find 1044 very stable for my purposes.

**Comment by Burrito78** [comment]
Nice to see you again, old ticket. Closed.
