### ISSUE TITLE
Golden Axe audio output issue on Windows 11

### ISSUE THREAD

**Issue by ggpettas** [dosbox-staging/dosbox-staging#1386]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Goldenaxe dos sound effects PC speaker not working. On old dosbox 0.73 and dosbox x they work.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Audio works fine for me. The game plays music via OPL and effects via PC Speaker.

Please try the attached ([GoldenAx-for-testing.zip](https://github.com/dosbox-staging/dosbox-staging/files/7577196/GoldenAx-for-testing.zip)), which is for testing purposes. 
1. Extract the zip.
2. Open a command prompt.
3. `cd` into the game's directory. 
4. Enter the path to your dosbox executable, such that is starts from within the directory.
5. The included `dosbox.conf` will launch the game.

If audio doesn't work, then this is possible a new bug specific to Windows 11.

**Comment by ggpettas** [comment]
Thanks for your reply.  I tried the above goldenaxe and conf and it didn't work. Then i tried older dosbox versions and i can confirm it works on staging version 0.75 x64. Above that stops working.

**Comment by kcgen** [comment]
Thanks @ggpettas ; very interesting. 
Do you know if other PC speaker games on Windows 11 are affected the same, or is this specific to Golden Axe?

**Comment by kcgen** [comment]
Thanks for this report @ggpettas.

Please try the latest Windows builds from here:  https://github.com/dosbox-staging/dosbox-staging/actions/runs/1491465861 with `zero_offset` to `auto` or `false`.

Normally this is true, but we noticed some Windows audio drivers [perform their own (very flawed) DC-offset correction](https://github.com/dosbox-staging/dosbox-staging/pull/625#issue-709558371), so that's why we introduced the option to disable it.
