### ISSUE TITLE
Implement instant-launch

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#139]
Instant-launch would take place when DOSBox is started with an executable (`.bat`, `.com`, or `.exe`) on its command-line.  ie: `dosbox rungame.bat`

Instant-launch would:
- skip all DOSBox-specific visual output (logos / banners / other messages)
- set the video-mode to whatever the game has requested, straight-away, without any prior video modes being set

If no executable is provided, DOSBox would start in **_interactive-mode_**, per its existing behavior:
- display the logo
- display the help banner
- display any other DOSBox-specific content
- deposit the user at the DOS command prompt

Motivations for instant-launch are:
1. to fall in-line with all other high-quality emulators that simply "get out of the way and start your game", such as those supported on RetroPie.
2. to match the experience in real DOS.  When your launch a game from the command prompt, Microsoft does not insert pre-popup fanfare before the game starts up.  
3. to eliminate visual redundancy.  If the user launches multiple games in short succession, these screens act as unavoidable redundancy to the user's experience.

**Please vote** with a 👍 or 👎   
(nothing personal here: this is simply an idea that we can kill or run with!)

**Comment by dreamer** [comment]
I like this idea :)

Some notes:

## Video mode concern
Right now, when a command or path is passed to DOSBox, it does a bit more than simply run the command - following sequence is injected into autoexec:
```
$ dosbox some/path/file.exe
Z:\> mount C some/path
Z:\> C:
C:\> file.exe
```
Because of this, it might be hard or impractical to go straight to video mode, that the game requested. Also, some execs might not request changing videomode at all and expect to stay in the current text mode (whatever it is 80x25, 80x50, or some different one). (Norton Commander is an example of such program). Maybe we can figure it out somehow.

## User option or CLI flags

I think user should have a bit more control over the splash screen; right now, the splash screen is hardcoded (I think it's because of companies distributing DOS games with bundled dosbox?) - but in many, many contexts it does not make sense to show it, even when starting simple terminal window (my terminal emulator does not show splash screen on each start - I would go insane if it did).

Maybe we should add a user setting `dosbox.show_splash` (with values `yes/no/auto`, `auto` being default resulting in instant-launch functionality). Optionally, we could also add new flags: `--show-splash`, `--no-splash` (but .conf setting might be enough).

## Banner

Blue banner on DOSBox start is a separate concern. I really don't like it - it contains too much information, so in the result users don't read it. In instant-launch mode we could simply add cls after switching to C: to avoid showing it. Personally, I would like remove this banner and replace it with better tutorial on dosbox usage than 'intro', and have a user option to not show it at all and start with a clean prompt (like a modern terminal emulator would do).

My point here: I suggest banner to be taken out of this feature and treated as a separate topic.

**Comment by krcroft** [comment]
Great suggestions @dreamer ; The additional of the splash screen flag and conf option are a very nice touch, especially with 'auto' being the default.

I also agree the info/help banner should simply be removed; but for this feature it will be hidden/skipped in instant-launch mode.  So it makes sense to tackle interactive-mode's help-banner under a separate feature.

**Comment by krcroft** [comment]
> I think it's because of companies distributing DOS games with bundled dosbox?

That's the consensus:
- https://www.vogons.org/viewtopic.php?t=23314
- https://www.vogons.org/viewtopic.php?t=69322
- https://www.vogons.org/viewtopic.php?t=69597

"_Unscrupulous vendors packaging DOSBox without giving credit_", so the splash-screen forces that credit and awareness upon the user, thus foiling the unscrupulous vendor.

Imagine if the other GPL authors followed suite? We'd sit through splash-screens for ALSA, Timididy/Munt, Ogg Vorbis, and SDL even before DOSBox's splash is displayed.

Strangely though, this splash-intensive worldview would have be welcomed by the DOSBox authors to avoid them being hipocrites.

I especially enjoy DosFreak's response to a user requesting a splash toggle: 

> If there were then everybody would just set it to "No".

**Comment by krcroft** [comment]
I do believe all credit is due to the DOSBox authors, and fighting plagiarism and copyright violation is a worthy and noble cause; however that war is best played out with a lawyer, lawsuit, and transference of money from the violating parties. 

If the battle against unscrupulous vendors is going to be played out on the splash-screen, then users should be adequately armed with procedures to follow if they purchased a "pirate DOSBox device" on ebay / amazon / AliExpress, on how to report and shutdown these vendors.

**Comment by kcgen** [comment]
For those wanting to try out instant launch, just run your executable or batch file like normal, ie: `dosbox-staging karateka.exe`.

The default banner mode is `auto`, which means that banners will be skipped when you launch an executable (.bat / .com / .exe) straight-away on dosbox's command-line.

Builds to try:
 - Windows: https://github.com/dosbox-staging/dosbox-staging/suites/757221737/artifacts/7832823
 - Linux: https://github.com/dosbox-staging/dosbox-staging/suites/757221777/artifacts/7832669
- macOS: https://github.com/dosbox-staging/dosbox-staging/suites/757221787/artifacts/7832849

**Comment by kcgen** [comment]
Calling for testing help!

Configuration option is as shown; set that to `auto` to try instant launch as originally described here, or set it to `no` to simply turn off the splash and intro banners.  

![2020-06-30_13-57](https://user-images.githubusercontent.com/1557255/86176443-c7254700-bad9-11ea-8aed-be77efcedc87.png)

The existing splash and intro banners are the default: `on`.

Source is on branch: ` kc/instant-launch-1`, or grab the build binaries:

- [:file_folder: Linux binary](https://github.com/dosbox-staging/dosbox-staging/suites/860659327/artifacts/9908260) 
- [:file_folder: macOS binary](https://github.com/dosbox-staging/dosbox-staging/suites/860659345/artifacts/9908438)
- [:file_folder: Windows binary](https://github.com/dosbox-staging/dosbox-staging/suites/860659282/artifacts/9908361)

**Comment by dreamer** [comment]
I like this solution very much; experienced users will just change it to `no` and not be bothered with welcome banner any more. Keeping `yes` as the default means users will always see the banner on the first run / first install.

So far I tested it on Gnome 3 + XWayland + Intel + OpenGL - works beautifully. Gnome 3 + pure Wayland - there are some bugs, but all I've seen are not regressions - just various issues we have in master.

Unfortunately, I don't have access to multiple displays at the moment, but tomorrow I'll attach it to the TV and do some testing this way and test some other DEs.

**Comment by kcgen** [comment]
Thanks for the help in getting this one off our list @dreamer !  Rounding up latest tests on my side too.

**Comment by kcgen** [comment]
On Windows 10 hardware, the Desktop's fade-effect causes it to fade-in with a white background. 

The PR right now is very minimal - but maybe we can try to eliminate this too (setting SDL's surface to black?); perhaps in a follow on PR.

**Comment by kcgen** [comment]
Whoah.. just for fun I hooked the boolean into WriteOutput, and it's essentially a `--quiet` mode:

``` text
void Program::WriteOut(const char * format,...) {
	if(!control->WantsBanners())
		return;

void Program::WriteOut_NoParsing(const char * format,...) {
	if(!control->WantsBanners())
		return;

```

The first SDL window is the game's window! No pre-console that flashes by.. 

```
[05:33:33@hoya meanstreet] d ms.exe 
dosbox-staging version git
---
CONFIG: Loading primary file dosbox.conf
OPENGL: Pixel buffer object extension: available
SDL: Mouse will move seamlessly without being captured.
MEMORY: Base address: 0x56533b10ae80
MEMORY: Using 4096 DOS memory pages (16 MiB)
MIDI: Opened device:none
MAPPER: Found no joysticks
SDL: Window has been shown
SDL: The window size has changed
SDL: Window has been exposed and should be redrawn
SDL: Window has gained mouse focus
SDL: Window has gained keyboard focus
SDL: Window is being offered a focus
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
MAIN: Emulator resolution: 640x480

 -- in the game --!
```
