### ISSUE TITLE
Gravis Ultrasound can't coexist with Sound Blaster 16

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#1446]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox (dosbox-staging), version 0.78.0-alpha-1091-g91d3d200+

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Gentoo

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It seems it is not possible to use Gravis Ultrasound in DOSBox when Sound Blaster is enabled in the configuration too. In such case GUS initialization fails (screenshot) and games are unable to play MIDI files using GUS patches (non-midi digital sound usually still works).

I didn't have any similar problems with similar configuration on PCem, so I assume it is valid and cards should be able to work together.

![screenshot](https://user-images.githubusercontent.com/48332137/146653516-dbf2ee1f-b5d3-4bc6-a05e-a7f51a05aa5c.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Enable Gravis Ultrasound in config, but not the Sound Blaster
2. Install GUS drivers 4.11 (latest version I know of) for DOS (ULTRINIT.EXE is version 2.28)
3. Enable Sound Blaster 16 (tried some other SB models, probably all of them trigger the problem), restart DOSBox
4. Execute **C:\ULTRASND\ULTRINIT.EXE -dj**
5. Result: GUS initialization fails (see the screenshot). Setting the BLASTER variable to the value defined by GUS software (for it's Sound Blaster emulation) does not help. Initialization succeeds again if Sound Blaster is disabled.

### Your configuration

```ini
[cpu]
core      = dynamic
cputype   = pentium_slow
cycles    = 10000

[sblaster]
sbtype  = sb16
sbbase  = 220
irq     = 7
dma     = 1
hdma    = 5
sbmixer = true
oplmode = auto
oplemu  = default

[gus]
gus      = true
gusbase  = 240
gusirq   = 5
gusdma   = 3
ultradir = C:\ULTRASND

[midi]
mididevice = none

[innovation]
sidmodel   = none

[serial]
serial1    = disabled
serial2    = disabled
serial3    = disabled
serial4    = disabled

[ethernet]
ne2000     = false

[autoexec]
@MOUNT C ~/.config/dosbox/drive_test
@PATH Z:\;C:\;C:\ULTRASND;
@C:

@C:\ULTRASND\ULTRINIT.EXE -dj
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
Found a workaround: use an older initialization program - search for ultrinit226a.zip, this one seems to work with dual-card setup on DOSBox.

**Comment by NicknineTheEagle** [comment]
> Found a workaround: use an older initialization program - search for ultrinit226a.zip, this one seems to work with dual-card setup on DOSBox.

That suggests it's a software issue rather than DosBox one. Would be nice to test this on real hardware.

**Comment by gmcn42** [comment]
I just ran into this problem in dosbox-x 0.84.2 and found this issue while googling for a solution. I know, different fork and all but I guess the GUS code might still be similar.

I did some digging into GUS docs, decompiled the ULTRINIT binary and used the dosbox debugger on it. The gist: It's a port conflict between the GUS and the OPL at 388h. Real cards *did* have a similar issue but this could be cured by running ULTRINIT which would succeed and (probably) deactivate the port on the GUS if SBOS won't be used. I can confirm this works on a real GUS classic in tandem with an ESS1688 (with OPL-compatible ESFM at 388h).

See [this VOGONS thread for more discussions about it on real hw](https://www.vogons.org/viewtopic.php?t=34408), apparently sometimes one needs to run ULTRINIT again after using a GUS game to get the OPL back but that's it.
What I gathered about what is going wrong in dosbox from decompilation and debugging:
* At some point, ULTRINIT 2.28 will try to write 0xAA to 388h (hard-coded) and read it back from GUS_BASE_ADDRESS+0x0A (24Ah in my case).
* GF1 seems to mirror what is written to 388h at 24Ah 
* If that happens, ULTRINIT is happy and goes on, if not, it will fail at that point
* On real HW this seems to work with a real OPL sharing the port because the write just goes to both devices, reading back does not conflict because port 24Ah belongs to GUS alone
      + This looks to me like it was intentional by Gravis due to the conflict-robust mirroring
      + Afterwards ULTRINIT seems to deactivate the 388h port on the GUS, SBOS will reactivate if loaded
* In dosbox the write to 388h seems to not reach the GUS if an OPL is present as well, the value read from 24Ah is 0x04 instead of 0xAA => ULTRINIT fails

**Comment by johnnovak** [comment]
Great investigation @gmcn42 , that's some very useful info! Seems like this will be an easy fix, after all.

**Comment by johnnovak** [comment]
Out of curiosity @FeralChild64 , what do you need `ULTRINIT.EXE` for? Most GUS supporting games only need the `ULTRASND` and `ULTRADIR` env variables set and the patch files present in `ULTRADIR` and that's it, no?

**Comment by FeralChild64** [comment]
Frankly, I don't remember now. Since then I have migrated a lot of games to use FluidSynth or Roland emulation.

**Comment by johnnovak** [comment]
> Frankly, I don't remember now. Since then I have migrated a lot of games to use FluidSynth or Roland emulation.

I'll play around with it and see if `ULTRAINIT.EXE` is really needed for anything.

**Comment by johnnovak** [comment]
The GUS and the AdLib at least can coexist at the same time in King's Quest IV: The Perils of Rosella Ultimate.
https://github.com/dosbox-staging/dosbox-staging/issues/3641

**Comment by FeralChild64** [comment]
Indeed, this works now. Thanks, @interloper98!
