### ISSUE TITLE
[BUG] New EGA changes for 1162 seems to have broken other machines.

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1463]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.78.0 1162

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I like whatever change was made to EGA mode. But, this change seems to have messed up the mode in every other machine.

I loaded up Space quest 2. The game goes into text mode to ask for your name. Looks good in EGA mode. But in any other mode the game screen is shrunk to half the height.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load space quest 2
2. Look at the opening few screens
3. Compare opening screens from EGA to any other machine

### Your configuration

```ini
I use my own custom CRT filter. It's Lottes, but not curved, and less pixel blurr. I tried to match the look of my Tandy 1000 on an ancient flat monitor.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks for the timely report @Jkapp76.  I reverted the commit.

Here's what I get for SVGA machine types, in Space Quest 2 (using zfast_crt shader):

![2021-12-24_10-41_1](https://user-images.githubusercontent.com/1557255/147369182-db9d32ec-7499-47ed-b9ed-053240fd6714.png)
![2021-12-24_10-41](https://user-images.githubusercontent.com/1557255/147369185-2ae1f977-68b8-4de2-83aa-6f8c12cf2d32.png)

And for `machine = tandy`:

![2021-12-24_10-42](https://user-images.githubusercontent.com/1557255/147369194-cf6f4f6d-38a0-431a-ac8a-dc7960c35432.png)

Glad you found some cases where it doesn't work - maybe with more testing, we can use this mode more selectively based on specific `machine=...` types - and use the original EGA mode otherwise.

**Comment by Jkapp76** [comment]
Your experience looks better than mine. My screen is crunched small in the middle of the screen.

![sq2_001](https://user-images.githubusercontent.com/89743985/147370576-524591cf-0fbb-4798-ac25-f1df44eb593d.png)

**Comment by kcgen** [comment]
@Jkapp76 , to help me reproduce this, are you using a specific machine= type? What about output= method? (Texture or OpenGL?). 

Ideally we could identify the specific settings where it breaks versus works.

**Comment by Jkapp76** [comment]
svga_s3 machine has this issue with 1162
opengl
using Lottes crt filter for scanlines.

EGA looks great, Tandy looks good. so far I only saw issue with svga_s3. EGA shrinks text mode on space quest 2, but looks great that way.

**Comment by Grounded0** [comment]
I wonder if this related to changes in these modes in our new S3 Trio64 code to fix the aspect ratio to be perfect?

**Comment by Jkapp76** [comment]
the newest version works perfectly. I didn't know you tweaked S3 Trio

**Comment by Grounded0** [comment]
0.78.0 has a completely new S3 Trio64 code with support for up to 8MB of VRAM. We did some improvements on it regarding aspect ratios particularly in these AGI games.

**Comment by Jkapp76** [comment]
the version previous to 1162 did not have this issue.

**Comment by Grounded0** [comment]
You could help us out to isolate this problem so we can enable "don't double line EGA 320x200" later with that problematic build.

**Comment by Jkapp76** [comment]
Let me know how I can help.
