### ISSUE TITLE
[BUG] Composite CGA modes do not allow scanline Shaders

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1492]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Relevant hardware info

nvidia geforce

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I use the CGA and PCJr composite modes a lot and have noticed these composite modes do not allow Shaders that make scanlines. I think the scanlines make these composite modes look best. the lines seem to elliminate the blurring very well.

I've been experimenting with Scanline shaders on 86box and include a few screenhots here. The screenshot feature omits the shader so I took pictures of the screen with my phone, sorry.

The games are Kings quest booter, BC quest for tires, Donkey Kong and Zaxxon. The scanlines seem to improve the picture and cut out some of the weird blur.

![20220102_171933](https://user-images.githubusercontent.com/89743985/147891228-43cf21c2-3877-49e8-b63b-41968c0a2949.jpg)
![20220102_171939](https://user-images.githubusercontent.com/89743985/147891229-499ccd25-d3c2-42f4-816f-00199b2d1d0d.jpg)
![20220102_172014](https://user-images.githubusercontent.com/89743985/147891232-f72a2643-003c-4cad-8c38-9dea21aa529f.jpg)

![20220102_172103](https://user-images.githubusercontent.com/89743985/147891239-69625985-fc28-4309-8bfd-a49bf005978e.jpg)
![20220102_172117](https://user-images.githubusercontent.com/89743985/147891241-d0b6e286-6f5b-4da8-8974-da557e4599d8.jpg)

![20220102_172302](https://user-images.githubusercontent.com/89743985/147891247-153c5683-55f9-441e-aa63-5d020f9eb41d.jpg)
![20220102_172315](https://user-images.githubusercontent.com/89743985/147891248-6805c241-8247-4f5a-8989-019875c94819.jpg)
![20220102_172518](https://user-images.githubusercontent.com/89743985/147891249-71f8e960-29ae-4035-bdec-39f5ca7a2727.jpg)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
GL Shaders work, and some look quite nice and produce a similar effect:

## Donkey Kong
![2022-01-02_16-15](https://user-images.githubusercontent.com/1557255/147893541-27290822-5c92-4af8-9cb5-cf116e13e7ef.png)
![2022-01-02_16-42](https://user-images.githubusercontent.com/1557255/147893540-046454ae-5473-4981-9151-45ce27f1a942.png)

## KQ2
![2022-01-02_16-12](https://user-images.githubusercontent.com/1557255/147893537-684c535a-e458-4bb5-bc36-828e8a6d94bf.png)
![2022-01-02_16-40](https://user-images.githubusercontent.com/1557255/147893536-3bf355e2-4d39-49e6-8d2f-71a4341b3f83.png)


## Jungle Hunt
![2022-01-02_16-39](https://user-images.githubusercontent.com/1557255/147893534-3f9c794e-d25b-4187-8e2d-b86b8b98ad58.png)
![2022-01-02_16-43](https://user-images.githubusercontent.com/1557255/147893532-f43f9ad3-4452-4fc8-b5e6-cf0d3fb802b1.png)

There are quite a few to choose from in Tyrell's repo:
``` text
crt-aperture.glsl
crt-caligari.glsl
crt-cgwg-fast.glsl
crt-easymode.glsl
crt-easymode.tweaked.glsl
crt-geom.glsl
crt-geom.tweaked.glsl
crt-hyllian-3d.glsl
crt-hyllian.glsl
crt-hyllian-updated.glsl
crt-lottes-fast.glsl
crt-lottes-fast.subtle+gain.glsl
crt-lottes.glsl
crt-lottes.tweaked.glsl
crt-mattias.glsl
crt-nes-mini.glsl
crt-pi.glsl
crt-pi-vertical.glsl
fakelottes.glsl
fakelottes.tweaked.glsl
pixellate.glsl
pixel_perfect.glsl
pixel_perfect-scanlines.glsl
ScanLine.glsl
smuberstep-glow.glsl
xbr-lv2-3d.glsl
xbr-lv2.glsl
xbr-lv2-noblend.glsl
xbr-lv3.glsl
yee64.glsl
yeetron.glsl
zfast_crt.glsl
```

They all need `[sdl] output = opengl`, but some work best with `openglnb`, others need softer input `opengl`, and some look best with integer scaling, so `openglpp`.  

Another thing to note is that most shaders multiply up from the original resolution by 2x2 but others go up by 4x4.  The nuance here is that composite mode itself acts somehwhat like a shader, in that it already runs at double the original 320x200 resolution: so you're "starting" with a 640x400 or 640x480 image, and then going up from there. 

So you might find some shaders simply don't do anything because they need such a large `windowresolution = ` to scale into. I use a 4k desktop with `windowresolution = large`, and of the shaders work.

Hopefully you find something! https://github.com/tyrells/dosbox-svn-shaders
