### ISSUE TITLE
Tyrian: Crackling SFX with Gravis UltraSound and some with music; both FluidSynth and GUS

### ISSUE THREAD

**Issue by RavenMacDaddy** [dosbox-staging/dosbox-staging#1524]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Relevant hardware info

DAC: RME ADI-2 DAC | Speakers: EVE Audio SC205

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Running Tyrian with GUS selected for SFX will produce sound that's constantly crackling.

This is both in its setup and when running the game, and since there are no parameters for GUS to adjust regarding its playback of sound, I've not been able to troubleshoot that component specifically - but with this said, comparable amount of crackling is present in the DOSBox-X fork and therefore the issue seems to be the core of DOSBox and not for example some fork specific enhancement.

I also noticed some instruments crackling depending on the soundfont that's being used with FluidSynth.

Using GUS as the music device also seems to crackle a whole lot, which is worth noting.

Changing the blocksize to 1024 and the prebuffer to 25 (as well as other values for the mixer to rule that out) according to the known issues list doesn't help at all it seems.

For reference I've also tried with the default rate of 48kHz, although I otherwise run with 44.1kHz when I'm not troubleshooting.

I've confirmed that the emulation is at a rock-solid 100% all the time with auto cycles always choosing 'max' as the setting.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. The game is freeware - see either [GOG](https://www.gog.com/game/tyrian_2000) or Jason Emery's (developer) dedicated site [here](https://www.camanis.net/).
2. Run setup.exe
3. Turn off either Music or SFX depending on what you want to troubleshoot/reproduce.
3. For GUS, change SFX playback to Gravis as the device, then navigate around the menu with Up and Down on the keyboard to easily notice the crackling just from those small SFX.
4. For MIDI, use FluidSynth with for example the recommended SF Arachno and try playing different songs. With the SF Arachno, song 11 in the setup's Jukebox most consistently crackled, while other soundfonts might crackle with instruments used in other songs - so keep that in mind.
5. Also try GUS as the music device for reference regarding that part of the issue.

### Provide a Log

[GUS log](https://gist.github.com/RavenMacDaddy/275624b3d4d72fcc0010f07680c7e72e#file-gus-log)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by RavenMacDaddy** [comment]
I'll try to adress your concerns and questions as they were written;

- I was actually pondering if I should specify which sound setup I'm using, cause I highly doubt it's making any difference and only posted it for reference - though I completely understand your thinking.
- Changing the sampling rate to the emulator's default 48kHz and matching that for the sound device doesn't have a positive impact - if anything it makes things worse since crackling is quite high regarding frequency.
- DOSBox vanilla behaves the same, possibly crackling a bit less - but definitely crackles consistently all the time.
- Other emulators and games using SDL are working just flawlessly.
- Jazz Jackrabbit using GUS for both music and SFX in DOSBox Staging works just great.
- RetroArch is something I'm not using as I like to have all my emulators individually rather than in the same package sharing a lot of settings and operation.

**Comment by kcgen** [comment]
Thanks for this report @RavenMacDaddy .

My hunch is that there's a problem with the game's GUS audio driver/mixer, because the cracking is present even if we disable the music and reduce the SFX volume to the lower possible level, using these settings:

![2022-01-13_17-24](https://user-images.githubusercontent.com/1557255/149436051-6aebbe7b-f8e7-4277-baa9-62ab65e97198.png)

To test this, now crank up your PC volume (yes - quite loud!) so you can hear the effects: they will still contain pops and crackles.

Staging keeps track of the loudest samples played for the entire lifetime of the process - and in the above case, it reports GUS only achieved 3% of the peak volume:

![2022-01-13_17-34](https://user-images.githubusercontent.com/1557255/149436224-01821f95-ef04-4b9b-970f-bdeab0aeab50.png)

With such low sample amplitudes, there's no risk of clipping or truncation. 

I also disabled the other audio devices to ensure errant audio signals weren't coming into play:

``` ini
[speaker]
pcspeaker=false
tandy=off
disney=false

[sblaster]
sbtype=none

[midi]
mididevice = none
```

If we take a closer look at the signal, we can see the discontinuities:

![2022-01-13_17-32](https://user-images.githubusercontent.com/1557255/149436048-4b37725a-6459-48e1-a315-8e382499d28b.png)

Notice the curve isn't close to the top and bottom edge; there's still ~20% headroom available.  So my hunch is the clipping is occurring inside Tyrian prior to it sending the samples into the GUS for playback.

If someone has a physical GUS card, they could verify this is the case.

**Comment by kcgen** [comment]
Even with the sound blaster disabled, it appears that Tyrian is using some kind of SB-compatible mode when using the GUS:

![2022-01-13_17-52](https://user-images.githubusercontent.com/1557255/149437861-ecab50a4-a46a-45c6-b21e-6afad125a338.png)

**Comment by RavenMacDaddy** [comment]
Very interesting stuff. 

Thank you for the analysis and insights so far @kcgen.

**Comment by RavenMacDaddy** [comment]
I would also expect the same for Windows Sound System in that case, even if that's not possible to test at the moment. Is that kind of support something on the roadmap by the way; WSS that's?

**Comment by kcgen** [comment]
WSS was very much like a Sound Blaster 16 "value edition": simple 8-bit and 16-bit PCM output + OPL3 FM support. Because it would be using PCM output, I would imagine Tyrian's WSS drivers would behave like its Sound Blaster driver, and sound exactly the same as if Tyrian was configured for Sound Blaster.

Tyrian's PCM samples are only 8-bit + stereo + <22 KHz, so there's no differentiation any of these cards can offer.  (If Tyrian has 48 KHz samples: OK, WSS would add value.  If Tyrian has a 24-channel MOD-style music? OK: GUS would sound great).

**Comment by RavenMacDaddy** [comment]
Once again, appreciate your insight - it's very interesting for me personally.

**Comment by kcgen** [comment]
I think we're as far as we can go here; suggest this be closed. 

PS- Was reading a bit more about Tyrian, and it's music was composed for OPL3, so although it's interesting to hear how its drivers convert the FM music to MIDI equivalents (and as a further conversion to Ultramid's MIDI instruments banks), the optimal listening would be with SB16 or the SB Pro2.  Both offer OPL3, and we know Tyrian's sound effects aren't 16-bit/44 kHz, so no harm in using sbpro2!
