### ISSUE TITLE
Incorrect timing behavior during active loops.

### ISSUE THREAD

**Issue by CrazyMoai** [dosbox-staging/dosbox-staging#1547]
Hi I'm developing a DOS game. 

I've an active loop as part of my frame rate control system. It waits for a volatile value to be incremented by the timer interrupt to let the program continue without speeding up in fast machines.

The framerate controlling system works fine in both real hardware and 86box, however dosbox staging seems to be slowing itself down when the "infinite" loop is detected and get's out of it much more slowly.

I've tested that the volatile value increases at expected rate if I don't use the active loop to check for it (for example if I rely on Vsync for timing). It is only when I check for it in a closed loop that this slowdown behavior happens. Seems like some kind of battery saving optimization working badly.

I'm using version 0.78.1 in windows 10 64bit

**Comment by kcgen** [comment]
![2022-01-27_08-48](https://user-images.githubusercontent.com/1557255/151404827-1f48600f-5b48-4906-a63c-daf6dfff434f.png)

There isn't a single reference to the word "battery" in:
 - the documentation
 - the code base
 - the last 20 years of commit comments

But.. I'm glad you've made an zero-effort assumption and simultaneously told us our code is bad in said assumed area - and you're asking for help.

That's called "getting off on the wrong foot" :laughing:

**Comment by kcgen** [comment]
Try using fixed cycles.

You can search for that term, "fixed cycles" in the README.

**Comment by CrazyMoai** [comment]
It's Ok, don't mention it. 

I'm a dev myself and I know it gets annoying to receive bug reports that point at issues without any real knowledge of how the thing works.

In this case, my phrase about the battery thingy was a "It feels like something like this", in case it is useful, not a " I STATE the problem is this". But it's clear that I failed to bring the point across correctly.

In any case using fixed cycles seems the solution. Thanks for pointing it out. I though I had already tried that but turns out after rereading the documentation I was just writing a number in the conf file without adding the "fixed" word first.

Btw, by no means do I think that the emulator code is bad. It's great! And it would not be less great If had really found a bug on it, no software is perfect.

Thanks for your help and for your work.

**Comment by kcgen** [comment]
Thanks for talking through those wording nuances, @CrazyMoai 

> In this case, my phrase about the battery thingy was a "It feels like something like this", in case it is useful, not a " I STATE the problem is this". But it's clear that I failed to bring the point across correctly.

The discussion about the wording turned out to be helpful for both of us! 

In my buttoned-up non-confrontational Canadian culture, the shorter form, _"Seems like the problem is .."_ is as close as people get to saying, _"I STATE the problem is"_ (which I've never experienced).  So the prior form is interpreted as such. Where the longer form _" I'm just guessing / for-what it's worth / if it's of any value"_  become a helpful and inquisitive remark, which removes any doubt about intent (and I believe I would have taken it correctly as you've intended).  But those nuances are my issues - the literal interpretation is well-meaning. :+1: 

Glad it's working now, and hope your games comes along well!

I wanted to mention that some games, like Jazz Jackrabbit can maintain a steady 70 FPS and (at least from what I'm seeing) don't consuming a lot of CPU cycles  - perhaps using something other than a busy/infinitite loop?.  I'm a game dev, but just mentioning that there might be other frame-pacing approaches.
