### ISSUE TITLE
Sound studders in Space Quest 4 (sounblaster_adlib)

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1559]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

I've tried the latest 78.1 release and the betas

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I set the Space Quest 4 Talky Version's sound settings to "soundblaster/adlib" and the intro music and later music stutters badly.

I set the cycles to=max and the sound is good.

However, other DOSBox builds like ECE and DOSBox-X sound great at my usual 8000 cycles. Staging has to be set very, very high to sound good. Even my 94000 cycle setting I sometimes use stutters with Staging.

I'm not sure if this qualifies as a bug or whatever, but it's unusual.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set the game's sound to soundblaster/adlib
2. Set cycles anywhere, even as high as 94000
3. Load the game and listen (the intro animation could be choppy too)

### Your configuration

```ini
I do use shaders, but I have no issue with dosbox-x or ECE.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Jkapp76** [comment]
I found an easy fix for this. I changed "vsync" to "off" and it plays perfectly.

If no one else had this issue it may be because the default setting is "off."

**Comment by Jkapp76** [comment]
Sounds good. I think the only reason this game worked perfectly on dosbox-x and ECE is because they don't have vsync as an option.

**Comment by Kappa971** [comment]
When I had a 60hz monitor with forced vsync from the video card control panel on different versions of DOSBox (vanilla, ECE, X, etc), the emulator didn't work well (especially the audio was starting to stutter). The solution was to turn off vsync and live with tearing or set the monitor to a supported 70hz mode. Another solution is to buy a FreeSync/G-Sync monitor. I think the problem here is that many DOS games run at 70hz, but many people today own 60hz screens. I don't think DOSBox Staging can solve this problem, or am I wrong?

**Comment by kcgen** [comment]
The latest builds should have this fixed now, with vsync=true in the conf and vsync forced-on in the drivers panel.
