### ISSUE TITLE
ARM64 build for Windows as well

### ISSUE THREAD

**Issue by holaimscott** [dosbox-staging/dosbox-staging#1599]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

NO, ut it would be more helpful to have a native ARM build of DOSBox Staging for Windows as well (specially since that one is also available for other OSes)

### Describe the solution you'd like

If an ARM build for DOSBox could also be available for folks in Windows

### Describe alternatives you've considered

Or if there is any ARM Win build instructions available for people.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@holaimscott ,

GitHub currently doesn't have ARM64-based Windows workflow runners for us to build on.

But if you have such a system, you could try by adapting the notes here: https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/build-windows.md#build-using-msys2, but knowing that your packages with use `aarch64` instead of `x86_64`:

![2022-03-24_22-36](https://user-images.githubusercontent.com/1557255/160060977-526fb2de-9688-4779-8270-4c3692fbc4d3.png)

So for example, where the notes mention 

``` shell
pacman -S $(cat packages/windows-msys2-clang-x86_64.txt packages/windows-msys2-gcc-x86_64.txt)
```

You would just use clang and replace all the `-x86_64-` architecture strings with `aarch64`:

``` shell
pacman -S $(sed 's/x86_64/aarch64/g' packages/windows-msys2-clang-x86_64.txt)
```

Assuming that works, you would then have a new Clang aarch64 terminal available in:
 - Start Menu > Programs > MSYS2 > MSYS2 MinGW Clang x64

After which (maybe?) the rest of the steps would go as already written.

References:
 - https://www.msys2.org/docs/environments/
 - https://packages.msys2.org/group/mingw-w64-clang-aarch64-toolchain

If you manage to get it built, we could includes similar

**Comment by shermp** [comment]
Also, I've just pushed an experimental branch to see if MSVC will cross compile for us. We'll see what happens.

**Comment by Burrito78** [comment]
The users issue was helped. We will get these as soon as GitHub gives us the ability and there is a need.

**Comment by kcgen** [comment]
@holaimscott : did you attempt to build it on your ARM windows machine using either VisualStudio or using MSYS2 and Clang, using the notes above?
