### ISSUE TITLE
Switch to using a proper audio resampler

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1673]
Related to https://github.com/dosbox-staging/dosbox-staging/issues/1662
Prerequisite to implementing sound-card specific output stage filtering

The current audio resampler uses simple linear interpolation, which is the second worst way to resample audio (after nearest-neighbour). It acts as a bad lowpass filter, which makes implementing proper analog output stage filtering near-impossible for the different soundcards.

The plan is to introduce SpeexDSP, which is a fast real-time audio resampler that maintains high perceptual sound quality. It's used in VLC, PULSE audio, ALSA, etc. Probably the overall best high-quality real-time resampler. I've measured the latencies, it's around 1ms when using good quality resampling (from anything to 48k).

https://github.com/xiph/speexdsp/

Some quick facts:

- Revised BSD license
- Debian & vcpkg available
- Has optimised paths for ARM NEON and Intell SSE2

**Comment by kcgen** [comment]
> The plan is to introduce SpeexDSP

Excellent! It's a great all-rounder with a nice interface.

**Comment by johnnovak** [comment]
From `AddSamples` onwards, we'll work with float streams exclusively. This is needed for implementing proper filters and the chorus and reverb effects, it makes life so much easier, and I have my doubts about the current fixed-precision jiggery-pokery being any faster on current hardware anyway... (I'd bet on it it's actually slower on desktop CPUs). Then we convert the final float mixbuffer back to `int16` *once* as the very last step.

The current linear interpolation resampling mechanism ("interpolate") will be completely gone, replaced by a two-stage process where both stages are optional:

- `zeroOrderHold`: if enabled, upsample the signal from the channel rate to the `zeroOrderHoldFrequency` rate using simple sample-and-hold (the current "no interpolation" path in `AddSamples`). This is needed for emulating the crummy output of pre-SB16 Sound Blaster boards with their questionable (but characterful!) "anti-alias filters".

- `zeroOrderHoldFrequency`: target frequency of the zero-order hold resampling (the DAC rate, effectively).

- `resample`: performs a proper resampling from the channel rate (or the zero-order-hold output rate, if it's enabled) to the host rate via SpeeX, which applies a brickwall filter at half the channel sample rate

In theory the zero-order-hold stuff could be done in `sblaster.cpp`. But in practice that would be at least 10 times more complicated, so I'll just do it in the mixer.

**Comment by kcgen** [comment]
> From `AddSamples` onwards, we'll work with float streams exclusively.

Makes sense!

> In theory, the zero-order-hold stuff could be done in sblaster.cpp. But in practice that would be at least 10 times more complicated, so I'll just do it in the mixer.

Good call.. the soundblaster implementation makes smart use of the mixer's various sample format output calls, which on the flip side makes post processing challenge without some design changes in it; makes a lot more sense to apply post processing in the mixer at that single collection point for it's samples. 

> sb1: .. upscale to ~23kHz rate. 

Game drivers set the SB1 PCM rate from 4000 Hz up to 23000 Hz (less for ADPCM encoded data) before transferring. I guess the card would then upsample the data to it's DAC rate, and that's the number you're trying to find? Most games of this era used 8 KHz PCM data, if that's of any help.

> PS1: yes, with speex available, it will make sense to leverage that and run the source signal at a higher rate. This can be considered out of scope of this though, but will be nice to have these options! (Same with the others.. could drop the sincresamplers and let speex handle the downsampling). 

> CD audio:

There are a couple pathways; for bin/cue, the data is  always 44.1 KHz / 16bit / stereo, but for compressed audio files, like FLAC, other rates, bit depths, and mono are fine too. We use DOSBox's resampler to handle their rates (whatever they might be). 

> In any case, probably it's best to switch to the new resampler.

Roger that: resample from 44.1 KHz in the bin/cue case, otherwise resample from whatever the source data is running at to the mixer's rate.

**Comment by johnnovak** [comment]
> I guess the card would then upsample the data to its DAC rate, and that's the number you're trying to find?

Exactly. The pre-SB16 cards appear to always upsample to the max frequency rate of the DAC by using the simplest & cheapest method possible ("strech" the stream by holding individual samples a bit longer), then send that through the fixed lowpass filter and call it a day. For the SB 2.0 and Pro models it's 45454Hz, but the SB 1.0 & 1.5 only support up to ~23kHz rates. 45454 / 2 = 22727 Hz seems pretty likely and logical, so I'll go with that for now. In any case, even if that's off by a few percents from the real rate, it wouldn't make much of a practical difference.
