### ISSUE TITLE
Reconsider '-Weffc++' warnings

### ISSUE THREAD

**Issue by shermp** [dosbox-staging/dosbox-staging#1695]
Could we reconsider enabling `-Weffc++` especially on GCC? GCC seems rather overzealous on `initialized in the member initialization list` where clang is perfectly happy.

I'm generally a fan of warnings, but I think `-Weffc++` has marginal value these days of modern C++, and I'm not sure how fair it is to report `-Weffc++` warnings to upstream projects.

For example, GCC will complain about
```cpp
struct a {
    std::string s;
}
```
Despite the fact that `std::string` has a perfectly valid default constructor.

**Comment by kcgen** [comment]
> seems rather overzealous on initialized in the member initialization list <snip>. For example, GCC will complain about (std::string) despite the fact that `std::string` has a perfectly valid default constructor.

The general best practice recommended by Scott Meyers and in other places (https://www.learncpp.com/cpp-tutorial/default-member-initialization/) is to always explicitly initialize members.

``` c++
struct Something
{
    int x;       // no initialization value (bad)
    int y = {};    // value-initialized by default
    int z = 2; // explicit default value
};
```

It's less about trying to figure out if the underlying class structure will eventually provide a default constructor or not (and therefore, relieves the programmer of having to be explicit).

It's about always be explicit.  There's no doubt, then, what the programmer intended.

For example, in the inconsistent non-explicit approach, I might see:

``` C++
struct a {
    std::string s;
}
```

And think, ahh, I can assume the programmer knows that the `std::basic_string` is provided a default constructor, so they really know what they're getting by default.

But then if I see:

``` C++
struct a {
    std::string str;
    char * c_str;
}
```

I think, uhhh.. in this case, did they just forget to initialize the pointer? Or did they actually forget to initialize both?

``` C++
struct a {
    std::string str = {};
    char * c_str = nullptr;
}
```

Ok - no more assumptions or guessing.

> I think -Weffc++ has marginal value these days of modern C++

`-Weffc++` warns about violations of the following style guidelines from Scott Meyers’ Effective C++ series of books:
 - Define a copy constructor and an assignment operator for classes with dynamically-allocated memory.
 - Prefer initialization to assignment in constructors.
 - Have operator= return a reference to *this.
 - Don’t try to return a reference when you must return an object.
 - Distinguish between prefix and postfix forms of increment and decrement operators.
 - Never overload &&, ||, or ,. 

I'd rather catch these automatically via CI instead of us reviewing the code and having to sweat these details in every PR review. 

> I'm not sure how fair it is to report -Weffc++ warnings to upstream projects.

Sure - maybe some don't care and can blast us back "I don't care about the warnings, especially not Scott Meyer's effective C++ warnings!" :zap: 

But some upstream projects care about all the warnings, even `pedantic`.  I haven't seen any upstream push back on these yet - and they can always just close the issue and tell us to take a hike (Cool, we won't submit them again).  Not a big deal.

Even if an upstream project is happy to violate Scott Meyer's suggestions, is that justification for us to also remove this flag from our CI chain? (Nahh.. because at least one maintainer (myself) thinks they're a bit valuable :sweat_smile: )

**Comment by shermp** [comment]
Interesting, no wonder Clang doesn't care:

> [-Weffc++](https://clang.llvm.org/docs/DiagnosticsReference.html#id263)
> Synonym for [-Wnon-virtual-dtor](https://clang.llvm.org/docs/DiagnosticsReference.html#wnon-virtual-dtor).

I've seen comments that GCC's `-Weffc++` is based on the first edition of the guide, which was written in the 90's, and has been heavily revised in later editions of the guide, and apparently it's buggy to boot: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81930

**Comment by kcgen** [comment]
It reliably catches uninitialized members.
 - Given the option of having PRs full of non-initialized members versus those that are fully initialized, I'd rather the latter.

It reliably catches classes that have pointer members but are missing copy and assignment operators. I remember those helping fix at least one assignment issue early on, I believe in the batch files. It was generating a sanitizer issue (but never actually crashed because the copied pointer still was pointing to valid memory because the other object never deleted it in its destructor.)

So I'd rather have it catching those classes too.

The other thing to consider is if it's annoying -  Jonathan Wakely  says is loaded with problems: but at least on our use case, it tends to warn about are the two issues I mentioned.  

If it was recommending non-sensical C++98 syntax or spewing false positives (or stuff we had to visually ignore) -- absolutely, I would pitch it.

But it's providing actual value with literally no downsides.

**Comment by kcgen** [comment]
One of the most common things  `-Weffc++` complains about is uninitialized members, and it turns out this is exactly what caused [unstable math calculations](https://github.com/TexZK/YM7128B_emu/pull/1) in the Adlib Gold PRs, which came close to derailing this pursuit.  With that data point fresh on the mind, will close this ticket.
