### ISSUE TITLE
Codepage doesn't switch back to 437 after using 858.

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1880]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Codepage can be changed to 858 but not back to 437 afterwards (858 is an example).

### Steps to reproduce the behaviour.

-Change the active codepage using 'keyb gr' to 858. 
-See change in font in DOSBox info box (kerning of 'f' character, width of 'v' character).
-Try to change codepage back using 'keyb gr 437' or 'keyb us'.
-The codepage doesn't change back.

### Your configuration

```ini
default config
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
Are you sure it does not set 437 back? Try to type some letters not available on CP 437 (right ALT + e produces euro sign, available in 858 only), press enter so that characters stay on the screen, switch back to 437.

Note, that if you ask to load code page 437, it takes it from FreeDOS CPX files; if I understand correctly, there is some ROM character set used by emulator if no code page is loaded, and it differs in appearance from FreeDOS 437 set.

**Comment by Grounded0** [comment]
CP850: https://github.com/dosbox-staging/dosbox-staging/files/9264222/cp850.zip
CP437: https://github.com/dosbox-staging/dosbox-staging/files/9264342/cp437.zip

If character designations and printed characters don't match then codepage and font don't match.
