### ISSUE TITLE
New windows installer user study with a first-time user

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1923]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

First time use of new Inno based installer on Windows 10 by a new user that never used DOSBox before.

### Add any other context or screenshots about the feature request here.

The test user is a 40 year old male with computer experience (Windows/Linux) and working in a technical support job.
He's my colleague, an engineer and a pretty intelligent guy.
He used DOS and Windows 9x back in the day to play games and work.
He never used DOSBox before.
We said he had 10 Minutes to get the game running so no long reading sessions involved during this.

Lets start!

Slight confusion: Do we really want to install to C:\ or would it be better to use "Program Files"?

![IMG_0421](https://user-images.githubusercontent.com/61995128/189856439-dc62ff56-7525-4454-a43c-68003c9f28a8.jpeg)

Not shown: Staging starts up with the Status Window (Log) open by default on Windows. Thats too much information for normal users.

He stopped and asked me what he should do next on this screen:

![IMG_0422](https://user-images.githubusercontent.com/61995128/189857963-09a19afb-0d67-4167-9dd1-406794d9f1ba.jpeg)

After a short while he came to the conclusion to maybe type 'intro'.
Intro gives back too much information and it still wasn't clear what to do next.
I then told him he had to mount a folder with the game on a provided USB stick to use it inside DOS.
He then entered 'intro' again and then 'intro mount' to get more information.

Note: The next screen was broken on Windows because of line length, it's been fixed already.

![IMG_0424](https://user-images.githubusercontent.com/61995128/189858913-987ee7bb-dd73-4d6a-9b44-7b034848128d.jpeg)

It was confusing if the first drive letter is the DOS or physical drive.
It was confusing that 'mount c e:' didn't work (the correct command is 'mount c c:\'):

![IMG_0425](https://user-images.githubusercontent.com/61995128/189859629-cf19d8d2-c7bc-4f1c-b6fa-832a83a9a936.jpeg)

After the mounting was completed, he got the game running 10s later.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Kappa971** [comment]
> Slight confusion: Do we really want to install to C:\ or would it be better to use "Program Files"?
> 
> ![IMG_0421](https://user-images.githubusercontent.com/61995128/189856439-dc62ff56-7525-4454-a43c-68003c9f28a8.jpeg)

I think `Program Files` is the best solution.

> Note: The next screen seems to be broken on Windows, it works fine on macOS which i use to translate.
> 
> ![IMG_0424](https://user-images.githubusercontent.com/61995128/189858913-987ee7bb-dd73-4d6a-9b44-7b034848128d.jpeg)

The text probably exceeds the maximum 80 columns.

**Comment by Grounded0** [comment]
<img width="609" alt="Screenshot 2022-09-13 at 14 50 53" src="https://user-images.githubusercontent.com/48192273/189926975-357f2133-2591-420e-9a57-c667a4cda58c.png">
<img width="1296" alt="Screenshot 2022-09-13 at 15 14 30" src="https://user-images.githubusercontent.com/48192273/189926992-b25f9909-1dd1-41b5-a961-7ec82614761b.png">

Should be "Program Files" in any of the languages:

At system startup, the actual paths to 'Program Files' and 'Common Program Files' are loaded from the Windows registry, where they are stored in the ProgramFilesDir and CommonFilesDir values under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion. They are then made accessible to the rest of the system via the volatile environment variables %ProgramFiles%, and %CommonProgramFiles%. Applications can also obtain the locations of these paths by querying the Setup API using dirids, or through Windows Management Instrumentation, or by querying the shell using CSIDLs, or ShellSpecialFolderConstants. These are all localization-independent methods.

If DOSBox SVN opens up this status window by default on Windows then we should open it too... It's a bit excessive for normal users but we want to be just like DOSBox SVN

After "Program Files" default path is added it's good to go at least in English and on first run config -wc is ran and writes conf file.

**Comment by Kappa971** [comment]
> Should be "Program Files" in any of the languages:
> 
> "At system startup, the actual paths to 'Program Files' and 'Common Program Files' are loaded from the Windows registry, where they are stored in the ProgramFilesDir and CommonFilesDir values under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion. They are then made accessible to the rest of the system via the volatile environment variables %ProgramFiles%, and %CommonProgramFiles%. Applications can also obtain the locations of these paths by querying the Setup API using dirids, or through Windows Management Instrumentation, or by querying the shell using CSIDLs, or ShellSpecialFolderConstants. These are all localization-independent methods."

Yes, "Program Files" in English, "Programmi" in Italian, etc... 
I think DOSBox 0.74 is installed in "Program Files (x86)" (but it is a 32 bit program).

> After "Program Files" default path is added it's good to go at least in English and on first run config -wc is run and writes conf file:
> 
> <img alt="Screenshot 2022-09-13 at 15 14 30" width="1296" src="https://user-images.githubusercontent.com/48192273/189926992-b25f9909-1dd1-41b5-a961-7ec82614761b.png">

I think DOSBox already writes the configuration file in English at the first start (if this is not already present).
It would be useful for other languages but currently it doesn't work well.

**Comment by Wengier** [comment]
Thanks for the study with an actual user for the installer! For the default installation directory, there were concerns about permission issues, since for example you cannot install or write to "C:\Program Files" unless you run it as an administrator, but after some discussions in Discord (especially an suggestion from @shermp) we decided to let the installer show a dialog asking whether to install DOSBox Staging for the current user or for all users, and it will be installed to "C:\Program Files" if it is installed for all users. You can download the updated Windows installer here:

https://github.com/dosbox-staging/dosbox-staging/suites/8278845595/artifacts/362586237

The new version now has three shortcuts for DOSBox Staging in the Startup Menu group, including "Run DOSBox Staging", "Run DOSBox Staging with console", and "Run DOSBox Staging with debugger". The first one no longer starts up with the console window open by default, but if one wants to see logs (e.g. when reporting issues), they can run DOSBox Staging using the second (or third) shortcut for this.

The new installer is also now rebased against the latest main code, which has the latest translations. The previous installer was not yet rebased against the latest main at that time since I considered that rebasing was automatic once merged into main, but considering that some may simply want to try the latest main code, I did manual rebasing for this. You can try the updated installer which now includes the latest main code. Thanks again for testing!

**Comment by Burrito78** [comment]
From Discord:

@Wengier OK, did try it, here are my findings:

1. I had the older version still installed so this was the result:
     - Old folder C:\dosbox-staging is still shown in selection dialog
     - One DOSBox Staging icon on the desktop, one DOSBox Staging with console in the start menu, nothing else.
     - No message saying "Old installation found! Do you want to update or reinstall?"
     - No message shown "Install for all users or just for you?".

2. I then removed the old version and did a fresh install:
     - 3 Icons are created in start menu and one normal icon on Desktop
     - Asks if i want to install for all users or just for me.
           - All users installs to correct path but is shown incorrectly in the UI as "Program Files" i'm on a german windows so it should display "Programme".
           - Just you installs to the user profile, i think thats expected too.

3. Lauch with Console icon and normal icon launch the respective versions of DOSBox.

Imho the worst offender is that "Program Files" is shown in the dialog where it should be the localized version e.g. "Programme"!

**Comment by Grounded0** [comment]
Connected ticket:

- #1920

**Comment by Wengier** [comment]
@Burrito78 Thanks for the further test. Only the old (now obsolute) installer once installed to c:\dosbox-staging, but all future installer will hopefully install to {autopf} by default as defined by Inno Setup, which means %ProgramFiles% if installed as administrator, and user program directory if installed as current user. Hopefully the change in default directory is made once for all so that there is no further need to be changed again. But of course the user can manually adjust the install directory if a different directory is desired by the user. The directory "Program Files" is not hard-coded in the installer; instead as mentioned earlier it is automatically expanded by Inno Setup, and I don't personally have a non-English Windows to test at this time. @Grounded0 and I thought that changing the Windows system language/locale may help reproduce this, but unfortunately the system %ProgramFiles% remains "C:\Program Files" in such cases. Perhaps it is recommended to install as the current user in such cases (the user program directory will be installed to by default) and you did see the following dialog for selecting the install mode when you make a fresh installation :

<img width="354" alt="image" src="https://user-images.githubusercontent.com/8216923/190314139-93587878-ed4a-4931-8f20-9c9cfc036a72.png">

**Comment by Burrito78** [comment]
@Wengier I think all your questions should be answered in my post above:
https://github.com/dosbox-staging/dosbox-staging/issues/1923#issuecomment-1247102974

One problem still remaining is that Inno doesn't ask if you want to upgrade or reinstall.

And of course the bug that Inno can't properly replace %ProgramFiles% with the proper german language string in the UI on a german Win10 Pro.

**Comment by Wengier** [comment]
@Burrito78 The 0.79.0 release is intended as the first version of DOSBox Staging to use the Windows installer, so there is really no “upgrade” option for it. You can either install anew or reinstall it, but not upgrade from a previous version. As for thr %ProgramFiles% expansion, I wish I had an environment to reproduce this. Of course the installer will hopefully be improved further in the next version including e.g. better handing for upgrades, but such improvements will be done after the current release, which is about to released very soon.

**Comment by Burrito78** [comment]
Yes, true. We will look after these issues after 0.79.0!

Good work, thanks for implementing this!

**Comment by Burrito78** [comment]
This is done, thanks everyone!
