### ISSUE TITLE
Manpage and help are outdated

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#1983]
Specifically `dosbox --help` command and `docs/dosbox.1` file. They miss some stuff like argument syntax unification (single vs double-dash) and `-set` option, maybe more.

**Comment by kcgen** [comment]
If anyone in the community can help in these areas - it will offload this work from the core team. This is how you can contribute, without being a developer or tester.

**How to contribute:** mention the before and after wording here, and we can paste it in, with commit credit to yourself.

**Comment by johnnovak** [comment]
> They miss some stuff like argument syntax unification (single vs double-dash) and `-set` option

I've raised a ticket for this specific issue: https://github.com/dosbox-staging/dosbox-staging/issues/2121

**Comment by GranMinigun** [comment]
With #2837 merged, do we still have any out-of-date documentation, or this ticket can be closed?

**Comment by johnnovak** [comment]
> With #2837 merged, do we still have any out-of-date documentation, or this ticket can be closed?

The various helps files in .txt format are also outdated. They should go 100% away once we have the user manual, until then... dunno, someone can update them if they want, I won't.

Also note that the online manual can be distributed in a ZIP file for offline use; you only need a modern browser. MkDocs is quite amazing, even the search works in offline mode!

**Comment by Grounded0** [comment]
I would say burn everything at stake that isn't a packaging requirement. Especially anything that uses nroff. 😁

**Comment by Grounded0** [comment]
@GranMinigun 

Lets close this since man page and --help are now addressed?

**Comment by kcgen** [comment]
Agree we should close this as 'resolved':
 - `man` page has been simplified and made current by @Grounded0
 - text files will be deleted when we rotate over to the MkDocs manual

**Comment by Grounded0** [comment]
Added a lot of context below for future maintainers of the man page since this will become outdated yet again.

Since nroff is a text-formatting language developed at Bell Labs in the 1970s this helped me a lot to author this man page:

[O'Reilly: UNIX° TEXT PROCESSING Chapter 4 nroff and troff](https://www.oreilly.com/library/view/unix-text-processing/9780810462915/Chapter04.html)

At least Emacs has an nroff mode which will make authoring man pages significantly easier. I used Emacs to author this man page:

[Nroff Mode (GNU Emacs Manual)](https://www.gnu.org/software/emacs/manual/html_node/emacs/Nroff-Mode.html)

More about nroff:

[nroff - Wikipedia](https://en.wikipedia.org/wiki/Nroff)

Connected issues and PRs:

- #2837 
- #2574 
- #2683 
- #2820 
- #2703 
- #2121 
- #2970
- #3052 
- #3062
