### ISSUE TITLE
Publish ARM-based Linux snapshots

### ISSUE THREAD

**Issue by ghost** [dosbox-staging/dosbox-staging#2]
The Steam Link is a streaming appliance running a custom embedded Linux by Valve. It has an ARMv7 processor and 512MB of RAM.

DOSBox could be compiled and packaged for this device which would allow games to be played directly on the hardware, rather than streamed. 

See: https://www.exploitee.rs/index.php/Steam_Link

**Comment by dreamer** [comment]
[Steam Link is now semi-officially supported on Raspberry Pi](https://steamcommunity.com/app/353380/discussions/6/2806204039992195182/). Raspbian includes dosbox in repos, so I think providing ARM builds should not be a big problem, but we need to approach this methodically and assure there won't be regressions. I think we need the following steps (not especially in that order):

- Have first proper SDL2-based release (at the moment we have working experimental version on my branch `po/boxtron-test-1`, but it does not pass on GitHub CI due to missing packages in Azure).
- Provide CI setup for ARM (probably cross-compile - we can see how Rust is handling builds for multiple architectures on Azure for inspiration).
- Provide nightly builds for ARMv7 in a format applicable to old Steam Link devices (I must note we don't have nightly builds at all in dosbox-staging yet)
- Get dosbox-staging packaged in Raspbian for new Steam Link devices

**Comment by dreamer** [comment]
Changed the title to reflect scope of this issue a bit better.

As for my points in previous post:

SDL2 is now on master, so this part is done.

I investigated ARM-based builds a bit, we have two options in here:

1. Use Linux x86_64 to cross-compile for ARM - I tried doing it, and soon got into a rabbithole of distro-specific tweaks and solutions. I don't like it (but maybe someone else have experience in setting up such builds? feel free to chime in)
2. Use normal builds using QEMU to boot any Linux distro; this option have very nice property of translating rather easily into GitHub CI (there are Workflows that enable this without much effort on our side).
3. Hook up our own, ARM-based runners to CI.

**Comment by dreamer** [comment]
Reopened because while we have now nightly-builds for ARM, they are not "snapshots" and require additional manual work to be released. Thus, the work is not finished.

**Comment by kcgen** [comment]
We're publishing ARM64 MacOS builds - those are ARM snapshot.

However, there's also:
 - armv7le 32-bit
 - armv8 64-bit
 - arm cortext 53 vs 72 (Pi3 vs Pi4 builds)
 - Pine64 SBC
 - Others

Suggest we don't try to release builds for all of these (technically they all fall under "Publish ARM snapshots).

As an alternative, @nemo93 has helped add Staging as one of many DOSBox forks on RetroPie,  Given this is the go-to option for emulation-based gaming on ARM SBCs, this is now the recommended way to install Staging (in addition to via Linux repo).  Closing.
