### ISSUE TITLE
About dosbox-staging 0.80.0 release

### ISSUE THREAD

**Issue by chenrui333** [dosbox-staging/dosbox-staging#2198]
👋  while [regression testing dosbox-staging formula](https://github.com/Homebrew/homebrew-core/pull/119985), we found that the checksum got changed, raising this issue to confirm if there is re-tag happening. Thanks!

**Comment by kcgen** [comment]
Yes, the day of the release I had to move the tag by one commit because the CI runners were not see the (original as-placed) v0.80.0 tag.  So I added a second commit to force-pull the tags in the CI workflows, which ensured that the runners see the tags and properly apply the version labels inside the code. You can see this added commit here: de47d98a8.

This issue has been a long running problem with previous releases, which thankfully is now solved.

**Comment by chenrui333** [comment]
Thanks for confirming it! 🙏
