### ISSUE TITLE
Hypervisor core

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2215]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Add option for hypervisor core, for example based on [virt86](https://github.com/StrikerX3/virt86) as discussed at https://github.com/joncampbell123/dosbox-x/issues/1089

(one of the items mentioned at #2185 that is relevant also for the most resource-intensive DOS games/programs)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Given the complexity of the undertaking, the maintenance effort, and the cost/benefit ratio, I find it extremely unlikely that this will happen in the foreseeable future.

Even if it was just moderately difficult and not too costly to maintain, it would only work on Intel, and the world has already started to move away from that architecture.

If I had to prioritise the backlog right now, I'd move this to the very bottom without much further thought 😎

**Comment by kcgen** [comment]
DOSBox was always meant to be a cross-platform, portable, and self-contained DOS-system emulator. 

This is achieved by having DOSBox insulated behind common cross-platform libraries and APIs, like SDL and OpenGL.

If DOSBox Staging interfaced directly with any host hardware, this would break this portable software abstraction, and create a unique hardware-specific dependency on specifically the x86-32 bit architecture. 

It's the same reason that requests to interface directly with Adlib or other retro-hardware are also denied: because we want to _emulate-old-hardware_ not _run-on-old-hardware_. 


Regarding speed: please see our about page again- we are not trying to be the fastest emulator. 

Are there DOS games that the currently not playable on standard desktop or laptops due to speed issues?

**Comment by kcgen** [comment]
Closing the ticket because it's our of scope, but I do appreciate your suggestions and thoroughness, and the care that you're showing for the overall PC emulation landscape! Thank you, @Torinde 🎉❤️
