### ISSUE TITLE
Paths handling on OSes other than unix/win32 (e.g AmigaOS, MorphOS)

### ISSUE THREAD

**Issue by kas1e** [dosbox-staging/dosbox-staging#223]
One user found today on MorphOS (and I can reproduce it on AmigaOS4), that we can't mount as virtual drives roots of amiga volumes.

For example if we compare all the oses, then:

Win32 - c:\
*nix - /
AmigaOS : - name:

So, for example, we have such paths "work:testdir/filename.txt". Or for some system file "system:kickstart/file".

Now, when I tried to mount in DOSBox any directory from work: partition, I can do that easy, like this:

```
mount d work:testdir -t cdrom -usecd0
```

Then DOSBox add "/" at the end, and mount "work:testdir/", which is ok. I can go to the D: and "dir" show me my files.

But, if I tried to mount pure "work:", like this:

```
mount d work: -t cdrom -usecd0
```

Then DOSBox says it mounts, but when I go to mounted volume and tried to "dir" it, then I had:

```
Directory of D:\
File *.* not found.
```

That happens (probably) because DOSBox add "/" to the "work:", and we have "work:/", which is wrong.

So I see there 2 issues :

1). Dosbox should warn us that he can't mount something.
2). that to just suggestion/question:  how to deal with it and wherein DOSBox code, so I can add AmigaOS ifdefs for. I assume in those ifdef just need to add check if we have ":" at the end of the mounted path, and if so, then didn't add "/" at end.

Thanks !

**Comment by dreamer** [comment]
This bug is being introduced in here: [dos_programs.cpp:324](https://github.com/dreamer/dosbox-staging/blob/master/src/dos/dos_programs.cpp#L324).

This is obviously bad implementation, I have no idea why this separator is being appended in here. We can't simply remove it - the code joining paths (likely somewhere in `drive_local.cpp`) will need to be fixed to correctly join paths instead.

The correct solution is to write a function for joining paths, include special handling for AmigaOS in there (not to sprinkle ifdefs in random places in code, please).

Long-term, this could be achieved by using C++17 and `std::filesystem::path` - does AmigaOS and MorphOS support C++17, specifically STL filesystem lib? If yes, then we could write implementation easily on Linux and AmigaOS builds could be the first platform to build with C++17 by default (I don't want to use it *as default* on other OSes yet due to ABI compatibility with older Windows and older Linux distros, but I don't know how Amiga/Morph compatibility scenario looks like - perhaps it's ok to use it).

**Comment by kas1e** [comment]
@dreamer 
We have on gcc 8x and gcc 9x, so c++17 are ok, but not sure if std::filesystem:path it handled properly on our side.

As for rust , nope, that one we don't have

**Comment by kcgen** [comment]
c++17 is now in-play. Need to revisit this and see how we can put it to use.

**Comment by kcgen** [comment]
@kas1e , can you try branch: `kc/mount-path-1` and report any results?
