### ISSUE TITLE
Hide macOS ".DS_Store" files inside DOSBox

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2231]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

These .DS_Store files that are always hidden in macOS Finder are shown in DOSBox using the DIR command.

<img width="902" alt="Bildschirmfoto 2023-01-18 um 21 29 21" src="https://user-images.githubusercontent.com/61995128/213288136-899b35d5-8b10-4693-a566-6c6a2ddbf5f2.png">

### Describe the solution you'd like

Automatically hide .DS_Store files inside DOSBox Staging.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Finder sounds like it's misbehaving if it's leaving behind temp files in other application's directories. Can Finder be uninstalled?

But yes.. we'll have to hide them, if that's normal on MacOS.

Break out the litter clean-up crew to pick up after Finder's messes:
``` shell
sudo find / -name ".DS_Store" -depth -exec rm {} \;
```

:warning: Finder developers: there's something called a relational database (like SQLite3): please use it instead of littering in other people's directories! :wastebasket:

**Comment by Burrito78** [comment]
On the Mac they often end up inside ZIP files because you just forget about them. :)
Thats why the Keka archiver has a special option "exclude Mac system files"...

**Comment by johnnovak** [comment]
I wonder how many people have a variation of this script in their toolbox! This is my variant 😂 

``` bash
rm-dsstore() {
  echo -n "Recursively deleting .DS_Store files from "
  pwd
  find ./ -name '.DS_Store' -exec rm -rf '{}' \; -print
}
```

**Comment by darkstar** [comment]
Yeah, I think it's best not to mess with these files in DosBox. Let the MacOS users figure it out for themselves how to delete them. You can even configure Finder to not create those in the first place

**Comment by Burrito78** [comment]
I learned today that its possible to disable the creation of these files through a terminal command.
`defaults write com.apple.desktopservices DSDontWriteNetworkStores true`

The point being that by default these files are created and shouldn't be shown in DOSBox.

If it's a relatively small change to hide these by default using the DIR command in DOSBox it would improve the user experience on macOS.

**Comment by johnnovak** [comment]
> If it's a relatively small change to hide these by default using the DIR command in DOSBox it would improve the user experience on macOS.

Hiding them by default seems like a good idea. These files are not useful from the point of view of the emulated DOS machine.

But then to do this properly, shouldn't we teach all the other DOS commands to exclude them? E.g., when you use XCOPY to copy files, these `DS_STO~1` files would be still copied. What about other tools that have a "select file" dialog that lists the files in a directory? The `DS_STO~1` files would be still displayed there.

Unless we filter these files out at the DOS interrupt level... Which is maybe a bit too heavy-handed.

So, in principle I agree with the idea, but it might open a whole can of worms.

**Comment by darkstar** [comment]
I agree that it's probably not worth the trouble this would create. What about other files? Should we hide "thumbs.db" on Windows as well? or "desktop.ini"? What if a DOS program/game happens to use that same filename? Or should we hide all files that start with a dot? What if I have a CD ROM with such dotfiles and I do want to access them?

It's just a minor inconvenience, it's one directory entry, and if that confuses people they can just delete it or disable these file in Finder

**Comment by kcgen** [comment]
Yes, to do it cleanly, it should be done at the filesystem emulation layer, so higher level commands aren't even aware of of the files to begin with (and so it's only placed in one bit of code). 

An exclusion list would also be used, so any number of junk files can be ignored (making this a feature "exclusions" instead of making this a macos-specific garbage cleanup). 

But I also agree that we should try to avoid this, and not double-down on two wrongs (Finder itself is broken, and now we're adding code to DOS emulation because Finder is broken). 

If there is stinking food in the fridge, the solution is not to hand out nose plugs to guests. 

Maybe we could add a one-time tip to "ls" and "dir", that if the ds_store file is found, to suggest `defaults write com.apple.desktopservices DSDontWriteNetworkStores true` (and then let the user do their own cleanup and disabling?). At least it wouldn't pullute the low level emulation.

**Comment by darkstar** [comment]
Changing the output of dir/ls could subtly break batch files that rely on a particular output, or filter the output in any way. Especially if it's done on the first occurence only.

I still think those files should be ignored. It's just another file/directory. With a strange/funny name, maybe. But it doesn't cause any issues with the emulation since it's name will be changed to a free 8.3 name. Changing the behavior of dir/ls, or even changing the behavior of the DOS emulation itself on the other hand can very much interfere with programs.

Are there any reports that people were actually confused or ran into problems because of these files?

**Comment by kcgen** [comment]
Yes, if we log anything, it will simply be to the console log (not inside the console). 
I believe @Burrito78 just doesn't want see the files; I don't think emulation is being negatively affected. 
Adding the help-wanted label, for anyone in the community to explore contributing an exclusion/filter.

**Comment by johnnovak** [comment]
> Maybe we could add a one-time tip to "ls" and "dir", that if the ds_store file is found, to suggest defaults write com.apple.desktopservices DSDontWriteNetworkStores true (and then let the user do their own cleanup and disabling?). At least it wouldn't pollute the low level emulation.

The problem is that macOS users are the least likely to look at those logs (or to even have a log window open).

> I still think those files should be ignored. It's just another file. With a strange/funny name, maybe. But it doesn't cause any issues with the emulation since it's name will be changed to a free 8.3 name. Changing the behavior of dir/ls, or even changing the behavior of the DOS emulation itself on the other hand can very much interfere with programs.

You've brought up a lot of good points, and I agree with the above. Those files are only a minor annoyance to deal with—now contrast that will all compatibility problems and other confusing behaviour the filtering change could potentially introduce. And where to stop? Ignore all hidden files on Linux, for example? And so on...

Overall, I'd say it should be the user's responsibility to remove those files from the mounted DOS directories if they become an annoyance. But they should rarely cause any harm.

> If there is stinking food in the fridge, the solution is not to hand out nose plugs to guests.

So good 🤣 I'm stealing this! 😎

**Comment by Burrito78** [comment]
> Yes, to do it cleanly, it should be done at the filesystem emulation layer, so higher level commands aren't even aware of of the files to begin with (and so it's only placed in one bit of code).
Absolutely agree. 

> Where do you stop?
Well, if someone complains or if it makes sense to us, because its a daily annoyance, it could be implemented.

But of course if it's not easy to do or risky then it's obviously not worth it at the moment. After all it's just a minor annoyance at best. Thanks guys for the feedback on this!

**Comment by kcgen** [comment]
@Burrito78 , when you have a chance to try one of the latest builds `v0.81.0-alpha-163` (or > 163) should have this fixed.

Turns out, DOSBox was more permissive in showing my hosts's hidden files than even GNU `ls` is by default! So this was a very welcome and generally-applicable fix.
