### ISSUE TITLE
Version to show build and architecture

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2268]
- when running - ver shows the Staging version number, but not the build (MSVC or MSYS2) and not the architecture (x86, x64, ARM, etc.) - can those be seen somewhere?

_Originally posted by @Torinde in https://github.com/dosbox-staging/dosbox-staging/issues/2258#issuecomment-1417688661_

Also, maybe to show the host OS as well.

**Comment by kcgen** [comment]
Great suggestion!

Yes, I think we should log all this info: version, host OS, host architecture, compiler, and possibly even compiler version. 

These details can be logged compactly on just a couple lines:

```
DOSBox Staging 0.81-alpha
- Compiled with GCC 12.0.1 (x86_64-pc-linux-gnu)
- Running on Ubuntu 22.04 GNU/Linux x86_64
```

This can be presented inside the DOS window on startup, in our console log output, and `ver` (perhaps with an addon-flag, because maybe some old programs parse its output and expect specific layout).

If anyone wants to help with this, it can be done in some separate steps (which don't have to be done by the same person):

1) Write some cross-platform shell or python script to discover these details.

2) Use Meson's variable-substitution to populate these as static strings in a compile-time header file (similar to `src/config.h.in`)

3) Figure out how to do the same using MSVC

4) Figure out how to discover the host details at runtime, also using cross-platform C/C++ code.  This doesn't have to tie into the build system: instead, it will run during DOSBox Startup and be shown on-demand.

**Comment by johnnovak** [comment]
Now the titlebar can optionally show the git hash and we're migrating towards a single build per platform model, so closing.
