### ISSUE TITLE
[Windows3.1] gaming issues

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#2356]
Hi, these days I'm testing gaming on Win3.1. It's on my todo for quite long... I'm posting all issues faced thus far. If these can be reproduced or if anyone ask me to I could crack separate tickets. Just let me know.

### Games that don't install
* Comix Zone (SEGA)
* Garfield Caught in the Act (SEGA)
* Civil War Generals 2 (Sierra)

The 2 SEGA games go through install process, create a "program group" and remove any installed files at the end of the process!! Only the install dir is left.
=> to reproduce: run the install process and wait for the end of it. I've tried various images including Redump.

Civil War 2 will throw an `error 115` toward the end of the installation, irrespective of the installation size chosen (small, medium, large). I've tested 4 to 5 different images in various languages still same issue. Not sure it's related yet I wanted to mention it.

### WaveOut failed/no digital driver available
* Donald Cold Shadow (SEGA)
* Almost any Sierra games (eg. Shivers, Shivers2, Betrayal at Antara, etc.)

If you run the games right after installing it, everything works fine. Yet the way I've configured my setup is by running games straight from my frontend (I've noticed eXo does the same). For instance I put this in my `[autoexec]` section:

`WIN : C:\RUNEXIT.EXE D:\COLDSHDW\COLDSHDW.EXE`

Using this will generate an error:

![krnl386_000](https://user-images.githubusercontent.com/8100500/226847037-eab5ba2d-f453-42f2-b8e8-d59ed425aeab.png)

**Workaround**: disable any startup sound on Windows start. Not sure it's a game bug or Staging's.

### No sound
* 3D Ultra Pinball (Sierra)

I can't get any sound at all (either SFX or MIDI Music). I've tried multiple CD images, also running right after installing it with same outcome. Worth noting that even when Windows closes I can't get the system sound associated. It's like this game disable completely the soundcard.

### CD Audio (redbook) continues even during Windows restart

You must have the CD Audio driver installed on your Win3.1 to reproduce. Then run Donald Cold Shadow (SEGA) for instance as its music is CDDA. You should hear music at the main screen. Then you have to restart Windows (not reboot it) by adding or removing a driver (Control Panel > Drivers). During restart you can still hear the CD music.
=> not sure it's a real issue yet I want to mention it.

### My setup

Raspberry Pi4 on 32-bit OS using Staging's `main`. Windows for Workgroup 3.11 with S3Trio driver, SB16 is properly installed with MIDI as explained in the Wiki. Latest WinG and Win32s also installed. Most games run just fine only the above gave me troubles.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
There's many many many versions of the SB16 driver for Win 3.1x. I've had success running late Sierra games with this one (thank god i always keep the well working driver installers archived!):

S16-31STD-1-US (Revision 2) Installation Disk:
[SB16DRV.ZIP](https://github.com/dosbox-staging/dosbox-staging/files/11039919/SB16DRV.ZIP)

If this helps to address this issue we have to begin promoting specific driver versions on our Wiki just like we do with our S3 driver (90% of them don't work or work poorly with Staging when you start to push up resolution and colours).

**Comment by Grounded0** [comment]
Some late Sierra Windows games like Hoyle Casino fail to run if cputype isn't set to 486_slow:
config -set cputype=486_slow

**Comment by nemo93** [comment]
@Grounded0 glad to read from you! I realized the vast amount of SB16 driver versions available. That's insane. I plan to try a few more SB16 versions to rule things out. Thus far only Ultra Pinball refuses to play any sound, no matter what I do. I should also try with GUS.

Regarding S3, I've been testing the "Vision" one from the Wiki (thanks to you) as well as a S3 Trio driver (latest I've found online which appears to be the one recommended by DOSBox-X). No issues to report yet I do not use anything higher than 640x480 at 256 colors. My RPi just can't handle it! I did a quick test using 16.7M colors and it worked yet most games tested complained hence me sticking to 256 colors.

**Comment by Grounded0** [comment]
I don't do startup sounds. 😁

**Comment by rderooy** [comment]
> There's many many many versions of the SB16 driver for Win 3.1x. I've had success running late Sierra games with this one (thank god i always keep the well working driver installers archived!):
> 
> S16-31STD-1-US (Revision 2) Installation Disk: [SB16DRV.ZIP](https://github.com/dosbox-staging/dosbox-staging/files/11039919/SB16DRV.ZIP)
> 
> If this helps to address this issue we have to begin promoting specific SB16 Win 3.1x driver version on our Wiki just like we do with our S3 driver (90% of them don't work or work poorly with Staging when you start to push up resolution and colours).

Here is a Win3.1 guide that I referenced for the DOSBox-X wiki. Is that the same driver version?

**Comment by Grounded0** [comment]
@rderooy 
ajp@milla:~/Downloads/unprocessed/SB16W3X $ cat DISK.ID 
Audio Software
S16-31STD-1-US (Revision 2)
Installation Disk

Yes.

**Comment by Grounded0** [comment]
I'll add to the Windows startup sound that the media stack is really arcane in Win 3.1x so that if the output device is reserved by Windows 3.1x to play a startup sound then the output device is de facto blocked for use by the game. So it's not a Staging bug. It could be just Win 3.x being early 1990s OS or the game not designed to be run with audio subsystem being in use.

**Comment by johnnovak** [comment]
I've never encountered these issues in Win3.x, e.g. I can run Shivers fine after installation. I did follow the Win3.1x setup guide from the wiki, it's very good and gave me zero problems with anything I've tried so far (about 20 games, give or take).

Couple of points:

1. Different drivers behave differently (duh!) — I learned this the hard way when installing my new AWE32 on my real DOS PC. Some random AWE32 drivers I tried first did not quite work; specifically, it was _mostly_ working, but certain features of the card were not working (e.g. reverb & chorus). Then I downloaded PhilsComputerLab's drivers which were the latest, and those work flawlessly.
**Moral of the story: you might be using buggy / incompatible drivers.**

2. Just because some game behave erratically, it does not mean these issues are caused by DOSBox! I think you can test these games relatively easily in PCem, 86box, or even VirtualBox. Basically, just because game X exhibits some weird behaviour or doesn't start with a certain Win3.x version and a certain set of drivers, it does not mean DOSBox is at fault. Hence, you'll need to cross-check using the _exact same_ drivers and Win3.x version in another emulator if you don't have access to real hardware (real hardware would be best).
**Moral of the story: it's a mistake to think every weird/buggy behaviour is caused by DOSBox. Many of these games are buggy, drivers are buggy, Win3.x itself is buggy... At the very minimum, one should cross-check in other emulators (not DOSBox) before claiming something is a DOSBox bug.**

**Comment by Grounded0** [comment]
DOS and Win 3.x gamers often had a first boss fight to get these games to run or to run properly.

**Comment by nemo93** [comment]
Thanks all for your inputs. I understand it's my setup or something I've done wrong. Hence me closing this one off. I've updated the Win3.1 section of the wiki accordingly. Apologies for the time waste.

For sake of completeness, the aforementioned issues can be replicated either:
* on a fresh Win3.1 install
* with GUS driver instead of SB16

For games that don't properly install as usual it's best to rely on eXo to get things working. Note: eXo doesn't have Garfield and there's something odd definitely with Civil War Generals 2 as the following lines are used to run the game:

```ini
[...]
@imgmount c .\eXoWin3x\Grant-Le\i150_304.img
@imgmount d .\eXoWin3x\Grant-Le\cd\cd.iso -t iso -fs iso -ide 2m
```

**Comment by Grounded0** [comment]
Yeah i'm also waiting for file locking support:
- #1489

**Comment by Grounded0** [comment]
@nemo93 Please add any SHARE.EXE problems you have to that ticket so it gets more priority.

**Comment by nemo93** [comment]
Let's make a list of impacted games then. The following are known to suffer the dreaded issue "share.exe not loaded" during install:

* Comix Zone (SEGA)
* Garfield Caught in the Act (SEGA)
* Microsoft Flight Simulator 5 - ATC Workshop (Microsoft)
* Monopoly
* Ultimate Yahtzee (Hasbro)

**Comment by Grounded0** [comment]
Can you post them into my ticket too so we have a one ticket for all SHARE.EXE problems.
