### ISSUE TITLE
Disabling the swap file causes Windows Explorer to crash in Win98

### ISSUE THREAD

**Issue by ThomasEricB** [dosbox-staging/dosbox-staging#2359]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha, latest commit (at the time of posting), git version

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

NixOS installed on a Chroot on SteamOS 3.0

### Relevant hardware info

Steam Deck: Processor: AMD APU - CPU: Zen 2 4c/8t, 2.4-3.5GHz (up to 448 GFlops FP32) - GPU: 8 RDNA 2 CUs, 1.0-1.6GHz (up to 1.6 TFlops FP32) - RAM: 16 GB LPDDR5

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Okay, to counter the Explorer crash that sometimes it would occur on boot (somewhat between 1 in 4 Windows boot), it was theorized that disabling the windows swap would fix the behavior. However, when disabling the swap file with "disabled virtual memory", Explorer would crash and remained crashed every time you boot (NOT BSOD). See the following crash message:

![](https://cdn.discordapp.com/attachments/1037262349586939954/1088250008580665465/image.png)

I created this issue (not exclusively) for @FeralChild64 and @joncampbell123 , however I'm also tagging @shermp and @Wengier because they might have something to say about it. This isn't really in the scope of DOSBox Staging, therefore why I tagged low priority. Just wanted to document the issue.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. On Windows 98, right click on My Computer and select Properties 
2. Go Performance -> Virtual memory
3. Click to choose your own settings with disabled virtual memory
4. Windows asks to reboot
5. If you don't reboot, as soon as you reject it Explorer crashes. Explorer stays crashed even if you boot another time.

### Your configuration

```ini
The most important setting:

mcb_fault_strategy = repair
```

### Provide a Log

```text
I don't have a log for this.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
FYI, although Explorer doesn't crash on a real machine when you disable the swap file, DON'T do it because quite a few games will exhibit bugs and crashes with the swap disabled. Some even warn you at startup that they need 256 MB swap at least if you disable it.

If you have 512 MB mem, you gain nothing by disabling the swap file, but you'll run into problem sooner or later. You can also enable conservative swap file usage in the Windows ini (look it up) and set the swap to a fixed size so it won't get deleted & recreated at every boot (that's what I do on my SSD equipped Win98SE box).

**Comment by johnnovak** [comment]
Also, with the swap disabled you will waste MORE real physical memory. You need to grasp how virtual memory works to understand this, but it can be a net loss of performance...

**Comment by ThomasEricB** [comment]
> FYI, although Explorer doesn't crash on a real machine when you disable the swap file, DON'T do it because quite a few games will exhibit bugs and crashes with the swap disabled. Some even warn you at startup that they need 256 MB swap at least if you disable it.

Like I said, this was suggested as a quick workaround for the issue we sometimes encountered on Windows 9.x

**Comment by johnnovak** [comment]
Well, I'd say it's not a very good tip then.

**Comment by joncampbell123** [comment]
Windows 98 from my testing so far seems to act up if the swap file is disabled, like it needs it.
Windows 95 seems to run OK without a swap file.

**Comment by joncampbell123** [comment]
Another guess of mine is that Windows 98 and later begin to use memory mapping (however primitive) for some files. Windows 98 was supposedly when PE executables were encouraged to align segments to 4KB boundaries so that Windows 98 could memory map them instead of read and copy into memory, though I'm not sure about that. But memory mapped backing does mean page faults and the system code to resolve page faults by reading the disk contents into memory.
