### ISSUE TITLE
Whats the easiest way to get single-scanlines on vga emulation?

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#2478]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.712

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

There are some newer games that don't look as good with double-scan mode. Is there a way to get single scanlines?

Lemmings, space quest, and others look great with single scanlines.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@Jkapp76 

```ini
[dosbox]
force_vga_single_scan = on
```

**Comment by Burrito78** [comment]
Wait, why does lemming look best using single scan? Why does double scan look different at all with lemmings VGA?

**Comment by kcgen** [comment]
The little guys look even floppier and  level details take on a more 3D and textured appearance. (Will attach screenshots later)

**Comment by Jkapp76** [comment]
That was an easy fix. update my conf file so I can set (force_vga_single_scan = on)

The scan lines add detail somehow. Looks less blocky.

**Comment by johnnovak** [comment]
> Wait, why does Lemmings look best using single scan? Why does double scan look different at all with lemmings VGA?

@Burrito78  because the in-game screen uses 320x200. VGA cannot display 320x200; it double-scans it in hardware to 640x400. Effectively, that's 2x hardware upscaling that all VGA hardware does!

This makes art appear more blocky, yes, and actually different than the original Amiga version that does not double-scan. Note that the differences will only appear when using a CRT shader; with the default sharp shader, the results look 100% identical!

Examples:

### Defaults (authentic VGA double-scanning enabled)

Pixels appear blocky because of the "hardware 2x upscaling" of VGA hardware of 320x200 content to 640x400.

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/e32ce7a5-0f1e-48a7-a6b4-66751bcff067">

### Force VGA single-scanning

With forced single-scanning the game looks similar to the Amiga version.

```ini
[dosbox]
force_vga_single_scan = on
```

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/9311786c-4376-4a2a-b60f-0c543e6a19e8">

### EGA

None of the pre-VGA cards perform any double-scanning, so you get single scanlines ("true 320x200") when using `machine = ega`.

```ini
[dosbox]
machine = ega
```

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/9aa55bea-93cf-45af-b9a8-dda96468d5f9">
