### ISSUE TITLE
Jazz Jackrabbit 'cannot enable A20' error after 'config -set memsize=16'

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2520]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dev

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When setting 'config -set memsize=16' before launching Jazz Jackrabbit (eXoDOS).
Memsize is set at '16' before as is default.

Tested with Staging 0.78.1, 0.79.1, 0.80.1 and latest DEV version.

DOSBox-X can't set memsize at runtime.
I guess vanilla also can't set it at runtime.

Proof:

![Bildschirmaufnahme 2023-05-23 um 19 37 10](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/1cd9ef3a-00ba-4c10-9290-43d00f0fdf8c)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Can confirm, I ran into this yesterday. I have a hunch it's not possible to change the memsize at runtime because of DOS OS limitations, TSRs too possibly, etc. It would be cool though, but Amiga emulators are the same; mem change setting will only be effective after resetting the emulated machine.

What we could do here, and in general with settings that are not changeable at runtime, is to let them take effect after the "reset machine"   command. Maybe that's doable.

**Comment by FeralChild64** [comment]
We do not have a working machine reset functionality in Staging, sadly. Indeed, changing the momory size during the runtime might be hard to implement (MS-DOS wasn’t designed for memory hot swap, AFAIK), but maybe there could be some kind of memory limiter, causing some XMS/EMS memory functions to report less memory than available? Such a limiter could probably be adjusted during the runtime.

**Comment by Burrito78** [comment]
Oh, i didn't know it doesn't work! 

It should spit out an error message then instead of trying to do it anyway and causing trouble.

**Comment by FeralChild64** [comment]
Right, CONFIG should warn if changing a setting is not possible during the runtime - currently it doesn’t. It’s also possible, that some settings are wrongly declared as changeable in the runtime.

**Comment by johnnovak** [comment]
Two more things:
- What does the WhenIdle setting flag mean? Is it just the opposite of "changeable at runtime"? It's a bit strangely worded then.
- `config -r` restarts the emulator, so I thought settings not changeable at runtime could be changed that way, but no. That wo ujld be a cool featurr, e.g. changing the machine type and the mem settings for example with the config command, and instead of raising and error a message would be displayed that these are pending changes that will take effect on the next restart with `config -r`. Basically would need to hold one more extra config layer in memory for the pending settings thst would take effect after the restart.

**Comment by Burrito78** [comment]
I'd like that idea, DOSBox-X has this i think? @joncampbell123?

**Comment by Burrito78** [comment]
Continued here: https://github.com/dosbox-staging/dosbox-staging/issues/1027
