### ISSUE TITLE
The GUS 'drum patch files' we provide lead to hanging notes in Duke Nukem 3D

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2536]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Relevant hardware info

M2 mini

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The ULTRASND files we provide here:
https://github.com/dosbox-staging/dosbox-staging/wiki/Sound-cards#procedure

Produce this issue:
- https://github.com/dosbox-staging/dosbox-staging/issues/1827

The files @kcgen linked in #1827 fix them for me too. 

Bugged files: https://github.com/dosbox-staging/dosbox-staging/files/9690113/ultrasnd.zip (16 MB)
OK files linked by kcgen: https://github.com/dosbox-staging/dosbox-staging/files/9229146/ultrasnd.zip (7,7 MB)

Does the files kcgen linked have any downsides and should we replace the files we provide?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
The smaller zip doesn't contain extras like SBOS and friend, which we want to discourage anyway because it's worse than DOSBox's own Sound Blaster emulation.

The small zip is used for all GUS MIDI game regression testing (and works great). If the purpose of the wiki is to give the user a reliable set of GUS MIDI patches, then it gets the job done.

If users want to explore the entire suite of GUS tools, then they can round all that up from archive sites.

**Comment by kcgen** [comment]
(all that to say: my vote is to rip 'n replace)

**Comment by johnnovak** [comment]
> If the purpose of the wiki is to give the user a reliable set of GUS MIDI patches, then it gets the job done.

I'd say the wiki should definitely have a narrow focus like that; less bloat, less clutter => less confusion.

So yeah, we should change it to the fuxed smaller archive.

**Comment by Grounded0** [comment]
Only offer the one that works.
