### ISSUE TITLE
Add the MOVE internal DOS command

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2539]
Shouldn't be too hard:

https://www.computerhope.com/movehlp.htm

**Comment by weirddan455** [comment]
I'll assign myself to this.  I've got it WIP.

**Comment by johnnovak** [comment]
> I'll assign myself to this. I've got it WIP.

Have you checked the behaviour of the real MS-DOS 6.22 command? I've just realised that page I linked to is a bit too generic.

Maybe this helps:

<img width="752" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/c6136e4c-8281-4cb3-9d74-031881df9f18">

<img width="752" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/a54cf804-552b-4a80-9a14-765565e70474">

<img width="752" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/4e2d7e1d-62b3-41c7-ae5b-270fa5103b35">

Although I'm not quite sure if we want to 100% replicate the original error messages. @FeralChild64 you seem to have more experience in this area?

**Comment by johnnovak** [comment]
Some more:

<img width="752" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/9978dfed-812d-4aa3-a409-22f4553ac42c">

**Comment by weirddan455** [comment]
Thanks.  I’ve got MS DOS 6.22 running in 86box I can test behavior with.  Curious how you got those screenshots on Dosbox though.  Did you just copy MOVE.COM from a DOS install?

**Comment by FeralChild64** [comment]
@weirddan `MOVE` is an internal command, you just need to run the `COMMAND.COM`. It is also possible to boot a real DOS under _DOSBox Staging_, check the `BOOT` command.

----

Regarding my private "policy" - I do not care to precisely replicate _MS-DOS_ messages. As a child I have migrated from _MS-DOS to _PC-DOS_, and later to localized _Windows 9x_ (and at some point I was experimenting with `PTS-DOS`, for a very brief moment), so I consider it normal that different DOS implementations display slightly different messages. But:
- if I can give better error messages, or provide better user experience with reasonable effort - I do
- I try to be consistent with the rest of _DOSBox Staging_, I consider this important

As for command syntax/features: we definitely want MS-DOS 6.22 compatibility. Moreover, I am trying to implement various extensions, from:
- _Windows 9x_ (_MS-DOS 7.1_), _Windows 11_ - these have the highest priority for me in case of syntax conflicts
- `PC-DOS`, `DR-DOS`
- `FreeDOS`
- other implementations I can find

In case of `MOVE` command, I could find two extended reimplementations:
- the one in `DR-DOS`
![move-drdos](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/1245c4ec-9da9-4016-bf41-89b16579293a)
- the one in `4DOS` shell replacement:
![move-4dos](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/e8fd885f-dcb5-4a77-95cd-61b049ce4366)

and their syntax is largely incompatible and many of these options are probably useless in real life. However, few switches seem to be the same: `/H`, `/P`, maybe `/R` (I'm not sure) - these might be worth implementing.
But this is entirely your decision. Since it is possible that Microsoft will extend the command in the future (contrary to `SETVER.EXE` I have implemented recently), not implementing any extensions is also a wise choice :)

**Comment by johnnovak** [comment]
> Thanks. I’ve got MS DOS 6.22 running in 86box I can test behavior with. Curious how you got those screenshots on Dosbox though. Did you just copy MOVE.COM from a DOS install?

Oh I had an HDD image with real MS-DOS 6.22 on it laying around from some earlier troubleshooting session with DOSBox SVN. So that was least path of resistance for a quick test 😄 

@FeralChild64's approach seems to be the way forward; I just wasn't sure as I never implemented a DOS command from scratch myself. MS-DOS 6.22 compatibility and consistency with the rest of Staging are the most important, then yeah we can improve a few things here and there. Also, those alternative implementations seem too overengineered, so let's not go there. The basic commands with perhaphs a few small improvements would suffice I think.
