### ISSUE TITLE
'integer_scaling=horizontal' text is cut-off with minimal window size

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2586]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-879

### What Operating System are you using?

Mac OS

### Relevant hardware info

M2 mini

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When setting 'config -set integer_scaling=horizontal' and resizing the window to the smallest size possible, the text is cut off, see screenshot.

![Bildschirmfoto 2023-06-09 um 18 16 02](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/6a830fc5-b172-4525-872c-ca3b899ec8e9)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

```ini
-noprimaryconf
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
I guess the only 100% fix for this is to set the min window bounds dynamically based on the actual output dimensions and/or resize the window too automatically.

E.g. some VESA 132-column text modes appear almost widescreen and they have 1056×352/400/480 resolutions. 

So imagine displaying 640x480 gfx with min window size which is 640x480, then switching to 1056x480 text mode with aspect ratio correction turned off... Major clipping!

**Comment by kcgen** [comment]
feels like a bug; the SDL/OpenGL canvas size and shape are not controlled or "pressed outward" by large DOS draw sizes. 

For example, here's a 1600x1200 DOS dimension rendered into the users desired (and set) window size:

 
![2023-06-09_16-16](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/d48726cc-7e00-405c-b271-27b7b2e4378f)

> resize the window too automatically.

We really want to avoid that - earlier versions adjusted the window size based on the DOS size, and it was a big source of problems (user feedback *"If I sent a window size, that's what I want, please don't pull the rug out from me"*), and worse, SDL doesn't differentiate between programmatically driven window changes versus "user GUI" changes -> and so all the usual SDL event callbacks fire, and this can cascade.  This lead to lots of code to disengage callbacks to prevent "on-change" feedback loops.

**Comment by johnnovak** [comment]
> That text mode should be letter-boxed into the 640x480 SDL window. It would be tough on the eyes (1056 wide scaled down to 640, and 480 tall scaled to ~290 tall 😆 ).

With `integer_scaling = horizontal` 1056 cannot be scaled down to 640, that's not an integer multiple. It must stay 1056, and therefore you'll only see the middle 640 wide are, 1056 - 640 = 416 pixels will be cut off at the two sides.

> We really want to avoid that - earlier versions adjusted the window size based on the DOS size, and it was a big source of problems (user feedback "If I sent a window size, that's what I want, please don't pull the rug out from me"), and worse, SDL doesn't differentiate between programmatically driven window changes versus "user GUI" changes -> and so all the usual SDL event callbacks fire, and this can cascade. This lead to lots of code to disengage callbacks to prevent "on-change" feedback loops.

Sure, that's a sensible decision, but then there's nothing to do here. The user must ensure that the window has big enough dimensions when using `integer_scaling` that cannot go below 1x scaling.

An alternative suggestion is that `integer_scaling` modes would turn off effectively when less than 1x scaling is required. I think probably this is the best we can do; it's better to see downscaled content that not see it at all because it's clipped. We'd just need to slightly reword the description of the feature: integer scaling is maintained if at least 1x scaling is achievable, otherwise defaults to integer scaling disabled and aspect-ratio preserving fit enabled.

**Comment by kcgen** [comment]
Oops; I missed that this ticket is about integer scaling.  Sorry!

> We'd just need to slightly reword the description of the feature: integer scaling is maintained if at least 1x scaling is achievable.

Sounds perfect.
