### ISSUE TITLE
Improve description and behavior of cputype option

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#2590]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

I would expect, for example, that by setting `cputype = pentium_slow` and `cycles = auto`, the cycles would be automatically set based on the speed of the chosen CPU, but DOSBox does none of this.

### Describe the solution you'd like

Make `cputype` and `cycles` closely related. Also the CPU type names and descriptions need to be improved, as they are currently difficult to understand (pentium_slow --> pentium_60??).

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
> Also the CPU type names and descriptions need to be improved, as they are currently difficult to understand (pentium_slow --> pentium_60??).

I agree, this is very confusing. Why do we have `486_slow` and `pentium_slow`, but no `486` and no `pentium`? Do we really need all the 386 variants (`386`, `386_slow`, `386_prefetch`)?

**Comment by Kappa971** [comment]
I propose: 
- `8086` (4,77 MHz)
- `286_12` (12 MHz, if needed for some games)
- For _386_slow_ I assume he means one of the slower 386s, perhaps the Intel i386SX 16 MHz? If yes, then it could be called `386SX_16`
- For _486_slow_ and _pentium_slow,_ following the same reasoning as above, it could be the Intel i486SX 16 Mhz and Intel Pentium 60 MHz, so `486SX_16` and `Pentium_60`
- I have no idea what 386 and 386_prefetch mean.

Also missing faster CPUs e.g. Pentium 200 MHz, Pentium MMX 233 MHz, one of the Pentium 2, maybe even faster versions of 386 and 486... I don't know, surely there is someone more expert here than me about it.
As already mentioned, `cycles = auto` should set cycles automatically based on the CPU you choose.

**Comment by FeralChild64** [comment]
I suppose `386`, `386_slow,` and `386_prefetch` differ by emulation accuracy. But which one is the most accurate, `slow`, or `prefetch` - I have no idea. IMHO this parameter should set the instruction set only, not the speed.

**Comment by Kappa971** [comment]
> I suppose `386`, `386_slow,` and `386_prefetch` differ by emulation accuracy. But which one is the most accurate, `slow`, or `prefetch` - I have no idea. IMHO this parameter should set the instruction set only, not the speed.

Or it could do both (cycles and instruction set), otherwise `cputype` should be renamed to something else because it's very misleading for the average user.

**Comment by johnnovak** [comment]
All this will be covered in the user manual, eventually. 

Don't worry about `cpu_type`, it's an advanced option and it's rarely needed. It influences how accurately a given CPU is emulated, not speed. E.g. a few Win 3.x games _need_ `pentium_slow`, otherwise they misbehave.

Again, don't worry about this setting, most of the time you don't need it. Also, we need to be careful about renaming/extending core DOSBox setting due to backwards compatibility.

What we could (and should) do is to introduce symbolic constants for the `cycles` value. But these are always going to be approximate—DOSBox cannot emulate any given CPU type/speed accurately, it's not possible. At the end of the day, you can use a rough approximate value for the target CPU speed as a guide, then you might need to tweak it a bit per game.

So we could introduce constants for these from the CPU table here (search for "rough guidance")

https://dosbox-x.com/wiki/Guide%3ACPU-settings-in-DOSBox%E2%80%90X

Then you could set `cycles = 486dx2-66` or `cycles = 386dx-25`, and that would translate the constant into the cycles value from the table. But... if you tweak the cycles setting in-game, you'll still need to write the number back into your config file...

**Comment by Grounded0** [comment]
Shouldn't messed with for backwards compatibility. It should be better documented what the hell all of them mean instead:
![dosbox_cputype](https://github.com/dosbox-staging/dosbox-staging/assets/48192273/47c2820b-efad-476d-8f31-2abd80eee809)

**Comment by johnnovak** [comment]
Fantastic find @Grounded0! 🎉  I'll put this into the manual straight away. Where did you find this? Is there more where it came from? 😄 

@Kappa971 you only need to mess with cputype if a program does not even start or somehow misbehaves, that's the short explanation. If it works but it's speed dependent, 99% of the time it just needs cycles adjustment.

Prefetch emulation might help with self-modifying code. CPU ID emulation can help with programs detecting the CPU and exiting if at least 386/486/Pentium is not found. The emulation of extra opcodes is obvious; if the program needs those opcodes, it will crash without them.

But these are costlier to emulate, and you cannot enable all of them at the same time anyway in an attempt to make everything work, so they are opt-in, only use them when really necessary (about less than 2-3% of games need these I'd say).

**Comment by MasterO2** [comment]
On the subject of CPU Cycles:

https://github.com/dosbox-staging/dosbox-staging/wiki/Frequently-asked-questions#advanced-cpu-cycle-count-configuration

(Originally from) https://github.com/dosbox-staging/dosbox-staging/blob/b8f72a08a2c87541314ef1e02ec2ff7ad16fce70/README#L1719

**Comment by johnnovak** [comment]
We've recently got rid of the `_slow` suffixes and that's the extent we're changing this, so closing.
