### ISSUE TITLE
Support mounting physical CDs

### ISSUE THREAD

**Issue by NicknineTheEagle** [dosbox-staging/dosbox-staging#260]
Attempting to mount a physical CD drive shows "MSCDEX: Mounted subdirectory: limited support" message and games that expect ISO9660 filesystem do not work properly. Viewing the code shows that support for physical CD drives was removed.
Why was this done? Almost every console and every PC emulator supports using physical disc drives. I currently mount a virtual CD drive because DosBox IMGMOUNT command is clunky to use and supports a very limited number of formats.

---
*edit on 6 April 2020 by* @dreamer 

It's still possible to mount physical CDs as any other directory, which should be enough to complete the installation of games distributed on CD. This feature request is mostly about physical playback of CD Digital Audio.

We've closed this issue to signify the end of the discussion as we don't plan to work on this. Is someone wants to pick this up, implement the necessary parts and maintain them, then leave a comment asking for reopening of this issue.

For more details, you can read the discussion below.

If you plan to work on implementation, the following issues have bits and pieces of information (or reverted implementation), that you might be interested in: #29, #81, #90, #95 (the work should start with re-introducing code removed in #95 with adaptation to changes in internal APIs that happened since then).

**Comment by krcroft** [comment]
@dreamer provides an explanation in the cost benefit section here: https://github.com/dreamer/dosbox-staging/issues/29#issue-516667214

In my opinion, the fewer requirements tethering us to original hardware (and original distribution media), the closer we get to pure portable digital emulation and the wider and more portable DOS gaming becomes.

Regarding imgmount formats, which games cannot be run with either bin-cue or file-based tracks+ISO? I have done extensive testing (almost 400 CD-based DOS games), and have not found one that fails to operate with either of these approaches.  That said, ripping and generating bin or track-based images is not the easiest task, and is an area we want to significantly improve!

**Comment by dreamer** [comment]
I will clarify: if there's a developer, who feels confident about porting SDL_cdrom to new code, testing, verifying, and maintaining it on multiple OSes, and will help with updating and testing internal dosbox interfaces as our requirements change over time… then I can accept re-implementation back in dosbox-staging. @krcroft did exactly this for SDL_sound, which now lives as `decoders` lib.

The start of this work is with functional re-implementation of changes removed with #95 - but it needs to be re-implementation, as we changed internal CD-DA related interfaces (but a lot of code from there can be recovered with tiny adaptations).

I am *not* going to do any of this work myself - it does not interest me, I can't assure quality of implementation for different OSes, and I don't even have a single working CD-ROM drive to test at my home (and frankly, I don't miss them). I am also *not* going to accept Windows-specific implementations for CD-DA based on MCI, DIO, or ASPI APIs.

If someone else wants to do the work of maintaining it (and that work is massive), I will gladly cooperate to include it in staging :)

That being said… if you own CDs with DOS games bought in 90s… back them up as ISO images ASAP - it's really important, even purely for archival reasons. After 20-25 years, most CDs start to bit-rot - advertised shelf life of "hundred of years" is only for carefully packaged, never used media, stored in a controlled environment.

**Comment by dreamer** [comment]
Btw, @NicknineTheEagle you are literally the first person, who asked for this feature back - do you have some specific game, that needs it?

Over last year of talking about dosbox related topics on various fora, I encountered 1 more person, who was glad physical CDs are supported - but that person used it for game installation only (Dark Forces) - and this usecase should be covered by mounting as subdirectory. I was actually asking people about this - and the vast majority of users *do not care about it*. Most new users build their collection of games based on digital distribution via GOG or Steam; older users have their collections archived as ISOs or BIN/CUE pairs already.

Also, I've seen one report of inability to rip a CD image of game Dominus due to DRM on [Pixelmusement](https://www.youtube.com/watch?v=XNO2L--QVpQ) (around 14:00), so in that case user needed to use physical media… except *none* of dosbox versions he tried (0.74-3, ECE, DOSBox-X) worked correctly for playing audio from a physical CD. Whatever DRM there is and prevents it from working correctly - eXo has this game in collection, so it's possible to create an ISO image.

**Comment by NicknineTheEagle** [comment]
Like I said, for me, it's a mere question of convenience. I have all my of my CD images stored as CUE/BIN but IMGMOUNT command is clunky to use without any kind of GUI or auto-completion so I use a virtual drive and mount it into DosBox.

**Comment by dreamer** [comment]
@NicknineTheEagle Would #92 be an acceptable solution to you? :)

**Comment by NicknineTheEagle** [comment]
Probably, yeah.

**Comment by dreamer** [comment]
I will be working on it again after 0.75.0 :) Drag'n'drop part is trivial to accomplish in SDL2, but internal dosbox interface for mounting images is very clunky - it's hard to use without duplicating a lot of code, so that code area needs to be cleaned up a little.

I have test solution hacked-in for imgmounting of floppies on branch referenced in comments of that issue.

**Comment by krcroft** [comment]
> I have all my of my CD images stored as CUE/BIN but IMGMOUNT command is painfully clunky to use

Fully agree @NicknineTheEagle.
One approach is to place a game's cd image in a standardized location resulting in `./cd/cdrom.cue`.  Once standardized, you can use a similar `start.bat` for each game, containing the same `imgmount d cd/cdrom.cue -t iso` line at the top.

I'm using an approach like this to avoid any hands-on the launch a game (I'm using the retropie frontend).

**Comment by kcgen** [comment]
Housekeeping; suggest we conclude this issue Apr 9 (unless there's more to discuss).

**Comment by dreamer** [comment]
I was thinking about renaming this issue to "Support mounting physical CDs", and placing it in "Rejected" column in our Backlog project. This way it would be easier to discover for newcomers, as they will be directed to Backlog from our contributing guidelines (once they are finished).

I would also edit the first post to include links to all related PRs and issues - in case someone will want to work on implementing this in the future.

@NicknineTheEagle are you ok with me reusing this issue in this way and editing first post?

**Comment by NicknineTheEagle** [comment]
> @NicknineTheEagle are you ok with me reusing this issue in this way and editing first post?

Go ahead.

**Comment by dreamer** [comment]
Thanks :) Did all the edits, closing the issue to mark end of discussion.

**Comment by Wengier** [comment]
Physical CD is implemented in PR #1540, including re-introduction of most code removed in #95 with adaptation to changes in internal APIs that happened since then (as mentioned in the first post).
