### ISSUE TITLE
The mapper is broken

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2706]
## Problem

This is how the mapper looks like on macOS here right now (High DPI screen) on SDL 2.28.1. Was working yesterday, it's totally broken today... which is perplexing as SDL 2.28.1 came out like a month ago?

It's not just small, it's unusable... The graphics are not scaled, but the mouse input is... 🤦🏻 Bluddy on our Discord has reported the same issue on Windows a few days ago. To the SDL folks' credit, at least they broke things on all platforms at the same time! 🥶 

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/cc55637e-875c-40f5-a76e-1134cfa29b06)

For reference this is how it should be like. That's what I get with v0.80.1 that uses SDL 2.26.1.

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/97a59be1-9e5e-4314-8c20-e15f222f7342)

## Solution

Obviously, we just cannot release a new DOSBox version with a completely broken mapper on High DPI. That's non-negotiable.

We'll need to fix this for 2.28.1 _somehow_, then we need to rethink our relationship with 3rd party dependencies and reproducible builds. My very strong preferences are:

- Pin _all_ 3rd party library versions
- Everything should come from Meson, absolutely _no_ dependency on system-wide libraries
- Build should be 100% reproducible:
  - If I rebuild the project tomorrow, it should never fail just because someone has published a new version of their library. But that's the better outcome; the worse is when it _does_ build but things break in a subtle way...
  - Another use case: if I build a commit from 6 months ago, I want to get the _exact same build_ I got on that day, not something "similar" using the currently installed libraries on my system.
- Ultimately, we do not want library updates being forced on us whenever the 3rd party authors feel like it's time for releasing a new version. We want controlled dependency upgrades, when we want, at our own pace (and yes, we should definitely upgrade... but in this case, I would have much rather stayed on an earlier stable SDL2 version, then only upgrade when the guys have fixed their regressions. And who knows, maybe the current behaviour _is_ correct... but it's different behaviour, and perhaps our workarounds we put in earlier for a good reasons in the past no longer work. The point being: we can't just take new library versions and expect them to work flawlessly just because we can still compile the project; everything needs to be thoroughly tested before we say we're ready to take the new version. High DPI support in SDL2 seems to be an especially fragile and flaky thing).

**Comment by shermp** [comment]
Issue confirmed on a locally built MSYS2 Clang64 build running on Windows 11. Linking against SDL 1.28.1

**Comment by johnnovak** [comment]
> Issue confirmed on a locally built MSYS2 Clang64 build running on Windows 11. Linking against SDL 2.28.1

Thanks for confirming.

**Comment by kklobe** [comment]
Hey team, I put together a very quick and dirty hotfix together in #2708, please review.

**Comment by weirddan455** [comment]
I will just note I think it's important to continue to have an option to dynamically link to system libraries since that's the way Linux distros will package it.

I do agree that also having an option to build all dependencies from source would be a good idea though. for the reasons you listed.  It would also be good for CI and for binary releases.  That MSYS CI build that randomly decided to fail because MSYS pushed some package updates is some nonsense we shouldn't have to deal with.

**Comment by kcgen** [comment]
Good catch @johnnovak and nice quick fix, @kklobe !

These are major functional SDL releases:
 - 2.26 was released Nov 2022
 - 2.28 came out ~9 months later June 20, 2023

(SDL usually skips odd release numbers)

The mapper hasn't been upgraded to handle hiDPI. The only reason why the main window wasn't similarly affected is because @GranMinigun has already put that handling in during the 0.80.x time frame.

So this is more of a functional hole in the mapper, which the latest SDL reveals now by default, instead of a regression or bugs in SDL.

**Comment by kcgen** [comment]
Although it's not nice to be caught off-guard by such as large functional hiDPI change (going from SDL 2.26 to 2.28), the good news is that it happened in the middle of our dev cycle.

On macOS, the CI release zip _are_ static builds including SDL containing the exact version(s) of SDL tested at the time of the releases.  

We similarly bundle the exact SDL libs into the Windows release zip and installer packages.

For Linux it's much harder: CI doesn't provide static SDL libs, and distros only offer single versions of their libs that they evolve with time. Some distros offer per-package lib versioning (like NixOS), but these distros are still rare.

Likewise, Linux distros and even macOS HomeBrew that build their own DOSBox Staging releases do so against their own repo-mandatated libs (There are old tickets of myself arguing with a hombrew maintainer about this.. ). 

Come 0.81 time, distros like Arch, Fedora, and HomeBrew /will/ build Staging against SDL 2.28.  If we include technical barries limiting them to 2.26 then they will "patch-upgrade" it or they will simply throw out the package (which we might prefer to avoid harming the users with broken functionality).

The above is a "state of the world" and not my person wish. I also want reproduceable builds because it's critical to help us bisect issues.

Meson actually does provide (and we use) version pinning at the wrap-level.  

```shell
grep version subprojects/*.wrap
```

Main:

```
subprojects/fluidsynth.wrap:wrapdb_version = 2.3.3-1
subprojects/glib.wrap:wrapdb_version = 2.76.4-1
subprojects/gtest.wrap:wrapdb_version = 1.13.0-1
subprojects/iir.wrap:wrapdb_version = 1.9.3-1
subprojects/libjpeg-turbo.wrap:wrapdb_version = 3.0.0-1
subprojects/libpng.wrap:wrapdb_version = 1.6.40-1
subprojects/mt32emu.wrap:wrapdb_version = 2.7.0-1
subprojects/slirp.wrap:wrapdb_version = 4.7.0-1
subprojects/speexdsp.wrap:wrapdb_version = 1.2.1-7
subprojects/tracy.wrap:wrapdb_version = 0.9.1-1
subprojects/zlib.wrap:wrapdb_version = 1.2.13-4
```

If you checkout 0.80, many of these versions will be a bit older.

Passing `--wrap-mode=forcefallback` tells meson to exclusively build using wraps, and ignore all system-provided libraries.

The missing piece is of course SDL (not in the above wrap list), because the SDL wrap is still quite elementary and doen't enable all the features we need.

**Comment by johnnovak** [comment]
Thanks for the comprehensive overview of our current build situation @kcgen , much appreciated that you took the time to write this down 🎉 

> Likewise, Linux and macOS HomeBrew maintainers that build their own DOSBox Staging releases do so against their own repo-mandatated libs, and often refuse to use version-pinned or embedded libs.
>
> There's an old mt32emu-related ticket of myself arguing with a homebrew maintainer who didn't want to use our version-pinned wrap, and instead wanted to disable mt32emu entirely because homebrew at the time didn't have its own mt32emu lib (yes: they would prefer to do without versus trust package-pinned static or embedded libs).
>
> Come 0.81 time, distros like Arch, Fedora, and HomeBrew will build Staging against SDL 2.28, whether we like it or not (because it's the only version of SDL they will have available).

Mandating that the whole world uses the same single giant dependency graph for all software in a Linux distro is sheer madness. I would actually put our officially approved, statically linked, or Flatpak'ed (or whatever it's called) release on top of our Linux downloads page. _That_ is the version that's guaranteed to work correctly! Then people can use Staging installed by their package manager using whatever random runtime dependencies at their own peril...

The benefits of dynamic linking are overblown and/or have never really materialised. It's an outdated model that made some sense in the days when everything was written in C... Also, dynamic linking for improving security is a fundamentally flawed idea, and so is _mandating_ (so much for "freedom", eh?) that everybody upgrades their libraries at the same pace (even libraries that pose no security issues whatsoever, or use maybe one or two harmless functions of the linked library). There are plenty of fact-based, real world examples out there that challenge the ideologically based "dynamic linking fundamentalism". Plus trying to achieve server-grade, military-level security in a _desktop OS_ is just not practical—these use-cases have very different security profiles that involved different tradeoffs. Just a few for who are interested:

"Static Linking Considered Harmful" Considered Harmful
https://gavinhoward.com/2021/10/static-linking-considered-harmful-considered-harmful/

Dynamic Linking Is Bad For Apps And Static Linking Is Also Bad For Apps
https://belkadan.com/blog/2022/02/Dynamic-Linking-and-Static-Linking/

Dynamic linking – Do your installed programs share dynamic libraries?
https://drewdevault.com/dynlib.html

Anyway, I could go on about this all day... 😄 

> The above is just a "state of the world"; I also want reproduceable builds because it's critical to help us bisect issues.

Yep, and I have no dog in this fight either when it comes to our Linux releases 😄

Sure as hell if I ever release [Gridmonger](https://gridmonger.johnnovak.net/) for Linux "officially", there will be a *single* x64 binary and maybe an arm64 binary that rely on libc only and that's it (as it's the default standard for Nim programs). Then dynamic linking enthusiasts can build their own versions, but I'm not gonna support all that in 312234 different runtime environments... that voids your warranty, pal 😎 

But let's focus on what's important for us — 100% reproducible builds at build time on our side.

**Comment by johnnovak** [comment]
> There's an old mt32emu-related ticket of myself arguing with a homebrew maintainer who didn't want to use our version-pinned wrap, and instead wanted to disable mt32emu entirely because homebrew at the time didn't have its own mt32emu lib (yes: they would prefer to do without versus trust package-pinned static or embedded libs).

So much for letting distro maintainers build your own software that you and no one else knows best 😬 In the name of "freedom", I guess? :trollface:
