### ISSUE TITLE
Remove extra noise from the console output when DOSBox is invoked with certain options

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2714]
# Problem

When the user executes `dosbox --printconf` to get the path of the default config, there's a lot of noise around the actually useful output, making it hard to find what he's really looking for.

In this case, there are 9 extra lines of stuff that can be considered just noise vs the _one single line_ of info the user asked for:

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/c7418051-f8ae-4387-80de-41a4b45df63f)

The following command line options have the same issue:

- `--editconf`
- `--eraseconf`
- `--list-glshaders`
- `--opencaptures`

# Solution

Logging should be turned off for these command line options. We should only print the useful info to the console without all extra the noise.

**Comment by weirddan455** [comment]
With the exception of `--startmapper`, I believe these can be moved to happen before Loguru gets initialized, like we're doing for `--version` and `--help`.  They're all just "do something and then exit the program".

`--startmapper` I think is fine how it is?  That one starts up the GUI and the once use exits the GUI, it loads DOSBox normally.  So I believe we need Loguru and SDL initialized already.

I can take a look at this after #2703 gets merged because the solution is most likely going to have merge conflicts with that.

**Comment by johnnovak** [comment]
Yeah, `--startmapper` is actually fine, good call. Removing it from the list.


Otherwise, sounds like a plan. Make it happen @weirddan455 ! 🚀
