### ISSUE TITLE
Default folders regenerating when specified elsewhere in portable conf

### ISSUE THREAD

**Issue by exmensa** [dosbox-staging/dosbox-staging#2772]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Tested with 0.81.0 release and current alpha

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using dosbox-staging.conf to specify where MT-32 roms are located - in my case, in a subfolder within the resources folder - DOSBox will recreate the mt32-roms folder in its root location.  The same happens with soundfonts, which I'd also tried relocating into resources, although I don't see a way to point to the subfolder itself rather than an individual file.

I'm not sure whether this should be filed as a bug or an enhancement, but it seems like undesired behavior when the locations are already manually specified.  The conf and status lines below are just to verify that the conf is being read correctly; I didn't see anything that actually said the default folder was being checked or recreated.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Move mt32-roms folder into the resources folder
2. Specify the new location for the romdir setting in dosbox-staging.conf 
3. Launch DOSBox - ROM folder is located and used, but original mt32-roms folder is regenerated

### Your configuration

```ini
[midi]
mididevice      = mt32

[mt32]
romdir      = resources\mt32-roms
```

### Provide a Log

```text
2023-08-18 21:49:32.412 | MT32: Initialised CM-32L/LAPC-I Control v1.02 from resources\mt32-roms
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
First of all, users are not supposed to put _anything_ into the `resources` folder. That is reserved for data files bundled with DOSBox Staging. The contents of the `resources` folder should neither be modified, nor deleted, nor should you put any extra files in there—otherwise you lose your warranty 😎 Think of it as an integral part of the program; it just happens to be on the filesystem, that's all.

Secondly, the `mt32-roms` and `soundfonts` folders are always created in either the portable directory (in portable mode, when `dosbox-config.conf` can be found in the same directory where the `dosbox` executable resides), or in the user home folder in non-portable mode. That's just how it works, whether you redefine the MT-32 ROM and Soundfont locations in the config or not.

Yeah, maybe a little bit illogical when you use custom locations, but then those empty directories don't really do any harm if unused. The alternative would be not to create these default directories at all, but overall I think it's more user-friendly to create them as most people would just happily use these default locations (at least that's the idea 😄 ).

Closing the issue and removing the bug label everything is working as expected.

Further info about the portable mode (search for "portable"):
https://github.com/dosbox-staging/dosbox-staging/blob/main/README

https://github.com/dosbox-staging/dosbox-staging/pull/2630#issuecomment-1603272056
