### ISSUE TITLE
Fail to build dosbox-staging on Fedora 39 (rawhide)

### ISSUE THREAD

**Issue by runlevel5** [dosbox-staging/dosbox-staging#2789]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

8270aad5b443b6deb10dd03331721419a3730378

### What Operating System are you using?

Other

### If Other OS, please describe

Fedora 39 Linux PPC64LE

### Relevant hardware info

IBM POWER9 CPU, Raptor Computing Blackbird workstation

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When run `meson compile -C build/release` I got [failed build](https://gist.github.com/runlevel5/e3ef97dfcf23c24b0f4f46ebf8327a4b)

```
../../src/cpu/core_dynrec/risc_ppc64le.h:755:28: error: invalid conversion from ‘const uint8_t*’ {aka ‘const unsigned char*’} to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
```

FYI gcc --version
gcc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. meson compile -C build/release

### Provide a Log

```text
https://gist.github.com/runlevel5/e3ef97dfcf23c24b0f4f46ebf8327a4b
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I don't know if any of us are developing on PowerPC.  I'm curious, does Fedora provide a binary for that architecture?  I know they package staging on at least x86_64.

As a workaround, you can try adding '-fpermissive' to the build flags.  Should go here in `meson.build`:

https://github.com/dosbox-staging/dosbox-staging/blob/8270aad5b443b6deb10dd03331721419a3730378/meson.build#L81-L85

Ultimately, those need to be explicitly `const_cast` or something.

**Comment by rderooy** [comment]
Fedora builds its RPMs for all architectures that RHEL are available in. That includes PPC64LE and S390X. You can put some directives in the RPM spec file to limit the architectures, but that is frowned upon.

**Comment by kcgen** [comment]
Thanks @runlevel5 !

I've been waiting for this day :smile: , see my commit message: https://github.com/dosbox-staging/dosbox-staging/commit/ef86642de390839afc77b2b591a6ea9ac43909b3

That Raptor Computing Blackbird workstation is quite a beast! (88 thread count?) Wow.

I'll try to get this compilable but also if check if the @weirddan455's suggestion gets you a working binary, that would also be good feedback.

**Comment by runlevel5** [comment]
Firstly thanks for prompt responses. You all are amazing.

@weirddan455 your suggestion works for me. Like @rderooy has pointed out, PPC64LE (though unpopular with x86_64 consumers) is quite popular in big enterprise / institutions.  

@kcgen I got it compiled but got segfault, that's different issue to look at (I will lodge a new ticket with full gdb stacktrace) I am more than happy to give you access to my box (either SSH or RDP) to aid with troubleshooting.

**Comment by classilla** [comment]
I guess this is where I show up. I'm "ClassicHasClass," the original ppc64le JIT author from https://www.talospace.com/2020/01/dosbox-jit-on-ppc64le-and-how-you-can.html . I'll take a whack at this when I get a moment.

**Comment by kcgen** [comment]
Glad to have your help (and constructive whacks 😅), @classilla!

**Comment by classilla** [comment]
I have it compiling now. Investigating some crashes in codegen.

**Comment by classilla** [comment]
Okay, there is another thing to correct. Right now it's assuming 4K page size, but it needs to handle both 4K and 64K page sizes (Fedora, for example, is 64K by default). With this fixed, codegen works again on ppc64le and I get ripping performance in Descent and Doom. Do you want these as one big PR, one PR with multiple commits, or multiple PRs?

@kcgen

**Comment by classilla** [comment]
(I should add that the compilation fix is entirely within the ppc64le backend and does not involve any other changes. The page size will need some `#ifdef`s elsewhere, probably.)

**Comment by kcgen** [comment]
Awesome progress, @classilla!

> it needs to handle both 4K and 64K page sizes (Fedora, for example, is 64K by default).

In `meson.build`, we have this temporarily commented out:

#if host_machine.cpu_family() in ['ppc64', 'ppc64le']
#  conf_data.set('PAGESIZE', 65536)
#endif

Perhaps you could re-enabled it, with a couple more checks to use 4K or 64K? 

If there's a way you can programmatically discover it with some C or C++ code, then Meson can compile and run checks, too - see `system_speexdsp_test = cxx.run` in `meson.build`, for how we're doing that.

Alternatively: if there's an OS-provided CLI tool that you know will always be present that discovers the page size for you, then you can see the Apple section for an example (because Apple provide a tool called 'pagesize'). See this snippet `pagesize_cmd = run_command('pagesize',` in `meson.build`.

> Do you want these as one big PR, one PR with multiple commits, or multiple PRs?

One PR is good. Given there's no risk of regressions in other parts of the code, and given you're the only one able to maintain this chunk - I'd say it's your call how granular the commit is.

Each commit should compile and run to best of your knowledge, so that way any future regression can be bisected.  Will leave it up to you how many are needed.

(perhaps if you did a second round of performance tweaks, that pass could go in a separate commit).

**Comment by classilla** [comment]
Pretty sure there isn't such a command generally; I was just going to rewrite that section to do a sysconf to get the pagesize from the C compiler, or fall back on 64K if not available. How's that?

**Comment by classilla** [comment]
Actually, skip that. I could use getconf.

**Comment by shermp** [comment]
Also, is it worth setting up a ppc64 docker image (cross-compiling, not native) in CI like we do for ARM?

**Comment by kcgen** [comment]
> Also, is it worth setting up a ppc64 docker image (cross-compiling, not native) in CI like we do for ARM?

Good call, @shermp. I think so. With an active user community (https://forums.raptorcs.com/index.php), makes sense to be aware of new warnings or build failures on this architecture.

**Comment by classilla** [comment]
I think `dyn_mem_adjust` is wrong (it just happens to work for 16K and 4K). It doesn't seem to correctly zero out the low bits at 64K.

**Comment by kcgen** [comment]
Hmm.. in support.h:

```
constexpr uint16_t host_pagesize = { PAGESIZE };
```

Looks like host_pagesize, as a uint16_t, will rollover back to 0 when given 65536.

Hopefully bumping it to uint32_t will fix it!

**Comment by classilla** [comment]
It won't even compile without that :)

There are actually two problems. One I've `ifdef`ed off so that there is no regression risk, but I think it's better code. Currently `dyn_mem_adjust` will drop down a page even if the pointer is already aligned, putting it potentially into unmapped memory and unsettling `mprotect()`. Also, it doesn't adjust the size correctly, at least for 64K. I wrote a new version just for 64K pagesizes. Other platforms use the older code.

The second problem is a workaround. The code that aligns `cache_code` from `cache_code_start_ptr` ends up stripping the top of a 64-bit pointer (Power ISA uses all 64 bits in the pointer address). The workaround is to only do that alignment step if the pointer came from `malloc()`, because the pointer from `mmap()` must be aligned to page size by definition. (Strictly speaking the old code will still break a 64-bit pointer on a system without `mmap()`, but that can be Somebody's Else's Problem.) This touches other platforms but I argue it's the "right" fix and shouldn't regress anything supported.

If those sound cool, I'll prep the PR.

**Comment by classilla** [comment]
I should note that these problems have been there all along, but only because I was trying to get `mprotect()` to be happy did they actually get unmasked.

**Comment by kcgen** [comment]
Sounds like a great approach, to split the function into the baseline plus a new 64K variation. 

If you think it's possible to then add a subsequent commit that collapses them into a new and improved one-size-fits all function, this code improvement would be very welcome (and any issues will bisect into it). 
But either approach is appreciated!

**Comment by classilla** [comment]
Posted. I'll look at some improvements separately, but this gets the port back in order.
