### ISSUE TITLE
[Feature Request] Add LFN support

### ISSUE THREAD

**Issue by runlevel5** [dosbox-staging/dosbox-staging#2831]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81-alpha

### What Operating System are you using?

Other

### If Other OS, please describe

Linux ppc64le

### Is your feature request related to a problem? Please describe.

Long File Name support has been part of DOS 7 in Windows 95 time. It really help with file management that uses long file names.

This feature has been implemented in some dosbox forks. IMHO it is not much effort to backport/cherry-pick this change to dosbox-staging.

It would be great to see this feature adopted in dosbox-staging. If users do not like this feature, I think a feature flag in config file or at build time to disable it.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by MasterO2** [comment]
https://github.com/dosbox-staging/dosbox-staging/pull/467

**Comment by kcgen** [comment]
The amount of work involed is non-trivial without any present team members willing to undergo such an effort/burden for the benefits involved.  

As mentioned in the PR linked by @MasterO2, the prior porting attempt was estimated to generate 500+ review comments and likely take weeks if not months to fully work through to achieve the desired code state. 

I am unfortunately not even willing to add it to our backlog, because I know it's not something any of us have the stomach for, so unfortunately closing this as "won't fix".
