### ISSUE TITLE
config -wc  command ignores -conf option

### ISSUE THREAD

**Issue by Ajaja** [dosbox-staging/dosbox-staging#2975]
### Different version than latest?

git master  (dosbox-staging, version 0.81.0-alpha-1744-gf61cded82)

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

`config -wc`  command ignores `-conf` option in the latest git builds

### Steps to reproduce the behaviour.
Create test.conf with
```
[autoexec]
config -wc 
```
Run `dosbox -conf test.conf`
It shows `Writing current config to 'dosbox.conf'` and creates new `dosbox.conf` instead of updating `test.conf`

**Comment by johnnovak** [comment]
Works as it should. For one, you can provide multiple `--conf` arguments, so it becomes ambiguous which one to even write. Secondly, this is now the `config -wc` works; it always writes the local `dosbox.conf` by design. If you wish to write the config to a different file, use `config -wc some_name.conf`.

The help of the config command documents all this precisely:

<img width="1088" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/68086ef0-7047-4d66-9d41-5fc9bb3960a9">

**Comment by Ajaja** [comment]
Ok. But before 0.80.0 it worked differently:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/297472/7cb2eca0-f3fc-4712-91cc-a94f19fc33b5)
And  in  `manual.txt`  from v0.80.1:
```
  -writeconf
     (or -wc)
     Write the configuration **to the primary loaded config file.**
```

All other versions of Dosbox write -wc to  the primary loaded config file too.

**Comment by johnnovak** [comment]
Yes, config writing was a mess before, and it's quite a mess in other DOSBox versions...

Please study the help text of `CONFIG /?` to learn how it works going forward. The behaviour is consistent and easy to understand now.
