### ISSUE TITLE
`dosbox FOOBAR.EXE` no longer mounts and launches the executable

### ISSUE THREAD

**Issue by es20490446e** [dosbox-staging/dosbox-staging#2987]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In `dosbox-staging.conf`, the `autoexec` section seems not to work when launching a game from the terminal with `dosbox [game]`. Only when launching `dosbox` first, then entering the appropriate commands to run the game.

Oddly it will work if you launch the game directly with `dosbox [game]`, then exit it without leaving the emulator, then launching it again by typing commands. On that second launch it will work.

For example `mixer fsynth 20` won't work.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
@es20490446e The `[autoexec]` section implementation was rewritten few months ago - if you can, try the latest GIT main, it now executes the supplied command after the content of `[autoexec]`.

**Comment by es20490446e** [comment]
Let me check...

**Comment by es20490446e** [comment]
I can't test because git just [crashes](https://github.com/dosbox-staging/dosbox-staging/files/12876425/dosbox.log) with any program. Also by deleting the dosbox configuration folder.

**Comment by johnnovak** [comment]
> I can't test because git just [crashes](https://github.com/dosbox-staging/dosbox-staging/files/12876425/dosbox.log) with any program. Also by deleting the dosbox configuration folder.

That seems like a clean exit according to the posted logs.

**Comment by kcgen** [comment]
@es20490446e , just to confirm, you're not using any [autoexec] sections because you're starting from scratch (without a primary config,which gets created).

Without an autoexec section, passing an executable on the CLI like:

`/Path/to/dosbox-staging INSTALL.EXE` 

Should result in:
1. The file's path (`./` in this case) should be mounted as`C:`
2. The `C:` drive should be switched into.
3. The executable, now present and available in DOS's current working directory, should be launched.
4. When the executable exits back to the DOS prompt, DOSBox Staging itself should exit back to the host (I believe with error-code passthru, too). 

In this case though, the executable doesn't even get off the ground for a split second, so step 4 is aborted and the shell is kept running so you can investigate the problem:

`SHELL: Exit blocked because program quit after only 0.2 seconds`

Looking at the logs, I'm not not seeing the install.exe's path being mounted as C. 

Can you try this instead as a bit more combersome workaround:

`dosbox -c "mount c ." -c c: -c install.exe -c exit`

That's roughly what the above should do automatically.

**Comment by es20490446e** [comment]
It still doesn't work: [record](https://youtu.be/aWRTUR96Vno).

**Comment by kcgen** [comment]
Thanks @es20490446e ,

The expanded form appears to be OK, like you mentioned:


![2023-10-12_08-00](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/5bc1d516-4db5-47f0-ae90-6bce2bcfc947)

![2023-10-12_08-01](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/e94b0fc6-a845-4816-81ff-919101550df0)

However the short-hand form appears to have a bug:

![2023-10-12_08-03](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/9bd78896-4161-4ea6-9fc6-1af85cfb22c7)

![2023-10-12_08-03-1](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/7c16bb08-dc3c-42f7-9e05-e6b1c1e5d604)

Passing an executable to DOSBox Staging, for example `dosbox gods.exe`, _should_ result in the expanded form, equivalent to:

![2023-10-12_08-02](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/96dd53e2-db6b-46d8-9f9a-9108be031f3f)

**Comment by kcgen** [comment]
In general, the sequence is:

1. Command line actions first (`-c`), in order
2. Then primary conf but can be blocked with `--noprimaryconf`
3. Then local conf (ie: `dosbox.conf`) but can be blocked with `--noplocalconf`, finally
4. All CLI-passed confs `-conf ...`, in order

**Comment by kcgen** [comment]
> This doesn't work at all. It just tries to execute INSTALL.EXE and then fails because it's not in a DOS path. The auto-mounting and switching does not work.

@weirddan455; yup - this is a new regression.

**Comment by weirddan455** [comment]
Confirmed regression.  It's working in v0.80.1.  I'll give it a bisect.

**Comment by FeralChild64** [comment]
It is most likely the result of my `[autoexec]` rework (mainly intended to add UTF-8 support to the whole `dosbox-staging.conf`, including `[autoexec]` section). The problem is, I couldn't find information how this should PRECISELY work - so it collected what I knew and what was clear from the previous code and implemented according to description/comments here: https://github.com/dosbox-staging/dosbox-staging/pull/2609

Mounting anything as drive C if only a command is supplied was most likely not implemented. We can add it, but we need precise information what to mount as drive C: and when exactly (conditions).

**Comment by FeralChild64** [comment]
In short: command

```./build/dosbox -noprimaryconf ./build FOOBAR.COM```

will give you the following result and generate the following `AUTOEXEC.BAT`:

![out](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/9f359bcb-252b-40f6-bddc-95fb81e43dfd)

**Comment by FeralChild64** [comment]
BTW - there is one important difference between 0.80.1 and GIT main regarding handling `dosbox FOOBAR.COM` command:
- 0.80.1 first mounts directory as drive `C:`, then executes `FOOBAR.COM`, at the end executes `[autoexec]`
- GIT main first executes `[autoexec]`, then executes `FOOBAR.COM`; if I'm not mistaken, this was changed even before my rework

It is very likely the `[autoexec]` section already contains a `MOUNT C some-directory-serving-as-drive` command; so we would need to be careful about when to mount directory with `FOOBAR.COM` as drive C: and when to not mount anything.

**Comment by kcgen** [comment]
It's unfortunately quite overloaded when mount-points conflict:
- The CLI `-c mount`s, can conflict with
- `[autoexec] mount`s, and that includes...
- `dosbox /path/to/FOOBAR.EXE` form as well, because it implies `-c "mount c /path/to"`

To resolve this ambiguity, we have the `autoexec_section = join / overwrite` conf setting:
- **`join`**:  Combine them into one big section (legacy behavior; default).
- **`overwrite`**:  Use the last one encountered, like other config settings.

In the `join` mode, the combined [autoexec] is formed in order:
1. CLI `-c statement`s including "expanded form" of `dosbox FOOBAR.EXE`
2. Then primary autoexec lines
3. Then local autoexec lines
4. Then `-conf custom.conf` (and number), of their lines, in order

Exactly like @weirddan455 mentioned:

> Previous behavior is more consistent. On git main, dosbox -c foobar.com (note the -c) executes [autoexec] last. I would expect the same when omitting the -c.

For `dosbox /path/to/FOOBAR.EXE`, one idea we could try is include the unmount as well, so it's expanded to: `-c "mount c /path/to" -c c: -c FOOBAR.EXE -c "mount -u c"`.

In `overwrite` mode, the CLI takes precedent; absent that, the last encountered `[autoexec]` section is the one executed (so `-conf custom.cont` would trump local confs, which in turn would trump the primary conf).

**Comment by FeralChild64** [comment]
@kcgen I'm not sure if I understand it correctly:

1. Should the command from `dosbox -c command` be executed:
- (a) before the secure mode is enabled
- (b) after the secure mode is enabled, but before `[autoexec]` content
- (c) after the `[autoexec]` content

2. Should the command from `dosbox command` be executed:
- (a) before the secure mode is enabled
- (b) after the secure mode is enabled, but before `[autoexec]` content
- (c) after the `[autoexec]` content

3. In case of `dosbox command1 -c command2` or `dosbox -c command2 command1` (current parsing code does not distinguish between these two) which one should be executed first, `command1` or `command2`?

4. `dosbox /path/to/FOOBAR.EXE` should be a new special case, with unmounting drive C between `FOOBAR.EXE` and `[autoexec]` content, right?

Please keep in mind that after secure mode is enabled, we cannot mount any new drive or unmount an already mounted one!

Sorry, I don't use this functionality (I just wanted a nicely formatted `Z:\AUTOEXEC.BAT` file + UTF-8 support), so it is very hard to me to tell what is correct and what is wrong - especially that I can imagine a lot of use cases.

In any case - usually it should be quite simple to manipulate the order, just go to https://github.com/dosbox-staging/dosbox-staging/blob/main/src/shell/autoexec.cpp and observe the definitions and usage of this `enum class`:

```C++
enum class Placement {
	// Autogenerated commands placed BEFORE content of [autoexec]
	InitialAutogeneratedCommands,
	// User commands executed just before secure mode gets enabled
	CommandsBeforeSecureMode,
	// Command to enable secure mode
	SecureModeCommand,
	// Content of [autoexec] section from the configuration file(s)
	AutoexecSection,
	// Final commands to boot guest OS or start given program or BAT file
	CommandsAfterAutoexecSection,
};
```

**Comment by kcgen** [comment]
The placement looks perfect as-is (I think it's just the expanded-form that needs fixing). Will answer one-by-one:
> 
>     1. Should the command from `dosbox -c command` be executed:
> 
> 
>     * (a) before the secure mode is enabled
> 
>     * (b) after the secure mode is enabled, but before `[autoexec]` content
> 
>     * (c) after the `[autoexec]` content
> 

**(a)**

`dosbox -c command` (and the generated commands from `dosbox FOOBAR.EXE`) should be part of the `InitialAutogeneratedCommands`.  

The command-line arguments are trusted and should be permitted prior to secure lock-out.


> 
>     2. Should the command from `dosbox command` be executed:
> 
> 
>     * (a) before the secure mode is enabled
> 
>     * (b) after the secure mode is enabled, but before `[autoexec]` content
> 
>     * (c) after the `[autoexec]` content
> 

**(a)**, same explanation as above.

> 
>     3. In case of `dosbox command1 -c command2` or `dosbox -c command2 command1` (current parsing code does not distinguish between these two) which one should be executed first, `command1` or `command2`?

They should be launched in the order given.

In case of `dosbox command1 -c command2`:

1. command1: is the new special case, followed by
2. command2: is a literal DOS CLI statement, as-is

In the case of `dosbox -c command2 command1`:

2. command2: is a literal DOS CLI statement, as-is, followed by
1. command1: is the new special case

I think it's fair to treat `-c command`s simply as literal DOS statements without any smarts behind them. 

Basically, `-c` lets users construct autoexec by hand. Something like:

```shell
dosbox -noprimaryconf -nolocalconf \
  -c "mixer 120" \
  -c "mount c /home/dos" \
  -c c: \
  -c "cd games\civ" \
  -c "echo running civ" \
  -c civ"
```

where as: `dosbox command1` requires this new special case when `command1` is actually a path to an executable on the host that (case-insensitive) happens to be a DOS executable ending with `.EXE/.exe`, `.BAT/.bat`, `.COM/.com`

> 
>     4. `dosbox /path/to/FOOBAR.EXE` should be a new special case, with unmounting drive C between `FOOBAR.EXE` and `[autoexec]` content, right?
> 

yes; :+1: 

> 
> Please keep in mind that after secure mode is enabled, we cannot mount any new drive or unmount an already mounted one!

Indeed.

Secure mode is meant to trust all things provided by the user launch DOSBox (CLI plus confs). 

Once the DOS command line is available to users, secure-mode shouldn't trust it with mounts.   

The best example is exposing your own DOSBox session via VNC to wide-open public users on the internet: secure-mode keeps them in a sandbox, so they can't mount new host areas nor can they affect future runs, like modifying the conf files.

(It's kind of a toy though - users like Archive.org probably just run dosbox in a docker container or BSD jail, and discard the entire session after)


> 
> Sorry, I don't use this functionality (I just wanted a nicely formatted `Z:\AUTOEXEC.BAT` file + UTF-8 support), so it is very hard to me to tell what is correct and what is wrong - especially that I can imagine a lot of use cases.
> 

yup - the user can still create lots of conflicts; that's OK though - we can't protect them from using conflicting mounts and such. They will see those errors and adapt their launch/organization to suite.

> In any case - usually it should be quite simple to manipulate the order, just go to https://github.com/dosbox-staging/dosbox-staging/blob/main/src/shell/autoexec.cpp and observe the definitions and usage of this `enum class`:
> 
> ```c++
> enum class Placement {
> 	// Autogenerated commands placed BEFORE content of [autoexec]
> 	InitialAutogeneratedCommands,
> 	// User commands executed just before secure mode gets enabled
> 	CommandsBeforeSecureMode,
> 	// Command to enable secure mode
> 	SecureModeCommand,
> 	// Content of [autoexec] section from the configuration file(s)
> 	AutoexecSection,
> 	// Final commands to boot guest OS or start given program or BAT file
> 	CommandsAfterAutoexecSection,
> };
> ```

This was a great addition and still perfectly suited to manage (or categorize) this new FOOBAR.EXE expanded form of the CLI.

**Comment by es20490446e** [comment]
> the user can still create lots of conflicts

In case of conflict, generally just taking into account the latest command probably will be the best solution.

**Comment by johnnovak** [comment]
I have only skimmed the details, but I've seen enough 😄 My preferred way of solving such Gordian knots where a single weird edge casey feature conflicts with everything else: throw the feature out.

We should not think about "how to shoehorn this in", IMO. We should think about "what is the most consistent and orthogonal system for autoexec handling and drive mounting". If this shortcut feature is in conflict with that, and it complicates the codebase a lot, I'd just drop it. It's a quite niche feature, after all.

The problem with special cases is that maybe 5 people will actively use it, but everybody else forgets the special rules and they're a maintenance burden. In general, I hate special casing.

**Comment by weirddan455** [comment]
>  (It's kind of a toy though - users like Archive.org probably just run dosbox in a docker container or BSD jail, and discard the entire session after)

Don't want to get too off topic here but I'm pretty sure the archive.org player runs entirely client side using something like [em-dosbox](https://github.com/dreamlayers/em-dosbox) that uses Emscripten to compile Dosbox into either Javascript or Web Assembly.

As far as I know, there's no client-server connection and security (on client side) is handled by the web browser's sandboxing.

**Comment by es20490446e** [comment]
By the way I'm trying to improve the upstream FluidSynth defaults [here](https://github.com/FluidSynth/fluidsynth/issues/1282).

If you have any suggestions on how to improve midi music, they would be very appreciated. Just [email me](https://es20490446e.wordpress.com/contact/).

**Comment by es20490446e** [comment]
> It's a quite niche feature

I have seen autoexec used frequently for having pre-configured bundles of games.

> think of writing the manual entry for it first

What I do for coding complex software is just:
- Breaking the code into the smallest functions.
- Improving the code into the smallest iteration, validating each iteration before continuing with the next one. Code the simplest case first, then add more.
- Designing to require as little documentation as possible, everything to be as obvious as possible to anyone. Organization, naming and usage.
- Provide a single way to do things.
- Have a unit test for each function, but written after coding the function.

Contrary to popular practice I don't design the software beforehand. I code the smallest iteration, and test that the design makes sense IN PRACTICE.

I don't make guesses, I validate empirically.

**Comment by kcgen** [comment]
Taking a runnable program as an argument is CLI 101:
- `bash myscript.sh`
- `python3 myprog.py`, and yes:
- `dosbox dosgame.exe`

But this just isn't theoretically used.. its very common for users to have a shortcut to dosbox on their desktop, and drag their game executables onto it. 

Linux users have historically (pre-Staging) had dosbox in their PATH (through their repo package install), and could manually navigate and launch games via the CLI:

```shell
cd dos/civ
dosbox civ.exe
```

It's also the default API used by game launchers when setting up a generic emulator (`emulator %1`)

Now.. I prefer to manage everything using local confs, so I won't be affected if we toss it.. but I'm positive this will affect a lot of people and this feature is "command line 101" friendly for new users.

**Comment by johnnovak** [comment]
Yeah, so my view is DOSBox is simply not a "regular" CLI app as it requires a GUI. So the comparison to Python and bash doesn't quite hold.

But then, if this can be supported in a simple way for those legacy use cases, then why not... I guess what I'm saying, don't go overboard with handling edge cases "correctly" when a local `dosbox.conf` or automounting is involved. Just do some simple thing, then if it conflicts, too bad. Please migrate to using proper configs 🤷🏻

**Comment by johnnovak** [comment]
> By the way I'm trying to improve the upstream FluidSynth defaults [here](https://github.com/FluidSynth/fluidsynth/issues/1282).
> 
> If you have any suggestions on how to improve midi music, they would be very appreciated. Just [email me](https://es20490446e.wordpress.com/contact/).

General MIDI DOS games were composed for the SC-55. FluidSynth cannot accurately emulate the SC-55 reverb and MIDI behaviour, full stop. It's impossible.

You can tweak the chorus & reverb defaults to suit any single game almost perfectly, but those defaults will likely sound "wrong" (not exactly the same as on a SC-55) in other games. Similarly, if the game doesn't use _static_ chorus & reverb settings but changes them per song or maybe even during a single song, all bests are off. You simply cannot find a single default setting that will work perfectly.

Tweaking the defaults for DOOM is very misleading as that games has a rather simplistic rock/metal soundtrack. That needs vastly different FluidSynth defaults than adventure games with more atmosperic soundtracks.

In general, the ScummVM defaults are fine, I think we're using those. Rock/metal type soundtracks like DOOM are still in the minority, I definitely wouldn't tweak our defaults for those.

But you cannot win here. Ultimately, you need accurate SC-55 emulation to enjoy these games in their best form.

**Comment by kcgen** [comment]
> OR simplify things: if you provide an EXE on the CLI as a second paramter, some other functionality will be disabled. Just to keep it simple and understandable and avoid the combinatorial explosion.

Indeed 👍; the `autoexec_section = overwrite` is a Staging-specific simplification that eliminates (upstream) multi-autoexec-aggregation.

I tried to eliminate the aggregation entirely, but it was still used.. so had to create a conf setting. And even then we still default to the more complex upstream behavior for out-of-the-box compatibility.

**Comment by johnnovak** [comment]
> I tried to eliminate the aggregation entirely, but it was still widely used and requested.. so had to create a conf setting. And even then we still default to the more complex upstream behavior for out-of-the-box compatibility.

That's... sad.

Which mean we need to keep it (I guess?), which means we need to document it... In any case, that will be a "legacy feature, don't using, warnings signs everywhere" section at the end 😄 

Seriously, if you need 5-10 bullet points to explain the various edge cases of a feature, I wonder who can remember all that crap in practice... I surely can't! That's inviting support tickets when users shoot themselves in the foot in wild and interesting ways...

Ok, I've said my piece 😅

**Comment by Grounded0** [comment]
Its the joys of dealing with over 20 year old software project. I'm quite sure it will be returned to the expected behaviour soon now that the expected behaviour is documented. Backwards compatibility rules the day if you can avoid becoming hostage to it which we have done so far quite successfully.

**Comment by es20490446e** [comment]
> I'm for _ruthless simplification_ when it makes sense 😎

Actually I personally don't need any of those commands, as I run dosbox through [exeCute](https://gitlab.com/es20490446e/exeCute) and it figures out all that manual configuration automatically.

I believe that's the real ruthless simplification 😛

---

> Those defaults will likely sound "wrong" (not exactly the same as on a SC-55) in other games.

It depends on your definition of wrong.

If wrong means that it sounds different, then it will be wrong.

But for me right is just sounding pleasant and natural. Worse is better.

---

> Tweaking the defaults for DOOM is very misleading as that game has a rather simplistic rock/metal soundtrack. That needs _vastly_ different FluidSynth defaults than adventure games with more atmospheric soundtracks or games with orchestral soundtracks.

By the way Christian Collins, the author of the great sound-font "General User", shared his config with mine and it works great.

He said he tested his settings with a wide array of MIDI files with GeneralUser and other sound-fonts.

---
Bottom-line:

> It's impossible.

Impossible is nothing. It's a matter of if you want to put the effort it takes.

**Comment by kcgen** [comment]
I've renamed the ticket to clarify the regression. 
The regression itself is small and well-contained.
Let's please let @FeralChild64 address it at face-value.

**Comment by johnnovak** [comment]
> By the way Christian Collins, the author of the great sound-font "General User", shared his config with mine and it works great.
> 
> He said he tested his settings with a wide array of MIDI files with GeneralUser and other sound-fonts.

Are his FluidSynth settings for GeneralUser publicly available somewhere? If not, can you share them?

More pleasing defaults is fine, of course, even if it's impossible to emulate the SC-55 accurately via FluidSynth. Well, you brought up DOOM in your related ticket and tweaking defaults for DOOM really doesn't inspire confidence 😄 , but now that you brought the author of GeneralUser GS into the discussion, I'm interested in his settings. That's the single best GS-capable SF2 that comes close to the SC-55 in character and balance, the one I personally recommend to everybody if they must use FluidSynth.

**Comment by es20490446e** [comment]
> can you share them?

I will share the pull request to FluidSynth, with the settings in it, once I have it ready.

**Comment by FeralChild64** [comment]
> I think @FeralChild64 has a clear path to fix this small regression

Not really - in fact, I understand even less than few days ago. Especially this puzzles me:

> Secure mode is meant to trust all things provided by the user launching DOSBox.
> Once the DOS command line is available to users, secure-mode shouldn't trust it with changing mounts.

The software we are running inside DOSBox certainly shouldn't be trusted either; if the FOOBAR.EXE has a bug (or maybe even not a bug, but a lesser-known functionality) allowing the malicious user to execute supplied commands, our security is basically compromised - that's why in case of `-securemode` switch I have blocked all the keyboard input until the generated `AUTOEXEC.BAT` code executes `CONFIG -securemode` command. If I have to launch a game executable before, I need to get rid of this protection.

----

I'll try to restore previous behavior of `dosbox FOOBAR.EXE`, `dosbox -c command`, but don't ask me to extend it - I somehow feel the whole idea behind these command line features is contrary to what I believe software should behave.

**Comment by weirddan455** [comment]
>  I'll try to restore previous behavior of dosbox FOOBAR.EXE, dosbox -c command, but don't ask me to extend it - I somehow feel the whole idea behind these command line features is contrary to what I believe software should behave.

How do you think it should behave?

>  The software we are running inside DOSBox certainly shouldn't be trusted either

I agree with that.  I'm not familiar with what `securemode` does exactly but I would expect it to sandbox the Dosbox environment from affecting the host.

I explained in an earlier comment how (to the best of my knowledge) things like the archive.org player work.

> The best example is exposing your own DOSBox session via VNC to wide-open public users on the internet: secure-mode keeps them in a sandbox, so they can't mount new host areas nor can they affect future runs, like modifying the conf files.

I think this is a very niche use case.  I actually can't think of anyone using Dosbox in this way.  I would expect a sandbox to protect against malicious or badly coded DOS programs from breaking the host.  Trying to protect against remote internet users seems misguided.

Of course, building a true sandbox is a lot of work so I'm not expecting anyone to implement that in the near future.  But if `securemode` doesn't provide that, I'm not sure what it's true purpose is exactly.

**Comment by kcgen** [comment]
There are old screenshots of DOSBox being used in semi-public environments like hospitals, factories, libraries, and and machining/milling centers.

(Recall in 2020.. DOSBox was being used for some office function but they hit some snag.  Their boss asked someone from the team to phone into their telecon and give status on the issue :facepalm: :rofl:)

Although I can't find it, jmarsh even mentioned on vogons that it's possible to escape the dynamic core (and presumably from there, activate existing DOSBox functions, or get out further into the user space and setup some bigger attack).

All that to say - I don't think any of us would rely on system security with `securemode`.  If someone doesn't trust the executable they're running, they should use an "industry-grade" containment systems that ascribes to security best practices (containers, jails, VMs, etc).

Secure mode was invented post-0.72 to fix [CVE-2007-6328](https://www.cve.org/CVERecord?id=CVE-2007-6328):

```
Author: QBix
Date:   Sun Mar 2 11:13:47 2008 +0000

    Allow longer commandlines in MOUNT and IMGMOUNT.
    Fix crash reported by MiniMax (mount -u 0).
    Fix bug reported by Tearex ("config -get" broken).
    Add some protection that makes it harder to mount a directory from
    within an executable.
    Add some protection to make mounting from command /c much harder.
    Add a securemode commandline switch to config and dosbox that should make it
    impossible to mount a location when this isn't wanted by the user. (Addresses concerns of CVE-2007-6328)
    Update documentation to reflect this.
```

The CVE issue itself is in dispute, likely because DOSBox has no additional filesystem priviledges than the user's own permissions.

A user can run a hostile executable inside DOSBox, which in turns can harm any files that the user already has write-access to.

The same issue exists if we remove DOSBox: _A user can run a hostile executable, which in turns can harm any files that the user already has write-access to._

**Comment by FeralChild64** [comment]
@weirddan455:

>  I'm not familiar with what `securemode` does exactly

It prevents the user from doing things which might be dangerous to host system - mainly blocks the ability to mount/unmount drives, but there are few other things which are blocked - search the code for `control->SecureMode()`

> How do you think it should behave?

1. IMHO too many things happen automagically, in a way which might not be clear to the user invoking the command - I don't like it.
- to mount the CD image there should be a dedicated switch, like `--mount-cd-img drive_letter image_name,[image_name_2,...]`, to mount hard disk image something like `--mount-hd-img drive_letter image_name` and `--mount-hd-dir drive_letter dir_name` - currently we are guessing desired action from file extension
- automounting the current directory as drive C is another example - there should be a switch for this, so that we are sure this is exactly what the user wants

2. I would prefer the supplied command to be executed AFTER `[autoexec]` (that's how we work with real DOS after all); if our user wants the opposite, he should pass `--noautoexec` switch; executing command first and `[autoexec]` next is, IMHO, bizarre.

3. If we have a `dosbox -c command` syntax, there should be no `dosbox command` syntax doing exactly the same (or there should be a clear difference between these two); Right now this is confusing.

@kcgen

> All that to say - I don't think any of us would rely on system security with `securemode`.

I agree - but one more protection mechanism won't hurt.

**Comment by kcgen** [comment]
> I agree - but one more protection mechanism won't hurt.

:+1: ; fully agree. Even a screen door keeps the mosquitos out, and that's  the worst we're dealing with here :-)

**Comment by kcgen** [comment]
@FeralChild64, 

I think your 2. proposal is good - I would suggest that straight away, and we can document it as-such.  `[autoexec]` default is empty, so this interaction won't harm new or default users.

For 3. the distinction is:
 - `dosbox -c statements` are just literals
 - `dosbox EXECUTABLE` will mount, run, and unmount

I don't know how make the second form work properly in `-c` statements.
But maybe you can find a way?

**Comment by es20490446e** [comment]
My bet is that when humans travel to Mars they will have dosbox onboard.

So they can play old school games like Tetris.

**Comment by es20490446e** [comment]
By the way probably removing the option to adjust fsynth gain without an autoexec command was a bad idea.

At least it doesn't make much sense now having to see the `mixer fsynth` output on every dosbox launch.

![Screen-1](https://github.com/dosbox-staging/dosbox-staging/assets/9594332/c9e5b6a4-0a79-4963-aed6-370bae313982)

**Comment by kcgen** [comment]
> By the way probably removing the option to adjust fsynth gain without an autoexec command was a bad idea.

@es20490446e, can you open a new issue, and copy-and-paste these unrelated MIDI discussions, because they have nothing to do with this `dosbox FOOBAR.EXE` regression, and have harmed the signal to noise ratio in this ticket; it's now a mess to scroll through.

Thanks.

**Comment by Grounded0** [comment]
Start your AUTOEXEC.BAT with:

`@ECHO OFF`

So it runs without command interpreter showing whats run

Run mixer in SILENT MODE:

`MIXER FSYNTH 65 /NOSHOW`

In order to avoid volume levels being shown.

**Comment by Grounded0** [comment]
This isn't a tech support forum but let me show how its done:

Start `AUTOEXEC.BAT` with line 1 being:

`@ECHO OFF`

So command interpreter doesn't show every command being run.

To run `MIXER` in silent mode:

`MIXER FSYNTH 65 /NOSHOW`

So it doesn't show volume levels each time its run.

**Comment by kcgen** [comment]
@es20490446e , @johnnovak , @kcgen , @Grounded0 -> seven posts involving MIDI comments have been marked off-topic to preserve signal-to-noise in this ticket.

@es20490446e, please don't bring up other random issues in ticket like this. It's generated useful responses from the team, but then harmed the ticket itself.

The content is still there - it's just collapsed.

**Comment by johnnovak** [comment]
While I was guilty of using our own tickets as a "general chat" type of message board at times with fellow dev team members, that doesn't mean the practice is encouraged 😄 Please don't use the same ticket to list all your woes @es20490446e, raise separate issue ticket in the future, or ask the questions on our Discord. There are lots of helpful fellow users there 😄

**Comment by Mastrius0713** [comment]
The only work around I have found for this is to add the TSR mount and path into the batch file.

MOUNT D E:\GAMES\NOVERT
PATH=D:\
NOVERT.COM
DOOM.EXE
