### ISSUE TITLE
Switching between fullscreen/windowed sometimes results in a black screen.

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2993]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Switching between fullscreen/windowed sometimes results in a (temporary, up to 1 second) black screen.

The issue is cycles dependent! Witch cycles=30000 you barely notice it, with cycles=1000 the screen stays black for longer periods.

Also it's not consistent, so sometimes the screen comes back instantly, sometimes it takes longer.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install latest DEV version of Staging.
2. Use eXoDOS v5 version of Falcon A.T. or download the repro pack.
3. Launch with efalcon.exe
4. Switch between windowed and fullscreen.

[EFalcon.zip](https://github.com/dosbox-staging/dosbox-staging/files/12880752/EFalcon.zip)

This is the screen i'm testing with:
![Bildschirmfoto 2023-10-12 um 13 14 45](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/0ab2ad0f-3eeb-49ca-b40a-c9f6906f0b11)

### Your configuration

```ini
default config
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by GranMinigun** [comment]
Likely a case of DOSBox recreating the whole renderer on window mode toggle, and then rendering a new frame only if it's different.

**Comment by johnnovak** [comment]
Does the black screen timeout coincide with the blink rate of some indicator on the otherwise static cockpit?

**Comment by Burrito78** [comment]
It happens a lot in PHM Pegasus, even 35000 cycles, on the copy protection screen. This is a static EGA screen.

[PEGASUS.zip](https://github.com/dosbox-staging/dosbox-staging/files/12893315/PEGASUS.zip)

**Comment by johnnovak** [comment]
> It happens a lot in PHM Pegasus, even on 35000 cycles, on the copy protection screen. This is a static EGA screen.
> 
> [PEGASUS.zip](https://github.com/dosbox-staging/dosbox-staging/files/12893315/PEGASUS.zip)

Can you try this in your config?

```
[sdl]
presentation_mode = cfr
vsync = off
```

That should fix it. Also paging @kcgen as there seems to be some problem with the frame replicating mechanism still in VFR mode.

**Comment by kcgen** [comment]
Yes, throttled VFR might have skipped rendering a frame just prior to toggling the fullscreen-to-window-mode (or vice-versa).

This skipping behavior _should_ be fine (for example: use `output = texture` and then using window-dragging to resize the window.. there are frames being skipped during those drag-resize events, too).

However, because we unnecessarily tear down and re-create the entire renderer and context across fullscreen-to-window-mode changes, it resumes life with a blank frame.

CFR in theory is affected too, but it does a good job at hiding it by simply re-presenting (at constant rate).
 
This is in my queue for 0.81, but I want to focus on the destruct sequence PR first.

The fix likely will require some kind of kludge to force-render both going in and out of these full context destruction sequences (mimicking CFR).

If anyone wants to poke around and fix this up in the meantime - please jump on it! I don't want to hold this up, nor am I trying to reserve this ticket "just for me" :sweat_smile: !

The gold-star long solution is @granminigun's sdl rework, which retains the rendering stack across these window events.

**Comment by johnnovak** [comment]
Cool, overall it's a low priority issue @kcgen, so I don't think there's much of an urgency here. 

1 second timeout seems a bit long, though. That means we're duping at 1FPS... I thought it was higher?

When you (or anyone) looks into this, it would be good to implement the low FPS bound config setting for the VFR mode. So, for example, people could set it to 30 or 40 if they VRR monitors misbehave when going below that rate.

**Comment by kcgen** [comment]
Yup, @johnnovak -- adding that lower bound VFR dupe rate (as a configurable, too) should do the trick!

**Comment by Burrito78** [comment]
> Can you try this in your config?
> 
> ```
> [sdl]
> presentation_mode = cfr
> vsync = off
> ```
> 
> That should fix it. Also paging @kcgen as there seems to be some problem with the frame replicating mechanism still in VFR mode.

Yes, this does fix the issue visually for me. 

What I noticed while testing with PHM Pegasus is that the issue happens in EGA only (hf.exe e), not in the default CGA mode of the game.

**Comment by kcgen** [comment]
@Burrito78, CI-generated .dmg ready for testing:

https://github.com/dosbox-staging/dosbox-staging/actions/runs/6519828271?pr=3004

**Comment by Burrito78** [comment]
@kcgen Yes, this seems to fix the issue I had!

Obervations:
-Screen still goes black when switching (expected) but always recovers quickly.
-Recovery times are sometimes quicker / inconsistent, but always fast enough.
-Recovery time isn't cycle dependent anymore.

Good job!

**Comment by johnnovak** [comment]
> @kcgen Yes, this fixed the issue I had (with a fresh default config of course)!
> 
> Obervations: -Screen still goes black when switching (expected) but always recovers quickly. -Recovery times are sometimes quicker / inconsistent, but always fast enough. -Recovery time isn't cycle dependent anymore.
> 
> Good job!

The third point is weird; this should never by cycles dependent AFAIK.
