### ISSUE TITLE
Have 'integer_scaling' default to "off"

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#3025]
I think it would be wise to have the new integer scaling be set to off by default, as it doesn't scale well on 1080p displays.

**Comment by Kappa971** [comment]
> I think it would be wise to have the new integer scaling be set to off by default, as it doesn't scale well on 1080p displays.

I think the default is "vertical" (auto) and the reason is the new CRT shaders (also default) which need vertical integer scaling. I already expressed my thoughts on this, but they attacked me. Anyway I think I've answered your question but I think what you ask can't be done.

**Comment by johnnovak** [comment]
> > I think it would be wise to have the new integer scaling be set to off by default, as it doesn't scale well on 1080p displays.

Read the output of `config -h integer_scaling` carefully 😄 

> I already expressed my thoughts on this, but they attacked me.

Nobody attacked you, mate. You were going on and on and on with your complaints about a feature you _admitted_ you were not interested in using at all in the first place. You were asked _repeatedly_ and nicely to stop, yet you kept going. What were doing was basically harassment. If you still don't see the difference and can't let it go, please look for another project to annoy with your presence.

**Comment by Kappa971** [comment]
> > > I think it would be wise to have the new integer scaling be set to off by default, as it doesn't scale well on 1080p displays.
> 
> Read the output of `config -h integer_scaling` carefully 😄
> 
> > I already expressed my thoughts on this, but they attacked me.
> 
> Nobody attacked you, mate. You were going on and on and on with your complaints about a feature you _admitted_ you were not interested in using at all in the first place. You were asked _repeatedly_ and nicely to stop, yet you kept going. What you were doing was basically harassment. If you still don't see the difference and can't let it go, please look for another project to annoy with your presence.

I replied to @OpenRift412, and it wasn't necessary for you to reply to what I wrote because the discussion was already closed on Discord and I don't understand why you are reopening the discussion, but I see that you must always reply last. Furthermore, this last answer shows again that you understood absolutely nothing about the discussion we had on Discord. I understand that you've spent days-months of your life on CRT shaders (and I've also never criticized your work), and it's a fantastic feature, but you took my "feedback" as a personal attack and it isn't ( and I don't know how to write it anymore!). The objective problem is that on 1080p monitors there will be limitations and @OpenRift412's comment demonstrates what I wrote. No subjective comments or attacks on you, just facts. Have you already made your decision? That's fine, you are one of the developers of the project and you have decision-making power, but maybe next time try to listen and understand the users' comments.
I hope it was clear now. Also avoid insulting someone who doesn't agree with you (especially if you don't know him), I've never done it with you.
You don't need to reply, the discussion is closed (I hope).

**Comment by johnnovak** [comment]
> but I see that you must always reply last. 

_wall of text of butthurt_

😐

**Comment by kcgen** [comment]
> I think it would be wise to have the new integer scaling be set to off

@OpenRift412 , the default `integer_scaling = vertical` will do the right thing based on the presence of and type of shader being used.  Some shaders need specific ratios to avoid moire patterns and other "grid-on-grid" effects. 

In 1080p full screen (alt+enter), with default settings, it should provide a similar look and feel versus a real PC CRT, when seated comfortably at a desk.

Here are my 1080p examples showing two EGA mode, VGA mode (double-scanned), and text mode, respectively:

![2023-10-17_16-05](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/15b914f7-13a9-4939-a73b-32dcdec1045b)

![2023-10-17_16-01](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/42614035-5c76-4340-805f-93cad7d1e1f2)

![2023-10-17_15-59](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/aad2633a-7090-4c39-994b-f1f42fbf88cd)

![2023-10-17_15-57](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/f639880b-4023-4b49-9b89-4684060e8774)

Because this provides a far more accurate representation of DOS software and games in their original state, as created by their authors and experienced by users on circa-80s and '90s hardware, the project has opted to make this the out-of-the-box default.

The prior inaccurate "big edge-to-edge pixels, all the time" look can be easily had with a single setting: `glshader = sharp` (or `glshader = none`) - and you will get an edge-to-edge image.

**Comment by johnnovak** [comment]
Nice examples & nicely explained @kcgen 👍🏻

**Comment by kcgen** [comment]
help-desk here: least I can  do to support this amazing feature :-)

**Comment by Kappa971** [comment]
Please remove this comment block and allow the person who created this problem to reply (if he wants). It doesn't make sense, we are all adults and this kind of thing is really stupid. Thank you
