### ISSUE TITLE
Crash at startup with `crt-auto-machine` shader

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#3059]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

GIT main - f861d58f894ed3862c8b4524ef4b8d6696583d14

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

With `crt-auto-machine` emulator crashes with exception very early during the startup.

### Steps to reproduce the behaviour.

1. In the configuration file set `glshader = crt-auto-machine`
2. Start DOSBox

### Your configuration

```ini
[sdl]
fullscreen          = false
fullresolution      = desktop
windowresolution    = 1067x800
viewport_resolution = fit
host_rate           = auto
vsync               = auto
vsync_skip          = 7000
presentation_mode   = vfr
output              = opengl
texture_renderer    = auto

[render]
aspect             = true
integer_scaling    = off
glshader           = crt-auto-machine
```

### Provide a Log

```text
2023-10-27 00:14:18.248 | DISPLAY: Initialised 1067x800 windowed mode using bilinear scaling on display-0
2023-10-27 00:14:18.314 | OPENGL: Vendor: Intel
2023-10-27 00:14:18.314 | OPENGL: Version: 4.6 (Compatibility Profile) Mesa 23.1.8
2023-10-27 00:14:18.314 | OPENGL: GLSL version: 4.60
2023-10-27 00:14:18.314 | OPENGL: Pixel buffer object available
2023-10-27 00:14:18.314 | OPENGL: NPOT textures supported
2023-10-27 00:14:18.314 | RENDER: Using adaptive CRT shader based on the configured graphics adapter
2023-10-27 00:14:18.314 | VGA: Pixel-doubling enabled
2023-10-27 00:14:18.330 | VIDEO: Using the DOS video mode's frame rate
2023-10-27 00:14:18.338 | MEMORY: Using 7936 DOS memory pages (31 MB) at address: 0x7f99340fb010
2023-10-27 00:14:18.338 | RENDER: Auto-switched to shader 'interpolation/sharp'
2023-10-27 00:14:18.338 | VGA: Forcing no pixel-doubling
2023-10-27 00:14:18.338 | VGA: Unhandled video mode 00h

Loguru caught a signal: SIGFPE
Stack trace:
9       0x56354a63c761 _start + 33
8       0x7f99c1573ac5 __libc_start_main + 133
7       0x7f99c1573a0a /lib64/libc.so.6(+0x23a0a) [0x7f99c1573a0a]
6       0x56354a8414d3 sdl_main(int, char**) + 7635
5       0x56354a64da36 Config::Init() const + 70
4       0x56354a64d8bb Section::ExecuteInit(bool) + 363
3       0x56354a801318 RENDER_Init(Section*) + 808
2       0x56354a90f5b9 VGA_SetupDrawing(unsigned int) + 57
1       0x56354a90d36f setup_drawing() + 2735
0       0x7f99c15889c0 /lib64/libc.so.6(+0x389c0) [0x7f99c15889c0]
2023-10-27 00:14:18.338 | Signal: SIGFPE
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Yeah, the init order is different per platform... It really is a big piece of shit...

I had to put in some workarounds for similar crashes on Windows and macOS (different per platform). The short-term workaround is to exit from some functions early when the graphics subsystem is not fully inited yet. E.g. return early from some function when the width and height of the rendered image is 0, etc. You'll need to play around with it, or wait until I'm back.

The good long-term solution is 100% deterministic init order across all platforms. But that cannot happen before the SDL rewrite; my guess is because SDL events are not normalised across platforms, we need to ensure such normalisation. Currently, slightly different UI events trigger the init mechanism at startup in slightly different ways--we need to make this platform agnostic.

Paging @kcgen and @GranMinigun to raise awareness on the importance of the issue again. I've been bitching about this, and I guess thst won't stop until we have a playform-agnostic init and teardown order 😄
