### ISSUE TITLE
Blood forgets to aspect-correct in 640x400 after Cutscene plays

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#3097]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.81.0-alpha-1907

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There's this issue I've encountered in Blood where when you set the resolution to 640x400 and start an episode that starts with a cutscene, and then when it gets to the game, aspect correction stops working and looks like this:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/29780788/bdcc4d59-8970-4e1c-b7e8-533ee3d76ec8)

Based on the log, it seems like it's trying to render a 640x400 frame to 640x480 resolution without any scaling for some reason. Don't entirely know if this at the fault of the game or DOSBox.

I think I've seen a similar phenomenon in GTA and some other games as well, but don't recall how to reproduce those.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Blood (make sure the CD is mounted so the cutscenes will play)
2. Go to the options, then video mode. Set resolution to 640x400.
3. Select New Game and start the first episode on any difficulty.
4. The cutscene will play fine, no display issues.
5. Once the actual game begins, the game will look similar to how it does above.

### Your configuration

```ini
https://gist.github.com/OpenRift412/26caa6852f92e4bc379e3daf036d0113
```

### Provide a Log

```text
https://gist.github.com/OpenRift412/a48238afab4e3831ef359b3c53866c60
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Can you check does this happen with 0.80.1. Thanks.

**Comment by OpenRift412** [comment]
> Can you check does this happen with 0.80.1. Thanks.

Yes it does. I also tested it with 0.74, and it has a similar issue.

**Comment by johnnovak** [comment]
Everything points at a game bug @OpenRift412—I don't think there's anything we can do. Specifically:

Following your repro steps, I can reproduce the issue using the eXoDOS v5 version. The game opens the 101h 640x480 VESA mode after the cutscene according to the logs (instead of the configured 640x400 mode) and I'm getting visual glitches in the lower 80-pixel area of the screen (see first screenshot). This seems like a game bug to me.

```
DISPLAY: VESA 640x480 256-colour graphics mode 101h at 70.007 Hz VFR, scaled to 1920x1440 with 1:1 (1:1) pixel aspect ratio
```

If I then switch to some other resolution than 640x400 in the video options in-game, then back to 640x400, I can coerce the game to use the 100h 640x400 VESA mode correctly:

```
DISPLAY: VESA 640x400 256-colour graphics mode 100h at 69.755 Hz VFR, scaled to 2133x1600 with 1:1.2 (5:6) pixel aspect ratio
```

Everything works as it should then as shown on my second screenshot.

If I follow your repro steps but configure the game for 640x480, everything works as expected, zero issues. Same for 800x600 and 1024x768. So in practice that's good enough to play the game.

I also tried 640x350, same issue as with 640x400 and the results look even funkier (3rd screenshot). All in all, it seems to be a buggy game. Could also repro on real hardware on my S3 card to be 100% sure, but for the verdict this is not a bug.

## Buggy 640x400 res rendered in 640x480 mode

![blood-640x400-bug](https://github.com/dosbox-staging/dosbox-staging/assets/698770/92227ef8-fe87-485c-ba27-342f49418a07)

## Correct 640x400 res

![blood-640x400](https://github.com/dosbox-staging/dosbox-staging/assets/698770/d4b5a322-d023-4224-b735-f874f592a0a1)

## Buggy 640x350 res rendered in 640x480 mode

![blood-640x350-bug](https://github.com/dosbox-staging/dosbox-staging/assets/698770/54cd5b10-bde1-4275-b46e-f627561156e7)

**Comment by MasterO2** [comment]
Now added to Game Issues section of the wiki:

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#blood

**Comment by Grounded0** [comment]
Latest release of Blood is version 1.21 that was only released as the One Unit Whole Blood special edition. Might as well check was it fixed there since few people are aware of this special edition.

**Comment by OpenRift412** [comment]
> Latest release of Blood is version 1.21 that was only released as One Unit Whole Blood special edition in 1998. Might as well check was it fixed there since few people are aware of this release.

This is false, One Unit Whole Blood is included in the GOG distribution of Blood: Fresh Supply, so it's a lot more common than you think. I was testing the game with v1.21, as you can see in my screenshot.

**Comment by Grounded0** [comment]
Yeah i don't purchase anything from GOG due to their abuse of the original DOSBox team but at least we know this bug exists with latest version 1.21 now.

**Comment by johnnovak** [comment]
Ah, so 1.21 has a different HUD, indeed. Missed that during my testing, but apparently it doesn't change much. Probably eXo v6 has the 1.21 version.

Might retest on hardware, but square pixel VESA modes are not buggy, so just use those.

**Comment by OpenRift412** [comment]
> Ah, so 1.21 has a different HUD, indeed. Missed that during my testing, but apparently it doesn't change much. Probably eXo v6 has the 1.21 version.
> 
> Might retest on hardware, but square pixel VESA modes are not buggy, so just use those.

It doesn't have a different HUD, you can change the screen size/HUD with the - and = keys.

**Comment by johnnovak** [comment]
> > Ah, so 1.21 has a different HUD, indeed. Missed that during my testing, but apparently it doesn't change much. Probably eXo v6 has the 1.21 version.
> > Might retest on hardware, but square pixel VESA modes are not buggy, so just use those.
> 
> It doesn't have a different HUD, you can change the screen size/HUD with the - and = keys.

Indeed. Clearly, I'm not an FPS gamer 😄 Turns out I'm using the 1.11 version, so we can concluce both 1.11 and 1.21 (and likely all versions) are affected.

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/7d903078-c0bc-484b-a549-d8ec0ae47e69">

**Comment by OpenRift412** [comment]
> > > Ah, so 1.21 has a different HUD, indeed. Missed that during my testing, but apparently it doesn't change much. Probably eXo v6 has the 1.21 version.
> > > Might retest on hardware, but square pixel VESA modes are not buggy, so just use those.
> > 
> > 
> > It doesn't have a different HUD, you can change the screen size/HUD with the - and = keys.
> 
> Indeed. Clearly, I'm not an FPS gamer 😄 Turns out I'm using the 1.11 version, so we can concluce both 1.11 and 1.21 (and likely all versions) are affected.
> 
> If you're bored @OpenRift412 , you can test in 86box / PCem too.
> 
> <img alt="image" width="1215" src="https://user-images.githubusercontent.com/698770/280868423-7d903078-c0bc-484b-a549-d8ec0ae47e69.png">

I actually just did that as well (had to reboot Win95 in DOS mode for cutscenes to not crash the game), and turns out it's the same phenomenon. My bad.

**Comment by johnnovak** [comment]
Thanks for confirming @OpenRift412, that's enough evidence to conclude the VESA mode handling of Blood is somewhat buggy. I don't think it's even necessary for me to test this on hardware.

**Comment by kcgen** [comment]
Folks on vogons discussed this bug in Blood's resolution handling ~5 years ago and ripsaw8080 shares some insightful comments: https://www.vogons.org/viewtopic.php?t=63441
