### ISSUE TITLE
3DFX Voodoo emulation improvements

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#3115]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

Hi, I would like to list here some possible improvements for 3DFX Voodoo emulation in DOSBox Staging (for future releases):
1. Optimized emulation for better speed (perhaps using GPU).
2. Support Truecolor 32-bit to remove dithering (like NGlide for Windows games).
3. Image scaling, for example making a 3D game with 3DFX support render in 1080p (like NGlide for Windows games).
4. Widescreen Hack. This idea came to me while playing with a PS1 emulator. It's still pretty unstable there (for example Silent Hill crashes in some specific places) and I have no idea if something like this could be implemented in DOSBox as well. I consider it a niche feature and certainly less important than the others.

If I have any other ideas, I'll add it.
As already said these are just ideas, if a developer comes out and wants to implement them in the next few years, it will be a great thing. Thanks

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Torinde** [comment]
- Extended 3DFX support. Depending on the DOSBox resolution up to 8k. https://github.com/MartyShepard/DOSBox-Optionals
- Voodoo 2 SLI, so that 1024x768 gets supported
- Voodoo 3/4/5 (mostly relevant for Win9x)
- lack of CLUT emulation so none of that fun gamma stuff works - from https://www.vogons.org/viewtopic.php?p=1097170#p1097170
- bad LOD calcs on MAME with some 3dfx-based arcade games emulated there like warfa - from https://www.vogons.org/viewtopic.php?p=1099811#p1099811
- mip-mapping, 2x2 filter - from sarah-walker-pcem/pcem/issues/205#issuecomment-1448373980

For "1. Optimized emulation for better speed (perhaps using GPU)." - do you mean something like https://github.com/kjliew/qemu-3dfx or http://dosbox-x.com/wiki/Guide%3ASetting-up-3dfx-Voodoo-in-DOSBox%E2%80%90X#_high_level_emulation or something else?

**Comment by Kappa971** [comment]
>     * Voodoo 2 SLI, so that 1024x768 gets supported
> 
>     * Voodoo 3/4/5 (mostly relevant for Win9x)

Based on information given to me by @kcgen and the other developers, DOSBox Staging currently emulates a Voodoo 1 (4 mb) and a Voodoo 1 on steroids (12 mb), and it doesn't accurately emulate the performance of a Voodoo 1, but it depends on speed of the Host CPU (and that's a good thing).
Probably all 3dfx DOS games support Voodoo 1 (or only support Voodoo 1 when installing from the CDROM). Some like Carmageddon have a second patch for Voodoo 2, but I don't know if there are new graphical effects.
If Voodoo 2 support was added in these games only because of the better performance of Voodoo 2 compared to Voodoo 1 and not because they use specific features of Voodoo 2, perhaps it is useless to add Voodoo 2 (and higher) emulation in DOSBox Staging (I think).

> For "1. Optimized emulation for better speed (perhaps using GPU)." - do you mean something like https://github.com/kjliew/qemu-3dfx or http://dosbox-x.com/wiki/Guide%3ASetting-up-3dfx-Voodoo-in-DOSBox%E2%80%90X#_high_level_emulation or something else?

Yes, something like that or whatever would improve performance.
I tried DOSBox-X SDL1 32 bit with Nglide but the performance wasn't good, someone else should try it too to see if I did something wrong (I don't notice any performance differences between the I7 860 I had years ago and the AMD Ryzen I have now, which is weird).

**Comment by Grounded0** [comment]
Carmageddon works perfectly with Voodoo. Can be disregarded.

**Comment by johnnovak** [comment]
There's nothing confusing about it @Torinde. There is no OpenGL passthrough, no Glide, nothing like that. The Voodo is implemented "in software", just the the GUS is, and the MT-32, the OPL, and so on.

**Comment by johnnovak** [comment]
> OK, then [this card](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-43001696) should be moved to 'Rejected'?

I've deleted it, we don't need it.

**Comment by Grounded0** [comment]
Relatively easy way to improve performance is to allow to run Voodoo emulation with multiple worker threads like DOSBox Pure does. Mostly helpful for people running Win32 games in unofficial capacity but that basically increases speed in linear fashion with each additional worker thread.

**Comment by Grounded0** [comment]
We're not going to do any of that Glide wrapper stuff since its Windows only. DOSBox Pure multiple worker threads model is the best way to squeeze more performance out in a multi-platform friendly way.

**Comment by interloper98** [comment]
That's good data with actual FPS boosts across a bunch of games. Thanks for passing that on, @Torinde.

We do have the `"voodoo_multithreading"` setting, currently it's boolean.

Are we beholden to keep using 3 threads? (Maybe for the pi?)

We could make `= yes` be a bit smarter and use something like `clamp(num-host-real-cores - 1, 1, 7)`

I think SDL gives us some cross-platform CPU APIs to get this value.

**Comment by johnnovak** [comment]
> We could make `= yes` be a bit smarter and use something like `clamp(num-host-real-cores - 1, 1, 7)`

That's the perfect solution combined with `SDL_GetCPUCount`, go for it @interloper98 🚀 
I'd say we should get rid of the `voodoo_multithreading` setting altogether as I see no reason for not enabling mulithreading when available. The less levers and more intelligent auto-config behaviour, the better! 👍🏻 

Great find @Torinde, btw 🎖️

**Comment by FeralChild64** [comment]
How about using this algorithm as a default (auto setting), but allowing the user to specify the thread count manually (preferably changeable at runtime)? Rationale:

- different games behave differently
- we only have test results from the AMD Threadripper; these CPUs are strange little beasts, with multiple NUMA domains (depending on the model, some of the domains can consist of CPU cores only, without the RAM), and they are the most effective if all the threads processing the given set of data are executed on cores belonging to the domain which keeps the data; once some threads are executed inside other domain#, the performance stop scaling that well
- the current most common Intel Core CPUs (and ARM CPUs used in certain Raspberry Pi-like computers) are strange little beasts with Performance and Efficient CPU cores, with the Performance cores being roughly twice as fast; the Core i5 has 6 Performance cores - I can fully imagine a performance loss caused by the Performance cores needing to wait for the last two threads which landed on one of the Efficient cores
- the AMD X3Ds CPUs, popular among gamers, are kind-of-hybrid too, as some cores have much more cache at the expense of their max frequency
- thanks to all of above, writing the efficient scheduler is, well, like a rocket science; different OSes behave differently, different Linux distros behave differently (depending what they are optimized for), Linux can run a GameMode server which does various tweaks for the best gaming performance, Windows can run AMD drivers altering the scheduler behavior for maximizing Threadripper performance (I don’t know if they are still in use; long tome ago they were a must for the 4-chiplet Threadrippers), etc.

Let’s face it: we have no resources to determine the best possible thread count selection algorithm, IMHO we should provide a sane default (like the one proposed above), but allow the power users to determine the value which works the best for them.

**Comment by johnnovak** [comment]
@FeralChild64 IMO, you're overthinking it; it seems the _overall_ best performance is at thread count of 7. Surely performance may vary per level, or even per room in a game, or based on the number of enemies on the screen, etc. As long as long we're in the best performance bracket within +/- 10-15%, that's good enough (I doubt many people care about playing a game at 50 vs 55 FPS...)

So dunno, I don't think CPU or OS variations matter much; overall parallelism of 7 seems best. Or 6. Or 8. Something like that, it's not an exact science 😏 

I'm happy to nuke the setting, but I also won't spend time arguing if you want to keep it, setting it to `auto` by default and allowing explicit numbers from 1 to 16 or something. I'm just not convinced it's worth exposing this for marginal tweakability, and we have enough settings already.

**Comment by FeralChild64** [comment]
It was just my opinion; I won’t be implementing the change, and I definitely won’t quarrel about it :)

**Comment by interloper98** [comment]
Intel Atom 15305 (Formerly known as RicketyTrail)
 - Power intense (P) cores: 0 (180W TDP/core, we're saving you power, bro!)
 - Energy efficient (E) cores: 1 (65W TDP/core)
 - Phony (Y) cores: 15 (0W TDP/core, for maximum power savings!)

My new 16 core CPU sucks, guys. 

I'm going to be trying to get the number of physical cores first (and ignore the PhonY cores and threads), and then only fall back to C++'s concurrency numbers.

**Comment by Grounded0** [comment]
Still think it should be just number of threads with a smart default and some hints that hey seven seems to extract most FPS.

We've been severely punished on this project for trying to be clever instead of offering a decent out-of-the-box settings with toggles.

**Comment by johnnovak** [comment]
> I agree @FeralChild64; the concept of a cpu core is starting to lose all meaning ...

Dunno man. Multithreading helps, and we just want generic good enough solutions, not maxinalist solutions with 5x the effort.

I'm a sweet spot, bang for the buck guy. Minimum change for maximum profit, and move on 😆

**Comment by johnnovak** [comment]
> Auto can use SDL to figure out a good number and still leave us an option to dial it in manually so I don't have battery anxiety when I'm returning from the city on a train. Maybe I should upgrade to ARM64 finally... 😁

Note that if you don't play a Voodoo game, the CPU cost is zero.

**Comment by Grounded0** [comment]
> Note that if you don't play a Voodoo game, the CPU cost is zero.

EF 2000 happens to be one of my top 5 games on DOS so that's not a luxury I have.

**Comment by Torinde** [comment]
The following issue answers my confusion above https://github.com/dosbox-staging/dosbox-staging/issues/3115#issuecomment-2351439884, https://github.com/dosbox-staging/dosbox-staging/issues/3115#issuecomment-2353878959
- https://github.com/dosbox-staging/dosbox-staging/issues/4532#issuecomment-3368584758
