### ISSUE TITLE
shell_history.txt non-Latin characters incorrectly recorded

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#3235]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging-windows-msys2-x86_64-v0.81.0-alpha-2226-g2dff7

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Testing latest build for the issues I mentioned at https://github.com/dosbox-staging/dosbox-staging/issues/3128#issuecomment-1825396175

shell_history.txt : Cyrillic characters are not properly converted to Unicode/host code page

![image](https://github.com/dosbox-staging/dosbox-staging/assets/97228894/1d0d194e-7edc-421b-a4a1-45b96723764b)
![image](https://github.com/dosbox-staging/dosbox-staging/assets/97228894/bcbd2996-0447-4e85-a475-d63422c312a2)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. portable mode with empty dosbox-staging.conf
2. type commands from screenshot

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I wrote this history feature.  It is not doing any kind of conversion currently.  For the most part, it simply dumps to a text file on exit and reads it on open.  Does pressing the up arrow correctly retrieve a command using non-Latin characters?  I would like to test two cases:

1. Enter a command with non-Latin characters.
2. Press up arrow and see if the command gets retrieved from the internal data structure correctly.
3. Close Dosbox and re-open it.
4. Test again with now that the history has been written to the text file and read back in again.

If both of the above cases work, presumably you could read the text file by simply setting your text editor to a DOS codepage (which one exactly, I don't know).  Maybe as an enhancement, we could do conversion back and forth to UTF-8.

I'm not sure how to test this on my system.  I tried setting my keyboard layout to Russian in KDE.  This made my keyboard input Cyrillic characters into Firefox, VS Code, and my terminal but Dosbox still input Latin characters.

**Comment by johnnovak** [comment]
> . another shell history improvement is not to record the same command twice after each other, e.g. if new entry is the same as previous - don't add it - not sure how common this scenario is, usually people enter different commands, but while testing I was entering the same...

One ticket, one issue. You know what to do 😏

**Comment by weirddan455** [comment]
Thank you for the additional information @Torinde 

I was able to type in some Cyrillic characters with `keyb bg` set.  The text file appears to be using the same encoding that DOS uses (codepage 3021 in this case).  To confirm, I opened the text file in a hex editor and compared to the table in this wiki article which looked to match up:  https://en.wikipedia.org/wiki/MIK_(character_set)

In my mind, the main functionality of this history file is to enable the DOS command line to retrieve previously entered commands via the up arrow.  It need not be readable by common text editors in order to achieve this.

UTF-8 conversion could be nice but would require a conversion routine for every codepage that Staging supports (maybe adding more complexity than is worth-while since the main purpose is functional as is).

I believe @FeralChild64 has done some work with localization and Unicode.  Do you have any thoughts?

**Comment by FeralChild64** [comment]
> would require a conversion routine for every codepage that Staging supports

I have already written such routines, they are present in `string_utils.h`:

`void dos_to_utf8(const std::string& in_str, std::string& out_str);`
`bool utf8_to_dos(const std::string& in_str, std::string& out_str, const UnicodeFallback fallback);`

For this use case the `UnicodeFallback::Simple` should be used - it drops the accents and does some other replacements if there is no matching character in the currently used DOS code page.

**Comment by FeralChild64** [comment]
UTF8 internals might be useful for languages where multiple incompatible character encoding were popular - yet, I’m not sure if national characters were common in commands, probably not. Yet, the change shouldn’t be complicated.
