### ISSUE TITLE
Coordination with realnc's libretro core

### ISSUE THREAD

**Issue by i30817** [dosbox-staging/dosbox-staging#324]
This project: https://github.com/realnc/dosbox-core

seems to have a minimal amount of 'drift' necessary to support a libretro core build, with features such as 'cd mounts appearing on libretro GUI cd switcher', 'conf settings appearing in core options' and 'make libretro load conf files for dosbox'. It might be easier to copy over those enhancements to a build target + some ifdefs here than that core copying over changes from here (such as for example, the proposed 'conf and cue file folder separator platform independence' RFE).

I'd suggest looking at the open bug reports and the closed ones on that repo to have some idea of the libretro specific changes, although that repo is itself a fork of a older project that might have more, so a more structured diff with upstream might be necessary to get a complete picture of what changed.

You could even ask for collaboration with them by asking to be their upstream instead of that older core based on upstream and point out advantages such as implemented RFE that make things better (such as that conf/cue platform independence RFE, hint hint).

**Comment by dreamer** [comment]
Well, let's chat to the developer :) (I believe we exchanged few words in /r/emulation already).

@realnc - I think we have similar goals in mind, and judging by Git DAG in your repo, I guess we have large overlaps in the workflow as well.

I think as a proof of concept, I could somewhat easily "transplant" history of your master branch to our repo (tell me if you're interested) - perhaps it would be easier to maintain retrocore as a compile-time option in dosbox-staging master instead of a separate project? Or maybe some other option?

That would mean no duplicated effort on syncing with upstream (SVN), and more eyes looking at the same code. But we established certain workflow in here already (no regressions on warnings on static analysis, formatting, obligatory code review process - these kinds of things - you can read our WIP
[CONTRIBUTING.md](https://github.com/dosbox-staging/dosbox-staging/blob/po/contributing-2/CONTRIBUTING.md) - and also send early feedback about it in #265).

There are some significant (but not impossible) differences between the projects:
- FluidSynth - we don't have it yet (but it's planned for 0.76.0) - I explained details in #262 
- MT-32 - we don't have it yet (scheduled for later) - I explained details in #257 
- C++17 - we will most likely switch from C++11 to 14 in 0.76.0 (we had one small problem with C++14, but it's resolved already); C++17 ATM is not acceptable to us (the reason being: last time I tried to enable it, there were ABI compatibility problems with Steam runtime, and this is pretty important target for us - but I haven't checked if this is still an issue for quite some time)
- BASSMIDI - I know nothing about this library (it's closed, optional dependency?)
- Native MIDI - we want this! (this is on my feature list to port away from Boxtron into dosbox-staging)
- NukedOPL - we have it in already (probably with tiny differences though)

For us, close cooperation means, that we are sharing the repo; @kcgen and @ant-222 have push access here, but even with push access - all commits to master go through review via PR (except trivial changes and SVN merge commits).

@realnc what do you think?

**Comment by realnc** [comment]
Rebasing the core to use dosbox-staging as its new upstream is a risky thing right now. It looks like it will involve quite a bit of work, and if dosbox-staging as a project doesn't actually take off and dies off, I would then need to switch back and undo all that work :-/

As for merging the core itself directly into dosbox-staging, that would be even more risky right now, as it's even harder to go back afterwards if the project dies. But merging can't happen anyway right now until C++17 (and C++20 soon-ish) is allowed. Platforms that don't have support for modern development tools should either get with the times or be ignored. If the code doesn't compile on Windows XP, so be it.

So what I'm trying to say is that it's too soon to switch to dosbox-staging right now. So wait and see how things pan out because I'm too afraid the project might not take off :-P

A few notes about the various additions that are in the core:

> FluidSynth - we don't have it yet (but it's planned for 0.76.0) - I explained details in #262
> MT-32 - we don't have it yet (scheduled for later) - I explained details in #257

This is newly written fsynth code that requires fsynth 2.1, which comes with the core as a submodule and build statically with cmake. Munt is also a submodule built with cmake. Note that the core itself does not use cmake. It just calls cmake to build the deps.

This is true for many of the other deps as well.  FLAC, libinstpatch, ogg, opus, libsndfile, SDL, SDL_net and vorbis are all bundled as submodules using their respective upstream git repos and built statically if requested. Otherwise, the system-provided versions are used, be it something installed on Linux with apt-get or whatever, or on macOS with homebrew/macports/fink or with pacman in msys2 in Windows.

This might be a good option for dosbox-staging as well if you don't want to go the conan/vcpkg/whatever route. If you're using autoconf, that would mean having options like `--with-system-flac`, `--with-system-sdl`, etc.

> C++17 ATM is not acceptable to us (the reason being: last time I tried to enable it, there were ABI compatibility problems with Steam runtime

I used modern C++ (at the time it was C++14) for a game I was hired to publish on Steam and the way I did that was to simply disable the steam runtime and ship my own libraries. All it took was launching the game executable through a script that unsets `LD_LIBRARY_PATH`.

Nowadays I would have packaged the Steam build as an AppImage. I just didn't know about it back then. AppImage is what I now use for my projects. You might want to use it as well, as it would allow people to just download and run dosbox-staging for Linux the same way they do for Windows or macOS without having to worry about missing libraries. Flatpak is nice and all, but nothing beats the "just download and run it" convenience IMO.

> BASSMIDI - I know nothing about this library (it's closed, optional dependency?)

It's a proprietary MIDI synth. The reason I added this is due to a large number of soundfonts having been designed with BASSMIDI in mind and as a result they sound wrong with fsynth. Whenever you use a soundfont with fsynth that has distortion/clipping issues with some instruments while others are barely audible, or some of them just sound completely broken, you use BASSMIDI instead and it sounds completely fine. That usually means the soundfont's author was using BASSMIDI.

On Windows, people simply use some kind of BASSMIDI driver. There's no such thing on Linux (at least not without resorting to Wine) and macOS, so that's why this was added directly into dosbox.

> Native MIDI - we want this

You already have it :-) It just means that dosbox-core supports MIDI output through dosbox. The older core didn't support that and instead relied on the frontend for MIDI output. RetroArch is the only frontend that has that, and it's a bit buggy as well. So allowing normal MIDI output by dosbox was added along with a MIDI port selection mechanism in the core options.

The MIDI port selection mechanism is something you might want to look into for dosbox-staging. Vanilla dosbox on Linux only allows specifying a port number. This is annoying, as these can change. If you use external Munt for example (rather than the built-in Munt) and it uses ALSA port 128:0, next time you start Munt it might have changed ports (because I started SoundCanvas VA meanwhile which grabbed that port.) So instead of using the port number (like `128:0`), dosbox-core uses the port name (`Munt MT-32:Standard` in this case) instead, which does not change. For dosbox-staging this would mean support for:

```
midiconfig = Munt MT-32:Standard
```

**Comment by kcgen** [comment]
@realnc , how does libsndfile tie in? (Is this related to integrating with libretro, or do you use it extend dosbox's audio functionality?)

I think libretro is now the overwhelming and dominant emulation back-end that's well beyond critical mass.. so your fork is definitely taking dosbox in the right direction where things are haded.  

The progress of SBC performance and NAND densities are allowing more and more generations of consoles (and PC platforms) to be properly emulated and stored on a single low-cost device.  In the next couple years, multi-TB SD cards will allow holding the entirety of pre-2000s gaming, and the idea of running "the entire Exo-pack" will be just a quick download away.

**Comment by realnc** [comment]
>  how does libsndfile tie in? (Is this related to integrating with libretro, or do you use it to extend dosbox's audio functionality?)

It's a dependency of libinstpatch and fluidsynth.

> I think libretro is now the overwhelming and dominant emulation back-end that's well beyond critical mass.. so your fork is definitely taking dosbox where things are headed.

It's more of a port of dosbox to libretro rather than a fork. Changes to the dosbox code base are kept at a minimum.

**Comment by dreamer** [comment]
> Rebasing the core to use dosbox-staging as its new upstream is a risky thing right now. (…)

Sure, I understand :) Let's check-up once in a while to see how things change.

It seems like keeping the retrocore in a separate repo (due to the approach to dependencies) is the most pragmatic choice anyways :)

> A few notes about the various additions that are in the core:
> 
> > FluidSynth - we don't have it yet (but it's planned for 0.76.0) - I explained details in #262
> > MT-32 - we don't have it yet (scheduled for later) - I explained details in #257
> 
> This is newly written fsynth code that requires fsynth 2.1, which comes with the core as a submodule and build statically with cmake.

We'll probably port patch for FluidSynth 2.x from your repo, but we won't be using git submodule (AFAIK Fluid2 is already in all repositories). We use vendor-recommended repos on all OSes (except macOS, where we use brew), and it serves us very well (we already use vcpkg on Windows). We do it this way to make it easier for distro packagers to include dosbox-staging in the repos.

> > C++17 ATM is not acceptable to us (…)
> 
> I used modern C++ (at the time it was C++14) for a game I was hired to publish on Steam and the way I did that was to simply disable the steam runtime and ship my own libraries. 

I don't have any fuzzy feelings about older C++ standards (the sooner I can responsibly move to newer one the better) - we will switch to C++14 ASAP (with an accent on P, not on S). We avoid C++17 for pragmatic reasons - but we'll likely going to use it once Ubuntu 16.04 LTS will reach EOL.
Our tarball releases work inside Steam Runtime just fine, we have no reason to duplicate testing effort and confuse users.

> Nowadays I would have packaged the Steam build as an AppImage. (…)

People already can download and run dosbox staging using tarball, because we were extremely careful about ABI compatibility - it works on any modern distro, because we *avoided* C++17 - but our primary target is being included in the distro repositories. I know AppImage, I don't want to use it. Users are free to package dosbox-staging in AppImage if they like, I don't care (if someone cares, I am open for PRs of course).

> > Native MIDI - we want this
> 
> You already have it :-) 

Oh, we know that we have it, but I am interested in improvements - including exactly the one you mentioned :)

> ```
> midiconfig = Munt MT-32:Standard
> ```

I already fixed MIDI for dosbox once in Boxtron, now I am looking into porting those fixes to dosbox-staging, so the problems will be resolved for a wider audience. There are other MIDI-related bugs in dosbox, but if you focused on configuration only, then I guess we'll need to fix them ourselves :)

**Comment by johnnovak** [comment]
> @realnc and Staging team, what do you think?

Well, I can't stand RetroArch and will personally never do anything with it, neither as a user nor as a developer. There are both technical and philosophical reasons for that, but yeah, won't touch it with a ten feet pole 😎 

The biggest technical reason: I think RA is a shit choice for home computer emulation in general, and I'm firmly against "consolifying" home computer emulation.

Having said that, I have nothing against authors who develop DOSBox based "cores" RA using parts of our code. Just like I don't have anything against any other project that forks our code or builds something else upon it.

So all I can say, I wish the devs good luck and have fun 😎 If you do some original fix, please ping us so we can port it back. But we want to do our own thing and what suits us, that's the gist of it.

**Comment by Grounded0** [comment]
It would be nice to have DOSBox Staging RetroArch core for sure. It would also make dosbox-core more competitive against dosbox-pure in RetroArch market.

**Comment by interloper98** [comment]
![8u2ref](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/5abb5404-b258-4aad-9737-6773ea8fd4da)

**Comment by johnnovak** [comment]
> Rebasing the core to use dosbox-staging as its new upstream is a risky thing right now. It looks like it will involve quite a bit of work, and if dosbox-staging as a project doesn't actually take off and dies off, I would then need to switch back and undo all that work :-/

> So what I'm trying to say is that it's too soon to switch to dosbox-staging right now. So wait and see how things pan out because I'm too afraid the project might not take off :-P

Yeah, so I don't think it can take off much more than this 😆

**Comment by johnnovak** [comment]
And to reiterate an earlier comment, any RA fork/core/port/whatever must be a separate project.

> It seems like keeping the retrocore in a separate repo (due to the approach to dependencies) is the most pragmatic choice anyways :)

**Comment by johnnovak** [comment]
> Clear. I opened discussion item on what the trigger need/want was:
> 
>     * [Android APK build #3773](https://github.com/dosbox-staging/dosbox-staging/discussions/3773)

Out of score, won't do, we don't have time & energy, massive complication, etc.

Fork project, start a phone/tablet/etc. version if desired & good luck 😄

**Comment by Grounded0** [comment]
We definitely don't view any Android or Libretro core forks negatively since we're not doing them.
