### ISSUE TITLE
Automated dependences and optimized compile on Retropie

### ISSUE THREAD

**Issue by jlopezvil** [dosbox-staging/dosbox-staging#330]
@kcgen commented this in another issue for correctly depends and later optimized compiling for dos-staggin on retropie. 
https://github.com/dosbox-staging/dosbox-staging/issues/326#issuecomment-619643011
"Can you try this in your dosbox-staging source directory:
sudo apt-get install -y $(./scripts/list-build-dependencies.sh -c gcc -m apt)
That should install all of the build dependencies. Then try an optimized build:
./scripts/build.sh -c gcc -t release -m lto"

Could be implemented in retropie or in biuld command for be called in the automated compiled on retropie?

**Comment by kcgen** [comment]
Certainty we're trying to simplify and minimize the steps needed to build and configure dosbox (you can now run `dosbox --editconf` to jump straight into your config file instead of hunting around like we did a couple days ago; super handy feature added yesterday by @dreamer!). 

When it comes to using those commands in Retropie's config menu, @nemo93 is currently assessing dosbox-staging on RetroPie, and is discussing it with the project's maintainers.  

If and when they want to use dosbox-staging, they might be interested in using our scripts to build it (or maybe not).  

One of the benefits is that we (here in dosbox-staging), can keep improving the build FLAGS, which retropie users would benefit from.  The con though is that the retropie project would give up their own control over those settings.  We'll see what happens, and is certainly a good suggestion!

**Comment by nemo93** [comment]
Staging is now part of Retropie. Thanks to everyone involved.

@jlopezvil @kcgen perhaps this ticket can be closed off?

**Comment by kcgen** [comment]
Glad to see everyone enjoying DOS games on low cost SBC hardware!

Thank you @nemo93 for over a year of your testing, documenting, and working w/ the RetroPie community.

We can certainly close this, I believe.
