### ISSUE TITLE
DOSBox-staging 0.81 RC1 freeze when text is selected in the log window

### ISSUE THREAD

**Issue by MonkeyPilot** [dosbox-staging/dosbox-staging#3311]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10 x64 (build 1909)

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The main window freezes when switching to full-screen mode if the text in the log window is selected

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Lunch DOSBox-staging
2. It will switch to the log output window and select any text (just select, do not copy to the clipboard). You can simply point the mouse at any place in this window and one character will be automatically highlighted.
3. Switch back to the main window and try to enter full-screen mode using the `ALT+ENTER` keys.

### Your configuration

```ini
Default config
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
This is expected.

Some console implementations (like Window's console) "freeze" their window content when you've selected text.

This prevents further content from scrolling the console upward, which would otherwise disturb your selection.  

The additional content that's being blocked is DOSBox Staging's LOG message  when it switches to fullscreen. So in your case - simply press enter in your console windows to copy or clear your selection, and "free the log jam"!

Another option is to use a different console implementation that lets new text keep flowing in, even when you've selected text (there are 3rd party consoles.. check them out).

https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10

**Comment by johnnovak** [comment]
It's normal. It's the WindowsLife(C)(R)(tm), as approved by Bill Gates himself 😎🤘🏻

**Comment by MonkeyPilot** [comment]
@kcgen
Yes, indeed, you are right, if you go back to the log window and deselect, the main window unfreezes. Nevertheless, we must admit that this strange behavior is easily reproducible and inconvenient (many Windows users will definitely encounter this). It is enough just to accidentally, inadvertently, poke at any place in the log window and one character will be automatically highlighted, after which the attempt to switch to full-screen mode fails and it is no longer possible to return back to the log window, because the main window is already in full-screen mode in a frozen state and there is nothing left but to forcibly close the task.
Maybe there is some way to get around this incident? For example, to determine the selection in the log window and temporarily stop the output?
