### ISSUE TITLE
Requesting help configuring pcjr version of King's Quest on 0.81.0-RC1

### ISSUE THREAD

**Issue by ErinWiebe** [dosbox-staging/dosbox-staging#3328]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-RC1

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

Hello,

I am configuring DOSBox Staging 0.81.0-RC1 on my ThinkPad X61 running Linux Mint Debian Edition with the goal of running early Sierra games, starting with King's Quest (pcjr version).

The X61 has a 2Ghz Core 2 Duo, 8GB RAM and has a 4:3 display with a native 1024x768 resolution.

DOSBox Staging is installed to ~/dosbox
The game directory is ~/dosbox/dosgames/kq1

I am using the **default** ~/.config/dosbox/dosbox-staging.conf file along with a separate ~/dosbox/dosgames/kq1/dosbox.conf file.

dosbox.conf

[sdl]
fullscreen=on
[dosbox]
machine=pcjr
[cpu]
cycles=fixed 300
[autoexec]
mount c ~/dosbox/dosgames/kq1
boot c:\disk.img

DOSBox is launched with $ dosbox --working-dir ~/dosbox/dosgames/kq1

When the above "fullscreen=on" line is removed, KQ1 successfully launches in a window, and the game runs well with no issues at what looks like stock PCjr speed. If I re-enable "fullscreen=on", the game launches full screen, but at perhaps 10% of the normal PCjr game speed and runs very choppy. The display also appears to be emulating scan lines too, which weren't present when running in windowed mode.

Is there a known dosbox.conf file for King's Quest PCjr version that would run the game normally at fullscreen?

Thank you.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by rderooy** [comment]
Your computer is rather dated, and has a very limited graphics chip (i965). Try to disable scanlines by setting:

```ini
[sdl]
glshader = sharp
```

**Comment by ErinWiebe** [comment]
Thanks for your reply. Yes, it is a dated laptop - I thought it would be a perfect platform for old Sierra games.

I added glshader = sharp as follows.
```
[sdl]
fullscreen = on
glshader = sharp
```
Doing this does improve the display rendering a little bit, and I can increase the rendering speed quite dramatically by increasing the number of fixed cycles well. The issue is, when fullscreen, the sound also glitches & stutters. So even with the display sped up, the sound remains slow & stutter-y.

**Comment by johnnovak** [comment]
> The display also appears to be emulating scan lines too, which weren't present when running in windowed mode.

That's the CRT emulation which is enabled by default in the RC. If it doesn't have sufficient resolution to perform CRT emulation, it reverts to the `sharp` shader. Your window is smaller than the full desktop, so that makes sense.

> Yes, it is a dated laptop - I thought it would be a perfect platform for old Sierra games.

Emulating old computers accurately, even released in the early 80s, might needs very powerful current-day computers. This might counterintuitive, but that's how emulation works.

We're not going for ultimate accuracy in all aspects of the emulation, but Staging still needs a relatively "modern" computer not older than say 10-12 years to run well. We make this clear in our mission statement on our [about page](https://dosbox-staging.github.io/about/).

    Focus on supporting up-to-date, current operating systems and modern hardware.

Lots of our users use Staging on the Raspberry Pi 4 with relatively modern and demanding VGA games (with performance tweaks, I have to add). So that is something I would consider the low-end specs that we support. Note that even an RPi 3 has 4 cores and a faster GPU than your old laptop.

Your laptop is 16 years old now. Unfortunately, there really isn't much other option for you than to use a better, more recent computer if you want to get the best out of Staging.

**Comment by kcgen** [comment]
> When the above "fullscreen=on" line is removed, KQ1 successfully launches in a window, and the game runs well with no issues at what looks like stock PCjr speed.

This is a good sign.

Can you post your console log output, specifically the `OPENGL: ...` lines?

It's possible that MESA is providing the OpenGL implementation, which is a software driver and performance can really degrade as the image size gets larger.

**Comment by johnnovak** [comment]
> > When the above "fullscreen=on" line is removed, KQ1 successfully launches in a window, and the game runs well with no issues at what looks like stock PCjr speed.
> 
> This is a good sign.
> 
> Can you post your console log output, specifically the `OPENGL: ...` lines?
> 
> It's possible that MESA is providing the OpenGL implementation, which is a software driver and performance can really degrade as the image size gets larger.

Yeah, try the `output = surface` mode in the `[sdl]` section.

**Comment by rderooy** [comment]
Also, if you are only interested in old Sierra games, you may want to try to run it via scummvm as an alternative. It may provide better performance for your use case.

**Comment by weirddan455** [comment]
>  It's possible that MESA is providing the OpenGL implementation, which is a software driver and performance can really degrade as the image size gets larger.

Mesa also provides hardware implementations.  `llvmpipe` is the usual software implementation (also provided by Mesa).

Pre Sandy Bridge Intel GPUs are quite weak even with proper hardware acceleration though.  Try the suggestions given above and see if it helps your performance.

**Comment by ErinWiebe** [comment]
> > When the above "fullscreen=on" line is removed, KQ1 successfully launches in a window, and the game runs well with no issues at what looks like stock PCjr speed.
> 
> This is a good sign.
> 
> Can you post your console log output, specifically the `OPENGL: ...` lines?
> 
> It's possible that MESA is providing the OpenGL implementation, which is a software driver and performance can really degrade as the image size gets larger.

Thank you all for your replies. I've attached the output from the console. 

[output.log](https://github.com/dosbox-staging/dosbox-staging/files/13941129/output.log)

**Comment by kcgen** [comment]
Thanks @ErinWiebe ,

Comments on the log snippets - 

```
2024-01-15 10:26:27.324 | OPENGL: Vendor: Intel
```

Great, you're using Intel's drivers.  This is as good as you can hope for, especially on older hardware.

```
2024-01-15 10:26:27.324 | OPENGL: Version: 2.1 Mesa 22.3.6
```

This is a relatively recent version of MESA, so that's good too.

Your T61 iGPU only supports shader language 1.2, but that's OK too - it's similar to macOS machines.

> SDL: Using standard SDI (auto) display refresh rate of 50 Hz`

Your T61 might be running in some kind of balanced performance mode where it reduces the screen refresh rate to save power.

Make sure your system is plugged, check your BIOS and Linux's power settings - make sure it can scale up to full speeds. The above LOG message should report 60 Hz on your system.

To help maximum gaming performance, install the `gamemode`, then run `gamemoderun /path/to/dosbox` to run the process with improved performance and latency.

Confirm the drivers are providing hardware acceleration:

```shell
apt-get install mesa-utils
glxinfo | grep "direct rendering"
glxinfo | grep -A17 "Extended renderer"
```

Look for `direct rendering: Yes` and `Accelerated: yes`.

Test your GPU's non-vsync'd OpenGL rendering speeds in windowed mode:
- Install `intel-gpu-tools` (if you can).
- Run `vblank_mode=1 glxgears`, it will report FPS every 5 seconds
- In another terminal, run `intel_gpu_top` to monitor your GPU.

Now try it fullscreen: 
- `vblank_mode=1 glxgears -fullscreen`
- and Alt+Tab to raise your `intel_gpu_top` terminal to see it in realtime

(Note: you can use `gamemoderun` in these tests, too to see if it can boost FPS).

My Skylake iGPU runs at > 9000 fps Windowed mode:

![2024-01-15_09-11](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/20e5ce4e-1337-41fc-b3c5-8bca0013a6ec)

But collapses to ~110 fps fullscreen in 4k:

![2024-01-15_09-13](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/10a86622-8aef-48bf-810f-07ff621fc5a8)


> CONFIG: Setting 'output = surface' is deprecated

(yup, `surface` was an option in 0.80.x, but it's gone in 0.81)

Try `output = texture` and `output = texturenb` (the latter might be a bit higher performance).

But even with this, SDL will still use OpenGL primitives to render the texture, so you could also try `texture_renderer = software`, which with then draw entirely to X11 using software calls instead of HW driver calls.

Finally, one option we recommend on the pi for fullscreen is:

```
fullresolution = original
```

This will try to run your display at the game's resolution instead of the hosts's maximum/native resoution, which reduces the load.

**Comment by ErinWiebe** [comment]
@kcgen Thank you so much for your help!

I confirmed, the X61 is running on AC and the BIOS is set for "Performance Mode".

I skipped applying "gamemode" to ~/dosbox for now but I may return to it. 

I installed `mesa-utils` and confirmed "direct rendering: Yes" and "Accelerated: yes" with `glxinfo`.

I installed `intel-gpu-tools` and ran `glxgears` and monitored output as you suggested using `intel_gpu_top` and `vblank`

Here are the results when running `glxgears` windowed.
![windowed](https://github.com/dosbox-staging/dosbox-staging/assets/156604736/ac43c961-e660-4c4d-acf1-90ef75808ab4)

And fullscreen.
![fullscreen](https://github.com/dosbox-staging/dosbox-staging/assets/156604736/7a7b5190-43a9-4d6d-83dd-302178f75633)

I then tried your suggestion of `output = texture`, and `output=texturenb` and these settings changed everything. Texturenb especially. They both work perfectly performance wise,  but the output is nice & sharp using texturenb.

I tried `fullresolution = original` too, but it crashed.

```
[sdl]
fullscreen = on
output = texturenb
#fullresolution = original
[dosbox]
machine = pcjr
[cpu]
cycles = fixed 300
[autoexec]
mount c ~/dosbox/dosgames/kq1
boot c:\disk.img
```

And the results of tweaking - the game runs perfectly fullscreen!

Using `output = texture`:
![kings_quest_pcjr_x61](https://github.com/dosbox-staging/dosbox-staging/assets/156604736/4aa3e527-0863-4f1e-b040-debd3aa94c70)

Using `output = texturenb` with `intel_gpu_top` running:
![kq1_fullscreen_intel_gpu_top](https://github.com/dosbox-staging/dosbox-staging/assets/156604736/a8a22068-f7a2-4e2b-b4a0-318227219da6)

**Comment by kcgen** [comment]
Glad you're up and running!
Linux save another old system :penguin: :smile:

**Comment by weirddan455** [comment]
Glad you were able to get it working!

>  I then tried your suggestion of output = texture, and output=texturenb and these settings changed everything. Texturenb especially. They both work perfectly performance wise, but the output is nice & sharp using texturenb.

Texture output is mostly there for compatibility with odd and dated hardware at this point.  Dosbox doesn't utilize the GPU too extensively.  Besides the CRT shaders (which you sadly miss out on using Texture output), the GPU is really just used for scaling and blitting the final output image and even that can be done entirely in software as @kcgen pointed out.

Texturenb is "non-billenear" which as you've noticed is a sharper method of scaling.

**Comment by ErinWiebe** [comment]
> Glad you're up and running! Linux save another old system 🐧 😄

A modern OS hosted on a 17 year old computer running a 40 year old game. :) 
Thanks again!

**Comment by johnnovak** [comment]
@ErinWiebe `texturenb` is sharper, but it scales the pixels unevenly because it's nearest-neigbour interpolation. It's not that noticeable with this game as the graphics is 160x200.

You can try integer scaling in the horizontal or vertical dimension to mitigate issue with `texturenb`, but the real solution is the `sharp` shader or the CRT shaders.

```ini
[render]
integer_scaling = vertical
```

**Comment by ErinWiebe** [comment]
> @ErinWiebe `texturenb` is sharper, but it scales the pixels unevenly because it's nearest-neigbour interpolation. It's not that noticeable with this game as the graphics is effectively 160x200.
> 
> You can try integer scaling in the horizontal or vertical dimension to mitigate the issue with `texturenb`, but the real solution is the `sharp` shader or the CRT shaders.
> 
> ```ini
> [render]
> integer_scaling = vertical
> ```

Thanks. Adding `integer_scaling = vertical` helped. The game looks slightly less stretched vertically now.
