### ISSUE TITLE
"integer_scaling = auto" does not work for manually selected CRT shaders

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3333]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Git Main

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Arch Linux

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The `integer_scaling = auto` setting is intended to enable integer scaling when a CRT shader is being used and otherwise disable it.  This does not occur when a CRT shader is manually selected (see config below).  It appears to only work if one of the automatic CRT settings is selected.

It would be nice if the auto setting was a bit smarter.  A naive solution could be to simply enable integer scaling for all shaders in the CRT folder (hard coded).  A smarter solution might be to have some variable in the shader code itself that requests integer scaling (could even be a comment that we parse on the C++ side).

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Use config below for render settings (others can be left as default).
2.  Resize the window and observe that it always fills fully (no integer scaling).

### Your configuration

```ini
[render]
aspect             = auto
integer_scaling    = auto
viewport           = fit
monochrome_palette = amber
cga_colors         = default
glshader           = crt/ega-1080p
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Technically, I could introduce a `prefers_integer_scaling` shader pragma, and then all CRT shaders could define it, similarly to our existing pragmas. E.g., these are the pragmas defined by `arcade-1080p.glsl` now:

```cpp
#pragma use_npot_texture
#pragma force_single_scan
#pragma force_no_pixel_doubling
```

But as I explained [here](https://github.com/dosbox-staging/dosbox-staging/issues/3334#issuecomment-1899343519), the fact that you can set these resolution-specific shaders separately is an implementation detail that has "leaked". I'm intentionally not mentioning the individual shaders anywhere, neither in the config descriptions nor in the release notes, only the "symbolic" auto-shader names:

- `crt-auto`
- `crt-auto-machine`
- `crt-auto-arcade`
- `crt-auto-arcade-sharp`

In the future, all these these individual shaders will be condensed into a single shader. We only have the 20+ shaders now because we don't have a preset system. Most of the current CRT shaders are the exact same code, just with different parameters.

I'm planning to introduce more symbolic names in the future to force the emulation of a specific monitor. Something like this:

`crt-auto-hercules`
`crt-auto-cga`
`crt-auto-cga-mono`
`crt-auto-composite`
`crt-auto-ega`
`crt-auto-vga`

But the selection of the ideal preset variant for a given "pixels per emulated scanline" ratio will be hidden from the user. I don't see any benefit in messing with that manually (maybe for testing only... for which I might include some hidden machinery, but nothing public 😎).

So I'm inclined to leave this as-is as setting single CRT shaders directly is discouraged (or to be more accurate, not encouraged anywhere 😅), and I expect the condensing to a single shader to happen in 2024.

**Comment by weirddan455** [comment]
I agree setting resolution specific shaders directly probably doesn't make sense.  I discovered this bug because I was playing around and wanted to see how EGA shaders looked in a VGA game.  It seems this is the only way to accomplish that until you add those new symbolic names.

>  So I'm inclined to leave this as-is as setting single CRT shaders directly is discouraged (or to be more accurate, not encouraged anywhere 😅), and I expect the condensing to a single shader to happen in 2024. Then the "undocumented" ability to set specific CRT shader resolution-variants will go away.

Fair enough.  Moving to a single shader will make this issue irrelevant.

>  One idea to discourage people using the shaders directly is to move them into a _private or _interal subdir inside glshaders perhaps (e.g., glshaders/_private/crt/ega-1440p.glsl, etc). What do you think @weirddan455 ?

I don't think it's worth doing that personally.
