### ISSUE TITLE
Restoring pre-0.81.0 shader behaviour

### ISSUE THREAD

**Issue by marsej** [dosbox-staging/dosbox-staging#3342]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0rc2

### What Operating System are you using?

Windows 10, FULLHD monitor (1080)

### Whats your question and how can we help?

I was using 0.79 with crt-lottes.glsl / crt-lottes_mod_svn.glsl and the bloom in it smeared the pixels to look more like on some '91 shadow mask VGA CRT with low quality cable. On 0.81.0rc2 the bloom no longer works. See the text in the screenshot comparison:

I had increased the bloom a bit for my own preference, so I attached the modified shader below.

The question is, what changes need to be done to the shader to get this working again... I only changed the numbers a bit, not the code and don't know enough about shaders to get it working again.?
 
(click to view full screen, looks a bit too soft otherwise)
![lottes bloom missing](https://github.com/dosbox-staging/dosbox-staging/assets/81806010/4b2681c9-6f8a-4451-a9a7-8e85a5381295)

[crt-lottes_mod_svn-ms.zip](https://github.com/dosbox-staging/dosbox-staging/files/14007590/crt-lottes_mod_svn-ms.zip)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
## Solution 

Insert the following two pragmas at the top of your shader file after the `#version` pragma, @marsej:

```cpp
#pragma force_single_scan
#pragma force_no_pixel_doubling
```

That will restore the previous behaviour of your shader (see comparison screenshots below).

---

## Explanation

In 0.81, we're doing proper VGA emulation, which means low-res VGA modes are scan and pixel doubled. E.g., the 320x200 VGA mode is indistinguishable from 640x400 from the monitor's point of view. If you take a 320x200 image as your basis, then 2x integer upscale it and display it in a 640x400 mode on VGA, the analog signal sent to the monitor will be _exactly the same_ for the original 320x200 and the upscaled 640x400 image. All VGA hardware does this 2x integer upscaling of 320x200 and similar low-res modes _in hardware_.

The result you were getting with your shader in previous DOSBox versions was because the shader operated on a 320x200 input image. Previous DOSBox versions did not authentically emulate the double scanning behaviour of VGA. Now that we're feeding the shader a 2x larger 640x400 image for the 320x200 VGA mode, the blur radius becomes a lot smaller. That's just how the shader was coded; the bloom/blur is dependent on the input resolution, apparently.

With the above two pragmas, you're forcing single scanning and _no_ pixel doubling for any VGA video modes. So the shader still gets 320x200 pixels for the 320x200 VGA mode as before.

The built-in CRT shaders might get additional blur / bloom parameters in the future as such things are supported by the multi-pass "glow" variant of the Hyllian CRT shader. Then we'll be able to dial in bloom/blur to taste even with the double scanned output. But we need a multi-pass shader pipeline for that first. Currently, we can only do single-pass, so I'm using the single-pass Hyllian shader as a base which doesn't have the extra bloom/glow params.

## Screenshots

### Your current shader

<img width="1728" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/f9b47d77-d382-4a38-ba0c-f278469abb24">

### Your shader + the pragmas

<img width="1728" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/490573f5-fec2-467a-bea4-358f46b44d5a">

**Comment by marsej** [comment]
Works now, thank you!
