### ISSUE TITLE
Screen squashed vertically with machine=cga and aspect=off

### ISSUE THREAD

**Issue by gzip** [dosbox-staging/dosbox-staging#3365]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81-rc2

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The screen is overly squashed in CGA mode when `aspect = off`. Changing `integer_scaling`, `viewport`, and `glshader` don't seem to affect it, nor does resizing the window. See steps to reproduce.

![image0002](https://github.com/dosbox-staging/dosbox-staging/assets/104513/86992235-c129-4aa5-8dd0-8ea51bd54a06)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Remove or rename any existing config in %HOMEDIR%\AppData\Local\DOSBox
2. Open a fresh install of DOSBox Staging 0.81-rc2 and let it create a new config
3. Close DOSBOX Staging and edit the config to include `machine = cga` and `aspect = off`
4. Open DOSBox Staging again and the screen is overly squashed vertically

### Your configuration

```ini
machine = cga
aspect = off
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
## Short answer

This is expected behaviour, there is no bug.

Please read the description of the revised `aspect` and `viewport` settings; everything works as described.

## In more detail

`aspect = off` forces square pixels. This is how 640x200 with square pixels looks.

Now, the legacy DOSBox behaviour was that even with `aspect = off`, _some) video modes that were "too wide" with square 1:1 pixels were height-doubled. This behaviour was pretty ad-hoc, and the proper PAR for 640x200 with `aspect = on` is 1:2.4, but `aspect = off` gave you 1:2 instead of 1:1...

Long story short, that "video mode special casing" behaviour is gone, and it's not coming back. It was arbitrary, inconsistent, and confused and complicated a lot of things (shaders, image captures, etc.) It's the result of a 20-year-old decision where aspect ratio correctness was an afterthought.

But the good news is, you can get what you want with the newly introduced `viewport` and `aspect` modes. Read on!


### Force 8:5 image aspect ratio

This is what you want: the same image aspect ratio as you would get with 320x200 VGA content displayed with `aspect = square-pixels` (same as `aspect = off`).

320:200 = 8:5

Deriving the vertical stretch factor of 83.33% is an exercise for the reader :)


```ini
[render]
aspect = stretch
viewport = relative 100% 83.33%%
```

Result:

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/da2ae94c-bea5-459e-a71f-1cc968edc5fb)


### Force 4:3 image aspect ratio

You did not ask for this, I'm just putting it here for reference. This setting will stretch the image to fit a 4:3 aspect ratio rectangle, no matter what (equivalent to using monitor's stretch controls to make the image always fill the 4:3 aspect ratio screen).

```ini
[render]
aspect = stretch
viewport = relative 100% 100%
```

**Comment by gzip** [comment]
Ok, trying to understand this better. It's 640x200 because its starting up in text mode 03, 80x25 characters, and it looks strange here because DOSBox legacy already has some magic, and we've never seen a display without that correction. Then when a game starts it kicks into mode 05 and the results are as expected with no aspect correction. But then why the difference in display between EGA and VGA at start up with aspect=off?

**Comment by johnnovak** [comment]
> Ok, trying to understand this better. It's 640x200 because its starting up in text mode 03, 80x25 characters, and it looks strange here because DOSBox legacy already has some magic, and we've never seen a display without that correction. Then when a game starts it kicks into mode 04 at 320x200 and the results are as expected with no aspect correction. But then why the difference in display between CGA and VGA at start up with aspect=off?

Mode 03h is always 80x25 characters, but the resolution changes between CGA, EGA, MCGA, and VGA adapters. To keep it 80x25 characters, the character matrix increases with the resolution too. Do the maths—it will check out! 😎 

- CGA: 640x200 resolution, 8x8 pixel character matrix
- EGA: 640x350 resolution, 8x14 pixel character matrix
- MCGA: 640x400 resolution, 8x16 pixel character matrix
- (S)VGA: 720x400 resolution, 9x16 pixel character matrix

I suggest learning more about the different video adapters and video modes to understand this better. Studying this table is a good start:
https://minuszerodegrees.net/video/bios_video_modes.htm

**Comment by gzip** [comment]
Ah, even though it's the same 80x25 text mode, the resolution and character size change, that was the piece I was missing. And from CGA to VGA the character height doubles, hence the difference in display at start up. I was looking for a table like that but couldn't find it, thanks!
