### ISSUE TITLE
Weird behaviour with 3dfx Voodoo emulation

### ISSUE THREAD

**Issue by SuperIlu** [dosbox-staging/dosbox-staging#3405]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0

### What Operating System are you using?

Windows 10

### Relevant hardware info

AMD Ryzen 5 4600H with Radeon Graphics (12) @ 2.994GHz

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When running DOjS and using 3dfx voodoo emulation the picture appears upside down.
This does not happen with DOSBox-X or real hardware.
![9561e86172bb563a](https://github.com/dosbox-staging/dosbox-staging/assets/1155988/4e7d4045-04c1-4b93-94f7-963275e2aa93)
![73752fd32c4c33ed](https://github.com/dosbox-staging/dosbox-staging/assets/1155988/1141b5f3-578f-4d20-91c6-d195e11ec3d2)

### Steps to reproduce the behaviour.

- Download DOjS https://github.com/SuperIlu/DOjS/releases/tag/v1.121
- Extract ZIP to DOSBox C-drive
- run `V_1.BAT`
- run `DOJS -rt examples\gltixy.js`

### Your configuration

```ini
https://gist.github.com/SuperIlu/328b6edca9b5bf5ab9473ac6ed27506a
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Thanks for reporting this @SuperIlu. Thus is an interesting one! 😅  Our main focus is getting games from the "true DOS era" running, so from the 1980 to 2000 period (and even 2000 is quite generous). AFAIK the team has tested all Voodoo games from the 90s and none have this flipped screen issue. So while probably you're right in saying this is a bug if the same code works correctly on real hardware, it's a very insignificant one as no known game triggers it.

We don't have too much love for Voodoo on the core team, neither are we Voodoo experts. We've mainly done it to please users who are into this stuff. Which means it's unlikely anyone from the core team will look into this. 

If this is important for you, by all means investigate and PR a fix. We'd very much appreciate the help! Thanks.

**Comment by weirddan455** [comment]
I'll take a look at it later.  I'm certainly not a Voodoo expert but this could be an easy fix, especially since other Dosbox forks are getting it right.  No promises though.

**Comment by johnnovak** [comment]
> I'll take a look at it later. I'm certainly not a Voodoo expert but this could be an easy fix, especially since other Dosbox forks are getting it right. No promises though.

Cheers @weirddan455. If you're interested, why not. I was managing expectations 😎

**Comment by SuperIlu** [comment]
Thanks for caring.
I'm not really a big help here, I have no real insight on the inner workings of GLIDE3 or the Voodoo hardware.
Just a side note: tixy.js does not directly use the GLIDE3 API, but it uses the OpenGL API of Mesa on top of GLIDE3.
So it might be that Mesa does some weird configuration of GLIDE that shows in this case...

Feel free to ask if you need information/help with anything I can provide...

**Comment by johnnovak** [comment]
> Just a side note: tixy.js does not directly use the GLIDE3 API, but it uses the OpenGL API of Mesa on top of GLIDE3.

Oh man, that makes the whole thing out of scope, yeah 😄 We support games that hit the Voodoo hardware without such middleware.

**Comment by weirddan455** [comment]
Maybe out of scope but this DOSjS project is really cool so I'm interested.  It's the first I'm hearing of it.  They have a working OpenGL + Javascript stack running on top of DOS + Glide.

I played around with it for a bit and the entire image is not upside down, the the text.  I wrote a test .js script to render a triangle with OpenGL to confirm it's rendering correctly.

The problem happens because it's rendering the text to an off-screen bitmap and then drawing that bitmap with `glDrawPixels`.  Somewhere in that process, the bitmap gets drawn upside down (and drawn at the bottom left instead of the top left).  A minimally reproducible program is as follows:

```js
LoadLibrary("ogl");

var img;

function Setup() {
    glInit();
    img = new Bitmap(200, 20);
    SetRenderBitmap(img);
    ClearScreen(EGA.BLACK);
    TextXY(0, 0, "Hello World", EGA.WHITE);
}

function Loop() {
    glDrawPixels(img);
    glFlush();
}
```

I suppose the next step would be to peel back these abstraction layers.  @SuperIlu would you be able to assist in pointing out in your project where the OpenGL -> Glide code lives?  I would like to see if I can reproduce this in a stand-alone DOS program and maybe this will point to a flaw in our emulation.

**Comment by SuperIlu** [comment]
Wow, you really dug deep into it already.
Also: thanks for the praise 😊

The JS->C mapping for `glDrawPixels()` is here: https://github.com/SuperIlu/DOjS/blob/85a47d94589956a23a0659ec3ddb18f8d7b2975c/plugins/ogl.dxelib/ogl.c#L310

I'm not to deep into Mesa, but I guess DrawPixel is implemented here: https://github.com/SuperIlu/DOjS/blob/master/3rdparty/MesaFX-3.4-master/src/drawpix.c

It seems like they check if the driver has an own implementation of DrawPixel, which the glide driver appears to be missing: https://github.com/SuperIlu/DOjS/blob/85a47d94589956a23a0659ec3ddb18f8d7b2975c/3rdparty/MesaFX-3.4-master/src/FX/fxdd.c#L1122

They seem then to call `WriteRGBASpan()` of the driver which seems to be mapped to `fxDDWriteRGBASpan()`
https://github.com/SuperIlu/DOjS/blob/85a47d94589956a23a0659ec3ddb18f8d7b2975c/3rdparty/MesaFX-3.4-master/src/FX/fxddspan.c#L194

This uses https://github.com/SuperIlu/DOjS/blob/85a47d94589956a23a0659ec3ddb18f8d7b2975c/3rdparty/MesaFX-3.4-master/src/FX/fxddspan.c#L160
which finally calls `grLfbWriteRegion()` via
https://github.com/SuperIlu/DOjS/blob/85a47d94589956a23a0659ec3ddb18f8d7b2975c/3rdparty/MesaFX-3.4-master/src/FX/fxddspan.c#L150
and
https://github.com/SuperIlu/DOjS/blob/85a47d94589956a23a0659ec3ddb18f8d7b2975c/3rdparty/MesaFX-3.4-master/src/FX/fxglidew.h#L308

The source for Glide3 I use is here:
https://github.com/SuperIlu/glide

You can also call `grLfbWriteRegion()` when using GLIDE directly and I cobbled together a short test program. In this case no image flipping occurs...
```
var img;

FX_BLACK = 0xFF000000;

function Setup() {
    img = new Bitmap(200, 20);
    SetRenderBitmap(img);
    ClearScreen(EGA.BLACK);
    TextXY(0, 0, "Hello World", EGA.WHITE);

    fxInit();
    fxOrigin(GR_ORIGIN.LOWER_LEFT);
}

function Loop() {
    fxBufferClear(FX_BLACK, 0, 0);
    img.FxDrawLfb(0, 0, GR_BUFFER.BACKBUFFER, false);
}
```

So, sorry, I'm not an expert on OpenGL/Mesa, I just happened to include it into my framework...

**Comment by weirddan455** [comment]
Thanks for the info @SuperIlu I did some more digging and got a repro case with a standalone plain C DOS program.  This is essentially how Mesa is drawing a bitmap using Glide calls.  It seems we are not respecting the `GR_ORIGIN_LOWER_LEFT` flag in `grSstWinOpen`.

```c
#include <glide.h>
#include <stdlib.h>
#include <stdint.h>

int main(void) {
    grGlideInit();
    grSstSelect(0);
    grSstWinOpen(0, GR_RESOLUTION_640x480, GR_REFRESH_60Hz, GR_COLORFORMAT_ARGB, GR_ORIGIN_LOWER_LEFT, 2, 1);
    int width = 50;
    int height = 50;
    uint32_t *buffer = malloc(width * height * 4);
    if (!buffer) {
        grGlideShutdown();
        exit(EXIT_FAILURE);
    }
    uint32_t *ptr = buffer;
    for (int y = 0; y < 25; ++y) {
        for (int x = 0; x < width; ++x) {
            *ptr++ = 255 << 16;
        }
    }
    for (int y = 25; y < height; ++y) {
        for (int x = 0; x < width; ++x) {
            *ptr++ = 255;
        }
    }
    while (1) {    
        grBufferClear(0, 0, 0);
        int bottom = 479;
        for (int y = 0; y < height; ++y) {
            grLfbWriteRegion(GR_BUFFER_BACKBUFFER, 0, bottom - y, GR_LFB_SRC_FMT_8888, width, 1, 0, 0, buffer + (width * y));
        }
        grBufferSwap(3);
    }
}
```

Left is DOSBox-X, Right is Staging

![voodoo](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/ed9e2ec1-1837-4211-a6f9-461e2923add5)

**Comment by johnnovak** [comment]
Whatever you do @weirddan455 , regression test at least 5 DOS games that support the Voodoo 😄

**Comment by weirddan455** [comment]
> Whatever you do @weirddan455 , regression test at least 5 DOS games that support the Voodoo 😄

Will do.  I'm testing a one-liner now that resolves at least this test case.  There's 2 different registers that have bits for determining the Y offset and we may have been checking the wrong one.

I'm trusting the test @SuperIlu did on real hardware because I don't have the hardware.  It goes against what I found documented though.

On the `grLfbWriteRegion` function:

> dst_x, dst_y Destination x and y coordinates The y origin is always assumed to be at the upper left.

https://www.gamers.org/dEngine/xf3D/glide/glideref.htm

Then again, documentation is often wrong :shrug:

**Comment by johnnovak** [comment]
> Then again, documentation is often wrong 🤷

I only trust working code as the source of truth 😎

**Comment by Grounded0** [comment]
I'm known as Antti on Mastodon to the author so let me jump in with one expert about this stuff. This is from our IRC channel:

```
05:49Z <@Anonymised> lul
05:50Z <@Anonymised> OpenGL's convention is origin at the bottom left, maybe that's related.
```

**Comment by weirddan455** [comment]
@Grounded0  In Glide, the origin is configurable but that probably explains why the Mesa code set Glide to have a bottom left origin so it can match OpenGL's conventions.

I found some better documentation going over the actual hardware:  http://bitsavers.org/components/3dfx/3Dfx_VOODOO2_Revision_1.16_199912.pdf

```
Bit(13) of lfbMode is used to define the origin of the Y coordinate for all linear frame buffer reads and linear
frame buffer writes when the pixel pipeline is bypassed (lfbMode bit(8)=0). Note that bit(13) of lfbMode does not
affect rendering operations (FASTFILL and TRIANGLE commands) -- bit(17) of fbzMode defines the origin of
the Y coordinate for rendering operations. Note also that if the pixel pipeline is enabled for linear frame buffer
writes (lfbMode bit(8)=1), then fbzMode bit(17) is used to determine the location of the Y origin. For linear
frame buffer reads, however, lfbMode bit(13) is always used to determine the Y origin, regardless of the setting of
lfbMode bit(8). When cleared, the Y origin (Y=0) for all linear frame buffer accesses is defined to be at the top of
the screen. When bit(13) is set, the Y origin for all linear frame buffer accesses is defined to be at the bottom of
the screen.
```

As best as I can tell, this is exactly what we're doing in our code so I'm hesitant to change it.  @SuperIlu can you please confirm what hardware you have tested this on?

I also found this bug you filed 4 years ago with DOSBox-X:  https://github.com/joncampbell123/dosbox-x/issues/1402

Tested it on their tip of tree code and ours.  They fail that test11.exe and we pass :smile: so I'm not looking to blindly replicate what DOSBox-X is doing.  Their emulation is not so accurate either.

Btw this is the one-liner:

https://github.com/dosbox-staging/dosbox-staging/blob/2a094170de5d6f354a830fb1a162416e81691b47/src/hardware/voodoo.cpp#L6203

Change that to check fbzMode instead of lfbMode and it's "fixed" (if that's actually what real hardware does).

**Comment by Grounded0** [comment]
@johnnovak 

Time to go to eBay with the money you got and get a Voodoo card for one of your rigs. Will become handy. 😁

**Comment by shermp** [comment]
I just tested this on PCem V17 using MS Dos 6.22. It too had upside down text with the provided reproduction using PCem's Voodoo emulation.

**Comment by SuperIlu** [comment]
@weirddan455 I'll re-test on my Voodoo today (and check that it is really a V1 and not a V2 as I'm supporting both).
Can you provide me with your minimal DOS EXE/test case as well?
I'll post a screenshot afterwards.

**Comment by weirddan455** [comment]
@SuperIlu Here's a zip that hopefully will work for you.  I used the latest DJGPP (GCC 9.3.0) plus the Glide binary from DOjS to compile it.  I had trouble compiling Glide from source.  I saw you had to use some old version so I just grabbed the binary instead of fussing with that.

[test.zip](https://github.com/dosbox-staging/dosbox-staging/files/14309519/test.zip)

**Comment by weirddan455** [comment]
I looked at the Glide source too and it's looking like the intent of `grLfbWriteRegion` really is to always have the origin at the top left even if the origin is bottom left for other drawing commands.  You can see it's hard-coded here and ends up setting the register accordingly:

https://github.com/SuperIlu/glide/blob/eabb2f9a43f8a1af8377b198f0e9229f227a1ea3/glide3x/sst1/glide3/src/glfb.c#L640-L645

Of course, testing on real hardware is the only way to be sure.  Just make sure to test with the same Glide version.  The glide.dxe is in the zip file above.

**Comment by SuperIlu** [comment]
Damn, I guess I have to dig out my "big book of apologies" now :(

I checked the test program and the gltixy.js both on my Voodoo1 (and to be sure on the Voodoo2 as well) and guess what?
The coordinates are upside-down as well. So DBS is right, DB-X is wrong (and even more my memories were)!

I could have sworn did run gltixy on my test box for speed testing, but it seems I didn't :(

So sorry for the false alarm and if I can sponsor any of you folks a cold beverage let me know...

**Comment by weirddan455** [comment]
@SuperIlu All good.  I got to learn some about how 3dfx internals work at least.  It seems like the Mesa code is buggy then.  You could probably do a find + replace `bottom - y` for `y` in this file for a quick fix for your project:

https://github.com/SuperIlu/DOjS/blob/master/3rdparty/MesaFX-3.4-master/src/FX/fxddspan.c

**Comment by SuperIlu** [comment]
@weirddan455 I have seen that the Q2DOS-People are now using Mesa 6(?), so I might even try to upgrade.
After all, DOjS is my black hole for spare time :)

**Comment by johnnovak** [comment]
> So DBS is right, DB-X is wrong (and even more my memories were)!

Nice. Staging did nothing wrong 😎
