### ISSUE TITLE
midi: wildfire integration

### ISSUE THREAD

**Issue by legluondunet** [dosbox-staging/dosbox-staging#347]
Hello,

do you think Wildfire could be a good option for DOSBOX-Staging to play midi music on all OS platform?
--> multiplatform
--> does not need root rights on Linux (userland)

https://github.com/Mindwerks/wildmidi

**Comment by dreamer** [comment]
No software midi synthesisers on Linux require root rights - if documentation or tutorials say otherwise, that's like a vestige from days before PulseAudio or some hacks to raise the process priority.

As for Wildfire… technically and license-wise it's in a clear… seems also available in a number of repositories: https://repology.org/project/wildmidi/versions - so that's good as well.

The problematic part is: project seems not active? There is barely any developer activity and they even let their homepage certificate expire… Does not bode well.

**Comment by legluondunet** [comment]
I wanted to draw your attention to this project, done! 
And keep the good work for Dosbox-staging :+1:
