### ISSUE TITLE
Installer: Restore -noconsole for primary Windows start menu shortcut (& for desktop shortcut)

### ISSUE THREAD

**Issue by dros0-0** [dosbox-staging/dosbox-staging#3473]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

This is a very trivial change, but for previous versions of DOSBox Staging on Windows, the primary start menu shortcut (as well as the desktop shortcut) as created by the installer included the -noconsole launch option by default. The 0.81.0 installer doesn't set up this launch option (for either the start menu shortcut or the desktop shortcut), but strangely still adds a "DOSBox Staging with console" start menu shortcut, even though that is now the default behavior of the primary start menu shortcut as well.

### Describe the solution you'd like

Restore -noconsole launch option as default for the primary Windows start menu shortcut, as well as for the desktop shortcut.

### Describe alternatives you've considered

If this change was intentional, then don't generate "DOSBox Staging with console" start menu shortcut if that is going to be the default behavior of the primary start menu shortcut.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
It's intentional. If you don't see the logs, you don't see the warnings either when you misconfigure something. Some of the features also rely on the logs, currently (e.g., joystick calibration).

Maybe I will turn the "with console" into "without console" as a secondary option, or just get rid of it.

**Comment by Grounded0** [comment]
I think we should offer both for 0.81.1 as macOS doesn't show console either as default. It's mainly for figuring out what went wrong instead of being something the user would be interested to see at all times. This was my call when Windows installer was delivered originally.

**Comment by johnnovak** [comment]
> I think we should offer both for 0.81.1 as macOS doesn't show console either as default.

Because of technical limitations. I would love to show the console by default on macOS, and make the "no console" option opt-in.

> It's mainly for figuring out what went wrong instead of being something the user would be interested to see at all times. This was my call when Windows installer was delivered originally.

The problem is it's already too late when the problem happened. I'm strongly in favour for showing the console window by default on all platforms if we can, but it's ok to give the user the option to disable it (but I discourage everybody from doing so; I never disable the console on Windows, and I don't see why it's a big deal that it's there).

**Comment by Grounded0** [comment]
Well as a compromise lets show console as default but add `-noconsole` icon there too for people who got a known good setup who want less window clutter.

**Comment by johnnovak** [comment]
> As a compromise lets show console as default but add `-noconsole` icon there for people who got a known good setup and want less window clutter.

I can do that, yeah.
