### ISSUE TITLE
Flatpak package: Quick and dirty manifest

### ISSUE THREAD

**Issue by Kirtai** [dosbox-staging/dosbox-staging#351]
Hi,
Attached is my quick and dirty flatpak manifest and appinfo, based on the SVN DOSBox flatpak on flathub [here](https://github.com/flathub/com.dosbox.DOSBox). (I was the one who mentioned it on the gog forums).

The appinfo file needs updating with screenshots and a better description, and a proper ID should be decided, but it builds and runs fine here. (Kubuntu 20.04).

I've set the sandbox to only allow access to it's own folder and  $XDG_DOCUMENTS_DIR/DOSBox but that can easily be changed to whatever you prefer.

Edt: removed unnecessary GLU library. 

[staging.zip](https://github.com/dosbox-staging/dosbox-staging/files/4589811/staging.zip)

**Comment by dreamer** [comment]
Yeah, I believe XDG_DOCUMENTS_DIR is not a good choice - I'll help out with polishing the package as soon as I'll find a minute :) Thank you for picking this up!

**Comment by Kirtai** [comment]
You're welcome :)

I chose XDG_DOCUMENTS_DIR because that's what the SVN flatpak did, Among the alternatives I considered were giving access to host (whole filesystem), home (obvious), XDG_DATA_DIR/dosbox, some other directory or limiting it to it's own sandboxed directory, none of which I was comfortable with choosing as a default.

Maybe giving access to --filesystem=host along with instructions on how to narrow the permissions to a users chosen folders would be the most practical.

I doubt adding XDG portal support to dosbox-staging would be practical though. Maybe :)

**Comment by dreamer** [comment]
Because of that XDG_DOCUMENTS_DIR, I needed to document how to use Flatpakked DOSBox with Boxtron in the past and it was somewhat annoying: https://github.com/dreamer/boxtron/wiki/Flatpak

I do understand sandboxing improves security, but I don't know any users who would keep their DOS games in `~/Documents/`… (personally, I store my DOS games in `~/.local/share/games/` with exception of those installed via Steam) - some people will have them in ~/Games, others in various game libraries (often on separate drives).

Anyway, there are other options with dosbox-staging as well - we support overlay mounts (unlike 0.74-3) and mounting read-only resources (unlike DOSBox upstream in general), so perhaps these features can be married with Flatpak to provide well designed user experience. To be investigated :)

**Comment by Kirtai** [comment]
Good points. Flatpak does support read only access, so maybe something like giving read only access to the host filesystem and storing overlays in the sandbox directory would be a better idea.

I'm not married to any particular setup though. Whatever you think is best.

XDG portals would probably be a lot of work, just to support stuff like flatpak. I expect they'd be very far down the todo list even if practical :)

**Comment by Kirtai** [comment]
Updated, changed permissions to host:ro,  fixed some bugs. added (but not tested) wayland, made it less horrible.
Still some problems with icons and appdata.

Also added a bundle built using the new manifest for anyone who wants to poke at it.

[dosbox-staging.zip](https://github.com/dosbox-staging/dosbox-staging/files/4594528/dosbox-staging.zip)

[dosbox-staging-0.76.bundle.zip](https://github.com/dosbox-staging/dosbox-staging/files/4594537/dosbox-staging-0.76.bundle.zip)

**Comment by Svadkos** [comment]
> Also changed ID to what flatpak recommends.

Shouldn't it be just `io.github.dosbox-staging`?
Also, i think `home:ro` is enough.

**Comment by Kirtai** [comment]
> Shouldn't it be just `io.github.dosbox-staging`?

The Requirements & Conventions page specifically mentions this [here](https://docs.flatpak.org/en/latest/conventions.html#application-ids). io.github.dosbox-staging refers to the organisation. It might seem redundant to double it, but it'll help disambiguate if another project is started under the same organisation, such as e.g. a gui configuration tool. (io.github.dosbox-staging.gui)

> Also, i think `home:ro` is enough.

It would be for many but as dreamer said, some keep their games on external drives or otherwise outside their home. Setting "host:ro" will allow it to work out of the box on pretty much any system, will prevent any file modification from bugs or exploits and it can be narrowed to your own storage layout using overrides. home:ro will break for those people. 

Of course, this assumes the use of overlays which I hope will become default eventually. It can always be tweaked regardless to suite the user.

**Comment by Kirtai** [comment]
Updated version, changed from json to yaml, includes some files from dosbox-staging (icon, desktop entry).

Should be a bit easier to read. I might need to create a 256x256 bitmap icon from the svg though. We'll see.

[dosbox-staging.zip](https://github.com/dosbox-staging/dosbox-staging/files/4698797/dosbox-staging.zip)

**Comment by dreamer** [comment]
@Kirtai I haven't looked into this in detail - do you think it's possible to hook up flatpak building, so our release builds would be automatically deployed to FlatHub? (I am interested in flathub part - I will be able to hook it up in our CI if FlatHub provides some kind of API for it).

Also, some time ago I read that Flatpak will allow nightly builds alongside normal release builds - is it perhaps available already?

About `home:ro`… I'm afraid it will still be not good enough… but it's a separate topic to be addressed later (and topic shared between Flatpak and Snap packages).

**Comment by Kirtai** [comment]
@dreamer I'm not really familiar with how flathub does things but this is how I understand it.

I believe the usual way is to have a manifest plus support files in a repo under their organisation which uses their build infrastructure to build new flatpaks, They seem to prefer that the ownership of this repo is given to the source project owner. [Here](https://github.com/flathub/com.dosbox.DOSBox) is the DOSBox one as an example.

However, I do know that external building is supported but don't know any details of that (Firefox does it)

I think nightly builds are released in flathubs beta channel, which you can subscribe to separately from the release one.

Also, I haven't changed the permissions and it's still host:ro for now.

**Comment by soredake** [comment]
Any progress on dosbox-staging flatpak?

**Comment by dreamer** [comment]
Nobody's working on this ATM; the task is free for the taking.

**Comment by rderooy** [comment]
FYI, I created a flatpak for dosbox-x a few days ago. Feel free to use it as a template.
https://github.com/flathub/com.dosbox_x.DOSBox-X

**Comment by rderooy** [comment]
A few more comments. 
- flathub only wants to publish tagged release versions, either directly using a github release tag, or using a release archive. So not suitable for nightlies.
- You will need a flatpak manifest file, and a metainfo.xml file.
- You should also have at least one screenshot (I still need to add this for dosbox-x)

**Comment by soredake** [comment]
>So not suitable for nightlies.

Not sure about this, as rpcs3 flatpak exists https://github.com/flathub/net.rpcs3.RPCS3/blob/master/net.rpcs3.RPCS3.yaml#L110

**Comment by kcgen** [comment]
Thanks for sharing this work @rderooy.
Regarding the limitations (https://github.com/flathub/com.dosbox_x.DOSBox-X#limitations), do you know if the dosbox executable can access local unix sockets to communicate with an external MIDI player (eg: ALSA 0:128)?  Can the serial ports open TCP/IP connections (for BBS / multiplayer) stuff?

Some folks have made snap and flatpak releases of staging, but these have been a couple common problems with them.

**Comment by dreamer** [comment]
Another area, that need testing was controller access and access to user-mounted directories outside of home (e.g. external HDDs or USB sticks).

**Comment by rderooy** [comment]
@kcgen I have not yet tried using external MIDI. Must give it a try.

As to serial, it works. I can dial a telnet bbs when I set serial1=modem
Likewise parallel and serial passthrough *should* work, but I have no way to test them. This is because access to /dev is allowed. Likewise game controllers also work.

@dreamer user mounted directories outside of home are not accessible with, as I have set access only for Home. So a user will have to transfer the files to his home directory before they can be accessed (symlink also does not work).

**Comment by rderooy** [comment]
I have also validated that external MIDI works (using external Munt)

**Comment by Kirtai** [comment]
I updated my flatpak to 0.75.1 at https://github.com/Kirtai/dosbox-staging-flatpak. Feel free to use it for inspiration.

**Comment by rderooy** [comment]
Something about wayland. I tested this with both dosbox-x and dosbox staging. And there is a problem... And due to this problem, I have removed the wayland line in the manifest for dosbox-x to disable it.

The issue is that with Xorg window decorations (title bar, min/max/close buttons, resizing controls) are so-called SSD (Server-Side-Decorations). Meaning we don't need to worry about them, or more accurately that SDL does not need to. And every app, regardless of toolkit used at least has the same window decoration.

Not so with wayland. Wayland instead uses CSD (Client-Side-Decorations). Meaning that the app is responsible, or the toolkit it uses. Meaning that a QT app will look different from a GTK app, etc. There is an **optional** extension called XDG-Decoration that allows SSD. This extension is supported by all wayland compatible window managers, except Gnome and Enlightenment. In fact the Gnome team have completely rejected it, and close and lock any bug reports requesting it.

This means that when you run dosbox-x or dosbox staging in wayland mode on Gnome, you get a borderless window. Try it yourself, if your running wayland how it looks on your system (no need for a flatpak):
```
SDL_VIDEODRIVER=wayland dosbox
```
The issue is that toolkits like SDL don't want to get into window management...

The only solution I have found is this library:
https://gitlab.gnome.org/jadahl/libdecoration

**Comment by kcgen** [comment]
@rderooy, thanks for the nice explanation and indeed I can confirm this happen with me running  Gnome using its wayland backend on Fedora 32.

The `sway` tiling WM hid this defect because sway tiled dosbox-staging's window content just like the other applications.

**Comment by dreamer** [comment]
Discussion about Wayland/CSD -> #650

**Comment by okias** [comment]
@Kirtai I'm 'stealing' your appdata :) it would make sense to include them even in Linux package (programs with metainfo looks really nice in GUI package managers). I'll add MR with it here.

**Comment by Kirtai** [comment]
Feel free, that's what it's for :)

**Comment by okias** [comment]
https://github.com/dosbox-staging/dosbox-staging/pull/669#issuecomment-711167479 for next release metainfo should be in. It's slightly modified, but I believe it'll fit flatpak also! :)

**Comment by dreamer** [comment]
I wrote a new manifest to cover all our icons and meta; FlatHub PR: https://github.com/flathub/flathub/pull/1996
