### ISSUE TITLE
Cyber Riders (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3511]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.0

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This is an interesting one. Out of all the dosbox forks only Dosbox X will play this games music. It does it with no special settings in the conf, just works. Every other fork has no music, just a quiet humm.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load game
2. Listen for music after 'WSP' title screen goes away
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by codengine** [comment]
The game works properly with "LOADFIX".

**Comment by johnnovak** [comment]
@Python-Exoproject Could you confirm the `LOADFIX` solution?

**Comment by Python-Exoproject** [comment]
I still had no luck when adding in loadfix. @codengine Could you pass me your conf? I assume your using 81.1

**Comment by codengine** [comment]
> I still had no luck when adding in loadfix. @codengine Could you pass me your conf? I assume your using 81.1

Its the same as here: https://github.com/dosbox-staging/dosbox-staging/issues/3640#issuecomment-2126003948

**Comment by Python-Exoproject** [comment]
With #3640 solved, any thoughts on this one? I thought it might be solved the same way as its the same issue on the surface, @codengine has it working with sound, I do not. But changing the core made no difference here and unlike Eddy and Co it uses OPL.

Maybe you would like to have a go @interloper98 as you had luck with Eddy?

**Comment by interloper98** [comment]
@codengine, I wasn't able to get sound working from your conf + loadfix.  I also tested the last release of DOSBox Daum, but it also has the same issue.

Isolated the fix in DOSBox-X between these adjacent releases (roughly one month worth of changes):
 - DOSBox-X release [0.82.4](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-windows-20180316-2157) 2018-03-16 (bad, commit: 8b89659)
 - DOSBox-X release [0.82.5](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-windows-v0.82.5) 2018-04-18 (good, commit: e813149)

The sound is pure OPL2 (doesn't use the SB's DMA or DAC). You can use:

```ini
[sblaster]
sbtype = none
oplmode = opl2
```

**Comment by interloper98** [comment]
Tried the new conf setting changed between X 82.4 and 82.5 and isolated it to `enable dummy environment block = false`.

Looks like this dummy environment stuff has been in DOSBox since 2005, but starting in DOSBox-X release 0.82.5 (April 2018), they stopped doing that by default, but still let users turn it back on like normal DOSBox with:

```ini
[dos]
enable dummy environment block = true
```

It's easy enough to follow this setting into `dos_memory.cpp`, so maybe (or making this env padding stuff optional, like in X) might get it working? 

```c++
// Create a small empty MCB (result from a growing environment block)
DOS_MCB tempmcb((uint16_t)DOS_MEM_START+mcb_sizes);
tempmcb.SetPSPSeg(MCB_FREE);
tempmcb.SetSize(4);
mcb_sizes+=5;
tempmcb.SetType(middle_mcb_type);
```

**Comment by johnnovak** [comment]
@interloper98 Well, @codengine said it works fine with `LOADFIX`. We want to exhaust the `LOADFIX` options first, then maybe even consider enhancing `LOADFIX` before messing with the MCB implementation.

**Comment by codengine** [comment]
Yes it was just LOADFIX <game>, but let me retest it now that I reinstalled everything.

**Comment by interloper98** [comment]
@codengine - have you retested this?

---

I was thinking about how the above fix in dosbox-x involved eliminating this dosbox-specific fake memory environment padding (I guess @joncampbell123 determined it was unneeded or actually detriment?), and that this change has been the default in X now for about 6 years.

Because it's a tweak to the runtime memory space, one idea would be add this to LOADFIX, given that LOADFIX is all about letting you adjust the runtime memory space.

In this case, maybe an option in loadfiz could deduct or eliminate this env padding. Just an idea that hot me the other day 🙂

**Comment by Python-Exoproject** [comment]
@johnnovak Would the adjustment to LOADFIX be a workable solution that wouldn't affect any other functions LOADFIX is currently used for?

**Comment by codengine** [comment]
@interloper98 I tried it again, yes. The game did start but the sound was garbage unfortunately. I don't know why it worked that one time :/

**Comment by interloper98** [comment]
> @interloper98 I tried it again, yes. The game did start but the sound was garbage unfortunately. I don't know why it worked that one time :/

Thanks for double checking @codengine

**Comment by Python-Exoproject** [comment]
Youve been on a roll recently @interloper98, would this one also be in your wheelhouse? All good if not, just asking

**Comment by interloper98** [comment]
Yup; looking into it. I need to try running it within a booted real MS-DOS environment. If that plays music, then this game is probably revealing a bug in the initial memory sizing.

**Comment by interloper98** [comment]
Booted into a Microsoft MS-DOS 6.22 HDD image (in Staging `main`) and also tried 86Box using an off-the-shelf config + bare-bones DR-DOS HDD image, however however the problem persists in both cases.

I wasn't sure how to capture video, so here's an audio-only recording of the game's music in 86Box (it's a mosquito party!):

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/c084d9ac-5565-42ac-873f-90ed35a9a4d4

Here the stand-alone 86Box config, HDD image, NVRAM (BIOS), and floppy image. Just launch 86box inside this directory and then use the GUI to manually mount the floppy image after DOS has booted.

Somehow 86Box is far more difficult to deal with than a real PC - because at least a real PC from Gateway or Compaq had all the I/O controllers integrated, tested, and BIOS pre-configured with working settings. I had so many failed attempts that gave up and starting downloading the canned stuff from archive.org :face_with_head_bandage:

**Comment by interloper98** [comment]
@Python-Exoproject, here's a working solution:

Run `loadfix /f` as a separate command before launching the game:

```ini
[autoexec]
loadfix /f
mount c ...
c:
cyber.exe
```

Even though the `/f` option is described as freeing _previously allocated_ memory by loadfix, it turns out `/f` releases a bit of front padding (and this is released even if loadfix hasn't been run before).

I don't know why, but the game really needs this front layout freed up. I also check if the game is just memory hungry but it's not: you can load a bunch of TSRs that drop free memory to 500 KB and the audio plays fine. So it's all about that early layout that's critical for it.  :man_shrugging: :laughing:

**Comment by Python-Exoproject** [comment]
Well ill be damned, thats it. Thank you very much for your assist yet again!

I wonder why X was special and worked without doing the loadfix first. 

Anyway, as far as exodos is concerned this one can be closed, up to you guys if there is anything else worth investigating

**Comment by interloper98** [comment]
Glad to help, @Python-Exoproject.

> I wonder why X was special and worked without doing the loadfix first.

The difference in X is that they've permanently eliminated that little bit of front memory padding that the `loadfix /f` is releasing in Staging. 

I'm not sure if this decision has hurt compatibility for X in anyway.. perhaps Staging could also knock out it out for good.  I guess we'll see how many more games benefit from an initial `loadfix /f` and decide from there.  (The fear is that we'd have new regressions if we knock it out).

Given even _real_ MS-DOS and DR-DOS failed to startup, I'd say this is a 'DOSBox bonus' compatibility feature for these extra stubborn games :-)

**Comment by johnnovak** [comment]
@interloper98 I'd say it's too risky to do what X did for a handful of games. Great that you found this trick, though 👍🏻 We just need to add this tip to the list of problematic games on the wiki.

**Comment by Grounded0** [comment]
@MasterO2 

Can you add this to Wiki? Thanks:

https://github.com/dosbox-staging/dosbox-staging/issues/3511#issuecomment-2198816853

**Comment by rderooy** [comment]
X has the problem that there are quite a lot of games that **require** loadfix due to this difference.

**Comment by johnnovak** [comment]
> X has the problem that there are quite a lot of games that **require** loadfix due to this difference.

That valuable info @rderooy. That makes this change highly undesirable, and I wonder why Jon did it.

**Comment by joncampbell123** [comment]
DOSBox-X didn't "knock it out", it was replaced by "minimum mcb free" and "minimum mcb size" settings to control how low the first MCB block is and how low the first free block is. It does the same thing. Then the defaults were set to mimic the typical DOS system of the day that had around 590K to 608K of free memory assuming no memory hungry TSRs were loaded first.

**Comment by johnnovak** [comment]
Thanks @joncampbell123. It's good know about the existence of these options. Maybe you meant @rderooy that with the default "minimum mcb free" and "minimum mcb segment" values in X more games needs `LOADFIX` compared to other DOSBoxes?

In any case, running games with the minimum fuss is the no.1 goal for Staging, and demoscene prods on a best-effort basis. Breaking existing configs (especially eXoDOS) with imposing different `LOADFIX` requirements on games is also a non-starter for us, regardless whether we would be closer to DOS with those changes. I'd argue the memory layout is quite different anyway because you don't need to load various drivers in Staging that would eat up the base mem.

**Comment by interloper98** [comment]
> DOSBox-X didn't "knock it out", it was replaced by "minimum mcb free" and "minimum mcb segment"

Thanks for explaining this @joncampbell123; yes - it's the first `tempmcb` that no longer exists in DOSBox-X and why I said it was knocked out:

![dos_setupmemory_compare_staging_to_x](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/69e597b0-296e-42c1-b6a8-6261280b3bd4)

Indeed, like you said, those two `tempmcb`s are now a single more flexible MCB in DOSBox-X.

> If something actually does need more base memory,

Surprisingly this game doesn't need much memory. It happily runs fine even with 500 KB free. What seems very important to it eliminating (or zero'ing) one of those two MCBs after the dummy device (which is why the initial `LOADFIX /f`).

Maybe the game is scanning the actual MCB data structures or something? I'm not sure :-)
