### ISSUE TITLE
GOG DOS menus messed up. Thank god we have dosbox-x

### ISSUE THREAD

**Issue by Erick-BR** [dosbox-staging/dosbox-staging#3514]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 8

### Whats your question and how can we help?

Same nazi position on my case as on issue 3027 that I didn't know.

If any program called an emulator cannot reproduce the behavior of the system it claims to emulate, this program can be called anything other than an emulator.

Changing the file's encoding means making it compatible only with staging, but there is a better solution, which is dosbox-x. If I had any doubts about which one to use, I no longer have them.

The community doesn't have to ask GOG to change anything. They already do exceptional work to preserve old games. You are the ones who need to have more humility and stop being arrogant. You can ban me I don't care,

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
> If any program called an emulator cannot reproduce the behavior of the system it claims to emulate, this program can be called anything other than an emulator.

We emulate DOS, not GOG config files.  There are no regressions in the emulation side relating to this.  DOS bat files continue to to work with extended ASCII as they were before.

The compatibility break you mentioned is cosmetic only and we gave you two easy ways to work around it.  You can either run a script, copy the menu to a DOS bat file, or use another Dosbox fork.  Our position on this is not going to change because you want to act like a child and call us names.

**Comment by Grounded0** [comment]
![image](https://github.com/dosbox-staging/dosbox-staging/assets/48192273/4cacfd37-5fca-4761-9f9a-1d3b7e68eeb5)

**Comment by johnnovak** [comment]
It was tempting to hit delete on this gem of a ticket, but decided to keep it due to @weirddan455's level headed response, to document what kind of entitled behaviour we periodically have deal with, and for comical value.

To sum it up:

- Four different people, three of them core members, helped the guy to resolve his issue raised in  https://github.com/dosbox-staging/dosbox-staging/issues/3513.  We provided multiple solutions to solve the problem, all within 24 hours of raising the ticket.
- One of the solutions could mass-convert all his GOG game configs, yet he chooses to ignore this fact and go off on weird tangents.
- The guy evidently has comprehension problems; he does not seem to grasp the finer details of the issue as evidenced by his above rant.
- Finally, after all this, he call us nazis and arrogant, violating our code of conduct which he agreed to.

What a way to start one's carreer on GitHub! 😆

**Comment by johnnovak** [comment]
Screenshot for posterity:

<img width="1015" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/ec163a3a-56cf-4e6a-8b84-efd999ef1ada">
