### ISSUE TITLE
Why 0.81.0 release still declare version as 0.81.0-rc1 in meson build?

### ISSUE THREAD

**Issue by runlevel5** [dosbox-staging/dosbox-staging#3521]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.81.0 branch

### What Operating System are you using?

Linux ppc64le

### Whats your question and how can we help?

The version in `meson.build` is still `0.81.0-rc1`. Should it be `0.81.0`?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Looks like something that could be fixed in 0.81.1.

**Comment by johnnovak** [comment]
It's a bit complicated how the version string gets compiled into the executable. It depends on many other things, not just the version in the Meson config. The TLDR is the version string that shows up in actual releases matters and in 0.81.0 that is correct (no -rc1 suffix).

You don't need to raise similar issues in the future @runlevel5  because when it's release time, I massage these things until the intended version shows up in the exe.

**Comment by romatthe** [comment]
Sorry for coming back to this silly issue @johnnovak, but I just compiled `dosbox-staging` from source at tag v0.81.0 (rev 4ee43d5fb260b1297cc832e7b4ed23a4be33a853) and I have to admit I'm also a little bit confused.

Booting up staging shows v0.81.0-rc1 at the startup screen:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/8373222/c782b3e4-858e-41cf-9a12-f4692b1be321)

`dosbox-staging --version` gives me a similar result:
```
$  ./result/bin/dosbox --version
dosbox-staging, version 0.81.0-rc1
```

And the README shows the following:
```
DOSBox (dosbox-staging) 0.81.0-alpha Manual
```

And finally there's some more confusion in `dosbox-staging.metainfo.xml`.
```xml
<releases>
    <release version="0.82.0-alpha" date="2023-12-20"/>
    <release version="0.81.0-rc1" date="2023-12-20"/>
    <release version="0.80.1" date="2023-01-06"/>
    <release version="0.80.0" date="2022-12-20"/>
    ...
<releases>
```

I know this all makes me look like a nitpicky jerk, but I primarily just wanted to make sure that I'm compiling the correct stable v0.81.0 release and not missing any hotfixes or anything.

Hope you don't mind me asking, I know you have better things to do than look at version tags.

**Comment by johnnovak** [comment]
@romatthe Version handling was overengineered and too fiddly previously. I've simplified most of it in this PR:
https://github.com/dosbox-staging/dosbox-staging/pull/3601

But that doesn't help you because that's 0.82.x material 😄 

We always ship binaries built by CI. You need to to execute the same commands locally as the Linux CI job, then all the versioning stuff will be correct. There's lots of hackery in the CI workflow to make it work... Good luck 😄 

You could try to use the same Docker image too, although probably not necessary.

Ignore `dosbox-staging.metainfo.xml`, that's just metadata; it's not used for building.

**Comment by romatthe** [comment]
Oh I see, I should have looked at the CI configuration before asking. It's indeed a little bit more complex than I thought 😄 Thanks for clarifying John!
