### ISSUE TITLE
Microsoft Flight Simulator (v1.0) (1982)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3563]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Graphics are stretched as per pic and console as per second pic. Works fine in ECE

![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/2e07f8cb-5ed0-4267-bc33-670fd0ca339b)
![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/612c33cb-fcfd-4691-a5cf-f173951af41a)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run game (I was using eXoDOS version)
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Can't reproduce with either 0.80.1, 0.81.0, 0.81.1, or `main`.

@Python-Exoproject can you please make sure you always test with our last public release or release candidate? You must have tested this with the old alpha that's currently in eXoDOS. You haven't provided the full logs either so we can see the version number at startup.

Config I'm using:

```ini
[dosbox]
machine = cga

[render]
glshader = sharp

[cpu]
cycles = 700

[autoexec]
boot floppy/FS105.IMG
```

Result:

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/e5256929-bfca-4bb1-8d94-373ec62abd98">

**Comment by Python-Exoproject** [comment]
@johnnovak I always check against every version of Staging from 80.1 through to 81.1 including 81.0a if I find issues

In this case you were close with your guess on aspect though. It wasnt in the conf which was pretty all on defaults except for cycles and cga (which is why I didnt list it, nothing worth noting) but it was being added in an exodos run.bat on the command line as "ASPECT=FALSE". Sure enough once you raised that possibility and I found that line and removed it the image corrected to what you displayed. Is there a nutshell quick way to explain why Staging stretches the image when Aspect=false vs ECE which doesnt do that?

I still think it may be worth considering if this is the correct image for the game though. The images I found online generally have rounded instruments vs the more oval ones when ASPECT=TRUE. As ASPECT=FALSE give that stretched image in Staging I cant use it to show the difference, but using ECE here are the two shots:

Aspect true
![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/670b23c2-b733-4c4c-8e78-a91fde452260)

Aspect false
![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/b5033341-0d58-4ff9-8ed7-8253993381a4)

**Comment by interloper98** [comment]
Who has photos of MS FS 1.0 running on period correct PC and monitor?

Moby has [screenshots](https://www.mobygames.com/game/4003/microsoft-flight-simulator-v10/screenshots/), but they don't show monitor bezel (so probably from dosbox) and show both circular and oval representations.  

For what it's worth, here's circa-1984 FS 2 running on a real PCjr:

![112MSFS](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/d1073ca2-626f-47fd-8861-6bad22a3f6aa)

![106MSFS](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/16f2f7f1-d388-4f42-955e-82fae6bf6593)

![107MSFS](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/8398eafc-6f8e-4eb5-944a-a754ce85b2ff)

https://www.techrepublic.com/pictures/dinosaur-sighting-microsoft-flight-simulator-for-the-ibm-pc-jr/

**Comment by johnnovak** [comment]
@Python-Exoproject Thanks for confirming your testing method, all good 👍🏻 Yes I was suspecting it must be `aspect = false`, but I fixed lots of aspect bugs since that alpha eXoDOS uses now, hence I thought of that as a possibility.

`aspect = false` now treats pixels as squares in Staging. In other DOSBoxes, modes like 640x200 were still height-doubled, so you got 1:2 pixel aspect ratio instead of 1:1. But then for say 320x200 or 640x480 `aspect = false` resulted in 1:1 PAR. It was messy, inconsistent, and rather arbitrary...

`aspect = false` or `aspect = off` or `square` now always give you square 1:1 PAR pixels in Staging, no matter what. No weird 1:2 PAR only for some modes.

In modes that don't have 1:1 PAR, the mathematical circle algorithm gives you ovals. To draw a circle in a drawing program for non 1:1 PAR modes, the program has to generate a pre-compensated oval, slightly squashed in the other direction.

Deluxe Paint IIe for DOS for example had an option for this. By default, the circle tool gave you the "mathemathically correct" circle algorithm. In 1:1 PAR modes such as 640x480, that gave you a perfect circle. In say 320x200, however, which is a 1:1.2 PAR mode, it gave you a vertically 20% stretched oval! By enabling the "Make square" option, the circle tool draw a vertically pre-squashed oval appropriate for the 320x200 modes 1:1.2 PAR so the end result 
appeared as a circle.

That's all good and well, but this was 1982 before Deluxe Paint, and even until tgen end of the 90s, many people don't gave a shit. There are ovals everywhete in games for objects that appear as circles in real life. Oval spped dials, oval suns, oval clocks, etc. Some artists just didn't give a shit 🤷🏻 One simply cannot rely on circles to reason about the "correct" aspect ratio most of the time.

640x200 CGA mode is stretched to fully cover the screen of a 4:3 CRT monitor. The stretched oval look is most definitely how it looks on hardware. Also, the Mobygames screenshot are almost always in the wrong aspect ratio, nobody should rely on those. People repeatedly told them about this and they don't give a fuck...

Having said all that, you can set a custom stretch factor in `viewport = relative` if that's what you desire. I put some examples into the Getting Started guide and the 0.81.0 notes.

**Comment by johnnovak** [comment]
Illustrating the "Square aspect" option Deluxe Paint when drawing circles in CGA 640x200 2-colour graphics mode which has 1:2.4 pixel aspect ratio. 

<img width="1072" alt="Screenshot 2024-04-05 at 10 17 13 am" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/f27334c7-37d0-4915-bd48-e90ba56dde17">
