### ISSUE TITLE
Something weird with mounting in newest builds

### ISSUE THREAD

**Issue by SmilingSpectre** [dosbox-staging/dosbox-staging#3616]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Always.

### Steps to reproduce the behaviour.

I use eXoDOS. During run of the game it runs DOSBox with specific config. And this config always mounts game dir. Staging works with that the same way as each other DOSBox. But latest versions behave strange after autorun section finishes.

Example: 688 Attack Sub (1989). It sets for Staging 0.80.1 right now. I left only mounting part in the autoexec section.

```
[autoexec]
@echo off
mount c .\eXoDOS\688Attac\
c:
```

Results:

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/cfb0b955-6356-4fad-9a7d-f286575c90d5)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/16ee1078-b9a3-459d-8822-a8dce1e64abd)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/8f0cd8e9-17bd-4f05-984e-94803c966166)

It's the right results which I expected.

Now the same with Staging 0.81.0:

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/9b961f0f-99ed-4cd1-ad8c-4670d5b85803)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/c0b55aeb-761e-4c69-a0da-dec72cde35d5)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/923cf273-7c4d-45cd-a48a-7b375dcc496a)

It isn't right dir. It's m:\eXoDOS\eXo, two levels up of supposed C:

It is always the same result, regardless of what dirs are mounted in [autoexec] section.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I need some way to reproduce this.  Does it work correctly if you type the mount command in manually or is it only from the autoexec?

The log in your screenshot also appears to be incomplete.  The mount command logs some useful information to the console when it is invoked but your logs just stop after the first few lines.  There should be many more lines of init stuff happening followed by the mount  command getting executed.

**Comment by SmilingSpectre** [comment]
1. No, I cannot mount dir manually if I remove both custom .conf altogether. Because somehow Staging already mounted the same C as above `m:\exodos\exo`. There is no any mounting commands in-between, or in the only remained default config (I literally deleted it, to be sure, and it was created automatically)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/311eb93b-081b-4a55-a226-be5bc5023eb8)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/8421b49a-d1ba-400c-9d3b-2b24038ad0f2)

2. You can see the running command. It's from eXoDOS `launch.bat` which resides in the `util` dir.

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/ebf158b6-aa55-4756-87f0-6fe123be5e31)

If it's important, `launch.bat` itself called from inside `exodos\!dos\[gamenam]\[gamename.bat]` file, like this:

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/9f12fe26-53d5-454e-bfe6-2cee0030ab48)

Command inside `[gamename.bat]` is always the same, and is `.\util\launch.bat`

3. Most weird fact is that mounting works, while it's inside [autoexec] section. It's mounted and run the needed files. But when it ends, C appears in totally wrong place.

4. Sidetracking issue (sorry for that). Default config has no language set. When I run Staging without any parameters, it shown in Russian (my system language). But here, as you can see, it detects "fa" language.

5. Yes, I seen the logging if I run the Staging separately. But this is all I see if I run in the eXoDOS, for all Staging versions here (0.80.1, 0.81.0a, 0.81.0). Maybe I can activate the better log manually, in conf?

**Comment by SmilingSpectre** [comment]
Wait, it's "- noconsole" key. Ok, I removed it.

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/e7b0accf-dc6d-4855-b2cb-8630d240c200)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/0f0d615b-741c-41cd-8553-dec7aba978f1)

**Comment by SmilingSpectre** [comment]
Wait, it's exactly the last command. It isn't here while autoexec still works.

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/f348ecd3-0133-4c34-ad5e-002c6530cf45)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/be2216be-d0b5-4bff-b8aa-950ae0112154)

**Comment by weirddan455** [comment]
>  No, I cannot mount dir manually if I remove both custom .conf altogether. Because somehow Staging already mounted the same C as above m:\exodos\exo.

Let's start here because I think this is your root cause.  You're saying that with no .conf files being loaded, your C drive is being mounted automatically?

Can you please run Staging outside of exodos using that directory as your current working directory to confirm?  Run this from the Windows command prompt.

```
cd m:\exodos\exo
"C:\Program Files\DOSBox Staging\dosbox.exe --noprimaryconf
```
Substitute with your real path to the DOSBox Staging .exe.  I'm not actually sure where the default install location is but it's probably something like that.

**Comment by johnnovak** [comment]
Ok, so holding off creating the 0.81.1 build until we have a better understanding of this @weirddan455, as we might need to backport a fix.

**Comment by SmilingSpectre** [comment]
Tried. Worked.

Moreover, it worked even if I tried to model it with direct calling, without eXo's bat juggling. Huh.

Moreover, it now works even with eXo's bat! ??

Analyzed original bat and what I modified, and found the issue. It's non-working keyword! (-nomenu in our case).

Any given key to 0.81.0 and up, if it doesn't supported, results in mounting the current dir as C.

Here what I have for "-abracadabra" key, for example.

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/4ae468e6-e88d-461f-a72e-e3b2d3a83a71)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/cdeef0d0-99b4-4b72-b76f-669bc2a0d7c5)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/24454178/40a40726-23aa-4d33-92e8-8a73d29c2f7b)

**Comment by weirddan455** [comment]
>  Any given key to 0.81.0 and up, if it doesn't supported, results in mounting the current dir as C.

Nice job narrowing the problem down @SmilingSpectre  That's a very strange bug indeed.  I can reproduce it on my machine now and I'll work on a fix.

**Comment by weirddan455** [comment]
Well maybe I should defer to @FeralChild64 because I don't know what the behavior is supposed to be exactly (probably not this though).  I didn't do a full bisect but I did confirm it is a regression from 0.80.1.  The mount command gets added to autoexec here and he was the last person to touch this part of the code.

https://github.com/dosbox-staging/dosbox-staging/blob/9865c936d0e980e981653d355128756233ed427c/src/shell/autoexec.cpp#L398-L404

I think it's supposed to be so the user can supply a DOS .exe as an argument.  In that case, mount current directory as C and execute.

I could probably hack in something to not do this behavior if the argument starts with a dash but maybe there's a better way to go about this?

**Comment by FeralChild64** [comment]
Unfortunately, I have no idea how this drive auto-mounting / command line switches are intended to work - IMHO this was a bad idea from the start (in general, I don't like computers trying to be too smart), and, if you ask me, it should have been purged completely long time ago. I have touched this code mainly because I wanted a nicely structured `Z:\AUTOEXEC.BAT`, with UTF-8 support in the `[autoexec]` section of the configuration file.

@SmilingSpectre Could you show us the content of your `Z:\AUTOEXEC.BAT`? Either type `MORE Z:\AUTOEXEC.BAT` and paste the screenshot, or copy the file somewhere and paste the content. This should give us some hints where this `M:` drive came from.

Regarding your side-problem (locale detection) - I'm currently reworking this code, but this is still going to take quite some time.

**Comment by weirddan455** [comment]
@FeralChild64 I believe `m:\exodos\exo` is @SmilingSpectre 's current working directory on the host.  There was a mount command in `[autoexec]` to mount the DOS C drive.  At the same time, DOSBox was being launched with an invalid argument `-nomenu` (not sure if this used to be valid in a previous version and was removed but it's not all that relevant).

@SmilingSpectre 's problem is that the invalid argument caused the C drive that was mounted in `[autoexec]` to become unmounted and replaced by the current working directory.  Removing the invalid argument has resolved the problem I believe.

On our side, this is a regression because (IMO) we shouldn't be fussing with the user's C drive if they pass in an invalid argument and this behavior does not occur in 0.80.1.

**Comment by weirddan455** [comment]
To be clear, the repro case is very simple.  Launch `dosbox --foo`.  Your current working directory will be mounted as C (regardless of mount commands in `[autoexec]`) and it will try to run the command `--foo` in DOS.

We had a lengthy discussion about this auto-mounting behavior in the past which I had mostly forgotten about until now:  https://github.com/dosbox-staging/dosbox-staging/issues/2987 (issue) and https://github.com/dosbox-staging/dosbox-staging/pull/3007 (PR)

Perhaps the solution should be simply check if the argument is a file on the host?  If it's not a file, don't do the mount + execute.

**Comment by FeralChild64** [comment]
Yes, mounting current directory as C: in this case was implemented on purpose.

> Perhaps the solution should be simply check if the argument is a file on the host?

That wouldn't be trivial and could be risky. After `dosbox "foo param"` executed, we would need to extract `foo`, than check for `foo.com`, `foo.exe`, `foo.bat`, and we shouldn't forget about case-insensitivity of DOS file names. Commands like `dosbox "more file.txt"` or `dosbox "%PLAYER% file.mod"` (with `PLAYER` variable defined in `[autoexec]` section and pointing to some utility on drive D:) would stop working.

How about ignoring files/commands starting from `-` and logging a warning about incorrect switch? This would be easy to implement and probably low risk.

**Comment by johnnovak** [comment]
> To be clear, the repro case is very simple. Launch `dosbox --foo`. Your current working directory will be mounted as C (regardless of mount commands in `[autoexec]`) and it will try to run the command `--foo` in DOS.

That's quite bad.

> How about ignoring files/commands starting from `-` and logging a warning about incorrect switch? This would be easy to implement and probably low risk.

That seems to be the way to go. Low risk and gets the job done. And people who want to run DOS executables starting with a dash in their name should get a life 😎 

I have no love for automounting when someone executes `dosbox BLAH.EXE` but it seems like it's one of those legacy features that far too many people and gamepacks might rely on. We should just keep it working.

**Comment by Burrito78** [comment]
`-nomenu` is a DOSBox-X feature, btw. "Starts DOSBox-X without showing its GUI menu".
