### ISSUE TITLE
How to make a game run in slow motion?

### ISSUE THREAD

**Issue by sabudum** [dosbox-staging/dosbox-staging#3623]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

I am trying to make a game run in slow motion in order to make it easier to play, the game in question is Constructor, 1997 game by Acclaim.
I tried changing the cycles to a low value and also changing dos_rate to a low value.
The game runs with worst performance, but it's actual speed does not change.
In Constructor, there is a 'days' counter on the top of the screen, each game day takes one real life second to pass.
By changing the emulation speed, I'd expect the in-game days to take longer, but they still pass at one real-life second each.

Instead of changing the game speed, the game just runs with a worst performance, and skips frames.
In my .conf file, frameksip is set to 0 (zero)

Is there another way to try and slow down the actual game speed?

I can increase the speed by pressing Alt+F12 (Unlock Speed), but not decrease it.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@sabudum We don't support running games slower than realtime. I don't think we will ever support such a feature as it could cause timing related issues.

Maybe you can control the game speed in some game menu like in SimCity.

Of course, if this is an emulation issue and the game runs much faster in Staging than on real hardware, you should raise a bug report. But as this is a 1997 game, such speed issues are unlikely.

**Comment by Jkapp76** [comment]
I've achieved slowdown just by lowering the cycles until the game is slow on a few games. I beat the rock n sock robots on space quest 3 this way...

**Comment by johnnovak** [comment]
> I've achieved slowdown just by lowering the cycles until the game is slow on a few games. I beat the rock n sock robots on space quest 3 this way...

Yeah, that's always an option when it works.

**Comment by sabudum** [comment]
Well, thanks for nothing I guess, every emulator has this feature, it's a shame this one can't have it.

**Comment by johnnovak** [comment]
> Well, thanks for nothing I guess, every emulator has this feature, it's a shame this one can't have it.

You're quite wrong as that's not true that "every emulator has it", but here's your money back:



😎

**Comment by weirddan455** [comment]
>  I've achieved slowdown just by lowering the cycles until the game is slow on a few games. I beat the rock n sock robots on space quest 3 this way...

It depends on how the game is programmed.  Space Quest 3 and other games of the era run too quickly on fast hardware because they advance the game state at a set amount per frame.  In some parts, it becomes impossible to complete unless you are able to slow the computer down.

Newer games started using delta time where they advance state based on the wall clock and older hardware will drop frames rather than run slower.

>  I am trying to make a game run in slow motion in order to make it easier to play, the game in question is Constructor, 1997 game by Acclaim.

If you're gonna be a dick then:  Skill issue.  Get good scrub.  :sunglasses:

**Comment by Burrito78** [comment]
@sabudum I'm very sorry to hear that you 

> Well, thanks for nothing I guess, every emulator has this feature, it's a shame this one can't have it.

Dear Valued Customer,
Thank you so much for taking the time to share your feedback with us. We truly appreciate your insights, as they help us strive for excellence.
We understand that the feature you mentioned is indeed common in many emulators and we sincerely apologize for any inconvenience caused by its absence in our software. Your satisfaction is our top priority and we are genuinely sorry if we fell short of your expectations this time.
We are constantly working on improving our software and your feedback has been noted with utmost importance. We will certainly consider your suggestion for inclusion in our future updates.
Once again, we deeply appreciate your patience and understanding. Please feel free to reach out to us if you have any more suggestions or concerns. We are always here to listen and assist you.
Best Regards, Your Software Team

**Comment by Burrito78** [comment]
On a serious note, try out Cheat Engine: https://www.cheatengine.org/index.php
The file you need for Constructor can be found here: https://fearlessrevolution.com/viewtopic.php?t=11543

Cheats are here: https://www.cheatbook.de/files/constructor.htm
