### ISSUE TITLE
Dunkle Schatten 2 freezes dosbox

### ISSUE THREAD

**Issue by Max833** [dosbox-staging/dosbox-staging#3668]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.1

### What Operating System are you using?

Windows 10

### Relevant hardware info

i73770k, GTX 1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The **_free advertising adventure_**  "Dunkle Schatten 2" freezes as soon as you try to start it. It works with dosbox 0.74-3.

Download: http://www.mediafire.com/download/z1z9zd139hqd235/Dunkle+Schatten+2.7z

### Steps to reproduce the behaviour.

Explain how to reproduce
1.
mount c ..\SCHATTEN2
C:
DS2.BAT

2. dosbox-staging freezes

### Your configuration

```ini
Default 0.81.1 settings
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by codengine** [comment]
It also crashes in DosBox-X, DosBox ECE works normally. It doesn't matter if DOS32A is used or not.

**Comment by codengine** [comment]
I just checked the versions and Dunkle Schatten 2 stopped working since 0.79.

**Comment by codengine** [comment]
A little bit more details:
Several years ago, the game was already troublesome. One had to use DOS32A to run it. One of the users mentioned that turning off the sound also works, and given that there was a major overhaul of the sound system in 0.79, I suspect it could be related to that.

But thats just digging in the dark.

**Comment by codengine** [comment]
More Info: With MS-DOS 6.22 installed within DosBox and booting from it, the game works just fine.

**Comment by weirddan455** [comment]
I've found 3 different regressions here.

1.  Change to automount behavior.  Can be worked around by setting `automount = false` in the config  first bad commit: 78ff04630f92ef93a5d3508916cf49cf77026335 - Auto-mount drives before parsing executable commands
2. Batchfile change.  Can be worked around by launching `engine.exe` directly.  first bad commit: 039532b95b04da2538a9ff806d9bef7193c1c14f - Use ByteReader in BatchFile
3. Something else causing a hang a bit further along in `main`.  About to do a 3rd bisect.

**Comment by weirddan455** [comment]
I've got a fix for the last regression.  It was just a leaked file handle that took me longer than it should have to find :man_facepalming:

**Comment by weirddan455** [comment]
The first regression is weird.  I must have messed up the bisect because it actually started when the automount feature was introduced.  Updated by comment above to reflect the real commit it broke.

However, there's nothing wrong with automount itself.  Rather, I'm able to trigger the bug by redirecting output to `NUL` which is done by automount to hide the output of the mount command.

Ex.  Type `echo foo > NULL` before you launch the game and it hangs.  Very weird.

**Comment by codengine** [comment]
Thanks for the quick support. I don't know if the game works properly without the batch file because it seems to use some kind of VM and the _RUNVM.VMC file has some kind of VM parameters. Of course, one could just do that manually.

**Comment by weirddan455** [comment]
Regressions have been fixed.  The game now launches and gets past the first couple of screens but still freezes at a later point.  The device chain is getting corrupted.  It works like a linked list and when it reads in the bad pointer ends up spinning forever in this loop:

https://github.com/dosbox-staging/dosbox-staging/blob/ffea16b2a60dbcb545654246e1d67d7af9eb55aa/src/dos/dos_devices.cpp#L238-L257

There's probably something we're not doing correctly either in file handling code or in managing this device chain that will need to be fixed to solve the root cause.

**Comment by weirddan455** [comment]
I missed where you said it worked on dosbox 0.74-3 so I went back to ancient history and bisected from there.  There is still in fact a regression.

First bad commit is 598de870fd6654bd8478b1e53afdc75e9372d272 - Support WFW networking from internal DOS shell

Before that commit, the game seems to work fine.
