### ISSUE TITLE
Screen corruption in 0.81.0 and 0.81.1 when exiting "Teddybear's Revenge" demo by Eclipse

### ISSUE THREAD

**Issue by PoulpSquad** [dosbox-staging/dosbox-staging#3723]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

i7 7700K, 32GB RAM, GTX 1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When demo ends or user quits, screen is corrupted as shown in the following screenshot:

![image0001](https://github.com/dosbox-staging/dosbox-staging/assets/91291669/703195da-7d24-4995-897d-0e2e41f11707)

Other machine= settings are not affected.

This also occurs with 0.81.0, but not on 0.80.1 nor 0.80.0.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run demo
2. Wait for demo to end or press ESC
3.

### Download URL of affected game or software

https://files.scene.org/get/parties/1996/saturne96a/in64/e_teddy2.zip

### Your configuration

```ini
[dosbox]
machine=svga_s3

[autoexec]
mount c f:\emus\dosbox\c -t dir
c:
cd e_teddy2
teddy.exe
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@PoulpSquad Does it work with `vga_render_per_scanline = on`?

**Comment by PoulpSquad** [comment]
Negative. Same screen corruption with vga_render_per_scanline = on (default value in .conf is vga_render_per_scanline = true by the way).

**Comment by johnnovak** [comment]
> Negative. Same screen corruption with vga_render_per_scanline = on (default value in .conf is vga_render_per_scanline = true by the way).

Thanks. Seems like a low-priority regression, but it might point to something more interesting.

**Comment by PoulpSquad** [comment]
Thank you for looking into this!

**Comment by johnnovak** [comment]
> Thank you for looking into this!

I'm not, but someone will maybe later ;)

**Comment by weirddan455** [comment]
First bad commit is 5f52fadaffc02457356f94c81ade05a3a77c27e0

**Comment by johnnovak** [comment]
> First bad commit is [5f52fad](https://github.com/dosbox-staging/dosbox-staging/commit/5f52fadaffc02457356f94c81ade05a3a77c27e0)
> 
> That one is (mostly) just a revert of [97f73bf](https://github.com/dosbox-staging/dosbox-staging/commit/97f73bf8c6737478837e273e38a5e5fcbe497c8a) though. This commit is good but [03ca658](https://github.com/dosbox-staging/dosbox-staging/commit/03ca6582bfa3094c7fbb92c1a8a0dadb8a65496e) (commit immediately prior) is bad.
> 
> I'll try another bisect starting from there.

Lol, we'll be patching up this crap well into 2026 😄 Careful with those bisects because I've been changing things back and forth this year too, as far as I can remember. So the bisect might give you misleading results as this could have been fixed, then broken, then fixed, then broken multiple times potentially...

**Comment by weirddan455** [comment]
Haha yeah that VGA code is tricky

I think b68b66f07831c91f197acf0b06f847c28c9a7946 may be the root cause.

**Comment by weirddan455** [comment]
Confirmed this patch fixes it on main.  Probably not what we want to do as the "half frame period" thing is needed for some games.  I remember running into issues with that commit before though.  I'll have to dig through my old PRs to see what I did in the past.

```
diff --git a/src/hardware/vga.cpp b/src/hardware/vga.cpp
index 742a4bc0f..2b34575ad 100644
--- a/src/hardware/vga.cpp
+++ b/src/hardware/vga.cpp
@@ -208,7 +208,7 @@ void VGA_StartResize()
                                                min_frame_period_ms,
                                                max_frame_period_ms) / 2;
 
-       VGA_StartResizeAfter(static_cast<int16_t>(half_frame_period_ms));
+       VGA_StartResizeAfter(50);
 }
 
 void VGA_StartResizeAfter(const uint16_t delay_ms)
```

**Comment by johnnovak** [comment]
Is this a real mode demo? Try different cycles setting, maybe that makes problem go away.

**Comment by PoulpSquad** [comment]
I tried different cores and cycles without any luck :(

**Comment by MasterO2** [comment]
@PoulpSquad, just so you know, on the subject of the `MODE` command: https://github.com/dosbox-staging/dosbox-staging/issues/3670

**Comment by PoulpSquad** [comment]
Thank you MasterO2. I didn't know that!

25.COM works much more consistently than MODE.COM for this issue. It brings the screen back to normal 100% of the time.

The demo freezes if I try to run it again, though.

**Comment by interloper98** [comment]
Did some checking on this; giving it "era correct" Pentium cycles but a slow vmem setting does the job. It exits back to `C:\>` and you can re-launch without any problems.

(Maybe the demo guys still had a slower video card? Infact, the high vmem_delay actually lets it run smoother.. so tells me maybe their code expects this.)

```ini
[cpu]
cycles = 100000

[dosbox]
vmem_delay = 10000
dos_rate = 60  # optional, but very smooth for me
```

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/58ad476d-fcd1-4ac5-b404-a962f937cecf

@weirddan455 @johnnovak on possible issue though - if you drop `vmem_delay` to 8000, like this, then the latest CI Win64 build just instant-quits when I launch teddy2.exe, without any errors or logs:

```ini
[cpu]
cycles = 100000

[dosbox]
vmem_delay = 8000
```

**Comment by weirddan455** [comment]
>  Is this a real mode demo? Try different cycles setting, maybe that makes problem go away.

It's protected mode.

@interloper98 Good find with those settings.  I can reproduce both it working with first set of settings and the crash with the second.  I'm getting debug assert failures with the 2nd set so I think it's a divide by zero crash.

Back to the display corruption on exit, it looks to be a race condition of sorts and it's with DOS interrupts rather than the demo directly manipulating VGA registers (though it may also be doing that elsewhere).

On start, the demo calls `INT10_VideoState_Save` followed by `INT10_SetVideoMode` to mode 13h.

On exit, it calls `INT10_SetVideoMode` to 03h followed by `INT10_VideoState_Restore`.

With increased delay either by setting `VGA_StartResizeAfter` in C++ or by increasing `vmem_delay` in settings it works out to:

1. `INT10_SetVideoMode` - Schedules a resize to happen later
2. `INT10_VideoState_Restore`
3. `VGA_SetupDrawing` gets called after the delay

With default settings on `main`

1. `INT10_SetVideoMode` - Schedules a resize to happen later
2. `VGA_SetupDrawing` gets called after the delay
3. `INT10_VideoState_Restore`

**Comment by PoulpSquad** [comment]
Awesome. Much better solution than my abominable fix!

**Comment by MasterO2** [comment]
Now added to https://github.com/dosbox-staging/dosbox-staging/wiki/Preparing-games-to-run-with-batch-files#teddybears-revenge-by-eclipse-demoscene

**Comment by weirddan455** [comment]
After more debugging, I found the actual problem.  It's a single register that gets restored that has to do with hardware cursor.

https://github.com/dosbox-staging/dosbox-staging/blob/25182883f969c8ddaf62eb9ae7766956b785c831/src/hardware/vga_s3.cpp#L114-L118

Hardware cursor never actually gets enabled but it calls into this routine anyway that changes the `VGA_DrawLine` function from `draw_text_line_from_dac_palette` to `draw_unwrapped_line_from_dac_palette` and this is what causes text mode to be distorted.

This was simply hidden by the delay because `VGA_SetupDrawing` resets `VGA_DrawLine`.  This function seems wrong to me but I don't know enough about this to know 100%.  Have you worked with this at all @johnnovak ?

https://github.com/dosbox-staging/dosbox-staging/blob/25182883f969c8ddaf62eb9ae7766956b785c831/src/hardware/vga_draw.cpp#L1438-L1447

**Comment by weirddan455** [comment]
Well I came up with a patch in #3725

I think `VGA_ActivateHardwareCursor()` was simply never intended to be called while in text mode.  Added a check to the S3 write handler to see if the state of hardware cursor was actually changed before calling it.

**Comment by weirddan455** [comment]
As for the crash on start @interloper98 found... that's a hell of an edge case you found :wink: .  It's only reproducible for me if I also add the demo to my `[autoexec]`.  One of the first things the demo does is call `INT10_VideoState_Save`.  You've set the real mode cycles so high and also added a vmem delay so it's doing this before `VGA_SetupDrawing` had a chance to run for the first time.  Basically, the demo started running before the welcome screen could even be shown :wink: 

If you instead run use this config to only change protected mode cycles (on dev branch, new cycles settings aren't in 0.81.1) it's fine:

```
[cpu]
cpu_cycles_protected = 100000

[dosbox]
vmem_delay = 8000
```

If you set `vmem_delay = off` it's also fine (for some odd reason).  If you remove the demo from `[autoexec]` and manually run the demo it's fine since then VGA will have been fully initalized.

I don't know of a fix for that one.  If I remove the `VGA_SetupDrawing` in code, the DOSBox window never appears so that's not an option.  Maybe just... don't use those very specific settings on this specific demo.

**Comment by johnnovak** [comment]
That's some outstanding, gold medal worthy detective work at display there @weirddan455 🥳 🎉 🥇

The hardware cursor fix seems reasonable and logical to me. It's entirely possible when it was introduced (by kcgen I think), the bug was masked by some intricate deck of cards of conditions that included timings, then as we keep fixing other VFA issues, there is a slight change in the timings and the bug can manifest.

As for the super weird edge casey bug at startup, while I agree it's low priority and we should not rush fixing it now, it would be good to capture it in an issue ticket for later investigation. Being able to get anything to run before the welcome screen is shown, regardless of how specific the DOSBox settings are, seems very fishy and a major bug even if it's extremely hard to trigger).

@PoulpSquad would you be able to raise a new ticket for it?

**Comment by PoulpSquad** [comment]
I think so. I'll open it right away.
