### ISSUE TITLE
Upscaling shaders (xbr) broken with output=opengl?

### ISSUE THREAD

**Issue by pgzh** [dosbox-staging/dosbox-staging#3770]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Git

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

Ryzen 7 Pro 5750G with integrated graphics

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Upscaling shaders (xbr) create artifacts in dosbox-staging git.
The issue was not present in 0.81.1 and I noticed only when trying the latest git.
Obviously the openglnb output was deprecated lately and the xbr shaders produce artifacts with opengl output.
If I switch to output=opengl with 0.81.1, the xbr shaders create the same artifacts.

dosbox-staging git / output = opengl
![staging-git](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/8f404420-53ac-43b5-9bed-a97759f6f7ad)

dosbox-staging 0.81.1 / output = openglnb
![staging-0 81 1](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/e6ddcdf8-0296-4702-810a-5973757ae75e)

I understand the openglnb output was removed intentionally and there were good reasons for this.

So this is not a classic bug report, but a request for help.
Did I misconfigure something or what could I try to get the xbr shader work with output=opengl nicely?

Thanks a lot!

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set output=opengl in 0.81.1 and use xbr shader
2. Use git and xbr shader

### Your configuration

```ini
https://gist.github.com/pgzh/ca4bba5e52dbc312dc2de36892bdf722
```

### Provide a Log

```text
https://gist.github.com/pgzh/aed0b0b87d181d330ea38b9b7f068d44
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
## Summary 

Okay @pgzh, when [migrating the Tyrell's SVN shaders into Staging](https://github.com/dosbox-staging/dosbox-staging/pull/2137
), I made the following remark:

> My executive summary of the xbr shaders is that they look like crap; I can't imagine anyone wanting to use these...

So yeah, I have no love for them 😆 But it's also true I did not take the time to learn how they are supposed to be used as intended. I'm not against re-instating them with the proper intended look.

If you'd like to play around with the old SVN shaders, you can get them from here: 

https://github.com/tyrells/dosbox-svn-shaders/tree/master/xbr

It would be helpful if you posted screenshots showing the intended look for all 4 shaders using some sufficiently complex image (so not the DOS prompt, but maybe the static start screen of a game that features lots of pixel fonts).

## Investigation

It turns out, the intended look seems to be with nearest-neighbour interpolation, as you said.

- https://github.com/libretro/glsl-shaders/blob/master/xbr/xbr-lv2.glslp
- https://github.com/libretro/glsl-shaders/blob/master/xbr/xbr-lv2-3d.glslp
- https://github.com/libretro/glsl-shaders/blob/master/xbr/xbr-lv2-noblend.glslp
- https://github.com/libretro/glsl-shaders/blob/master/xbr/xbr-lv3.glslp

There is a README about their later Slang versions, but it's not overly helpful:
https://git.libretro.com/libretro-assets/slang-shaders/-/tree/3f49a3f1fb33ee246be0303eec7d3b72ca7b3f3c/xbr

So, I'm also quite certain these xbr shaders assume sRGB encoded pixel values as input (as they're quite old, so awareness of using correct gamma was even worse then than in current times), so these pragmas should _not_ be enabled in our variants of these shaders:

```c
#pragma use_srgb_texture
#pragma use_srgb_framebuffer
```

They also need the non-pixel doubled original input image to work correctly (see [here](https://github.com/dosbox-staging/dosbox-staging/issues/3520)):

```c
#pragma force_single_scan
#pragma force_no_pixel_doubling
```

So it looks like I'll need to introduce a `use_no_bilinear_filtering` pragma or something, then we'll need the following pragmas with these shaders:

```c
#pragma use_no_bilinear_filtering
#pragma force_single_scan
#pragma force_no_pixel_doubling
```

## Related tickets

- https://github.com/dosbox-staging/dosbox-staging/issues/3478
- https://github.com/dosbox-staging/dosbox-staging/issues/3520
- https://github.com/dosbox-staging/dosbox-staging/issues/3475

**Comment by pgzh** [comment]
Wow, that was a lot more feedback than I expected. Thanks a lot for that!

For some games I prefer these shaders' tendency to create a "smoother" image that has softer edges, rounder corners but without blurryness. The xbr shader does produce questionable results with text, but a lot of objects seem to have prettier shapes/outlines compared to advmame3x, which produces better results for text.
Even though it does not reproduce the original images accurately, to me it seems these shaders make a lot of games look what they may have looked if created with higher resolutions to begin with.
This is very hard to describe, I hope you get a rough idea what I mean.

Actually I prefer ScaleFX (from Retroarch) for many games, but that's a more complicated multi-pass shader that cannot work with dosbox-staging.
xbr comes close to its look, but it has its downsides...

Back to topic: I haven't found any noticable differences with how the xbr shaders look between 0.80.1 and 0.81.1.

Here's a comparison between the 'sharp' and 'xbr-lv2-noblend' shaders:

sharp:
![Fire_Ice_sharp](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/e4f39b55-6a77-4c9e-bec3-0db2cc236f17)

xbr-lv2-noblend:
![Fire_Ice_0 80 1](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/ad45caac-d578-45b9-89f6-01c1f5eb0c89)

With the latest git, the same image looks like this:
![Fire_Ice_git](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/6d8a7e6d-4110-485f-81f6-69a10ad60255)

There are differences between the variants of the xbr shaders, and the xbr-lv2-3d shader never seemed to work properly (for me).
I think I've always used the xbr-lv2-noblend variant which produces "best" (for me) results.

xbr-lv2-noblend:
![xbr-lv2-noblend](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/a9fcc227-8eaa-44c1-af90-8cbdd47da04f)

xbr-lv2:
![xbr-lv2](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/8fd95287-4630-4b85-9c6f-8aa9db773d6a)

xbr-lv3:
![xbr-lv3](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/1b2c8c09-90c2-456e-bdc5-ce8d0691ae86)

xbr-lv2-3d:
![xbr-lv2-3d](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/e68ce575-78d9-46ef-92cf-3bb6811ab6e6)

I created the screenshots with 0.80.1.

**Comment by pgzh** [comment]
Since @johnnovak removed the openglnb output (for reasons that were very understandable) and knowing your personal opinion about xbr, I am truly surprised to see the xbr scalers being shipped with dosbox by default now.
Thank you very much for doing a lot more than I hoped when I created this ticket!
I can confirm the issue is completely solved.

**Comment by johnnovak** [comment]
> Since @johnnovak removed the openglnb output (for reasons that were very understandable) and knowing your personal opinion about xbr, I am truly surprised to see the xbr scalers being shipped with dosbox by default now. Thank you very much for doing a lot more than I hoped when I created this ticket! I can confirm the issue is completely solved.

Enjoy man 😎 I have softened my stance on this; although I think they make pixelart look like rubbish, there is no harm in having the scalers as a tucked-away option. Some people like them and it was easy enough to restore them.

But you won't see me advertising them 😎 I appreciate the kind words, though; play these classic games however you prefer 😄
