### ISSUE TITLE
Runtime verbosity

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#379]
We log messages when the follow change:
- Mouse capture state
- Window focus state
- Window dimensions

For regular gamers, this information had little to do with their game or its content, so this logging feel excessive.  Also, when the debugger is run, these message mangle its text interface rendering it unusable:

![Screenshot at 2020-05-15 10-43-37](https://user-images.githubusercontent.com/1557255/82096587-2825c680-96b6-11ea-91ee-acac8762676e.png)

Some thoughts:
- We can comment these out
- Hide them behind some kind of `#DEBUG` ifdef
- Add verbosity levels (ie: `error`, `warning`, `info`, `verbose`, `debug`), and tag these messages with either the `verbose` or `debug` levels. We'd also add command-line handling to turn up or down the message verbosity.
- Other ideas?

**Comment by dreamer** [comment]
> We log messages when the follow change:
> 
>     * Mouse capture state
>     * Window focus state
>     * Window dimensions

I find Window dimensions to be very important, also when running as a user, but maybe we could make logs on entering/leaving fullscreen less verbose… I find it very useful because games can change the resolution themselves and it's not always clear what resolution is being used - and this affects pixel perfect mode and more advanced shaders (in my testing, some CRT shaders turned from cool-looking to unusable depending on window/screen/emulated resolution combination).

Window focus state is excessive, and I think we could safely change it from `LOG_MSG` to `DEBUG_LOG_MSG`.

Mouse capture state… I'm not sure. It's a bit excessive, but I think we still have some usability issues about mouse capture state; these logs help me personally whenever I get confused about mouse behaviour I did not expect - but maybe its a topic for another issue.

> Some thoughts:
> 
>     * We can comment these out

No, please.

>     * Hide them behind some kind of `#DEBUG` ifdef

This was my idea initially in the first iteration of `DEBUG_LOG_MSG` (the `DEBUG` define turned them on). I decided to back away from this, as it allows for weird scenarios in the code (like macro DEBUG and NDEBUG defined at the same time - it will confuse people).

For DEBUG_LOG_MSG I decided, that I'll only respect NDEBUG define and nothing else. We need to keep reminding users, that this macro should be defined for release builds, and excessive logs help in here. It's also easier to use day-to-day during development in my opinion. For development - excessive logs are not such a big deal.

>     * Add verbosity levels (ie: `error`, `warning`, `info`, `verbose`, `debug`), and tag these messages with either the `verbose` or `debug` levels. We'd also add command-line handling to turn up or down the message verbosity.

This is already implemented in dosbox code :/ And you can judge how "good" solution this is by the number of logs we encountered that utilize this… I don't know how to trigger logging of different `LOG_SEVERITIES` from user perspective, because the feature is of course completely undocumented… And whenever I see one of these (`LOG(LOG_MISC,LOG_WARN)("…");`) I cringe… and so does `clang-format`, as it gets confused about formatting these lines - they are broken in unexpected places (seen this several times e.g. in your recent PRs).

>     * Other ideas?

Yup. Out of various projects I've seen, I find solution implemented in Wine to be particularly good.

https://wiki.winehq.org/Wine_Developer%27s_Guide/Debug_Logging

It's pleasant to work with in code, it's easy to use as a programmer, it gives plethora of options to testers.

But, *please*, let's not rush into any particular solution here - let's spend some time investigating what would be good option for our use cases (which are similar, but not exactly the same as Wine).

In particular, logging on Windows is atrocious right now and I would like to get rid of stupid console window started automatically whenever user double-clicks on dosbox.exe (and get rid of `--noconsole` option as well and probably `sdl.waitonerror`). We *probably* should create a text log file (but this topic comes with its own set of design problems).

**Comment by Burrito78** [comment]
@kcgen Since we switched to Loguru and we have a ticket #1470 discussion log levels already i will close this.
