### ISSUE TITLE
Command & Conquer: Red Alert crashed

### ISSUE THREAD

**Issue by F0xMcloud** [dosbox-staging/dosbox-staging#3802]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging-windows-x64-0.82.0-alpha-bc5db

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

During installation program run fine, but when installation finished, program freeze.

If you run main program "RA.EXE", show green screen (not intro video or menu are shown) and after some time, emulator close.
Console didn't show none error, i am using default dosbox staging configuration, none tweak.
With previous developement builds (2 weeks ago) games was working fine.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install game
2. Wait to installation finished
3. Installer freeze when finished installation
4.  or run game manually after installation

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
This was one of those "fun" bisects where we had 2 regressions.  f46b5a731f94fcf8e5f9f3159f21871925cb0b33 by @interloper98  broke it to where it would get stuck at a black screen, although that commit has since been reverted on `main`.

Current regression is one of mine from the recent file changes.  First bad commit is f46b5a731f94fcf8e5f9f3159f21871925cb0b33 so I'll take a look.

**Comment by johnnovak** [comment]
Nice work @weirddan455 and @interloper98 🏅
