### ISSUE TITLE
VGA Paradise virtual VGA card gives build error exclusively on 64-bit MSVC release

### ISSUE THREAD

**Issue by Expack3** [dosbox-staging/dosbox-staging#388]
Checking on the progress of #381 , I tried building the 64-bit MSVC version of dosbox-staging with the given instructions. Building debug works fine, but for some reason, vga_paradise.cpp gives me this error upon attempted build: `Error	C5208	unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes	dosbox	D:\dosbox-staging\src\hardware\vga_paradise.cpp	26	
`
While I must admit I'm far from familiar with MSVC, I still find it odd this error only manifests when trying to build a release version.

**Comment by dreamer** [comment]
@Expack3 what version of Visual Studio are you using 2019? 2017? Older? MSVC installed differently?

**Comment by Expack3** [comment]
Visual Studio 2019, MSVC installed using the official Visual Studio Installer application.

**Comment by dreamer** [comment]
I'll reboot to Windows and retest later today - I believe I did verify 64-bit release build alongside debug configuration (because I was making performance comparisons of different options in release builds), but maybe I missed something…

It might be a result of MSVC going forward with C++20 compatibility (when compiling on Linux/macOS we explicitly limit standard to C++14, but on MSVC we had no reason to do it) - maybe there was a MSVC update over the last couple of days…

It seems like having an inline function in an anonymous struct is no longer a well-formed typedef. In this case it will be easy to make a fix to avoid this problem (by just turning typedef into normal struct declaration).

I'll prepare test fix later today.

**Comment by Expack3** [comment]
I found the problem blocking the build at the line mentioned in the error:

Instead of the following:
`typedef struct {
	Bitu PR0A;
	Bitu PR0B;
	Bitu PR1;
	Bitu PR2;
	Bitu PR3;
	Bitu PR4;
	Bitu PR5;

	inline bool locked() { return (PR5&7)!=5; }

	Bitu clockFreq[4];
	Bitu biosMode;
} SVGA_PVGA1A_DATA  ;`

I moved the typedef class definition to the top, since my limited experience with MS C# and C++ tells me that class names need to be in the same line (e.g. `string struct foo`):

`typedef struct SVGA_PVGA1A_DATA {
	Bitu PR0A;
	Bitu PR0B;
	Bitu PR1;
	Bitu PR2;
	Bitu PR3;
	Bitu PR4;
	Bitu PR5;

	inline bool locked() { return (PR5&7)!=5; }

	Bitu clockFreq[4];
	Bitu biosMode;
} ;`

It compiles, runs, and plays games, but I don't know if I've broken anything, nor do I own any games which would use the features of the VGA Paradise virtual VGA card.

**Comment by dreamer** [comment]
@Expack3 you definitely did not break anything with this :)

`typedef struct { … } name;` is old C idiom; native C++ way of writing the same is: `struct name {};`, which you did (with additional typedef in front, which is no longer needed).

If you would like to make a PR out of this, go ahead - otherwise, I will do it later today :)

**Comment by Expack3** [comment]
Pull request made: https://github.com/dosbox-staging/dosbox-staging/pull/389

**Comment by dreamer** [comment]
… and merged-in: 736d06eff1b7d4695a35311d70d7d0e61f5fa0bf Thanks! :)
