### ISSUE TITLE
Keyboard input isn't registered Rapberry Pi 5 / Bookworm

### ISSUE THREAD

**Issue by devarionarias** [dosbox-staging/dosbox-staging#3899]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Relevant hardware info

Raspberry Pi 5

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

After installing the snap and opening it, keyboard input isn't registered. Keyboard works fine after the application is terminated. It's a standard 105-key wireless keyboard being used over the USB 2 port. I've also tried a wired USB keyboard with the same result.

I'm using a Raspberry Pi 5 with Raspberry Pi OS (bookworm) lite x64.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install and update snap
2. Execute application
3. Try and type something

### Your configuration

```ini
Default
```

### Provide a Log

```text
N/A
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Asked the author to post here since this could be our issue:

- https://github.com/popey/dosbox-staging-snap/issues/15

**Comment by interloper98** [comment]
My Linux dev environment is on Raspiberry Pi OS (bookworm) aarch64, and keyboard input is OK. I'm not using snap packages though, just local builds.

**Comment by Grounded0** [comment]
Could you provide the log for us so we can have a better idea why keyboard isn't being recognised?

**Comment by devarionarias** [comment]
Yes, I will if possible. If an automatically created log is present, where would it be stored?

**Comment by weirddan455** [comment]
Correct me if I'm wrong but you said you're running Pi OS Lite which I take to mean no desktop environment.  There's a special mode that runs when you launch Staging from a text console with no X11/Wayland environment.  Input in this mode requires direct access to the files in /dev/input/ which usually means adding your user to the input group (or running as root but I wouldn't recommend that).

First of all check your permissions.  Add to input group and logout, log back in for it to take affect.  If that doesn't work, it may be blocked by the sandboxing that Snap provides so you'd need to try a regular build.

>  Yes, I will if possible. If an automatically created log is present, where would it be stored?

It doesn't log to file.  It only logs to the console but you can use a shell redirection if you like.  Ex:  `dosbox &> log.txt`

**Comment by devarionarias** [comment]
@weirddan455 Yes, that is correct. No desktop environment. I will give this a try when O am able. Thank you.

**Comment by devarionarias** [comment]
I was unable to get this to resolve and have decided I will try compiling locally instead. Thanks for your suggestions.

**Comment by weirddan455** [comment]
> We don't support weird "no desktop" Linux environments.

I mean, we do have code in sdlmain.cpp specifically for this feature.  It also logs a warning on permission issues with the input event files which is still what I suspect @devarionarias 's problem is.

This environment is apparently pretty common for the Raspberry Pi and it works the last I checked.  I don't know how we determine what "support" we give to some feature.  You could argue the Pi isn't supported at all since we don't ship Linux ARM binaries but it works and a lot of people use it :man_shrugging: 

https://github.com/dosbox-staging/dosbox-staging/blob/d9224f0c8249bbfde63967798fa18e72802990f4/src/gui/sdlmain.cpp#L1657-L1686

**Comment by interloper98** [comment]
> Yes, that is correct. No desktop environment. 

I just tested this using the Debian package from the bare console.  It seems to work fine straight away!

@weirddan455 -> thanks for that snippet. I checked that on my raspberry pi OS, and groups are setup properly. I'll mentioned this check to @devarionarias below.

@devarionarias, here's what I did. The steps were pretty easy, so hopefully you can confirm on your side too.

All steps are run directly on the bare console; no desktop involved.

1. Download and enter the source tree:

    **`git clone https://github.com/dosbox-staging/dosbox-staging`**
    
    **`cd dosbox-staging`**
   
1. Create a Debian package:

    Run **`./scripts/build-debian-package.sh`**.
    It will let you know if you need to install packages.
    The `.deb` file will be sitting **_outside_** your source dir (**`cd ..; ls`**)

    (Lazy approach!) or download and unzip my ARM64 `.deb` I just built [dosbox-staging_0.82.0~alpha-d9224-1_arm64.deb.zip](https://github.com/user-attachments/files/16852397/dosbox-staging_0.82.0.alpha-d9224-1_arm64.deb.zip)

1. Install the `.deb` package with apt:

    **`sudo apt install -y ./dosbox-staging_0.82.0~alpha-d9224-1_arm64.deb`**

1. Check that your account has access to the input devices:

   **`ls -1l /dev/input/*`**

    ```
    crw-rw---- 1 root input 13, 64 Aug 30 14:10 /dev/input/event0
    crw-rw---- 1 root input 13, 65 Aug 30 14:10 /dev/input/event1
    crw-rw---- 1 root input 13, 66 Aug 30 14:10 /dev/input/event2
    crw-rw---- 1 root input 13, 67 Aug 30 14:10 /dev/input/event3
    crw-rw---- 1 root input 13, 68 Aug 30 14:10 /dev/input/event4
    crw-rw---- 1 root input 13, 69 Aug 30 14:10 /dev/input/event5
    crw-rw---- 1 root input 13, 63 Aug 30 14:10 /dev/input/mice
    ```

    See the `'crw-rw- ... root input`` permissions for each file?

    The first `crw-` corresponds to the `root` _user_.
    The second rw-` corresponds to the `input` _group_. It lets everyone in the `input` group read and write to the devices.

    So just make sure your user account is part of that group. Run **`groups`** and look for the `input` group.

    My `pi` user is part of these groups: pi adm dialout cdrom sudo audio video plugdev games users input render netdev lpadmin gpio i2c spi, so I'm all good because I'm in the `input` group.

    If your user doesn't have access, @weirddan455 showed that DOSBox Staging will quit and give you instructions how to fix this (so carry on)!

1. Unset your `SDL_VIDEODRIVER` environment variable just to be sure it's not forcing the use of x11 or wayland.

    **`unset SDL_VIDEODRIVER`**

1. Edit your default settings to use a slightly lower resolution.

    **`dosbox --editconf`**

   Find the `windowresolution = ` setting and set it to `1280x720`. This will give you smoother frame rates in most games (on my system, 1080p is just too heavy for it).

1. Launch: **`dosbox`**. This should launch your Debian-installed package from `/usr/bin/dosbox`, and you should have working keyboard and mouse controls.

**Comment by devarionarias** [comment]
Wonderful! Thank you for the instructions @interloper98 . I'll give it a try.

**Comment by johnnovak** [comment]
> I mean, we do have code in sdlmain.cpp specifically for this feature. It also logs a warning on permission issues with the input event files which is still what I suspect @devarionarias 's problem is.
> 
> This environment is apparently pretty common for the Raspberry Pi and it works the last I checked. I don't know how we determine what "support" we give to some feature. You could argue the Pi isn't supported at all since we don't ship Linux ARM binaries but it works and a lot of people use it 🤷‍♂️

What is in the codebase is a bit immaterial in the sense of what we actively support. There's a lot of legacy weirdness and cruft there that we have been removing on sight when we encountered it. Those things were kinda "supported" until their eventual removal, in the sense that they "worked"... maybe, but we don't know for sure as nobody actively tested them, and nobody in the team was aware they existed.

Supported feature to me means the feature is available in our official release binaries out of the box, we actively test those features at least semi-regularly, and we fix them as a matter of priority when they regress.

It is exciting to add more features, but they every single new feature is a liability as well.

We haven't been officially supporting the RPi because we did not want to take on the extra liability that properly supporting the RPi involves. However, we've been "RPi friendly", but that's no different than being "weak hardware friendly" on any of our three officially supported platforms and having ARM support on Linux, which just works. Then the RetroPie folks have been recompiling Staging anyway and they changed the default settings to accomodate for the weak RPi hardware. I see this more like a partnership; we can accomodate their wishes when we can, but it's good to be able leave RetroPie support to them (hey, we're a small team; x86 desktop Linux is enough for us).

To me, this goes a bit beyond what we officially should support, but I'm open to different views. If such desktopless usage is common on Linux, and it's not to hard to keep it, and our Linux core team members are willing to officially support the feature (regularly test it, fix bugs, etc.), then I'm okay with that.

Still, that's not RPi support, but desktopless Linux support, which I'm actually more OK with as it's broader (and I'm not too thrilled to take on official RPi support; I'm happy to redirect those people to the RetroPie forums).

**Comment by interloper98** [comment]
> I'm not too thrilled to take on official RPi support; I'm happy to redirect those people to the RetroPie forums

> that's not RPi support, but desktopless Linux support Linux support, which I'm actually more OK with as it's broader.

@johnnovak - that's how I saw it, too. 

If someone's running RetroPie-bundled DOSBox binaries from RetroPie's frontend system (Emulation Station) -- OK, that's 100% a RetroPie support issue. 

But if @devarionarias wants to compile and run from the CLI, then sure - it's just basic Linux usage, and I can give it try on my side.
 - Linux -> Yes, supported.
 - Local build of `main`? Yes, supported.
 - Launched directly from command line without any frontend tomfoolery? -> Yes, I'm happy to test & help.
 - Using a supported SDL driver (kmsdrm)? -> Yes, SDL supports this, so I can try too (if it breaks or there are host driver issues? OK, it's beyond our scope).
