### ISSUE TITLE
Sync with SVN

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#3914]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Last sync with upstream I see is [Merge branch 'svn/trunk' into kc/merge-r4481](https://github.com/dosbox-staging/dosbox-staging/commit/dc449ac9714595ecd83f7f4b66df8e89326165c5)
- https://sourceforge.net/p/dosbox/code-0/4482/ Correct CMS sound pitch
- https://sourceforge.net/p/dosbox/code-0/4483/ saa1099 - Fix compilation in Visual Studio 2008
- https://sourceforge.net/p/dosbox/code-0/4484/ Fix wav capture glitches on buffer wrap around

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
- I've been using @johnnovak's audio test pack, and CMS sounds perfect.
- Visual Studio 2008 only supports up to the C++03 spec. It's not until Visual Studio 2019 where C++20 is supported, which is what DOSBox Staging using. 
- As per @johnnovak's audio test instructions, I've been testing WAV capture and it's perfect.

Based on these it makes sense that these are not synced (or are not applicable). I'll close it.

**Comment by johnnovak** [comment]
@Torinde can you please be more thorough when raising these suggestions? You could have figured out what @interloper98 said if you used Staging regularly. 

I assume you _do_ use Staging regularly, right? You're not just raising tickets without using our software, yes? We see little value in issue tickets raised based on "abstract" knowledge and superficial "research"...

These abstract tickets based on superficial "research" do not help; on the contrary, they use up our valuable time because we need to respond to them. **Please stop**, and find some other outlet if you're bored, or learn to code and do some actual work via code contributions to the project.

I sound irritated and that's on purpose because I am. We did tell you this numerous times, but you don't seem to get what our problem is with the majority of your tickets and contributions... We can Google things too; pasting a bunch of links and "stuff" based on superficial research is not help.

Sorry man, but **this gotta stop**.
