### ISSUE TITLE
Joshua & the Battle of Jericho (1994) - Invalid EGA video mode

### ISSUE THREAD

**Issue by einstein95** [dosbox-staging/dosbox-staging#3953]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.2

### What Operating System are you using?

macOS (Apple Silicon)

### If Other OS, please describe

macOS 14.6.1

### Relevant hardware info

Macbook Air M1 (2020)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Running the game in EGA mode freezes when starting, log says `INT10H: Trying to set invalid video mode: 13h`

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open dosbox-staging with `--machine ega`
2. Run `JOSHUA.EXE`
3. Game freezes on boot with music still playing

### Download URL of affected game or software

https://archive.org/download/msdos_Joshua_and_the_Battle_of_Jericho_1994/Joshua_and_the_Battle_of_Jericho_1994.zip

### Your configuration

```ini
Default config
```

### Provide a Log

```text
2024-09-24 09:40:15.741 | VGA: Pixel doubling enabled
2024-09-24 09:40:15.742 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
2024-09-24 09:40:15.760 | DISPLAY: EGA 640x350 16-colour text mode 03h at 59.702 Hz VFR, scaled to 1400x1050 pixels with 1:1.37143 (35:48) pixel aspect ratio
2024-09-24 09:40:15.760 | OPENGL: VSync state: off
2024-09-24 09:40:15.826 | MOUNT: Path '/opt/homebrew/Cellar/dosbox-staging/0.81.2/share/dosbox-staging/drives/y' found
2024-09-24 09:40:15.827 | MOUNT: Path '.' found
2024-09-24 09:40:16.100 | SB16: DSP was reset
2024-09-24 09:40:17.224 | INT10H: Trying to set invalid video mode: 13h
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@einstein95

This seems like a buggy game.

Mode 13h is not a valid EGA mode; it's only available on MCGA and VGA:
https://www.minuszerodegrees.net/video/bios_video_modes.htm

I cannot get the game to work on `machine = ega` in either DOSBoxSVN, DOSBox-X, or earlier versions of Staging.

DOSBox-X displays a janky flashing screen, all the others just hang at the loading screen. DOSBox-X result:

<img width="752" alt="image" src="https://github.com/user-attachments/assets/eff52331-eea9-4dff-9a25-036ff49b491c">

Error in the logs from DOSBox-X:

<img width="545" alt="image" src="https://github.com/user-attachments/assets/543c3c8d-cf33-43f8-8b7b-ccccfa7472b6">

So I think it's a buggy game. I'll leave this open if someone wants to get further confirmation by trying to run it on an emulated EGA machine in PCem or 86box. I can't test on hardware because I don't have EGA cards and monitors, only SVGA.

**Comment by einstein95** [comment]
> So I think it's a buggy game. I'll leave this open if someone wants to get further confirmation by trying to run it on an emulated EGA machine in PCem or 86box. I can't test on hardware because I don't have EGA cards and monitors, only SVGA.

Yeah, looks like a buggy game (despite having the code and data there for EGA graphics). Tried in 86box and got this lovely screen (not pictured: the flickering graphics):
![Monitor_1_20240927-104152-160](https://github.com/user-attachments/assets/3d59fc98-9493-4ba8-9021-62fd2f7cfac7)

Gonna close this as a BTANB (Bug That's Actually Not a Bug)

**Comment by johnnovak** [comment]
Thanks for the extra confirmation @einstein95 

> Gonna close this as a BTANB (Bug That's Actually Not a Bug)

🤣 Yeah, a bug present in the game, not an emulator bug 👍🏻
