### ISSUE TITLE
-march=native breaks distcc

### ISSUE THREAD

**Issue by solskogen** [dosbox-staging/dosbox-staging#4014]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86

### Is your feature request related to a problem? Please describe.

I cannot use distcc to compile dosbox-staging due to the fact that it's using -march=native.

### Describe the solution you'd like

I made a *very* rough diff that works on Linux (but no other platforms) as I'm not very familiar with meson. 

### Describe alternatives you've considered

```
diff --git a/meson.build b/meson.build
index 8484424..1fe8ab7 100644
--- a/meson.build
+++ b/meson.build
@@ -91,7 +91,11 @@ prefers_static_libs = (get_option('default_library') == 'static')

 summary('Build type', get_option('buildtype'), section: 'Build Summary')
 summary('Install prefix', get_option('prefix'), section: 'Build Summary')
-
+result = run_command('sh', '-c', 'gcc -### -E - -march=native -mtune=native -mcpu=native 2>&1 | sed -r \'/cc1/!d; s/"//g; s/^.* - //g; s/ -dumpbase.*//\'')
+c_flags = result.stdout().strip()
+cxx_flags = result.stdout().strip()
+add_project_arguments(c_flags.split(), language: 'c')
+add_project_arguments(c_flags.split(), language: 'cpp')
 # extra build flags
 extra_flags = [
     '-Wno-unknown-pragmas',
@@ -259,7 +263,6 @@ endif
 if get_option('autovec_info')
     # At least O2 is needed enable auto-vectorizion
     extra_flags += [
-        '-march=native',
         '-O2',
         '-Wno-system-headers',
         '-Rpass-analysis=loop-vectorize',
@@ -289,10 +292,9 @@ simd_instruction_sets = []

 zlib_ng_options = get_option('use_zlib_ng')
 zlib_ng_wants_native = zlib_ng_options.contains('native')
-zlib_ng_is_native = zlib_ng_wants_native and cc.has_argument('-march=native')
+zlib_ng_is_native = zlib_ng_wants_native

 if is_optimized_buildtype and zlib_ng_is_native
-    extra_flags += '-march=native'
     simd_instruction_sets += 'native'
     message('Enabling native SIMD optimizations')
 endif
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
When I checked the CI releases, they are not built with `march=native`, so that's the place to look.

The CI builds are just running `meson setup .. ` then `meson compile ..` just like you would on your distcc build.

You can see those commands by going into actions, then click the workflow file in the bottom left:

![2024-10-27 16_36_24-Complete support for code page 59829 · dosbox-staging_dosbox-staging@66f6074 - C](https://github.com/user-attachments/assets/067dcaa1-2def-4557-bebd-03bd4ae7de53)

This is for macOS ARM. I've highlighted the `meson setup` chunk.

I would suggest using the `-Duse_zlib_ng=sse2,ssse3,neon` in your `meson setup`. That should fix it.

**Comment by solskogen** [comment]
I don't quite understand your reply here. 
The default build method (meson setup build) will enable "-march=native" on Linux. Instead I'm proposing to not use that, but rather figure out what options "-march=native -mcpu=native -mtune=native" actually enables and use that instead.

**Comment by interloper98** [comment]
> The default build method (meson setup build) will enable "-march=native" on Linux. Instead I'm proposing to not use that

For now, just try this and it should work with distcc:

```
rm -rf build
meson setup -Duse_zlib_ng=sse2,ssse3,neon build
```

If that works, you can go further if you want by overriding cpp_flags and c_flags or use the environment variables like CFLAGS and CXXFLAGS.

But I don't think this extra step is needed. I haven't seen any real performance benefits in DOSBox by going further, at least on my hardware.

**Comment by solskogen** [comment]
Yes, that builds. But that wouldn't help my initial request here. The solution I propose should work for all architectures. Either that or perhaps get rid of it totally, if it doesn't have (much) impact on performance.

**Comment by interloper98** [comment]
> Yes, that builds. But that wouldn't help my initial request here. The solution I propose should work for all architectures.

I wasn't sure what the four-part sed statement was doing: (sed -r \'/cc1/!d; s/"//g; s/^.* - //g; s/ -dumpbase.*//\''). If we wanted to use it, it would need to be documented and I guess we'd have `sh` and `sed` as new dependencies. (Meson  is 100% python based and can run on Windows from the cmd.exe or powershell, which might not have those GNU tools).

> Either that or perhaps get rid of it totally, if it doesn't have (much) impact on performance.

Right; when I read the ticket, I wanted to help you get your distcc system going and avoid `march=native` all together, but still let you set some reasonable SIMD instructions sets that zlib-ng can benefit from.

@weirddan455 linked a ticket which would lead to a cleaner solution, so I think waiting for @weirddan455's ticket is probably the best approach.

---

But in the meantime, I'm doing Staging dev on a Pi4 using **ccache** and the **mold** linker (all local, without `distcc`).

Full builds from scratch finish in 30s or less. That's including the setup phase with all features enabled, and after pulling changed files from new merges.

I suspect your Pi5 would be quite a bit faster. Here's some quick notes if you want to try it.  First install them: `sudo apt install ccache mold`

Then set some tweaked CCACHE settings in your `.bash_profile` or `.profile`:

```shell
export CCACHE_MAXSIZE="1024M"
export CCACHE_DIRECT="true"
export CCACHE_DIR="$HOME/.ccache"
export CCACHE_COMPRESSLEVEL="6"
export CCACHE_COMPRESS="true"
export CCACHE_SLOPPINESS="pch_defines,time_macros"
export CCACHE_UMASK="002"

export CXX_LD="mold"
export CC_LD="mold" 
```

1. Optionally disable `distcc` (I'm not sure how)
2. Source your profile to ensure those environment variables are set.
3. Delete your `build/` area, then do a full build (`meson setup build && meson compile -C build`)
4. Repeat step 3 (delete + full build). It should be really fast.

```
pi@raspberrypi:~/src/dosbox-staging-interloper98 $ rm -rf build
pi@raspberrypi:~/src/dosbox-staging-interloper98 $ time (meson setup build && meson compile -C build) > /dev/null

real	0m23.013s
user	0m19.383s
sys	0m7.720s
```

**Comment by solskogen** [comment]
The sed just removes everything from the gcc output that are not related to the optimizations that "-march=native -mcpu=native -mtune=native" gives - There might be a better way of doing that, that works on more systems than just Linux.
With regards to the build time I got down to one and a half minute with distcc, while a normal build takes 5 minutes.

**Comment by interloper98** [comment]
> The sed just removes everything from the gcc output that are not related to the optimizations that "-march=native -mcpu=native -mtune=native" 

I finally managed to get that statement working in my shell, and I think it's not just removing options unrelated the "-march=native -mcpu=native -mtune=native" optimizations.

It's asking GCC to dump the explicit platform and CPU-specific flags that would be implied by the `native` alias, given the local host machine's CPU type.

So on an modernish Intel CPU `-march=native` expands to `-maes -mpclmul -mavx512vl -mavx512bw -mavx512dq -mavx512cd -mavx512er -mavx512pf -mavx512vbmi -mavx512ifma -mavx5124vnniw -mavx5124fmaps -mavx512vpopcntdq -mavx512vbmi2 -mgfni -mvpclmulqdq` ... and a lot more.

It makes sense now why it works with heterogeneous distcc machines. If `distcc` doesn't perform this `native` expansion on the source compiling machine, then it's allowing every compiling working machine to use their own (different) -march=native` results.. so it would be a dogs breakfast of different results.

It seems like a distcc bug, honestly.

> There might be a better way of doing that

Definitely; and not just better - I think the current solution is basically a hardcoded solution for your specific environment, and will break down in many more.

It hardcodes the compiler (not only to gcc, but the binary named `"gcc"`), however the build system might be explicitly using `gcc-12` on a system where the default `gcc` is too old.  Or the compiler might be Clang or a versioned executable like  `clang-17`.  So that's a problem regardless if we're using Meson or Cmake in the future.

So the first comment: make it use the build system's actual compiler.

Also, the diff just slaps those arguments into the project, even if the compiler doesn't support them.  The flags should be extracted from the build system's C compiler and C++ compiler individually, because these are different binaries and have slightly different flags.. despite large overlap between C and C++ flags.

Even if these could be better addressed, shoving all this into cmake or meson just feels wrong to me. It's distcc that taking the local `gcc -march=native` command and launching it on a bunch of (possibly different!) worker machines. 

distcc could trivially compile a "hello world" program on all the machines, query the incoming flags, and compare them across all the machines and decide if the flags are the same or different - and then figure out the least common denominator (or something like that).  It could even say "Nope, we're not going to make a dogs breakfast here".

I would investigate distcc to see if it has some features to enable this handling.

**Comment by interloper98** [comment]
Edit: it looks like this has come up again and again on the distcc project: https://github.com/distcc/distcc/issues/331, https://github.com/distcc/distcc/pull/384, and https://github.com/distcc/distcc/pull/350

Definitely agree it's a deal breaker, as some of those users mention.

**Comment by interloper98** [comment]
I'd vote this as a "won't fix" for the project but reasonable to leave the ticket open awaiting the solution to @weirddan455's ticket, which might mitigate the problem for you.

**Comment by solskogen** [comment]
I totally I agree!
