### ISSUE TITLE
Astral Blur^TBL broken since v0.82.0.r1

### ISSUE THREAD

**Issue by BackSpace54** [dosbox-staging/dosbox-staging#4015]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi,
[Astral Blur](https://www.pouet.net/prod.php?which=1) from TBL is broken in DosBox Staging 0.82.0rc1 and >
Tested with an empty conf file, this demo runs until version 0.81.2, with 0.82.0.r1 and above astral.exe show this message when executed:
`Error while initing the file system!`
`Possible errors are: - not enough descriptors available`
`- cannot find overlay file`
`- error in executable in overlay`
`- more exe's loaded in mem then possible`
`- error in overlay`
Could you check this issue?
Thanks.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Get the demo
2. Use a clean install and empty conf file of DosBox Staging 0.82.0rc1 and >
3. Try to execute the demo with astral.exe --> got error message
4. Try the same with DosBox Staging 0.81.2 --> demo starts

### Download URL of affected game or software

https://files.scene.org/get/demos/groups/tbl/pc/astral.zip

### Your configuration

```ini
Empty conf file
```

### Provide a Log

```text
Log is from execution of the demo
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
First bad commit is 7d806a86d6f346418e57805608e2fcd885dcbbe8 - I'll take a look

**Comment by weirddan455** [comment]
I think this is a bug in the demo technically.  It's opening `ASTRAL.EXE` with sharing bits set for "deny none" then later opening it again (while it is still open from the first call) with no sharing bits set (compatibility mode).

From MS-DOS Encyclopedia page 1302:

> 100 (deny none). Similar to compatibility mode, but does not allow other processes
> to open the file in compatibility mode. This mode fails if the file has already been
> opened in compatibility mode by any other process.

I think we are doing the right thing here by denying access on the 2nd call.  On real MS-DOS, this is handled by the `SHARE.EXE` TSR which was included from MS-DOS 3.0 onward but probably wasn't loaded on most DOS systems as most DOS programs didn't care about this.  It was mostly used for networking from what I can tell.  Windows 3.1 programs started caring about this more which is why I added this feature.

I'll need to test on real MS-DOS with `SHARE.EXE` loaded to confirm we have correct behavior.  If so, I think the best we can do is add a config option to disable file locking for buggy DOS programs.  This is what Dosbox-X does.

**Comment by BackSpace54** [comment]
> I'll need to test on real MS-DOS with `SHARE.EXE` loaded to confirm we have correct behavior. If so, I think the best we can do is add a config option to disable file locking for buggy DOS programs.

At least in 86box got the `Error while initing the file system!` error when trying to execute `astral.exe` while `share.exe` is loaded in memory. This is probably the correct behavior, waiting for real hardware test.

**Comment by weirddan455** [comment]
> At least in 86box got the Error while initing the file system! error when trying to execute astral.exe while share.exe is loaded in memory. This is probably the correct behavior, waiting for real hardware test.

Thanks for testing.  I'm seeing the same.  I don't have hardware to test on but I don't think it's needed in this case.  This is just DOS software behavior we're testing.

It should be pretty easy to add a config option to bypass the locking checks.  I implemented it as hard-coded to "on" because this is the first DOS program I've seen to have a problem with this.  DOS programs should really be leaving those bits cleared to zero if they're not actively doing anything with sharing.  Microsoft marked those bits as reserved from the very beginning of DOS but you know demo coders gonna do demo things.

**Comment by johnnovak** [comment]
Nice detective work @weirddan455 🏅
