### ISSUE TITLE
Have default shader be 'sharp' instead of 'crt-auto'

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#4028]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

As well-implemented as the adaptive CRT shaders are, I know that such a feature is a divisive thing amongst emulation fans. 

### Describe the solution you'd like

As someone who's dabbled both with and without CRT shaders, I think it would be less intrusive to have CRT shaders disabled by default for a cleaner and less intrusive initial presentation.

### Describe alternatives you've considered

I've also thought about having it default to the 'nearest' shader, but this doesn't seem to be a favorable option among the devs, so 'sharp' seems like the next best option.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
The first lesson of any open-source project: no matter what you do, there will _always_ be someone who will disagree with it. Trying to please absolutely everyone is a fool's errand; you just cannot win there 😆 

We in the core team see ourselves not just as the maintainers of this fine emulator project but also as educators, disseminating IBM PC and DOS-related knowledge to the broader public and correcting past wrongs.

One of such correction was defaulting to aspect ratio correction in the stock config. 

Another was making screenshots also aspect ratio correct by default.

The third was enabling the adaptive zero-config CRT shaders out of the box, as this is what best approximates the experience of using an IBM PC in the 80s and 90s. DOS games were designed and meant to be played on CRT monitors.

Now, our users fall into two categories:

1. Most people who grew up with CRT monitors were delighted by the new CRT shaders. For many, the authentic CRT look was one of the last important missing ingredients; it serves as a super powerful nostalgia trigger for them. Many people congratulated us on the shaders; they were absolutely thrilled by them.

2. Those who grew up with LCD screens on earlier Windows versions might find the CRT look strange initially. Same deal for people who are only used to using "modern" computers with LCD screens. Some might develop a taste and love for the look; some might not.

Our aim is to showcase the CRT shaders to as many people as possible. Why is that? Because we feel strongly about preserving the authentic, original experience, and many people from the first group had bad experiences with shaders before. If we were not giving them a gentle nudge by enabling the CRT shaders by default, they might completely miss out on the adaptive CRT shader experience.

Similarly, we want to educate people from Group 2 on what the authentic experience looks like. Who knows, they might fall in love with it! But if they don't, no big deal; they can turn it off. The important thing is we want to give them a _chance_ to enjoy how DOS games are supposed to look.

This is described in detail in the Getting Started guide [here](https://www.dosbox-staging.org/getting-started/setting-up-prince-of-persia/#authentic-crt-monitor-emulation), and we also show people how they can [turn the CRT emulation off](https://www.dosbox-staging.org/getting-started/enhancing-prince-of-persia/#sharp-pixels), should they wish to do so.

All in all, we don't want to force the CRT shaders on everybody; that's not the intent here. All we want is to give a gentle nudge to make sure people don't miss out on them (either due to previous bad experiences with shaders or due to unfamiliarity) and to play our part in not letting emulating the authentic CRT experience fall into oblivion, which is very important to us.

**Comment by johnnovak** [comment]
I just saw this comment this morning; another happy customer 😎 

So, by all means, if making both groups _equally_ happy with our choice of defaults is mutually exclusive, we _definitely, 100%_ want to optimise for the happiness of the group who value recreating the authentic CRT monitor experience 😎 🤘🏻 

<img width="900" alt="image" src="https://github.com/user-attachments/assets/197d2f64-3c39-4664-8509-7a3f106dc503">

**Comment by interloper98** [comment]
@OpenRift412 , it's pretty quick to make one-off changes to your conf after upgrading. For this example: `dosbox --set glshader=sharp -c "config -wcd" --exit`  (and you're done!)

**Comment by QmwJlHuSg9pa** [comment]
Happy with the shaders, though I can't help but notice the performance impact of the CRT shader, when glshader is set to "auto" and while running various 3D games -- the games go from completely smooth to stuttering and experiencing audio underruns. So, the "auto" setting isn't really viable at this time.

I don't exactly recall whether performance was comparative since 0.81, as I had taken a lengthy break from playing with this stuff while waiting for 0.82 to release. If it turns out there's no performance to be (re-)gained, then I guess I'm asking for a lighter-weight CRT shader as a default -- and I'm not running an RPi or anything, but a Ryzen 2600X...

**Comment by johnnovak** [comment]
> Happy with the shaders, though I can't help but notice the performance impact of the CRT shader, when glshader is set to "auto" and while running various 3D games -- the games go from completely smooth to stuttering and experiencing audio underruns. So, the "auto" setting isn't really viable at this time.
> 
> I don't exactly recall whether performance was comparative since 0.81, as I had taken a lengthy break from playing with this stuff while waiting for 0.82 to release. If it turns out there's no performance to be (re-)gained, then I guess I'm asking for a lighter-weight CRT shader as a default -- and I'm not running an RPi or anything, but a Ryzen 2600X...

Probably user error. The shaders are quite performant and have been tested on 10+ year old Macs, a GTX 750 Ti from 2015 (my previous GPU), and various low-end hardware. These are extremely lightweight on GPUs released in the 5-10 years, so probably something else goes wrong on your machine.

**Comment by QmwJlHuSg9pa** [comment]
> Probably user error. The shaders are quite performant and have been tested on 10+ year old Macs, a GTX 750 Ti from 2015 (my previous GPU), and various low-end hardware. These are extremely lightweight on GPUs released in the 5-10 years, so probably something else goes wrong on your machine.

Yeah, good call. I had forgotten I had set `MESA_LOADER_DRIVER_OVERRIDE=zink` (this was the problem) in an attempt to get MangoHUD working, though IIRC no luck because Flatpak.

**Comment by johnnovak** [comment]
> > Probably user error. The shaders are quite performant and have been tested on 10+ year old Macs, a GTX 750 Ti from 2015 (my previous GPU), and various low-end hardware. These are extremely lightweight on GPUs released in the 5-10 years, so probably something else goes wrong on your machine.
> 
> Yeah, good call. I had forgotten I had set `MESA_LOADER_DRIVER_OVERRIDE=zink` (this was the problem) in an attempt to get MangoHUD working, though IIRC no luck because Flatpak.

Glad you figured it out. It seems it's easy to shoot yourself in the foot on Linux in spectacular ways when it comes to GPUs 😆

So yeah, all my claims are based on my own experience on Windows and macOS where the GPU drivers JustWork(tm). Any mid-tier GPU from 10 years ago can handle the shaders with flying colours with zero performance impact. So I'm confident in saying that if you have a recentish laptop or desktop rig, shader performance is total non-issue... unless something is royally screwed up on the person's system 😆
