### ISSUE TITLE
Add reset configuration command

### ISSUE THREAD

**Issue by MonkeyPilot** [dosbox-staging/dosbox-staging#4042]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

A typical example is when we have several games in a directory and they need separate sound card and processor cycle settings. This can be easily done by creating a `BAT` file to launch each game:
```BAT
@echo off
config -set sbtype sb16
mixer sb reverse
keeper.exe
mixer sb stereo
config -set sbtype ess
```
In this example, the necessary settings are set on the fly, the game is launched and after setting up, you need to return them to their original state, as they are now in the config. Obviously, there is redundancy here, after exiting the game, you have to re-change the parameters and return them to their original state. It would be convenient in this case to have one command to reset the parameters (take from the config).
Moreover, we can't know for sure what settings we currently have in the config. Therefore, a reset parameter would be very preferable.

### Describe the solution you'd like

```BAT
@echo off
config -set sbtype sb16
mixer sb reverse
keeper.exe
config -revert
```
Which would automatically return all the settings from the config.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
This is a very specific use case. Adding generic support for specific niche wishes is the straight road to feature bloat, so we won't do this.

The good news is you already have all the building blocks to create such a config restoration system. First, you don't need to reset _all_ the parameters, just a few. So you could have a `base.bat` or whatever that sets your "machine defaults" after exiting the game. Job done 😎 

Or you can be more sophisticated and create a `push.bat` that queries the values of certain settings and writes them to a `pop.bat` that resets them. I'm doing something similar in my upcoming DOS demo pack with the cycles settings as those can vary a lot across different demos.

There are tons of DOS-era utilities to help create you such batch files dynamically on the fly.

**Comment by FeralChild64** [comment]
I'm not sure if this such a niche - I have the same problem. Like probably everyone else who uses a DOS game launcher inside Staging. For sure, you can always work it around with some .BAT files, yet everything becomes more complicated and error prone.

I definitely won't do this in the near future (too many open topics), but in the future... who knows. Looking at the code in `setup.cpp`, it doesn't seem to be that hard to implement.

**Comment by johnnovak** [comment]
> I'm not sure if this such a niche - I have the same problem. Like probably everyone else who uses a DOS game launcher inside Staging. For sure, you can always work it around with some .BAT files, yet everything becomes more complicated and error prone.
> 
> I definitely won't do this in the near future (too many open topics), but in the future... who knows. Looking at the code in `setup.cpp`, it doesn't seem to be that hard to implement.

Yeah, a simple implementation of this is not that hard, but I have concerns how it would work together with the GUI, specifically.

You will be able to change about half the setting from the GUI while a game is running, including fullscreen/windowed, shaders, CGA colors, audio levels, reverb, chorus, crossfeed, lowpass/highpass filters, mouse sensitivity, and a lot more.

So would the "restore config" command nuke all these settings I have changed after launching the game? 99% of the time you want only to restore a handful of settings between launching different games, but what settings exactly is very user specific.

Surely, you could add a lot of complexity to the restore feature to deal with these issues, but that's exactly where my feature bloat warning lights start wildly blinking 😆

The current set of configuration options are already _too complex_ to be 100% supported on the GUI (without going into extreme feature bloat on the GUI side as well, making it difficult to use for virtually everybody). So I really don't want to add any more complexity and special cases to it.

That's why I'm leaning heavily making all this the user's problem because supporting it _generically_ in the GUI and even just for CLI usage would add a lot of conceptual complexity (not talking about code complexity here, that's kinda irrelevant for this discussion).
