### ISSUE TITLE
keyboard_layout=auto does not work on Fedora 40, it works on Ubuntu 24.10

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#4093]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

git

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Fedora 40, Ubuntu 24.10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Dosbox does not correctly detect my german-keyboard with english Fedora 40
but my english Ubuntu 24.10 + german keyboard works

fresh Linux installes, fresh dosbox release build, fresh config + keyboard_layout=auto 

i think the mru-sources and XDG_* env-vars are not handled correctly in my case

**in Fedora 40 (English and german layout installed: german is active)**
  `echo $XDG_CURRENT_DESKTOP` ==> `GNOME`
  `echo $XDG_SESSION_DESKTOP` ==> `gnome`
  `gsettings get org.gnome.desktop.input-sources sources` ==> `[('xkb', 'us'), ('xkb', 'de+nodeadkeys')]`
  `gsettings get org.gnome.desktop.input-sources mru-sources` ==> `('xkb', 'de+nodeadkeys'), ('xkb', 'us')]`

the first of mru-sources seems to be the current one - follows my switching of layout

**in Ubnutu 24.10 (only german layout installed)** , **SUSE Tumbleweed behaves the same as Ubuntu with gsettings but the envs are like in Fedora with GNOME and gnome** 
  `$XDG_CURRENT_DESKTOP` ==> `ubuntu:GNOME`
  `$XDG_SESSION_DESKTOP` ==> `ubuntu`
  `gsettings get org.gnome.desktop.input-sources sources` ==> `[('xkb', 'de')]`
  `gsettings get org.gnome.desktop.input-sources mru-sources` ==> `@a(ss) []`
  
`@a(ss) []` means empty list (use only first entry of sources)

when i add English as layout to Ubuntu i get the following
  `gsettings get org.gnome.desktop.input-sources sources` ==> `[('xkb', 'de'), ('xkb', 'us')]`
  `gsettings get org.gnome.desktop.input-sources mru-sources` ==> `[('xkb', 'de')]`
  
  changing to english layout

  `gsettings get org.gnome.desktop.input-sources sources` ==> `[('xkb', 'de'), ('xkb', 'us')]`
  `gsettings get org.gnome.desktop.input-sources mru-sources` ==> `[('xkb', 'us'), ('xkb', 'de')]`

  now `us` is the active

**in Debian 10/Buster(~2022) and recent Debian 12/bookworm (only german layout installed)**
  `$XDG_CURRENT_DESKTOP` ==> `GNOME`
  `$XDG_SESSION_DESKTOP` ==> `gnome`
  `gsettings get org.gnome.desktop.input-sources sources` ==> `[('xkb', 'de')]`
  `gsettings get org.gnome.desktop.input-sources mru-sources` ==> `@a(ss) []`
  
`@a(ss) []` means empty list (use only first entry of sources)

when i add English as layout to Debian i get the following
  `gsettings get org.gnome.desktop.input-sources sources` ==> `[('xkb', 'de'), ('xkb', 'us')]`
  `gsettings get org.gnome.desktop.input-sources mru-sources` ==> `@a(ss) []`
  
  changing to english layout

  `gsettings get org.gnome.desktop.input-sources sources` ==> `[('xkb', 'de'), ('xkb', 'us')]`
  `gsettings get org.gnome.desktop.input-sources mru-sources` ==> `@a(ss) []`

  nothing changes!!!

  so its different on Debian Buster/bookworm 

### Steps to reproduce the behaviour.

just start dosbox and try Umlaute äöü - if you can :)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by LowLevelMahn** [comment]
it seems to complex but why do all other tools im using getting it right? maybe dosbox does not the fully correct or compatible way of aquiring the language/layout information - or whats the magic?

**Comment by rderooy** [comment]
This is on my Fedora 41 laptop:
```bash
$ localectl 
System Locale: LANG=en_GB.UTF-8
    VC Keymap: us-euro
   X11 Layout: us,us
  X11 Variant: euro,intl
$ gsettings get org.gnome.desktop.input-sources sources
[('xkb', 'us+euro'), ('xkb', 'us+intl')]
$ gsettings get org.gnome.desktop.input-sources mru-sources
[('xkb', 'us+euro'), ('xkb', 'us+intl')]
$ env|grep DESKTOP
DESKTOP_SESSION=gnome
XDG_SESSION_DESKTOP=gnome
XDG_CURRENT_DESKTOP=GNOME
```
Log fragment from current git build:
```
2024-12-08 18:30:37.393 | LOCALE: Loading native locale for country 61 - 'International (English)'
2024-12-08 18:30:37.393 | LOCALE: Using numeric/time/date/currency format detected from host OS
2024-12-08 18:30:37.394 | LOCALE: Loaded code page 437 (ROM font)
2024-12-08 18:30:37.394 | LOCALE: Loaded keyboard layout 'us' - 'US (standard, QWERTY/national)'
```
For me DOSBox Staging does the right thing:
![image](https://github.com/user-attachments/assets/d8f88acd-b0dc-4acd-8616-9e7abb21e84c)

**Comment by FeralChild64** [comment]
> it seems complex but why do all other tools im using getting it right? maybe dosbox does not use the fully correct or compatible way of aquiring the language/layout information - or whats the magic?

Because we are using keyboard in a way completely different than other apps.

Normal application just wants to be informed about the key after the OS does the whole keyboard layout magic - it doesn’t care which keyboard layout is set, if it changes 10 times a second, if the user pressed a dead key, etc. It just want to know, that the user pressed something that should produce, for example, the letter W.

But not us. We are interested about the physical key, regardless of what the keyboard manufacturer decided to print on the key - so that we can emulate the keyboard hardware for games and software that accesses keyboard directly. Then we emulate the BIOS, doing appropriate scancode processing - so that applications which use BIOS directly can work properly. Then we emulate the DOS, with the keyboard layouts which are compatible with MS-DOS ones (and not necessary reflecting the host OS keyboard layouts), and which are build using a model largely different than what modern OSes use.

Who else does something like this? Other DOSBox forks? AROS hosted? DOSEmu? Some other emulators? And how many of them try to synchronize the internal keyboard layouts with the host one?

And I can’t just use the native host OS API standard call to get the list of the host keyboard layouts - there is none. No sane application needs such information, therefore no API call exists. I have to directly read the Windows registry, Apple property lists, KDE’s ini file, GNOME’s GConf storage, you name it.
Well, there is a generic way to read the keyboard layouts on Linux - but it needs X11 running (the real one, not Wayland), and it requires either a command line tools not everyone has installed or to link directly against X11 libraries (read: new link dependency) - so I don’t want to use it.

And each host OS has it’s own quirks. Windows presents the keyboard layouts list over which the user does not have the full control (at least I think so - this OS just feels plain alien to me), Linux has gazillions of desktop environments (plus either X11 or Wayland), Apple has the transliteration keyboard layouts which are reflected in quite a complicated way in the property lists (fortunately just skipping them should not cause serious problems for us), etc.

It’s just complex.

**Comment by FeralChild64** [comment]
@LowLevelMahn Sorry for not being able to check this in details earlier. So - the problem is here:

```gsettings get org.gnome.desktop.input-sources sources ==> [('xkb', 'us'), ('xkb', 'de+nodeadkeys')]```

It looks like the first keyboard layout is US and the second one is German, with US being the default one.

![1](https://github.com/user-attachments/assets/a9e58b6c-9b93-4b0f-a12e-5e8f49663c79)

Reorder them, so that German layout is the first one - this should fix your problem:

![2](https://github.com/user-attachments/assets/dfcf38f0-de39-411b-a32c-94066985569a)

**Comment by FeralChild64** [comment]
I did some experimentation - I noticed that despite both KDE and GNOME allow to reorder the keyboard layouts, they behave differently:
- KDE always starts with the first configured layout - therefore it makes sense to honor the order set by the user
- GNOME starts with the last used one - therefore it makes more sense to consider the keyboard layouts as randomly ordered

I'll adjust the code accordingly.

**Comment by LowLevelMahn** [comment]
> Reorder them, so that German layout is the first one - this should fix your problem:

i get you, but then keyboard_layout = auto makes no real sense again :)

**Comment by FeralChild64** [comment]
The `auto` just means: pick what suits the host settings the best. Anyway - the PR to change the behavior in the GNOME environment is in the review.
