### ISSUE TITLE
[Suggestion] to provide dosbox-staging-git.conf

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#446]
### Proposed feature
To provide `dosbox-staging-git.conf` along with the source code would be helpful. This will allow an easy way to spot new changes and to compare these with an existing file for instance.

### Reason for change
Today the only way to get `dosbox-staging-git.conf` is by running Dosbox-staging from the command-line with no argument.

### Additional context
I'm running Dosbox-staging exclusively on a Pi (no desktop). I have to SSH and run the command-line to get me the last config file version which is not handy :-) Please keep me honest if there's a simpler way to get that file (or to update the existing one).

**Comment by kcgen** [comment]
If you're inside a running dosbox session, you can run `config -writeconf /somewhere/my.conf` and that will write your current settings plus underlying default values, if you haven't overridden them.  
That said - dosbox is almost impenetrable at revealing it's command-line arguments. 
- `dosbox -h`? Nope.
- `dosbox -help`? Nope
- `dosbox --help`? Nope

Run dosbox, and at it's `C:\>` it's intro screen mentions running `help`! Ahh, ok.  Now it shows me some commands..  but wait `config` isn't in the list.   Ahh, now it tells me I can run `help /all` to see all the commands.  Nope, `config` isn't in that list either.

**Comment by FeignInt** [comment]
builds on what @kcgen suggested
untested, and I'm unfamiliar with the Pi

assuming dosbox has already been deployed to the pi, and public key auth., i.e. you don't type a passwd when using ssh to your pi
 
```
ssh user@thepi \
   "dosbox -c 'config -writeconf /tmp/newdosbox.conf' \
           -c  'exit' "
# all one line
```
now to compare
```
diff -u \
 <( ssh user@thepi "cat .config/dosbox-staging-git.conf" ) \
 <( ssh user@thepi "cat /tmp/newdosbox.conf" )
```
sending the stdout of the subshells to file descriptors, which diff is treating as files, because they are :D

the output is the difference, probably just the version header

This is probably not what you want, I have made changes to the default conf, and those changes are included in the  "/tmp/newdosbox.conf"

you would need to cache clean defaults
1. mv conf to backup
2. launch dosbox -c exit
3. launch dosbox -c "config -wr.... "
4. diff -u <( ssh .....
5. act and restore your custom conf to the default.conf

or always pass -conf /path/to/custom.conf when launchng on the pi

alias, shell wrapper, desktop icon launcher?

and only refresh the default when you see a significant change 
```
dosbox -eraseconf
# -resetconf does same as erase, no new file written
dosbox -c exit
```

and update your custom conf accordingly
This seems the best way to sync a custom config with current defaults.

during very limited testing changes are version header and phonebook ( which is tagged with version number )
I don't now how volatile the default.conf is 

it does look like you compile yourself without changing the version tag in configure.ac, so you will see very little change
if you frequently compile , consider versioning the builds
```
sed -i -E 's/(AC_INIT.+,[[]?)[^])]+/\1'$( git describe --tags )'/' configure.ac
./autogen.sh
git restore ./configure.ac
# git checkout with older git versions
```
having wrote that, a static version actually makes it easier to deal with from a scripting perspective, since the diff will have no output unless a significant change has been made.

**Comment by FeignInt** [comment]
without all the messing about with ssh
```
sed -n "/void Config_Add_SDL()/,/^}$/p" src/gui/sdlmain.cpp

```
and diff the output with previous

`git log -p --reverse -- src/gui/sdlmain.cpp` for history of that file
( oldest change first )

if you are interested only in the history of that function

```
sed -n '/@@ void Config_Add_SDL()/,/^$/p' \
    < <(git log -p --reverse -- src/gui/sdlmain.cpp )
```
but that is crude, only good for a rough overview, you lose a lot of context  e.g. its creation Feb 1st 2009

If you are only interested in what changed since you compiled it last, the first is probably enough for you, you just need to dump the output somewhere between compiles

**Comment by dreamer** [comment]
I don't know why discussion in here turned into diffing the files around, but no matter.

@nemo93 yeah, I understand it would be handy to have default .conf files for reference somewhere… but unfortunately, parts of this file might be specific to the users' machine (e.g. available `texture_renderer` values - Linux users won't see `directx` and Windows users won't see `metal` in there). Writeconf is *a* solution, but it's not *the* solution.

Theoretically, we could generate a generic .conf file during the build and bundle it with the zip/tarball/dmg file… but I don't know what to do about those values filled-in on runtime.

I need to think a bit what's the best option for communicating available options to the users - this will be relevant for #262 as FluidSynth introduces several new options and we're not going to use the same option names as old FluidSynth patches.

**Comment by FeignInt** [comment]
from what I understood @nemo93 wanted the .conf included in the source, so changes could be reviewed and action taken by themselves.

But the .conf is generated at runtime based on the system it is running on, so not easily satisfied.

simply looking at the difference in the function that generates the .conf between @nemo93 's previous build and current seemed the simplest way to satisfy the wish in the short term.

no change no action,  <= most of the time
a change, maybe action 

long term, perhaps print a reference conf to stdout when --print-default-conf is passed. this would be a clean generated conf ignoring the values on disk.

Or, on disk dosbox-staging.conf.template read the version header, re-write if old. The template is purely for reference
of course self built "git" versioned  would never get refreshed.

If dosbox-staging encounters config values it does not understand ( or deems outdated ), print to stderr a hint pointing to the template.
Probably not all that helpful to those not using cmdline. I assume launchers like retropie would log/report stderr.

dbus notification if available?, would catch some of those who launch via .desktop 

Windows and MacOS, I have no ideas

**Comment by nemo93** [comment]
Thanks all for your very useful responses. I'm fine closing this one off too if you think it goes nowhere.

**Comment by dreamer** [comment]
@nemo93 Overall we'll need to rework how dosbox-staging treats the default .conf file - but I think it'll be a long haul of gradual improvements. Closing this issue for now.
