### ISSUE TITLE
PC speaker regression noticeable in Duke Nukem 1

### ISSUE THREAD

**Issue by BPaden** [dosbox-staging/dosbox-staging#453]
To reproduce, just boot up episode I hold the button down the walk forward. You should hear a quiet, high-pitched noise behind the usual walking sound.

**Comment by dreamer** [comment]
@BPaden Are you comparing against DOSBox or against real hardware? Because Duken Nukem is known to have broken PC speaker emulation in DOSBox. If you're comparing against real hardware - do you have a somewhat accurate recording of how it is supposed to sound?

Also, what version are you testing?

@kcgen You'll probably the best person to look into this ;)

**Comment by BPaden** [comment]
I'm comparing git master vs dosbox, yeah. The sound seems obviously unintentional, though. I also didn't hear it with the pc speaker patch or in an emulated 486 in pcem.

**Comment by kcgen** [comment]
Thanks @BPaden! I tested w/ Keen and Secret Agent (both Apogee games); but not Duke.  Will look into it.

**Comment by kcgen** [comment]
@BPaden , when you have a chance, please give `kc/pc-speaker-regression-1` a whirl with your golden ears :-)
I tested this on Duke 1 along with the prior set of games in the original PR.

**Comment by BPaden** [comment]
That was a quick response, thanks for the fix @kcgen.

**Comment by kcgen** [comment]
Thanks for the report @BPaden; very thankful to have a second set of ears - and a different set of games - helping test!
