### ISSUE TITLE
Support MMX emulation

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#461]
Late-stage MSDOS games required or used MMX registers to accelerate their math operations.

Kekko (author of the 3dfx patch), has recently [shared a patch on Vogons](https://www.vogons.org/viewtopic.php?t=74877) adding MMX support:

> It adds Pentium MMX emulation to Dosbox.
> The instructions are for the interpreter; the recompiler can use it too, but it has to fall back to the interpreter core.
> It finally allows to run games which strictly require this instruction set, like Serious Sam (combined with the 3dfx patch).
> Probably the first AAA title from 21st century ever run in Dosbox :-)

The post includes the following attachments.

![ss1](https://user-images.githubusercontent.com/1557255/85446424-47cbcc80-b549-11ea-89d8-06bc93a445a8.png)
![ss2](https://user-images.githubusercontent.com/1557255/85446428-48646300-b549-11ea-886c-88da8cbc0359.png)
![ss3](https://user-images.githubusercontent.com/1557255/85446430-48fcf980-b549-11ea-884f-e9fca94b877d.png)
![ss4](https://user-images.githubusercontent.com/1557255/85446432-48fcf980-b549-11ea-83db-d9f17e9172d8.png)
![ss5](https://user-images.githubusercontent.com/1557255/85446436-49959000-b549-11ea-9280-3c0fb2c47c2c.png)
![ss6](https://user-images.githubusercontent.com/1557255/85446438-49959000-b549-11ea-87c7-2af298648eb1.png)

**The patch:** [:floppy_disk: mmx_20200623.diff.gz](https://github.com/dosbox-staging/dosbox-staging/files/4821368/mmx_20200623.diff.gz) 5.8KB.

Per Kekko's past request regarding the 3dfx patch, we will similarly provide any further improvements via the Vogon's thread linked above.

**Comment by dreamer** [comment]
AFAIK Serious Sam is not a DOS game, so I guess it depends on Windows 95 or later running inside dosbox? Personally I am not interested in running games from this era via dosbox-staging - Wine works sooo much better for this purpose (the game works perfectly in Proton); also, there is Linux-native port in the form of Serious Sam Fusion.

If anyone plans to work on inclusion of this patch (I don't) - I would prefer if we avoided new build-time configurations.

**Comment by kcgen** [comment]
Oh, good point; if no bonefide DOS (or Win 3.1) games require or benefit from it - then the case for it goes out the window.. along with the case to support Windows 95+ (which I'm also not interested in).

**Comment by GranMinigun** [comment]
There's also [Extreme Assault](https://www.mobygames.com/game/dos/extreme-assault), and I'm pretty sure there's more.

**Comment by kcgen** [comment]
@GranMinigun - popping this issue back open. I wonder if Extreme Assault _requires_ MMX?

**Comment by dreamer** [comment]
@kcgen no, it does not - but there's an option in menu to enable/disable MMX - right now this option is greyed-out.

**Comment by kcgen** [comment]
Cool.. and unless Kekko's patch somehow pipeline N instructions per cycle and maps the mmx calls to underlying SIMD instruction sets in the  dynrec backends, then we would still have serial execute - so the underlying performance would be unchanged (making the patch purely for compatibility).

**Comment by kcgen** [comment]
> perhaps someone is interested in working on this patch.

Unless it's necessary though, why would accept another truck load of very complex code to be maintained?

**Comment by GranMinigun** [comment]
I'm only aware that MMX accelerated fog and translucency effects in Extreme Assault (probably same for Z.A.R., but it has patches to support Windows and graphics accelerators). As for requirement - none comes to my mind.

**Comment by dreamer** [comment]
To summarize:

What is interesting about MMX emulation is a small emulation speedup that should be visible *only for games that use MMX*. It boils down to loading 64-bit values from memory and processing them together - and this patch actually accomplishes it (albeit I don't know if these tiny performance gains are negated by other parts of the implementation).

Or, to put it in other words: loading any values from memory is currently a very hot path in dosbox - partly because loading any word/double-word is being verified against memory page boundary; loading single 64-bit value instead of e.g. 4 16-bit values save us exactly 3 page boundary checks. Another tiny gain could be connected to using fewer operations in dynrec on 64-bit systems, but I can't say if it's a bigger or smaller gain.

So far we know exactly 2 games using MMX:

- Z.A.R - [steam](https://store.steampowered.com/app/351820/ZAR/), [pcgw](https://www.pcgamingwiki.com/wiki/Z.A.R.) - haven't tested it myself
- Extreme Assault - [wiki](https://en.wikipedia.org/wiki/Extreme_Assault), [pcgw](https://www.pcgamingwiki.com/wiki/Extreme_Assault) - works perfectly with max details and software rendering, even on my 8-year old sandy-bridge laptop (later game re-using the engine was Windows-only).

If these performance gains were shown to speed-up DOS games, where we *do* have performance issues (like e.g. Carmageddon), then I would be more interested in porting it; but as it stands right now - I think the costs of maintaining it in our codebase are bigger than any gains.

If upstream will take this in, we'll merge it in (of course). If there will be a compelling case due to performance improvements, or e.g. - if author was interested in helping us maintaining the code in-tree, then I will be happy to accept this new code as well. As it stands right now, neither is the case - for me this patch only adds a cost of resolving more potential code conflicts with upstream.

Request shall stay open in case someone wants to work on this :)

**Comment by nemo93** [comment]
As a side note: Megarace 2 will warn you upon launch if the CPU doesn't support MMX instructions. Game is playable anyway though.

**Comment by dreamer** [comment]
Oh! I actually test in Megarace 2 very often (one day I'll beat that game ;)) and was not aware it uses MMX - but it totally makes sense (considering how much video-heavy the game is).

@nemo93 Megarace 2 is very peculiar about options it needs for running (I remember crashes e.g. when SoundBlaster IRQ was not set in-sync with setup utility); I'll re-install the game on my laptop in the evening and report the set of options I use for playing on Linux.

**Comment by nemo93** [comment]
@dreamer I do confirm that Megarace 2 requires the following to be able to run:

```
[dosbox]
machine = svga_s3
```

**Comment by kcgen** [comment]
The MMX patch has been updated per the suggestion from jmarsh made last summer. 

From kekko:

>  "Hi,
> I updated patch on the first post
> - Added x86 recompiler support
> - Fixed fpu regs usage
> - Fixed makefiles and vc project files
> 
> x86 recompiler support is very basic, yet still much faster than the interpreter.
> On my 13yr old core2 it reaches almost playable speeds with Serious Sam.
> It uses emulated mmx regs, just like the interpreter. It doesn't use host mmx registers at all, avoiding breaking host fpu status/regs.
> this approach is way more stable than the dosbox-x implementation.
> plus it should be easier to port to other architecture s.

https://www.vogons.org/viewtopic.php?p=869449#p869449

**Comment by dreamer** [comment]
Good to hear kekko's not using MMX registers - modern CPUs deliberately make those registers as slow as possible, as there's no good reason to use them on 64-bit CPUs. I think implementing x86 recompiler support is not worth the time (we live in 2021… everyone on x86 is using x86_64 nowadays).

Anyways - if kekko would like to submit his work to us, then we could talk. I am not going to merge his patch myself. Almost every single time we changed something in CPU emulation, upstream makes changes in the same code area - making it a pain to sync up with SVN. Because of that PPC and PPC64 dynamic recompilers are disabled now (and I don't know if it even makes sense to keep them in code).

**Comment by kcgen** [comment]
I agree @dreamer.

It makes sense to follow the Dosbox Team's lead on core changes. If this adds value to DOS gaming, then I'm confident they will eventually merge it, in which case those fixes will flow down to Staging and others. 

With this decision deliberately out of our hands and for upstream to decide, I will tentatively close this.

**Comment by dreamer** [comment]
Yup. But just to repeat: if kekko will decide to submit the change to us, the gates are wide open :)

**Comment by GranMinigun** [comment]
...no?

![xa_000](https://user-images.githubusercontent.com/11149380/184507897-2cf5efde-3160-44eb-aa5a-442911817033.png)
![xa_001](https://user-images.githubusercontent.com/11149380/184507899-5a8f533c-28bd-4ad6-94c9-f2da80d1d3c2.png)

**Comment by Grounded0** [comment]
Changed closed type to not incorporated.

**Comment by rsribeiro** [comment]
[Little Big Adventure 2](https://www.mobygames.com/game/1765/twinsens-odyssey/) has mmx support. It is perfectly playable without it. Afaik there is no visual difference playing it with or without mmx

**Comment by FeralChild64** [comment]
Initial attempt to integrate MMX: https://github.com/dosbox-staging/dosbox-staging/tree/fc/mmx-1

- simple and normal cores seem to work
- dynrec dynamic recompilation core seems to work
- dyn-86 dynamic recompilation core does not work, DOSBox crashes

Tested with Extreme Assault game on AMD64 CPU.

**Comment by johnnovak** [comment]
Reopening, as discussed. Demos (e.g., Heaven Seven), demoscene tools (e.g., Impulse Tracker), and emulators (e.g., RealSpec) would benefit from this. Some of these programs won't even run without MMX support, some will offer extra features on MMX.

**Comment by FeralChild64** [comment]
OK, I'll prepare it for merging behind experimental flag, then. Some small cleanups have to be done first.

**Comment by johnnovak** [comment]
> OK, I'll prepare it for merging behind experimental flag, then. Some small cleanups have to be done first.

As I mentioned, I'm fine to merge this to main behind an experimental flag. But 95% of the time, MMX support makes sense for apps that need, well, Pentium MMX speeds 😎 So 100k+ cycles, sometimes 200k+, which calls for dynamic core support; otherwise, this is more like a theoretical exercise if it only runs on the normal core.

**Comment by johnnovak** [comment]
@FeralChild64 Should we notify Kekko at least as per kcgen's comment once this is merged?

> Per Kekko's past request regarding the 3dfx patch, we will similarly provide any further improvements via the Vogon's thread linked above.

**Comment by FeralChild64** [comment]
I think it would be better to notify him via private message, or something. VOGONS admins tend to get a little nervous when someone starts talking about DOSBox Staging :/

**Comment by johnnovak** [comment]
> I think it would be better to notify him via private message, or something. VOGONS admins tend to get a little nervous when someone starts talking about DOSBox Staging :/

Let them 😎 I'm happy to mention it in the thread, or you can PM the guy later if you prefer that.

**Comment by FeralChild64** [comment]
If you are willing to write the post by yourself, I consider the problem solved.
