### ISSUE TITLE
Links LS 97 cannot start due to executable name, ls.exe

### ISSUE THREAD

**Issue by bmunger** [dosbox-staging/dosbox-staging#504]
**Describe the bug**
The game, Links LS 97 has the main executable called LS.EXE and when run, only shows the output as if it was ls *.exe.
This can be worked around by running .\LS.EXE but is not obvious this is required in this situation.  DOSBox SVN does not exhibit this issue.

**To Reproduce**
Run LS.EXE

**Expected behaviour**
Execute the program if it matches an executable or batch file before a built in command

**Environment (please complete the following information):**
Ubuntu 18.04

**Version of dosbox-staging:**
v0.76.0-alpha-321-g8a74e224

**Configuration parameters:**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/1947284/87818701-03c2a380-c839-11ea-8cd9-fff8060a0246.png)

**Comment by kcgen** [comment]
Great corner-case discovery @bmunger !
Merely achewy morsel for @dreamer to enjoy improving :-)

**Comment by MasterO2** [comment]
You guys can name the linux LS command to LS**D**, so it won't conflict with the game LS.exe . :)

**Comment by MasterO2** [comment]
> 
> 
> As a test, I wondered if the DIR command was also affected. Turns out it is as well, and probably other built in commands.
> 
> ![image](https://user-images.githubusercontent.com/1947284/87823355-235dca00-c841-11ea-9779-63d901eaa271.png)
> 
> However that behavior is also the same in the upstream SVN version too.
> 
> Checking further, I tested real MS-DOS and found that behavior for dir.exe is the same. I think that since it's expected behavior for dos built in commands, applications probably avoided that name, however LS was never a built in dos command so this edge case was discovered. I'm not sure the best way to handle this case except maybe to treat it differently than a dos built in command, even Unix/Linux systems had it as an executable /bin/ls and not a shell built in.

Since the game is called Links, why not just rename the game exe LINKS.exe?

**Comment by bmunger** [comment]
@MasterO2 That may work in this case, some games/applications may not work that way, and the bigger issue is that without knowing this is an issue, someone else may not know how to work around it and give up.  It's not expected DOS behavior.  Chances are that Links LS is likely the only title affected and so few people probably still play it, but it's a low priority bug nevertheless.

**Comment by kcgen** [comment]
> I tested real MS-DOS and found that behavior for dir.exe is the same.

Wow!  I would expect PATH precedence to trump; and in DOS, that means anything in your current-working directory wins.

1. Do I have `dir.exe` right here? If so execute that.
2. Fallback to PATH order
3. Fallback to DOS internal command (if those exist)

**Comment by bmunger** [comment]
@kcgen I thought so too!  I tested it under MS-DOS 6.22 in PCEM.  Went to the DOS directory, copied mem.exe to dir.exe and typed dir.exe and got the same directory listing.  I never knew that in all the years I have used DOS.

**Comment by dreamer** [comment]
OK, we could "fix" this issue, but I am not sure if we should…

In cases like these, an executable can still be run in this, rather obvious way (although for DOS users it might not be obvious):
```
C:\> .\ls.exe
```
Yeah, just like in PowerShell, although Unix users will be more familiar with this; I bet the same will work in MS-DOS as well.

Now: why issuing `ls.exe` did start internal command instead of `ls.exe` file? Because DOS shell has a mis-feature of treating suffixes as parameters (that's why `cd..` or `dir/w` or `dir.foo` works…). `ls.exe` -> `ls .exe` -> `ls *.exe`

That's quite different from Unix shells, that do not allow such constructs unless they are aliases: `ls-l` will not be silently translated to `ls -l`, but e.g. `cd..` is translated to `cd ..` via alias (at least in GNU systems).

As for traditional DOS commands, we are very unlikely to find DOS software that is covered by internal commands (sometimes it causes problems - e.g. equivalent of `cls` in textutils is called `clr.cmd` for this reason). But for non-DOS commands (such as `ls`, and perhaps `mkdir` (was this ever a DOS command?) we might find other conflicts like this one.

Personally, I am aware of one more program causing such conflict [Open Cubic Player](https://www.cubic.org/player/) uses `cp.exe` executable, which would conflict if we'll introduce `cp` as an alias or better version of `copy`.

I'll do some experimenting, but in the end I think I'll make a simple filter for differentiating between MS-DOS commands and DOSBox/dosbox-staging additions. MS-DOS commands should behave as they were (so `dir.exe` should list all exe files in the directory) while new commands will likely require a space to separate parameters.

**Comment by MasterO2** [comment]
@dreamer Can that mis-feature of treating suffixes as parameters be corrected in dosbox-staging?  Or would that break other things?

**Comment by kcgen** [comment]
That explains why they never made a game named **Delicious**:

![2020-07-18_09-28](https://user-images.githubusercontent.com/1557255/87857122-12609780-c8d9-11ea-983e-0911cdb0cd10.png)

Developers> _I told you boss, we've gotta call it something else!_

**Comment by bmunger** [comment]
@dreamer I think that's the right approach.  Non standard DOS commands should be treated differently than standard built in commands and behave more like an executable in your PATH.

**Comment by dreamer** [comment]
> @dreamer Can that mis-feature of treating suffixes as parameters be corrected in dosbox-staging? Or would that break other things?

I know for a fact, that DOS users have things like `dir/w` ingrained in their muscle memory… Even worse - it could be used in batch files distributed with the games. At the moment, I think treating old commands and execs differently than new commands is the only way forward.

**Comment by Wengier** [comment]
@dreamer I think a solution for this is to put LS command as a program on the Z: drive rather than a shell command. Then typing "LS" will definitely run the LS.EXE on the current directory rather than executing the LS program on the Z drive.

**Comment by Wengier** [comment]
@dreamer I have already done this for DOSBox-X in my latest pull request there.

**Comment by MasterO2** [comment]
@dreamer Will you use Wengier's implementation of this in Dosbox-X?

**Comment by dreamer** [comment]
Haven't looked at it yet, it might be the best solution - the only problem is: it introduces a small mess in code: `ls` command shares code with `dir` command, and is placed in `shell_cmds`; if we move it to being a separate program (which makes sense), that means we'll have a program tucked in the shell code, where it doesn't belong (messy) or move it to a new file - but it means functions shared with `dir` need to be made public (inconvenient), or duplicate the code (we won't do that).

**Comment by Wengier** [comment]
@dreamer In my implementation I made the separate *stub* LS program in dos_programs.cpp which loads the existing shell LS command, while disabling the direct entry to the shell LS command. By doing this the existing code of the shell LS command remains more or less unchanged (so if there is any shared code with DIR then it remains so), but when a user tries to execute the LS command only the separate LS program can be executed. Maybe still be a little messy in the source code level, but it appears to work since then.

**Comment by dreamer** [comment]
@Wengier yeah, this seems to be good first step - creating a stub first, and then gradually moving some stuff out of `shell_cmds`.  I'll probably implement it the same way, maybe I can even cherry-pick your commit without too many conflicts (I'll look into it, don't send PR).

There are some other commands in there, that should get a similar treatment, e.g. `choice` or `help` - they were never internal `command.com` commands AFAIK.
