### ISSUE TITLE
LibADLMIDI Support?

### ISSUE THREAD

**Issue by MasterO2** [dosbox-staging/dosbox-staging#540]
Since Fluidsynth will be in dosbox-staging in the near future, can LibADLMIDI also be supported?  LibADLMIDI's sourcecode is located on Github as well:

https://github.com/Wohlstand/libADLMIDI

It's one of the MIDI libraries supported by GZdoom and Doom's music sounds great with it:

https://github.com/coelckers/gzdoom/search?q=adl&unscoped_q=adl

https://zdoom.org/wiki/LibADLMIDI

Edit: 8/11/2020 Also add this alongside LibADLMIDI:  

https://github.com/sneakernets/DMXOPL  (YMF262-enhanced FM patch set for Doom and source ports).

https://www.doomworld.com/forum/topic/95697-dmxopl-v210-happy-holidays-nov-27/?page=2

Any thoughts, @dreamer or @kcgen ?

**Comment by dreamer** [comment]
@MasterO2 Is there any particular reason why libADLMIDI is better than FluidSynth?

Supporting every another dependency is a *cost* (testing effort spread between redundant features, slower CI, more complicated buildsystem, documentation, etc, etc).

I don't feel we should support multiple built-in MIDI synths. We support multiple OPL synths only because Nuked is too slow for some devices (I hope we'll fix it at some point ;)).

@kcgen What do you think?

**Comment by MasterO2** [comment]
> 
> 
> @MasterO2 Is there any particular reason why libADLMIDI is better than FluidSynth?

@dreamer 

I'm only suggesting it because of DMXOPL and how great it sounds with Doom and Doom 2's music.  If you do not want to support it, that's ok as well.

**Comment by MasterO2** [comment]
Closing issue, since dosbox-staging already has Fluidsynth.
