### ISSUE TITLE
Include the build/commit version in VER's output

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#543]
Suggestion from Vogon's forum user Akuma:

I would really like the ver command to display the git version, this makes bug reporting much easier when it comes to "which version did you use ?" eg:

``` shell
C:\> ver
dosbox-staging version git-2335a224. Reported DOS version 5.00
```

**Comment by FeignInt** [comment]
your .github/workflows already do this

linux.yml
```
      - name: Inject version string
        run: |
          set -x
          git fetch --prune --unshallow
          export VERSION=$(git describe --abbrev=4)
          sed -i "s/AC_INIT(dosbox,git)/AC_INIT(dosbox,$VERSION)/" configure.ac
          echo ::set-env name=VERSION::$VERSION
```

and I have a similar sed in *debian/rules*

for example, the PPA Weekly ( 2020-08-07 )
both **dosbox --version** and **dosbox -c ver**  output this version string 
```
0.76.0~alpha~404~g0314-1+u20.10
```

:information_source: it is just git describe, mangled to fit Debian's version string  rules, un-debianised v0.76.0-alpha-404-g0314

The **g0314** indicates commit: dosbox-staging@03143a60e0ab410a2bde3e566a462dfd22410c69


`git describe --abbrev=4 0314` :wink: 


Now, the real trick would be to automate it, for those who compile themselves.

instead of hardcoding AC_INIT , and sedding the placeholder have AC_INIT set with code

have it look for a VERSION file ( created when generating tarball ),
if no VERSION do **git describe** if that fails fall back to placeholder

**If they are compiling from**
- an artifact download, *VERSION* file sets it
- git, *describe* sets it
- zip download from  github, then it behaves as it does now, i.e. "git" placeholder

I never got round to figuring out the .ac macro code, sed was just easier

**Comment by kcgen** [comment]
I like your suggestion @FeignInt!

**Comment by FeignInt** [comment]
@kcgen I don't know if you have seen the edit I made which hacks autogen.sh

I recalled reading that autoconf macros [git-version-gen script](https://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob;f=build-aux/git-version-gen;h=7aa025365d1724c56029aaa680c9de78587af1ca;hb=refs/heads/branch-2.62) is considered official solution

```
AC_INIT([GNU Autoconf],
»·m4_esyscmd([build-aux/git-version-gen .tarball-version]),
»·[bug-autoconf@gnu.org])
```
:information_source: » is tab

last revision *`scriptversion=2012-03-18.17; # UTC`* suggests it is stable
The advantage is it will do versioning each *./configure* run


For the Debian side, I would probably look at patching it to prefer DEB_VERSION which the deb-helper  script exports after pulling version with
```
DEB_VERSION = $(call dpkg_late_eval,DEB_VERSION,dpkg-parsechangelog -SVersion)
```
:information_source: debian/rules __`include  /usr/share/dpkg/pkg-info.mk`__

This would be better than my current *debian/rules* sed hack

**Comment by dreamer** [comment]
The situation right now is:

- dosbox-staging stable release (built by our CI) -> the version information after invoking `ver` is correct (e.g. 0.75.0)
- dosbox-staging stable packaged by 3rd party (any OS) -> the version information is correct
- dosbox-staging development snapshots (build by our CI) -> the version information is correct  (e.g. v0.76.0-alpha-425-g105b346d)

User will see `git` instead of version info only when our *unstable* builds are made *locally on user's machines*.

**Comment by FeignInt** [comment]
simply placing the [*git-version-gen*](https://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob;f=build-aux/git-version-gen;h=7aa025365d1724c56029aaa680c9de78587af1ca;hb=refs/heads/branch-2.62) in *scripts/* and 

```diff
diff --git a/configure.ac b/configure.ac
index 76e3a811..3cf9750e 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1,5 +1,5 @@
 dnl Init.
-AC_INIT(dosbox,git)
+AC_INIT([dosbox],m4_esyscmd([scripts/git-version-gen .tarball-version]))
 AC_DEFINE([CONF_BRAND],["staging-git"],[Suffix of the .conf file.])
 AC_PREREQ(2.50)
 AC_CONFIG_SRCDIR(README)
```

seems to work , should also **.gitignore**  *.version* and  *.tarball-version* 

I can then patch with *debian/patches/set_version_string.patch*
```diff
Description: prefer DEB_VERSION string
 prioritise DEB_VERSION when setting version string
Author: Feignint <FeignInt@users.noreply.github.com>
Last-Update: 2020-08-13
---
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
Index: b/scripts/git-version-gen
===================================================================
--- a/scripts/git-version-gen
+++ b/scripts/git-version-gen
@@ -144,6 +144,12 @@ then
         && echo "$0: WARNING: $tarball_version_file is missing or damaged" 1>&2
 fi
·
+# prefer DEB_VERSION
+if test ! -z "$DEB_VERSION"
+then
+  v="$DEB_VERSION"
+fi
+
 if test -n "$v"
 then
     : # use $v
```
and drop my sed hack from debian/rules ( I just need to **export DEB_VERSION** instead )

in the yaml, either create the **.tarball-version** file, or test **$VERSION** in same way as I did with **$DEB_VERSION**
:warning: actually, I should add checks to ensure the version string makes sense

the git-version-gen defaults to **UNKNOWN** when shallow and no meta file

I have not done a great deal of testing, but thus far it seems to be working as I would expect, at least on Linux no idea about windows/mac

**Comment by dreamer** [comment]
> If they are compiling from
> - an artifact download, VERSION file (…)

What artifact download? Are you suggesting we should create new tarball artifacts, redundant to built-in GitHub functionality?

**Comment by dreamer** [comment]
> ```diff
> -AC_INIT(dosbox,git)
> +AC_INIT([dosbox],m4_esyscmd([scripts/git-version-gen .tarball-version]))
> ```

This is bad solution, because script will be generated during configure phase and not compilation phase. It will work ok for CI and packagers (but we don't need it for CI and packagers, simple sed works fine for those cases already), but it will be harmful for people compiling locally.

If we went this route, then some users would keep seeing otdated version info in their builds, which is *worse* then seeing placeholder info.

**Comment by kcgen** [comment]
Ideally we'd move the functionality as close to the system that knows about it: that being git.
Something like that git "on-commit" trigger that writes a one-liner `version.h` file, which is picked up universally regardless if we're using autotools / VisualStudio / cmake / ...

**Comment by kcgen** [comment]
> other alternative implementation ideas **_in the form of PR_** are welcome

Here here to that :-)  If anyone wants to tinker with this, please push a PR!

**Comment by FeignInt** [comment]
> User will see `git` instead of version info only when our _unstable_ builds are made _locally on user's machines_.

If they are building locally from git with annotated tags they will see correct version string
if they git pull, they should at least do **`autoconf -f`** which will force recreation of **configure**
Ideally they should **make distclean; ./autogen.sh**, which they should be doing anyway.

It won't fix github zip download, or shallow fetch, or tarball lacking version meta

But it does address Akuma's request

It will break some seds
```
sed -E 's/(AC_INIT.+,[[]?)[^])]+/\1'$VERSION'/' # fails
```
but anyone using such seds can probably figure out that they no longer need them.
or can fix their sed e.g.
```
sed -E 's/(AC_INIT.+,).+/\1'$VERSION')/' 
```
/!\ assumes one line in configure.ac

Alternative is to document the sed in build instructions and/or include the ** sed ...$( git describe ... ) ... | autoconf ** in either autogen.sh or some other helper script ( like build.sh )

**Comment by dreamer** [comment]
> If they are building locally from git with annotated tags they will see correct version string
> if they git pull, they should at least do **`autoconf -f`** which will force recreation of **configure**
> Ideally they should **make distclean; ./autogen.sh**, which they should be doing anyway.

People modifying and building from our Git repo should do neither of those things. It will trigger a clean build even when incremental one would work just fine.

I don't think documenting sed in build instructions is necessary, because it's easier to just run `git describe`; also, it will lead to packagers running sed or patching our release branches, which would be bad.

**Comment by dreamer** [comment]
WIP, unfinished, proof of concept solution: 83cc8efaa63887b96a0cd70803892a807b6a23aa (branch `po/version-2`)

Pros:

- doesn't *require* clean build to work
- doesn't *cause* full rebuild
- maybe it can replace a *single* sed line in our CI scripts
- works nice for users building locally and developers

Cons:

- (nitpick) slows down build a little bit - new cpp file is generate on every build
- does not work for MSVC builds, thus introducing diffrent beheviour for Windows and non-Windows builds (maybe a big deal, maybe not, I don't know)
- it complicates something that otherwise was trivial

**Comment by FeignInt** [comment]
> WIP, unfinished, proof of concept solution: [83cc8ef](https://github.com/dosbox-staging/dosbox-staging/commit/83cc8efaa63887b96a0cd70803892a807b6a23aa) (branch `po/version-2`)
> 
> Pros:
> 
>     * doesn't _require_ clean build to work
> 
>     * doesn't _cause_ full rebuild
> 
>     * maybe it can replace a _single_ sed line in our CI scripts
> 
>     * works nice for users building locally and developers
> 
> 
> Cons:
> 
>     * (nitpick) slows down build a little bit - new cpp file is generate on every build
> 
>     * does not work for MSVC builds, thus introducing diffrent beheviour for Windows and non-Windows builds (maybe a big deal, maybe not, I don't know)
> 
>     * it complicates something that otherwise was trivial
> 
>     * a full solution will need to address or at least document all the edge-cases that won't/can't be handled: shallow clones, tarball downloads, missing bash, missing git, etc, etc

That is a poor solution that causes even more problems for packagers

for example
```
0.76.0~alpha~425~g105b-1+u20.10
```
The **-1+u20.10** is lost.

I would just end up either patching your solution out and reverting to how it is currently
or patching it to prefer DEB_VERSION, trivial with the established *git-version-gen* script.

For the record, The only real problem with the present state is that *some* of those who compile themselves do not know how to set the version string and see only **"git"**
Simply documenting using sed to set the version string solves that problem. If it crops up again, point them to build.md. I seriously doubt that detailing sed for setting version is going to change the behaviour of packagers, they are most likely already using sed to set version string.

**Comment by FeignInt** [comment]
I've warmed to it, 

no need for bash, or UUOE | sed
```
cat <<EOT
blah blah
        return "$(git describe --dirty)"
}
EOT
```
would work just fine

however

configure,ac
```
AM_CONDITIONAL(GIT_DESCRIBE, test -d .git)
AM_CONDITIONAL(GIT_TARBALL, test "x$( basename "$PWD" | cut -c 16 )" = "x0" )
```

Makefile.am
```make
.PHONY: version.cpp

if GIT_DESCRIBE
version_string != git describe --dirty
endif
if GIT_TARBALL
# only set if git describe didn't, assumes git init,git remote add, ...
version_string ?= $(subst $(dir $(abs_top_srcdir))dosbox-staging-,v,$(abs_top_srcdir))
endif
version_string ?= unknown
version.cpp.in  = // This file was automatically generated, edits will be lost.\n$
version.cpp.in += const char *DOSBOX_GetVersion()\n{\n\treturn \"$
version.cpp.in += $(version_string)$
version.cpp.in += \";\n}

version.cpp:
» @echo -e "$(version.cpp.in)" >$@

```
» is `<tab>`

The git test is dumb, in that it does not check if shallow (yet)
simply being shallow is not a show stopper, my Weekly PPA push is shallow but I fetch "since date" after getting the meta from guthub API for the aplha tag

It should support release tarball/zip, until version hits 1.x.x
assumes the dir was not renamed

Since it is checking for .git, the lack of *git* command is unlikely to be an issue

no bash, so that isn't a problem
 
I have no idea if windows will be happy with **basname $PWD | cut**
I guess Mac would be ok with it, but just a guess.

The conditionals are set during *configure*. So if they go renaming the src dir or adding/removing *.git*  and don't re-run *configure* the logic will be blind to the changes. This is very unlikely to happen.

I would just have debian packaging patch
```diff
-version.cpp.in += $(version_string)
+version.cpp.in += $(DEB_VERSION)
```

**Comment by dreamer** [comment]
I think I have an idea how to get rid of generating the file altogether, will show it in 2nd proof of concept.

**Comment by FeignInt** [comment]
I look forward to it

I do have a tighter git_describe test
```
AM_CONDITIONAL(GIT_DESCRIBE, test -d .git -a "$( git tag | wc --lines )" -gt "0" )
```

- A truly shallow clone will be set "unknown", unless the *abs_top_srcdir* happens to have a 0 at char. 16

- A shallowish *( git fetch --shallow-since= )* that pulled in a tag, like [this commit](https://github.com/FeignInt/dosbox-staging-deb/commit/69ef17785c2415dcf68d792ff5f8644ef393aa01) does, would be set as per *git describe*

actually, regards "unknown"
```
version_string ?= $(VERSION)
```
may make better sense as the fallback

This seems to work
```make
.PHONY: config.h
if GIT_DESCRIBE
new_VERSION != git describe --dirty
endif
if GIT_TARBALL
# only set if git describe didn't, assumes git init,git remote add, ...
new_VERSION ?= $(subst $(dir $(abs_top_srcdir))dosbox-staging-,v,$(abs_top_srcdir))
endif
new_VERSION ?= $(VERSION)
current_VERSION != grep -Po "( VERSION .)\K[^\"]+" $(abs_top_srcdir)/config.h

config.h:
»$(shell test "$(current_VERSION)" != "$(new_VERSION)" &&    \
»sed -i -E 's/^(D.+"VERSION.+=.{4})[^\\]+/\1$(new_VERSION)/' \
»$(abs_top_srcdir)/config.status )
```

As it messes with config.h it triggers a full rebuild, but only if VERSION changed

no idea if windows will be happy with the *grep -P*

**Comment by dreamer** [comment]
Note for my future self: Meson supports this functionality out of the box: https://mesonbuild.com/Reference-manual.html#vcs_tag
