### ISSUE TITLE
Snap package: Joystick doesn't work

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#597]
**Describe the bug**
As per title. A user left me a report, that joystick/controller does not work at all when dosbox-staging is installed via a snap package (user does not have a GitHub account and prefers not to create one).

Needs to be confirmed, but I would say it's highly likely, that existing snap package is missing some API check and no input events are forward via SDL2 in the result.

To be investigated…

**Additional context**
Theoretically, this should be a bug report against snap package repo and not our repo, but our plan is to take over snap packaging for 0.76.0 release (as it's the best way to assure users of Ubuntu 16.04, 18.04, and other distros will have out-of-the-box access to FluidSynth feature).

So if we're going to take it over anyway, let's make sure the joystick issue is addressed as well.

**Comment by kcgen** [comment]
My hunch is that this is a security block. Snap packages adhere to a "least privileges needed to run" model, where access to memory, file-systems, directories, namespaces, and control groups all have to be explicitly granted.

My guess is the snap integrator enabled just enough access until the the GUI game to life, because access to `/dev/input/joyX` or `/dev/js0` will be silently handled by dosbox as if a joystick simply isn't plugged in.  

I wouldn't doubt if external MIDI players (via the UNIX 0:12x socket) would similarly be blocked, which is another very nice benefit of FluidSynth integration.  

Same with TCP/IP network access via the softmodem; I woulnd't doubt if that's entirely cut off too (unless the Snap integrator knows about multiplayer).

**Comment by dreamer** [comment]
I definitely remember that external MIDI players were completely blocked when I tested DOSBox-X snap package. It won't be such a big deal when using integrated FluidSynth (but is still leaves out all users who want to forward MIDI to the physical synthesiser).

The good news is: when we'll take over the Snap package, most of the decisions will be ours to make. I started reading snap documentation some time ago, and their sandboxing seems to be more user-friendly and not as restrictive as flatpak sandbox.

**Comment by kcgen** [comment]
Snap packaging support is outside the project scope. The issue should be brought to those who authored the snap package. 
Closing.

**Comment by apandada1** [comment]
@dreamer Can you update to the latest version in the snap and check if the issue still exists?

**Comment by kcgen** [comment]
@apandada1 , requests involving 3rd-party created packagers (Snap/Flatpak/ZeroInstall/NIX/etc..) should go to those maintainers and their users. 

The maintainers of Staging itself don't have time to be involved in all of the activities that will ultimately come about from each of these 3rd party packages: install issues, features that are missing, features that blocked due to security issue or packaging issues. And so on.

**Comment by apandada1** [comment]
I did not notice that @dreamer was a maintainer :sweat_smile:. I thought he was a user. Sorry about the confusion.

**Comment by kcgen** [comment]
Very much so! 
https://github.com/dosbox-staging/dosbox-staging/graphs/contributors?from=2019-09-01&to=2021-05-01&type=c
Has had other priorities in current months. Such is open-source; we all contribute when we can.

**Comment by popey** [comment]
For anyone coming to this, the snap does support joystick, it's just not enabled by default.
`snap connect dosbox-staging:joystick` will enable it.

**Comment by popey** [comment]
Further to this, I've requested that the `joystick` interface be auto-connected so users don't have to issue the command above. https://forum.snapcraft.io/t/joystick-autoconnection-for-dosbox-staging/28542

**Comment by popey** [comment]
This is now approved, so the joysticks/gamepads should work out of the box in dosbox-staging snap now.
