### ISSUE TITLE
Utility drive / Tools drive

### ISSUE THREAD

**Issue by Akuma-Git** [dosbox-staging/dosbox-staging#601]
**Is your feature request related to a problem? Please describe.**
The DOSBox Z: drive is for dosbox tools eg: loadfix, mount, mixer, debug
This is basically the same but for user tools:
* Sound files: Gravis Ultrasound patches (ULTRASND)
* File Managers: Volkov Commander/Norton Commander
* Archivers: ARJ/LHA/ZIP
* Dos-Extenders: dos4gw, cwsdpmi, dos32a

**Describe the solution you'd like**
A folder in userdata or .config where users can copy files to (host) or install to (from dosbox)
Maybe something that automatically adds folders to the path, but that might not be feasible,
due to the path length limited at 255 bytes iirc.

**Describe alternatives you've considered**
Do it manually: 
`mount y ~/.config/dosbox/apps or mount y userdata\dosbox\apps`

**Additional context**
This prevents users from copying files, over and over.
It also takes part of the incentive away of starting dosbox with multigame folders.

**Comment by Wengier** [comment]
Although this feature suggestion is asked in the dosbox-staging issue tracker, I feel that it is especially useful for DOSBox-X because DOSBox-X supports DOS software (including games and applications) equally, so I have already added the feature to the latest DOSBox-X code (just put your own programs or files in the apps directory which will appear on the Z drive). Thanks for making such a suggestion, and hopefully this feature will be added to dosbox-staging in the future as well.

**Comment by kcgen** [comment]
Thanks for the heads up @Wengier. Would you be able to link to the commit where you've already added this feature?  :+1:

**Comment by Wengier** [comment]
The DOSBox-X commit I made is here:

https://github.com/joncampbell123/dosbox-x/commit/452e386b2fa4cdfca554e8598f726c1303a5457f

Part of the code is for long filename (LFN) support of the program files added to the Z drive, as DOSBox-X supports long filenames in addition to 8.3 names. Since dosbox-staging does not support the LFN feature yet, this part of code probably don't apply to dosbox-staging at this time.

**Comment by kcgen** [comment]
Thanks @Wengier.
Thinking about this for staging, one approach would be something like this:

 1. If `drive_z/` directory exists inside `dosbox-user-config-directory`, then overlay-mount it to `z:\`

 2. If a write occurs to z:\, then
    a. Check if step 1 has been performed, otherwise create `drive_z/` and perform step 1
    b. If successful, allow the write to continue, dropping the file inside the overlay mount.
    c. If failed, inform the user we couldn't create `drive_z` and reject the write with a failure code

**Comment by Akuma-Git** [comment]
> Although this feature suggestion is asked in the dosbox-staging issue tracker, I feel that it is especially useful for [DOSBox-X](http://dosbox-x.com/) because DOSBox-X supports DOS software (including both games and applications) equally, so I have already added the feature to the latest DOSBox-X code (just put your own programs or files in the "drivez" directory which will automatically appear on the Z drive). Thanks for making such a suggestion, and hopefully this feature will be added to dosbox-staging in the future as well.

You wouldn't happen to have a solution for these already ?
https://github.com/dosbox-staging/dosbox-staging/issues/542

**Comment by Akuma-Git** [comment]
> Thanks for the link @Wengier, and insight into what's involved regarding long filenames.
> 
> Thinking about this for staging, one approach would be something like this:
> 
>     1. If `drive_z/` directory exists inside `dosbox-user-config-directory`, then overlay-mount it to `z:\`
> 
>     2. If a write occurs to `z:\`, then
>        a. Check if step 1 has been performed, otherwise create `drive_z/` and perform step 1
>        b. If successful, allow the write to continue, saving the file inside the overlay mount.
>        c. If failed, inform the user we couldn't create `drive_z` and reject the write with a failure code

Already had my setup before I discovered the overlay, but the only thing that held me back changing it to Z: was the possibility of deleting legitimate files from it (mixer, debug, loadfix)

So a mitigation for this is preferable as I assume you don't want to deal with bug reports from people to discover they deleted something.

**Comment by dreamer** [comment]
Overlays currently do not work with Z drive - author of the overlay feature decided not to support this case for some reason. I think we'll implement utility drive by removing this limitation :) (but we'll see as I'll dig deeper into the code).

**Comment by Wengier** [comment]
Overlays at this time are for mounted local drives **exclusively** - it is simply a subclass of the local drive class. It will require a major rewrite if you want to make it work for virtual drives. Instead, I think it is much easier to add a config option to remove specified file(s) from the Z: drive, as I have already done for DOSBox-X (so that you can now add, replace or remove **any** files you want from the Z drive).

@Akuma-Git I don't use the debugger often, but @joncampbell123 (the DOSBox-X project maintainer) is very familiar with the debugging feature.

**Comment by Wengier** [comment]
Also, I agree with @Akuma-Git that a full write ability on the Z drive from inside the emulator may not be desired. That is why I think it may be better to make the Z drive fully configurable from outside the emulator (DOSBox-X or dosbox-staging), but not writable from inside the emulator.

**Comment by kcgen** [comment]
>  I agree with @Akuma-Git that a full write ability on the Z drive from inside the emulator may not be desired.

Right - I suppose someone could DoS themselves by overlaying same-named executables for those in Z:\ (although the fix would be pretty straight forward.. just delete or rename them in `~/$conf/drive_z/`.

> Overlays at this time are for mounted local drives exclusively - it is simply a subclass of the local drive class. It will require a major rewrite if you want to make it work for virtual drives. 

That's good to know @Wengier!  I hit similar issues when I tried to augment directory-style CDROM mounts (ie: `mount d some/directory -t cdrom`) with MSCDEX's CDDA audio.  It required separating all the CDDA calls from the image-specific class, and then deriving two new CDDA-capable filesystem classes (image-drive + CDDA and local-drive + CDDA).  It was far too much work and risk while only bringing a small bit of convenience. 

So given the wrinkle you mentioned (and that this is purely convenience-related), maybe there's a "good enough" solution that doesn't involve over-loading Z:\ with two purposes?

Similar to dosbox consuming Z:\ for it's own internals, perhaps we provide an out-of-the-box "user drive" or "utility drive" (both nicely starting with "u"), as `u:\` drive, that users can place common utilities and tools just like dosbox has it's own tools on `z:\`.

Pseudocode:
 
1. dosbox starts and creates `~/<confpath>/drive_u/` if it doesn't exist.
2. dosbox mounts `drive_u` it to `U:\`: `mount u ~/<confpath>/drive_u/`. 
3. dosbox adds `U:\` to the PATH, making it `PATH=Z:\;U:\`

I think this would bring a lot of convenience to intermediate and novice users wanting to use a couple favorite utlities and  perhaps place their `ultradir` somewhere.

**Comment by Akuma-Git** [comment]
> @Akuma-Git I don't use the debugger often, but @joncampbell123 (the DOSBox-X project maintainer) is very familiar with the debugging feature.

@joncampbell123: if you happen to read this and feel up to it before 2030 or so, much obliged!

**Comment by joncampbell123** [comment]
@Akuma-Git What would you like to know about the debugger?

I'm taking a bit of a break from DOSBox-X to work on something for the DOS games jam this fall.

**Comment by Akuma-Git** [comment]
> @Akuma-Git What would you like to know about the debugger?
> 
> I'm taking a bit of a break from DOSBox-X to work on something for the DOS games jam this fall.

I need a solution for Linux to lock the debugger window to 80x50 like in Windows.
https://github.com/dosbox-staging/dosbox-staging/issues/542

When I move windows around, sometimes they become smaller than 80x50 and that breaks the debugger. Which can be very frustrating, depending on the length of the session.

**Comment by joncampbell123** [comment]
DOSBox-X does not support a fixed size debug interface because you can't force it like you can Windows. In fact DOSBox SVN's hard-coded size in Linux just causes crashes if the console falls below 80x50 for any reason. The best way to provide a debugger interface is to go with what the system gives you and resize it when the system says the user resized it. DOSBox-X's debugger interface was heavily modified to present each part as a window and appear/disappear/resize as appropriate for that reason. I can't force a fixed size console in Linux, sorry.

**Comment by Akuma-Git** [comment]
@joncampbell123: I'm taking the conversation to https://github.com/dosbox-staging/dosbox-staging/issues/542.

**Comment by Burrito78** [comment]
We have a tools drive now.
