### ISSUE TITLE
Adding a BASIC interpreter (GW-BASIC/QBASIC 1.1 level)

### ISSUE THREAD

**Issue by Arucard1983** [dosbox-staging/dosbox-staging#604]
Apart of a built-in text editor (as referenced by this issue https://github.com/dosbox-staging/dosbox-staging/issues/392) idea that can be useful to edit DOS games settings files directly on the emulator, one of fun stuffed DOS that was shipped with real MS-DOS and Windows 9x (requires a manual installation from the CD-ROM) was the inclusion of a BASIC interpreter.

My suggestion was to include the "basic" command (and the alias qbasic and gwbasic, if necessary) to start the interpreter or to run BASIC scripts. To maintain the level of compatibility, I suggest to support the syntax of the old BASIC standard that was implemented on GW-BASIC and the earlier QBASIC.

Essentially, it was the old fashioned unstructured BASIC language with enumerated lines, and goto's to everywhere, that was intended to replicate.  QBASIC 1.1 beginning to support structured programming with custom functions more akin to the modern programming standards.

On Github exists several projects to implement a basic interpreter on C/C++ that could be merged to DosBox code and used to implement the featured interpreter. Additional functions for graphics could be added later, once the initial commit was made.

One of BASIC interpreters that could be used as a base to DosBox BASIC was this prototype:
https://github.com/spenot09/Cpp-BASIC-Interpreter

**Comment by Akuma-Git** [comment]
This could be hung under: https://github.com/dosbox-staging/dosbox-staging/issues/601

**Comment by dreamer** [comment]
I just closed #392 as a rejected feature, but including a Basic interpreter is a little bit different beast. Putting this one in backlog, waiting for people who might be interested in implementing this.

I looked briefly at Cpp-BASIC-Interpreter code - I would much rather have properly written interpreter (with tokenizer, parser, etc) than a toy (no offence intended towards that project).

**Comment by dreamer** [comment]
Oh, and Microsoft release GW-BASIC source code on MIT license (therefore we can use it): https://github.com/microsoft/GW-BASIC so one way of approaching this might be to translate their asembler into nasm, co we could use it on various OSes.

**Comment by Arucard1983** [comment]
Other similar project is the Bywater BASIC interpreter.

However, I agree that such feature requires a little planing, since GW-BASIC and QBASIC explore the graphic features of IBM-PC, and any implementation would use the DosBox BIOS functions to work.

**Comment by Arucard1983** [comment]
Those two projects runs the simpler BASIC programs from QBASIC as long don't had any graphical function or the USR assembly routine (Qbasic was deprecated such features through).

Things such as presented by Tiny-Basic, like:
`REM This code prints n fibonacci numbers
LET a = 0
LET b = 1
LET n = 10

REM This is how loops work for now
100 PRINT a
IF n = 0 THEN END
LET t = b
LET b = a + b
LET a = t
LET n = n - 1
GOTO 100`

Or requiring user inputs:

`PRINT "How many stars do you want?"
LET stars = 0
INPUT stars
10 IF stars = 0 THEN END
PRINT "*"
LET stars = stars - 1
GOTO 10`

Runs fine on Qbasic and bwbasic.

**Comment by LowLevelMahn** [comment]
> Apart of a built-in text editor (as referenced by this issue #392) idea that can be useful to edit DOS games settings files directly on the emulator, one of fun stuffed DOS that was shipped with real MS-DOS and Windows 9x (requires a manual installation from the CD-ROM) was the inclusion of a BASIC interpreter.

first question would be: What Basic Interpreter and which Version and how kompatible need it to be? just a Interpreter like the MSDOS 5 shipped QBasic?

**Comment by Arucard1983** [comment]
@LowLevelMahn 
Yes, a open-source version of a BASIC interpreter that are similar to QBASIC syntax would be enough.

**Comment by LowLevelMahn** [comment]
so something like https://www.freebasic.net/, but why not install it yourself if you need it? adding it to the dosbox staging default will extend the workload for the developers here to source updates/maintanance or building of newer binary versions of this interpreter - could be very time consuming
- no problem if there is a large suffering user-base for this but i've personaly never heard anybody ask for a QBasic like interpreter in dosbox besides you :)

**Comment by dreamer** [comment]
That's why I suggested GW-BASIC - it would be a fixed version, exactly the same program people used in real DOS.

**Comment by LowLevelMahn** [comment]
so something like this: https://robhagemans.github.io/pcbasic/ (a GW-Basic Kompatible Interpreter)

according to: https://www.infoq.com/news/2020/06/microsoft-gw-basic-open-source/
First GW-Basic was shipped with DOS, then optimize BASCOM BASIC and then  superseded by QBasic, there was also
BASICA available in very early times of DOS

so it needs to be a non DOS-Version of GW-Basic - because the open source release of Microsoft is a very old version and not fully buildable (my last information) - so it needs to be buildin dosbox

but there is still the question: how big is the userbase?

**Comment by affonsoamendola** [comment]
I dont see how bundling a BASIC interpreter is different than including EDIT, and doing any of them opens the door to "Hey we should include a C compiler! Hey we should include an Assembler! Hey I dont like EDIT lets add vim", I think all of those can be considered "external programs" or "external utilities"

I think all of those things are great ideas, but probably for side project like a dosbox-utils repository, and then maybe add a flag when building dosbox-staging to download and build it (Kind of like MAME's utilities, but on another repository), but I think keeping it optional is a good idea.

But whatever the path decided on bundling, I think that using the original Microsoft open-sourced thing gives me a very cool legit feeling, I mean, it is the original thing right!

So if the decision is made to use MS GW-Basic, we would either need to find a way to cross-compile it (it is 16-bit code, I've been experimenting with compiling 16 bit code natively and the only way I found to do it is with OpenWatcom, but that would create a probably unwanted dependency on that project), or compile it inside dosbox, which would be a pain, or rewrite the entire thing to a format that we can compile (@dreamer mentioned NASM, never worked with it so cant say anything about that)

Is this view of things correct?

**Comment by dreamer** [comment]
@affonsoamendola Yes, 100% :) I believe this is exactly the best way of pushing forward with this.

Few weeks ago I tried if I could maybe compile some binaries from Microsoft MS-DOS archive or GW-Basic archive repos (all files in there are written in assembly, using MASM; and sources for MASM 2.x are included). Unfortunately, it turns out files in there are mish-mash of various versions (sometimes incompatible) recovered from various floppy disks - those files are slightly corrupted and need to be manually fixed to get something that works… There were no version control systems back then, so yeah… ~90% of required asembly code is in there, maybe more - but there's no obvious way to build it ATM. But crucially - those assembly sources are thoroughly documented by original authors in the 80s.

I see two routes towards making this code usable again:

1. Hack on this old MASM assembly and try to bootstrap the environment using available files (pre-built masm.exe is included in the archive). But working in programming environment from 80s is not fun and not very productive…
2. Translate/transpile MASM 2.x (or whatever old version is used in there) to NASM. I don't know any existing project that can do this translation… but it's translating from one (old) assembly syntax to another (more feature-rich) one. We can do this. [Here's some more details.](http://left404.com/2011/01/04/converting-x86-assembly-from-masm-to-nasm-3/)

I suggested using [Netwide Assembler](https://www.nasm.us/), because it's cross-platform, maintained (for more than 2 decades), very well documented, and has proper Free license. It can create .COM files (I tested it and it was easy, I was able to generate simple .COM program, runnable in dosbox-staging, using Linux, and everything necessary was provided by my distro). It can also create small 16-bit .EXE files (I have not tested this; [more info here, I don't know if it's up-to-date](https://www.csie.ntu.edu.tw/~comp03/nasm/nasmdoc7.html)). NASM is also used by FreeDOS project.

> I've been experimenting with compiling 16 bit code natively and the only way I found to do it is with OpenWatcom, but that would create a probably unwanted dependency on that project (…)

Yup, unfortunately :(

For generating 16-bit code I investigated the following solutions:

- GCC - [can be tricked into generating 386 COM file runnable in dosbox](https://nullprogram.com/blog/2014/12/09/) ;) [another article on the same topic](https://sudonull.com/post/15640-How-to-build-a-dosovsky-COM-file-with-the-GCC-compiler)… but there are limitations
- Turbo Pascal / Turbo C - probably the easiest route to have something working easily. TP is not Free though, so we have the same dependency problem as OpenWatcom. TP binaries can be freely used (certain versions, not all of them). It is much easier to setup programming environment for DOS than any other option (still).
- DJGPP - I think the project is dead? There were some forks merging-in newer GCC, but I think they didn't pick up steam. Tried to prepare DJGPP based build environment for myself in FreeDOS, but it was very unwieldy and not fun.
- FreePascal - does not have feature for cross-compiling to DOS built-in - it requires manual build AFAIR. Overall better compiler than TP, and widely available on any OS.
- bcc: Bruce's C compiler - not sure, haven't used it. I expect it will be problematic (e.g. my Linux distro does not package it, and package/binary name conflicts with BPF Compiler Collection - unrelated to DOS in any way)
- [SmallerC](https://github.com/alexfru/SmallerC) - looks promising (2-clause BSD license); project seems inactive (but maybe it's "good enough")

And tried one solution for writing *new* DOS binaries / utilities for us (but it doesn't work ATM, as  Rust Nightly evolves built-in assembler feature):

- [Creating DOS executables in Rust](https://github.com/o8vm/rust_dos) - it's not relevant to this issue though (bundling BASIC), just listing it as one of the things I tried :)

**Comment by LowLevelMahn** [comment]
FreeBasic (https://www.freebasic.net/) can also build for DOS, or the GGC IA 16 (https://github.com/tkchia/gcc-ia16, gcc 6.3 with real 16bit support, in use by FreeDOS)  project (Tiny and Small Support)

**Comment by dreamer** [comment]
> and don't forget the OpenWatcomV2 project 

It is the same legal landmine as any software licensed under horrible Sybase Open Watcom Public License. It's a shame that DOS open source community is bound by this license. We won't be.

**Comment by affonsoamendola** [comment]
GCC-IA-16 looks extremely cool, it cannot be used to compile GW-BASIC, but for other programs written in C or using the GNU Assembly Syntax it is a nice option.

Some people have tried their hand (and some succeeded!) in compiling it, namely [tkchia](https://github.com/tkchia/GW-BASIC), the same person behind GCC-IA-16, the code still needs some fixes (There's some stuff missing I think) and they used JWasm to do the compiling.

Thing is, JWasm is a fork of the OpenWatcom assembler so it is under the same license, and as always, all roads in retro-programming for DOS lead to Sybase.

But still, having a compilable code is a bit of an improvement from the original uncompilable source so thats a plus.

**Comment by LowLevelMahn** [comment]
i still don't understand what the rational is for discussing the integration of an very very old version of GW-BASIC?

the open source release seems to be shipped with DOS 1.x around ~82-83

according to https://www.os2museum.com/wp/gw-basic-source-notes/
the open source release is very near to "EAGLE GWBASIC Version 1.20 11/11/83 (C) Copyright Microsoft 1982"

and in the early times there wasn't a "official" Microsoft version of GW-Basic, all OEMs more or less got its
own micro tiny different version around

beside history preserving reasons - what is the benefit of having an outdated version combined with dosbox?

if i need to run GW-Basic programs then i can use GW-Basic compatible PC-BASIC (http://robhagemans.github.io/pcbasic/) to run under Windows/Linux
and if i really need the good old GW-Basic i can grab a copy of the last version at numerous place in the internet - even copying
the last GWBASIC.EXE from DOS 4.01 works (its self contained) - i know its not a free version but who needs GW-BASIC out-of-the-box?

so whats the point?

**GW-Basic History:**

```
DOS 1.25 (May, 1983)
BASIC.EXE,BASICA.COM,BASIC.COM 
Basic 1.12
<-- Microsofts open source GW-Basic code is from somewhere around here

DOS 2.2-2.12 (October, 1983-July, 1985)
BASIC.EXE,BASICA.COM,BASIC.COM 
Basic 2.01

DOS 3.0 (April, 1985)
BASIC.EXE,BASICA.COM,BASIC.EXE 
Basic 3.00

DOS 3.10 (May, 1986)
BASIC.EXE,BASICA.COM,BASIC.EXE 
Basic 3.11

DOS 3.20 (July, 1986)
BASICA.EXE 
"GW-BASIC 3.11"

DOS 3.31 (November, 1989)
GWBASIC.EXE
"GW-BASIC 3.22"

DOS 4.01 (April, 1989)
GWBASIC.EXE 
"GW-BASIC 3.23" (also the last release)

DOS 5 (Juni 1991)
GWBASIC.EXE replaced with QBASIC.EXE
```

**Comment by affonsoamendola** [comment]
Yeeah... I think you're right.

Might have gotten a bit carried away with the love of all things ancient, so the version of GW-BASIC we've been discussing might be way older than needed.

But I think the main reason for having it included is just what you said, it would be a fun project, since the source code is locked in time, its a one time compile, include with the utils and forget it, and we will forever have the power of GW-BASIC.

Also the reason to including this particular version of GW-BASIC is mostly because its the only version that's been open-sourced (I believe), so we CANT include later versions, at least not without infuriating uncle Bill from 40yrs ago (And infringing some copyright)

But all that being said, I do think you are right, I believe this is MOSTLY for fun and/or historical preservation, so it should be rather low priority, but that is a rather nebulous concept, since people will work on what they are interested.

And I'm rather interested in this, so.....

**Comment by LowLevelMahn** [comment]
> And I'm rather interested in this, so.....

you could add an GW-Basic compatible intern command (like LOADFIX and others) - you need to derive from a program class inside the Dosbox source to get your own internal application

then use up to date C++ etc. for the Parser/Interpreter and the Dosbox backend to even Support evil PEEK/POKE correct :)

**Comment by kcgen** [comment]
See the wiki page regarding utlities, which recommends installing existing tools via the freeDOS package manager.  Closing.
