### ISSUE TITLE
Acid88 CPU tester produce a CTD

### ISSUE THREAD

**Issue by bleuge** [dosbox-staging/dosbox-staging#638]
There is a new CPU tester by reenigne, the same guy that produced the first 8086 microcode disassembly (at least in public)

https://github.com/reenigne/reenigne
http://www.vcfed.org/forum/showthread.php?76926-8086-CPU-timing-test

running it simply CTD dosbox-staging, 

**To Reproduce**
Just run acid88 from commandline

**Expected behaviour**
Don't crash? :D 

**Environment (please complete the following information):**
Windows 10 64 - 

**Version of dosbox-staging:**
dosbox (dosbox-staging), version v0.76.0-alpha-761-g7bb0

**Configuration parameters:**
Default ones

**Additional context**
I know DOSBOX has never tried to be a perfect cpu emulator (it would be called 8086box instead :D), but don't crashing and producing some results would be nice.

**Comment by dreamer** [comment]
Just tested on Linux, and running acid88 causes dosbox-staging to hang (not crash).

From [acid88 documentation](https://github.com/reenigne/reenigne/blob/master/8088/acid88/acid88.txt):

> * Some tests will only pass with the 1501512 XT BIOS (the "JMP FAR rb" and
"CALL FAR rb" undocumented instructions cause control flow to pass into the
ROM area, and require byte 0xCC at address 0xFFF70 to resume correctly with
the current implementation.

From abovementioned thread:

> It will likely crash on CPUs that don't implement undocumented instructions in a way that is functionally identical to Intel 8088 ones (in particular the JMP, CALL, JMP FAR and CALL FAR instructions with byte sized operands).

In other words, acid88 is likely to hang or crash real hardware as well unless specific CPU and specific BIOS version is used. And only real-life usecase for doing so seems to be running [8088 MPH demo](https://trixter.oldskool.org/2015/04/07/8088-mph-we-break-all-your-emulators/).

@bleuge it would be nice to know - does lack of support for those undocumented instructions prevent any real-life DOS games (or software) from running inside dosbox-staging?

Perfect hardware emulation is [not a priority for dosbox-staging](https://dosbox-staging.github.io/about/) (we are more interested in real-life games instead of artificial benchmarks).

That being said, if someone has free time to investigate what changes to our CPU emulation are needed, feel free to send us PR or document your finding in here.

If changes won't be too invasive, I would be ok with adding e.g. `cputype = 8088_accurate` to be used with `core = normal`.

**Comment by kcgen** [comment]
> @bleuge it would be nice to know - does lack of support for those undocumented instructions prevent any real-life DOS games (or software) from running inside dosbox-staging?

 - We've waiting 18 months for @bleuge to answer the above question (without response).
 - Likewise in the same timeframe, no issues have been opened citing the need for this.

Closing.  If more information comes to light, it can be re-opened.
