### ISSUE TITLE
[RPi4] can't compile latest master

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#646]
**Describe the bug**
can't compile latest master on an up-to-date pi4.

**To Reproduce**
```
./autogen.sh
./configure --disable-opengl CPPFLAGS="-DNDEBUG" CFLAGS="-O3 -march=native" CXXFLAGS="-O3 -march=native"
make clean
make -j2
```

**Expected behaviour**
To properly compile without errors.

**Environment**
* OS: Raspberry OS 10.6 / Buster
* Stock pi4

**Version of dosbox-staging:**
using branch `kc/fps-pacing-1`

**Additional context**
debug output: https://pastebin.com/6TYtHQc5

**Comment by kcgen** [comment]
Thanks for the report @nemo93.

Looks like `./configure` is detecting FluidSynth > 2.x somewhere on the system but one of the necessary functions isn't defined in its header(s).

What do `pkg-config --libs fluidsynth` and `pkg-config --cflags fluidsynth` return?

My guess is the package would have been manually installed because Raspbian's repo doesn't contain fluidsynth. 

If possible, it would be good to delete any *fluidsynth* files and directories you can find in /usr or /usr/local

Once deleted, we can use the new static build of FluidSynth in the contrib areas:
1. Enter the `contrib/static-fluidsynth` directory
1. Run `make`
1. Copy and paste the resulting two `export` lines back into your shell
1. Move back to the dosbox-staging root source directory
1. Perform a fresh ./autogen.sh, ./configure, and then make (with your preferred flags). 

This should build and link clean. I've tested it on my Pi3. Curious how it goes!

**Comment by dreamer** [comment]
Or simply `./configure --disable-fluidsynth` until 2.x will be available on the OS.

**Comment by kcgen** [comment]
I did submit a request to get FS 2.x in Debian Buster (which Raspbian uses as their repo source), however my request was denied because FS 2.x is already in the `testing` repo and will land in Debian Bullseye, which doesn't have an ETA but likely ~9 months from now mid-2021 -- https://en.wikipedia.org/wiki/Debian_version_history#Debian_11_(Bullseye)

**Comment by dreamer** [comment]
So maybe it's available in Raspbian Testing already?

**Comment by kcgen** [comment]
It's way back in the discord history, but I was able to start the install process using the testing branch - but it rippled into Debian's equivalent of RPM hell (eventually wanting to replace libc and other major low-level libraries); fortunately I didn't carry out thoee actions and brick my install!

**Comment by FeignInt** [comment]
@kcgen
have you tried compiling the fluidsynth testing source package with buster 10.6 instead of simply installing the testing package binary package?

very quickly looking at debian/control, build-dep *libinstpatch-dev (>= 1.1.0)* might be a problem, buster's version is 1.0.0, I have no idea what changed between them.
The *debhelper-compat* can simply be lowered to 12 ( but 13 is available in buster-backports )

[#Don't_make_a_FrankenDebian](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian)
[#Some_safer_ways_to_install_software_not_available_in_Debian_Stable](https://wiki.debian.org/DontBreakDebian#Some_safer_ways_to_install_software_not_available_in_Debian_Stable)
https://wiki.debian.org/SimpleBackportCreation

However, as @dreamer pointed out, at the end on the day simply disabling fluidsynth in dosbox-staging is probably much easier.

It would be interesting to know where this rogue fluidsynth comes from, like you say buster does not have *fluidsynth 2.x* and off the top of my head I don't see how ./configure would confuse 1.x for 2.x

**Comment by kcgen** [comment]
On discord a couple months ago, nemo and I tinkered with building FluidSynth from source on our Pi systems because it's not in Buster -- so that's likely the rogue instance.  

> have you tried compiling the fluidsynth testing source package with buster 10.6

I haven't (and admit to having little interest in a debian-only work-around for laggy package maintenance), especially given that the contrib builder creates static and locally-contained files (without any extraneous network or service interfaces) and is cross-platform.

**Comment by dreamer** [comment]
Pinging @nemo93 to paste this info requested by @kcgen - it's likely to root cause of the issue:

> What do pkg-config --libs fluidsynth and pkg-config --cflags fluidsynth return?

**Comment by nemo93** [comment]
Once again I'll have to apologize as it was indeed due to an older fluidsynth compilation attempt. Some pieces were left around in the /usr/local dir on my distro :( After removing any files as @kcgen suggested and following the guide, it works flawless (tested for now only on Under a Killing Moon with Fatboy sf2).

Thanks again (I might put something in the wiki soon re MIDI).

**Comment by kcgen** [comment]
My fault @nemo93 for not giving you a heads up regarding cleaning up our manual build attempt of FluidSynth.

Very happy to hear all is tidy again and you're running with a full-featured build once again.

**Comment by grapeli** [comment]
@nemo93 
[FluidLite](https://github.com/divideconcept/FluidLite) is a FluidSynth 1.x fork that is dosbox-staging compliant. Relatively actively developed. It does not require Glib2.

`cmake . -DFLUIDLITE_BUILD_STATIC=true -DFLUIDLITE_BUILD_SHARED=false -DENABLE_SF3=false -DSTB_VORBIS=false`

In dosbox-staging, you only need to replace the header file `fluidsynth.h` in [midi_fluidsynth.h](https://github.com/dosbox-staging/dosbox-staging/blob/master/src/midi/midi_fluidsynth.h#L31) to `fluidlite.h`.

**Comment by jlopezvil** [comment]
Sorry. I have no exit in compiling dosbox-stagin on pi4.  Attempted all things readed on this post. Maybe some advice o post the compiled file for pi4?
