### ISSUE TITLE
D3D Pixel Shaders

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#661]
**Is your feature request related to a problem? Please describe.**
As mentioned in a previous issue post, I've noticed that there is an intermittent stuttering when running games using the OpenGL output option. The main appeal of this being that you can use GLSL shaders for a potentially more enhanced or authentic experience, which of course, is only available for OpenGL/nb. 

**Describe the solution you'd like**
So my suggestion would be to implement a Direct 3D alternative for using shaders, that being DOSBox-X's D3D pixel shaders. Every computer is different, so having this as an option would definitely add more versatility to Staging.

**Describe alternatives you've considered**
My main alternative for a stutter-free experience with the bonus of shaders has been DOSBox Optionals, which as I've mentioned in my previous issue thread, seems to use a different implementation of OpenGL output. Though the main caveat with that is that theres no drag-and-drop-to-open feature like most mainline DOSBox forks (vanilla, SVN, and staging included). Not to mention it's nowhere near as clean as Staging ;)

**Comment by dreamer** [comment]
No, I will not work and am unlikely to accept DirectX code in our output rendering. We worked very hard on removing broken and complicated DirectDraw support - not with intention of bringing it back again in form of Direct3D, duplicating rendering paths, rewriting shaders in HLSL, introducing maintenance burden and duplicating testing and support effort on our side.

If anyone wants to work on this, then I suggest spending time on #565 (Vulkan support) instead.

If we have a regression in OpenGL support (still nobody except you is able to reproduce it), then it will be easier to fix it instead of bringing in thousands of lines of code for supporting DirectX, and then spending hundreds of hours on testing.

I'm sorry - rejecting this request.
