### ISSUE TITLE
Linux mobile phones support

### ISSUE THREAD

**Issue by okias** [dosbox-staging/dosbox-staging#666]
Since I've managed to get running `dosbox-staging` on
HW: Librem 5 devkit
SW: PureOS (Debian Bullseye + mobile stuff), [dosbox-staging](https://salsa.debian.org/okias-guest/dosbox-staging), 0.75.1

there is few issues to tackle:

Priority:
- [ ] cpu consumption while idle is 40% of 1 core on arm64 (cortex a53), while on my amd64 desktop/laptop is it 25% and it doesn't matter. On low power device as phone, it would be great if idle could get optimized for battery usage (maybe in exchange for some preciseness?)
- [ ] squeekboard (on-screen keyboard) isn't triggered when DOS prompt is shown

Normal:
- [ ] when dosbox-staging is run from ssh, it won't respect screen size (similar to default old DOSBox behavior) 

Enhancement:
- [ ] only half of dosbox-staging loading screen is shown on 2X scale 720x1440 resolution

**Comment by kcgen** [comment]
@okias , thanks for all the progress rounding up these issues!

Can you please break them out into separate topics?  (ie: idle CPU usage has nothing to do with on-screen-keyboards, which has nothing to do with 2x scaling). 

Separate topics keeps the thread discussion focused; it lets us close a topic as soon as its resolved (instead of pinning open multi-issue threads until every possible concern is addressed). When someone views the list, they can see exactly what an issue discusses instead of _"Here's my grab-bag of issues"_).

Please drop unhelpful text in the subject line.  _"(don't be evil)"_ and _"tracking"_ aren't adding any value.
 - The issue list is by definition a list that we track. We're not going to track this issue any harder than the other issues we're tracking. 
 - We certainly don't try to be evil nor are we implementing evil solutions.  _"Hmm.. should we implement the evil solution?"_  Not this time @dreamer; @okias has requested a non-evil solution.  :-)

**Comment by kcgen** [comment]
Oh! Forgot to mentioned that I've added tags for you:
 - **PureOS** - normally we don't include individual Linux distros, however PureOS is unique in that it includes mobile stuff (touch, onscreen keyboard, etc) so it's very unique from the others.  
 - **Android** - I know you didn't mention Android, I'm adding this simply as the largest other mobile OS (and I've personally build dosbox-staging on Android, but haven't reported issues yet).
 - **handheld** - For issues that might be common or a specific concern regarding hand-helds.  High CPU usage or touch keyboard issue (regardless of mobile OS) might be good examples to get this tag.

**Comment by dreamer** [comment]
@okias Regarding cpu idle usage - do you test in-game or in shell/commandline?

What's your `cycles` setting in `cpu` section? It defaults to `auto`, which means dosbox-staging emulates "3000 cycles / ms" (sort-of like old 30MHz i386 CPU, but not exactly - anywhere between 20MHz and 40MHz, depending on the game) - with defaults, dosbox-staging uses ~10% of single core on my desktop. `auto` then switches to `max 100%` when a DOS program using extended memory is run.

(For convenience reasons I prefer to use `cycles = max 80%` myself, but that's a different topic ;) )

**Comment by grapeli** [comment]
`pidstat -C dosbox -u -r 1`
average ~7-8%
With [dosidle](https://archive.org/details/dosidle) (out of curiosity) an average of ~5-6%.

**Comment by okias** [comment]
- [x] squeekboard won't enter anything (when running under Xwayland, it reports not recognized by SDL... X11 KeyCode 139 (141) and similar errors. On wayland it won't print any errors into terminal. Issue likely between squeekboard <-> SDL

Fixed with recent squeekboard version.
