### ISSUE TITLE
Layer cake configs

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#670]
Configuration values should be prioritized following a layer cake approach:

| Priority | Location |
| --- | :--- | 
| First | Immediate command-line argument: `-userconf gus.conf` |
| Second | Found in the local directory `./dosbox.conf` |
| Third | User's primary configuration `/home/user/.config/dosbox/dosbox-staging.conf` |
| Fourth | Default values built into the binary |

Example with values:

| Priority | Location | Contains |
| --- | :--- | :--- |
| First | `-userconf gus.conf` | `[gus]`<br>`gus = true`<br>`[sblaster]`<br>`sbtype = none` |
| Second | `./dosbox.conf` | `[cpu]`<br>`cycles = 8000` |
| Third | `/home/user/.config/dosbox/dosbox-staging.conf` | `[renderer]`<br>`glshader = crt-lottes-fast.glsl` |
| Fourth | Builtin defaults | everything else as-is |

If the above example files were used, simply running `dosbox` (without any arguments) in the game's directory would give you:

```
[renderer]
glshader =  crt-lottes-fast.glsl

[cpu]
cycles = 8000

.. and everything else default ...
```

And running `dosbox -userconf gus.conf` would give you:

```
[renderer]
glshader =  crt-lottes-fast.glsl

[cpu]
cycles = 8000

[gus]
gus = true

[sblaster]
sbtype = none

.. and everything else default ...
```

This approach is both intuitive to understand and much less cumbersome than remembering to type `dosbox -conf -userconf dosbox.conf -userconf gus.conf` (to effect the same behavior).

**Comment by dreamer** [comment]
I agree, that current behaviour regarding .conf files is… unwieldy. And the layered approach would work better in practice.

But I'm afraid it will introduce serious compatibility issues with games packaged for DOSBox 0.74.x or older - thus staging would no longer be a drop-in replacement for old DOSBox binaries :(

The deal is:

- Bad game packagers throw multiple versions of .conf files into the game installations (which reflects the unintuitive nature of DOSBox normal behaviour with .conf files) - e.g. game can include `dosbox.conf`, `game.conf`, and `gamev2.conf`, and then be run with commandline forcing `gamev2.conf` and some `-c` parameters, bypassing `dosbox.conf`.
- Good game packagers (e.g. GOG, but I expect GUI frontends do this as well) invented their own layered scheme, and enforce it by passing every single `.conf` file in their commandline, in very specific order.

And now the kicker… This would not matter that much if we were concerned only about normal values in .conf files… But DOSBox treats `autoexec` section "specially" :( Later .conf files *do not overwrite* lines in the autoexec section - they *append* to the autoexec :(

- Bad packagers do not care about this and (unknowingly) depend on behaviour where passing single -conf file will not load other .conf files.
- Good packagers do care about this and might use earlier .conf files to prepare env, and later .conf files to load the game.
- (!) The moment we implement layered loading, user setups will start to fail - because if they add `mount C something` in their `dosbox-staging.conf` file, it affects *all the games*, so every single game will refuse to mount game-specific C dir.

I was thinking about the ways to address this in backwards-compatible manner, and as for now I think perhaps we should introduce new conf file section called `include` or `import`? This way users could opt-in into this behaviour, e.g. this way:

```
[include]
conf_defaults = true   # true - load dosbox-staging.conf, false - start with built-in defaults
conf_file_1 = <path-to-conf-file>
conf_file_2 = <path-to-conf-file>
```
Another way could be using a parametrized ini files sections (e.g. git uses this approach, see your `.git/config` file):
```
[include] # non-parametrized include would be synonymous to [include "dosbox-staging.conf"]
use_autoexec = false

[include "path-to-file.conf"]
use_autoexec = true
```

@kcgen What do you think?

**Comment by arrowgent** [comment]
ive had very similar thoughts on this also
i use .bat files for generic modification for all my games instead of using seperate .conf files for each
i know this is fairly frowned upon.  the alternative we see is a dozen full conf files

parts of `[SDL]` and parts of `[DOSBOX]` cannot be modified after dosbox is launched
but everything else can be modified from config inside c:\ dosbox

example:

`imgmount d ~/Games/dosbox/cd_iso/dig95.iso -t iso
config -set "dosbox machine=svga_s3"
config -set "cpu cycles=auto"
config -set "cpu cputype=auto"
config -set "sdl sensitivity=60"
mixer master 95:95
d:
dig
c:
mount -u d
`
