### ISSUE TITLE
dosbox-staging with Xserver

### ISSUE THREAD

**Issue by paul-goodall** [dosbox-staging/dosbox-staging#673]
Hi - apologies for asking a really simple question - I did try to search for a solution but couldn't find the answer.

Is it possible to use dosbox-staging with Xserver?  My intent was to set everything up on an Ubuntu server and then ssh -X over to use dosbox-staging on my local Mac.  Is this supported?

**Comment by kcgen** [comment]
It is possible - I did this many years ago with SVN, although I haven't tried it recently. 
I suggest just trying it, and wrestling with it until you get it. Some tips:
- First, ensure you can atleast pass a simple application over SSH, like `xclock`
- Then move to an X application that uses more advanced API calls, like `glxgears`
- Modern OpenSSH has new security features, so you might need to use ssh -Y instead of -X
- You might need to adjust DOSBox's output mode; if you just get a black window you know the rendering surface is isn't being passed so try `texture` and non-hardware accelerated modes like `software`.
- Finally, you will need another technique to pass the audio (so you might need to write a helper script to create this audio pass-through in tandem when starting DOSBox).
- You might have discard the SSH approach all together in favour or `rdesktop`, VNC, etc.

Finally, the X protocol is quite heavy when it comes to passing raw raster surfaces at high framerates: so expect high CPU usage. Moving 30 fps at 1024x768 at 16bit will saturate your wifi, so you might need compression (which adds lag filling packets). 

Please report back if you have any success! It would surely be worth a wiki page to help others. This information would be helpful for Dosbox DOSbox and all forks.

**Comment by dreamer** [comment]
> Hi - apologies for asking a really simple question - I did try to search for a solution but couldn't find the answer.

Actually, I find this question to be very interesting :)

> Is it possible to use dosbox-staging with Xserver? My intent was to set everything up on an Ubuntu server and then ssh -X over to use dosbox-staging on my local Mac. Is this supported?

I can imagine some interesting use-cases for setup like this, but we provide native macOS bundle. If you use older macOS, then [brew package](https://formulae.brew.sh/formula/dosbox-staging) is the way to go.

Is there something additional about your usecase, that is not covered by our macOS builds?

**Comment by kcgen** [comment]
Follow onto @dreamer 's suggestion: if your DOS game library is hosted on the Ubuntu server, you can NFS-share it to your macOS machine, and run DOSBox locally there. 

A couple resources, but lots out there:

- How to setup an NFS server on Ubuntu https://computingforgeeks.com/install-and-configure-nfs-server-on-ubuntu-debian/

- How to mount an NFS share on macOS https://knowledge.autodesk.com/support/flame-products/troubleshooting/caas/simplecontent/content/how-to-access-to-linux-nfs-share-mac-osx.html

**Comment by paul-goodall** [comment]
Thank you @kcgen and @dreamer for your speedy replies.

These suggestions are great - I'll have a crack and report back with progress.

I didn't do a great job of explaining the rationale for this approach - I'm trying to set-up a retro game that I used to play with my Dad.  I'm in Australia and he's in the UK, and Covid means no travel, so it's one of my Covid projects to get it set up again :D  The game features multi-player via IP and Netbios, but the game is turn-based and sends lots of data between the peers after each turn which ruins the experience.  My thoughts were two host both games via two docker containers on the same server, and pass the UI to him and me via Xserver.

It's a long shot, but I'll see how far I get before I fall over :D

**Comment by kcgen** [comment]
Hi Paul, thanks for the description of what you're trying to accomplish.

It sounds like the games aren't video intensive (ie: more a turn-based), so the remote-desktop approach sounds doable.  

Regarding running two DOSBox's on the same machine: unique network separation via Docker containers isn't needed. You can even run the same `dosbox` binary: feed one instance a `conf` file that sets its serial port as the server/listener and the second a client `conf` file.

To put each of these dosbox instances in separate visual spaces, launch them using a virtual frame-buffer wrapped in a VNCx11 session.

You can start by trialing just the two dosbox's side-by-side and nail down their configurations, and then follow that up by learning about vncx11 and xvfb-run, which is how you can launch them in seaprate x11 spaces (so you and your Dad will get your own desktop and not see eachother).

Your final process space will look like something like this:
```
server
  your logged in session (console)
     Local X11 session (may or may not exist)
     VNCx11 xvfb-run dosbox -conf /path/to/server.conf (serving on :1)
     VNCx11 xvfb-run dosbox -conf /path/to/client.conf (serving on :2)
```

Then you and your Dad will `vncviewer <ip>:1` and `vncviewer <ip>:2`, respectively.

(Just how I would do it)

**Comment by paul-goodall** [comment]
Thanks @kcgen -that sounds really promising, and way smarter than what I was trying to do.

I've gotten up to the point of having the client.conf and server.conf files as needed, such that I can do:

`
[doxbox|dosbox-staging] -conf /path/to/server.conf &
[doxbox|dosbox-staging] -conf /path/to/client.conf &
`

I didn't specify any ports in the .conf files, but just have:
`IPXNET CONNECT 127.0.0.1`
since it's only connecting to localhost.  (I guess IPXNET is just using its default port of 213).

I'm really struggling with the VNCx11 and xvfb-run parts - I cannot get it to work at all.
I've installed x11vnc (assuming that's what you meant instead of VNCx11?) and Xvfb, but other than that I'm at a loss (other than diving into the depths of the interwebs and stackoverflow etc).  I think I'm a bit out of my league here...

**Comment by kcgen** [comment]
@paul-goodall, 

Nice progress in getting both sides of your game speaking to each-other over `localhost`; that's perfect!

Next steps, we'll:
- Adjust your dosbox game conf files to be a bit more compatible with remote dislay
- Wrap both dosbox instances in their own X11 instance
- Export each X11 session using VNC server (the listening ports which you will then expose via port-fowarding on your router or VM instance), and finally ...
- Connect to them using your VNC viewer of your choice (maybe your Dad's running Windows or macOS).

### Let's get started!

1. **Adjust your conf files**

We need to use window-mode, software rendering at 800x600, seamless mouse capture, raw mouse input, no glshader, and without audio.

    ``` ini
    [sdl]
    fullscreen       = false
    windowresolution = 800x600
    output           = texturenb
    texture_renderer = software
    capture_mouse    = seamless middlerelease
    raw_mouse_input = true
    
    [render]
    aspect    = true
    scaler    = none
    glshader  = none

    [mixer]
    nosound = true
    ```
    1. I suggest using a fixed cycles count and the lowest need to ensure acceptable game-play, to afford the remainder of the CPU time for rasterizing & compression (typically JPEG). For example, the following is sufficient for 688 Attack Sub, which is another popular two-player IPX game.

``` ini
cpu]
core      = dynamic
cycles    = 2000
```

1. **Launch your dosbox instances headless**
    1. Enter your client game directory
    1. Run `xvfb-run -l --server-args="-screen 0 1024x768x24" -f /path/to/client/xauth dosbox -conf /path/to/client.conf game.bat`. Run it in the foreground; no `&`
    1. In another shell, discover its DISPLAY number using `ps x | grep Xvfb`.
    You're looking for  `Xvfb :99 ...`, my client DISPLAY is 99, and yours will likely be too.
    1. Do the same steps for your server-side game:
    ` `xvfb-run -l --server-args="-screen 0 1024x768x24" -f /path/to/server/xauth dosbox -conf /path/to/server.conf game.bat`
    1. Get your server-side DISPLAY value (likely 100).
    1. At this point, both instances should be running but invisible because they're in a virtual X11 session

1. **Export each X11 session using VNC**
    1. In a separate shell, enter your client game directory.
    1. Run: `XAUTHORITY=/path/to/client/xauth x11vnc -ncache 10 -display :99.0 -usepw -forever -rfbport 5900 -nocursor -scale 800x600`, where `:99.0` is your client's DISPLAY number and the `XAUTHORITY=...` file path needs to point to the file written after the `-f` xvfb-run arguement.
    1. VNC server will ask you for a password to use for client sessions. It will offer to save this to a file, which it will re-use for future sessions.  Enter your answers, and then leave it running.
    1. In a separate shell, enter your server's game directory.
    1. Run: `XAUTHORITY=/path/to/server/xauth x11vnc -ncache 10 -display :100.0 -usepw -forever -rfbport 5901 -nocursor -scale 800x600`
    1. At this point, both VNC server sessions will have printed something like: `The VNC desktop is: hostname:0 PORT=5900`

1. **Connect to either VNC session**
    1. In a new console, run: `vncviewer localhost:0` to connect to your client, and `vncviewer localhost:1` to your server.
    1. A couple notes: there is no window manager, so the session is simply 100% dosbox.
    1. For your mouse cursor, you will see your game-drawn cursor normally, however a one-pixel black dot cursor will also be faintly visible; it's a minor annoyance that I couldn't completely eliminate; maybe you will find some options to hide it completely.

Assuming the DOS game is stable, you might want to disable the  Ctrl + F9 (Quit DOSBox) shortcut via the key mapper (for these game instances), because if either of you close DOSbox, it tears down the entire house of cards.  (Then again, you will probably want to wrap all of this in an auto-restarting script)
 
At this point, you can expose ports 5900 and/or 5901 (VNC uses TCP, not UDP) on the Internet via router's port-forward option, and see if your Dad can connect :-)

**Comment by paul-goodall** [comment]
Thannks @kcgen - that worked a treat!

I did what you suggested and created a little wrapper script to spin it up and then kill everything off afterwards.
There are probably better ways of doing this than screen (maybe nohup?) but I went with it anyway.
Pasted below in case it's useful to others.  Thanks for the help, I've learnt a lot!

`#!/bin/bash

# OPTIONS...
game_dir="/your/game/dir"

server_screen1_name="server_screen1"
server_screen2_name="server_screen2"
server_display_n=101
server_port=5901

client_screen1_name="client_screen1"
client_screen2_name="client_screen2"
client_display_n=102
client_port=5902

display_res="1024x768"
display_depth="24"
display_settings="${display_res}x${display_depth}"
# ---

if [[ $1 == "start" ]]
then
    
    echo   "xvfb-run --server-num=$server_display_n -l --server-args=\"-screen 0 $display_settings\" -f $game_dir/server_auth dosbox -conf $game_dir/server.conf " \
    > screen1_script1.sh;

    
    echo   "XAUTHORITY=$game_dir/server_auth; x11vnc -ncache 10 -display :$server_display_n.0 -usepw -forever -rfbport $server_port -nocursor -scale $display_res" \
    > screen1_script2.sh;

    
    echo   "xvfb-run --server-num=$client_display_n -l --server-args=\"-screen 0 $display_settings\" -f $game_dir/client_auth dosbox -conf $game_dir/client.conf " \
    > screen2_script1.sh;

    
    echo   "XAUTHORITY=$game_dir/client_auth; x11vnc -ncache 10 -display :$client_display_n.0 -usepw -forever -rfbport $client_port -nocursor -scale $display_res" \
    > screen2_script2.sh;

    chmod 755 screen*sh;
    rm $game_dir/*_auth;
    rm $game_dir/*.log;
    
    
    screen -dmS $server_screen1_name -L -Logfile $game_dir/screen11.log $game_dir/screen1_script1.sh;
    screen -dmS $client_screen1_name -L -Logfile $game_dir/screen21.log $game_dir/screen2_script1.sh;

    # Prevents the x11vnc from running before the x-buffer is set-up.
    sleep 1;
    
    screen -dmS $server_screen2_name -L -Logfile $game_dir/screen12.log $game_dir/screen1_script2.sh;
    screen -dmS $client_screen2_name -L -Logfile $game_dir/screen22.log $game_dir/screen2_script2.sh;

fi

if [[ $1 == "stop" ]]
then   

    screen -X -S $server_screen1_name quit;
    screen -X -S $server_screen2_name quit;
    screen -X -S $client_screen1_name quit;
    screen -X -S $client_screen2_name quit;

    # For some reason the Xvfb lives on after the screen has died:
    kill $(ps x | grep "Xvfb :" | awk '{print $1}' | head -n 2 | column)
   
fi

# -- END
`

**Comment by kcgen** [comment]
Great to hear that @paul-goodall, and thanks for sharing your tidy script to help others!
