### ISSUE TITLE
Provide a GUI-less operation mode

### ISSUE THREAD

**Issue by clausecker** [dosbox-staging/dosbox-staging#688]
**Is your feature request related to a problem? Please describe.**
dosbox-staging, just like DOSbox, seems to require an SDL window to work.  This is annoying when the DOS program you want to execute does not actually require graphics or provides textual output on the console you want to log somewhere.  It's also rather annoying to have windows constantly pop up when dosbox-staging is used to execute programs as part of a script, such as when building Open Watcom. 

**Describe the solution you'd like**
Dosbox should have a graphics-less operation mode in which no SDL window is created and all interaction is done over stdio.  This could be done in two ways:

* the DOS emulation could pretend the console is redirected to a serial port, i.e. as if someone typed `ctty com0`.  That serial port is then connected to stdin/stdout with optional character set conversion.
* an MDA graphics card could be emulated and displayed using a curses-like interface on the console.  Alternatively, a CGA-card with text mode only could be emulated.  However, this may make it difficult to tell programs not to display any graphics.

It should be possible to redirect both input and output from/to files regardless of what mode is implemented.

**Describe alternatives you've considered**
I don't really have any alternatives.

**Additional context**

**Comment by grapeli** [comment]
You can use the sdl video driver dummy for this.
`SDL_VIDEODRIVER=dummy ./dosbox`
https://drive.google.com/file/d/1fzpNEt6KhZb43R2lQJeCD0ZVr5pYiyK3/view?usp=sharing

**Comment by dreamer** [comment]
@grapeli That's interesting, I didn't know there's `dummy` driver - perhaps it will allow us to run more automatic tests now - even before this feature is implemented.

But I think the feature @clausecker is describing is more about having also an option for interactive input from a normal terminal emulator.

Personally, I am somewhat interested in implementing this (without any possibility of turning on any graphics mode - pure text only); that's why having it tied to a potential new <code>machine = [mda](https://en.wikipedia.org/wiki/IBM_Monochrome_Display_Adapter)</code> is a really good idea.

**Comment by kcgen** [comment]
This is not a goal of the project (supporting SDL-less application text-modes), and will likely require considerable changes. Because of both of these, this is likely not be undertaken.

Because the author noted the SDL window was simply an annoyance within a scripted process (_It's also rather annoying to have windows constantly pop up when dosbox-staging is used to execute programs as part of a script, such as when building Open Watcom._), I believe the headless mode suggested by @grapeli has met the authors needs -- as this prevents the SDL window from popping up.

Closing.

**Comment by john-peterson** [comment]
I am getting text output but it's completely garbled

I am looking for some ways to alter the output

```
unset DISPLAY
dosemu -t SOFTPORN.EXE
dosbox SOFTPORN.EXE
```

![Screenshot_20230908-102048](https://github.com/dosbox-staging/dosbox-staging/assets/207571/f687a31f-130a-406e-b4de-397f4f37e8af)
![IMG_20230908_102106](https://github.com/dosbox-staging/dosbox-staging/assets/207571/b8edcc91-1165-4480-9c5b-6c0b0b889186)

**Comment by johnnovak** [comment]
> The source code for this original version with famous bugs is lost but I want to recreate it for the video game preservation archive. But I don't have any usable display. I'm on vacation and only the phone will suffice. It does run in SDL but it's a clutch to work with on the phone. Pure text is the only sensible solution

SDL and and graphics capable display is a hard requirement. That's not going to change.

**Comment by Grounded0** [comment]
These things aren't like my SGI Octane that could run headless through serial console from boot so probably will not go ahead.

**Comment by johnnovak** [comment]
Yes, keep it real, guys 😅

**Comment by Grounded0** [comment]
We got more politically correct term for the same thing. 😁
