### ISSUE TITLE
Improving performance on PowerPC

### ISSUE THREAD

**Issue by samo79** [dosbox-staging/dosbox-staging#689]
The recent introduction of the dynamic recompiler for 32-bit PowerPC brings really a lot of benefits in any PowerPC based version of DOSBox!
However DOSBox was (and still) not exactly famous for its general performance and this can effect in a way or another the real usability of this emulator with certain PPC based hardware.

As far as performance goes, actually with core=normal we more or less get 0.7fps from PCPBENCH, while with core=dynamic we instead get 3.1fps.  
This was a fantastic improvements, however in real life even "simpler" DOS games continue to struggle a bit on certain PPC hardwares

The scope of this ticket is a proposal to our talented devs to include some other big-endian improvements that can increase a bit more the performance, atleast to get it up this bench to 4.0

**Comment by dreamer** [comment]
On modern hardware (and by modern I mean basically every CPU released in last 10 years or so) DOSBox Staging should be quite playable for any DOS-era game - I regularly test on 9-year old Sandybridge i5, and it's good enough for emulating basically everything (unless I start using very GPU-taxing shaders).

Can you share the speed (or even better: model) of your CPU? What `output` setting do you use? There are limits of what we can reasonably implement…

How do you run PCPBENCH? Because on my i7 Haswell CPU @ 3.50 GHz (using completely unoptimized, debug build) the results vary from 226 FPS in 320x200@8bpp (`PCPBENCH.EXE 150 /nolinear`) to 30 FPS in 1152x864@16bpp (`PCPBENCH.EXE 20a`).  The default 640x400@8bpp gives me 118 FPS.

Can you by any chance run Linux on your PPC machine? With Linux we could run `perf` and generate flamegraphs to identify the areas that might be bottle-necks - by comparing to a flamegraph on x86_64 we might discover something unexpected.

**Comment by samo79** [comment]
Thanks for answering me :-)
My testing hardware is a Sam440ep Flex 800 Mhz running AmigaOS 4.1 

More info about this board:
https://en.m.wikipedia.org/wiki/Sam440ep

Certainly not the fastest machine but hopefully there may be room for some further optimization, atleast me hope so :-)
For other information that could be useful to you, during the porting on AmigaOS4 we have a long detailed discussion with kas1e and other users and we conducted several tests that you can read here:

https://www.amigans.net/modules/xforum/viewtopic.php?start=0&topic_id=8155&viewmode=&order=ASC&type=&mode=0

As for the eventual testing under Linux .. sorry no, unfortunely i'm unable to install it yet

**Comment by dreamer** [comment]
@kas1e was helping us with testing/fixing stuff for AmigaOS before, so maybe he'll have a moment :)

@kcgen do you still have your PPC machine? What CPU do you have - is result in PCPBENCH somewhat comparable?

I looked through the discussion, and I think the first step would be to make sure you have properly optimized build - that is using -O3 instead of -O2 - it should make a difference due to GCC enabling some optimizations that are quite important (or maybe even making PGO-optimized build, we want to squeeze as much from the hardware as possible after all) and proper set of compilation flags.

Also, we need to make sure the builds are using high-quality compiler, that inlines `memcpy` calls properly - we did tests with a number of compilers, but I think all of them were rather new.

Running dosbox via `perf` (I don't know if there is a similar tool for AmigaOS) to create flamegraph on PPC should be the next step.

**Comment by samo79** [comment]
According to our tests, at the time there were pratically no difference in term of perfomance between -O2 and -O3, so we still leaved -O2 by default to stay in line

**Comment by dreamer** [comment]
I guess it might depend on the compiler and available CPU instructions, but -O3 in GCC enables a number of optimization options, e.g. much better loop vectorization, (has big impact on audio and video emulation). Other optimizations, like generating jump-tables affects CPU emulation…

We can track what optimizations were applied by passing specific flags to GCC.

On Linux x86_64 the difference between -O2 and -O3 (for dosbox-staging) is very noticeable (at least in my experience - maybe 10% of speed). With PGO builds we were able to squeezee another ~5% IIRC, but at cost of complicating the release process a lot, so decided not to it at this time.

**Comment by kas1e** [comment]
@dreamer 

In the case of PPC-JIT 02 or 03 make no sense: and that not only on slow hardware like samo have, but also on my one, which has 2ghz CPU and fast memory buses/caches/etc. Even if -O3 enabled more optimization, in the case of PPC-JIT it makes no differences, as seems everything coming to the fact what kind of hardware one has, and what kind of games want to emulate. I.e. only JIT code matter for real. Maybe playing with optimization levels, memcpys and stuff can add 0.01 speed up, but that not worth of hassle of course. Id says if there is no way to improve speed by measurable values, that not worthy of worry.  Like, spend months to speed up it on 0.1% which no one will notice :)

As for "perf", sadly nope, it didn't work on OS4

@samo79 

All the work about PPC-JIT were done by Jmarsh: https://www.vogons.org/viewtopic.php?f=32&t=65057
He does already pretty optimized and decent kind of work, you may try to ask him if he can optimize it further.

**Comment by samo79** [comment]
@kas1e 

Jmarsh is not already working here on this project?
If so maybe there is no need to search him elsewhere, soon or later he will probably note this ticket

**Comment by kas1e** [comment]
@samo
He will not, as he not works on dosbox-staging, he works on original dosbox. And my version for os4 based on original dosbox, but with some manual fixes added from dosbox-staging (such as better cd-rom handling).

**Comment by dreamer** [comment]
@kas1e 

> (…) as seems everything coming to the fact what kind of hardware one has, and what kind of games want to emulate. I.e. only JIT code matter for real.

Yes, it heavily depends on emulated software. In the past I created flame graphs for several games, investigating the potential choke points - in games I tested (Quake, Carmageddon) the JIT was taking 70-80% of CPU time, but some other stuff (e.g. vorbis decoding or scalers) can take a significant portion of time as well. (I strongly suggest to NOT use scalers and rely on GLSL shaders or pixel-perfect modes instead). The biggest performance problem seems to be page trashing causing delays on emulated memory pages.

PPC JIT is also affected by -O3 (code generation part), but it's "one time cost" - does not affect FPS too much (in short tests, codegen could take up to 20% of total CPU time though).

The results for PPC might be radically different - we can't say for sure until we test :) If you'll have Linux installed on your PPC machines we could investigate further.

**Comment by kcgen** [comment]
> do you still have your PPC machine?

Yes, but recent monitor swap has left me without a way to view its analog video output; so need to order a dsub15-to-hdmi converter to get this setup back in play again.

> What CPU do you have - is result in PCPBENCH somewhat comparable?

It's a 400 MHz "spitfire" 7400, single core running a modern Linux kernel. Although I haven't benchmarked it using pcbench, I am able to get roughly 4000 fixed dynamic cycles out of it with noaudio=true, and fewer if I use audio. I'm not sure how 4000 cycles translates to PCB fps scores though.

**Comment by kcgen** [comment]
@kas1e , @samo79 , can you try a build using the `fps-pacing-1` branch? 

This branch's changes are only active with a fixed cycle count, and you should set it something higher than you would normally expect for you machine.  

For example, if your machine maxes out around `cycles = 15000` then try 20000.

This at least seems to work around some video pipeline issues in SDL2 on the Raspberry Pi 4, and to a lesser extent on the Pi 3. 

Just curious; it's a work in progress.

**Comment by samo79** [comment]
@kas1e 

Ok, just registered on Vogons and asked him (used the old PowerPC forum topic)
Hope he will reply

**Comment by kcgen** [comment]
Suggest we close this, as the performance on dynrec PPC is equal-to and even exceeds, on a per-MHz basis, dynrec on other non-x86 platforms, such as arm-v7.  So this implies the PPC dynrec code is likely already very well optimized.

Also, the response on vogons did not give the impression that the author, jmarsh, was going to embark on overhauling the PPC dynrec code to extract more performance (however little may be left).

**Comment by khval** [comment]
Maybe there are cpu cycles wasted on other parts of emulator, improving efficiency of graphics conversions can more cpu cycles for other things.

**Comment by dreamer** [comment]
@khval 
We won't know until someone who actually owns a real PPC machine (either ppc or ppc64) will install somewhat new version of Linux on it, gather performance data using `perf`, and generate [flamegraphs](http://www.brendangregg.com/flamegraphs.html).

On x86_64 I generated such graphs and we are rather aware where the bottlenecks are - I can help with explaining how to generate such graphs, but I do not own any PPC machine.

If users of PPC CPUs want improvements, then community using PPC needs to get involved…
