### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by tiagotarifa** [dosbox-staging/dosbox-staging#698]
I know it's awkward but, I wanna give a "second chance" for an old, but 100% functional, notebook.
It's only run Windows XP because its SiS video driver. Its Linux (and FreeBSD) drivers are old and more slow than XP.
I read that dosbox staging has Windows XP support for run but when I tried the 32bit version, it's give that error: "dosbox.exe is not a valid Win32 application".
My Windows XP is updated with all avaliable hotfixes. All Microsoft Visual C++ libraries (2005 to 2017) are installed too.

My notebook is a Acer Aspire 3000:
- Semprom 3000+ with mmx, sse and sse2
- 2Gb Ram
- Video: SiS 661 + 128MB

Binary that I tried:
https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.75.2/dosbox-staging-windows-x86-v0.75.2.zip

**Comment by dreamer** [comment]
Our official builds won't work on Windows XP by default - we don't test it, we won't work on it, sorry. Minimal requirements for CPU for our Windows builds is SSE 4.2; you can try version 0.75.0 - it had SSE support turned OFF and was not bundling VC++ libraries compatible with Win 7 or newer (but I seriously doubt it will work on XP anyway).

I am not sure Microsoft's VC++ 2015 and 2017 libraries are even compatible with Windows XP…

You can try compiling your own version (and it should work… mostly, there are some small issues due to old version of C standard library available on Windows XP), but it will be *a major chore*.

- VS 2019 does not work on Windows XP any more, Microsoft changed project solution format, so you won't be able to use build using VS from Windows XP days
- vcpkg does not support Windows XP (never did)
- Git does not support Windows XP (for several years?); you can find very old versions of Git and install that
- MSYS2 does not support Windows XP (I don't think it ever did)

You would need to use MSYS1 (I don't even know where to find it…) and build all dependencies manually. We had one dev who managed to successfully do it (before 0.75.0), but later he switched to using Linux instead.

**Comment by kcgen** [comment]
@tiagotarifa, 

I noticed you're a fellow Linux and shell user in your profile, so if you're up for some command line labour (ie: manually compiling precursor dependencies, then mid-level dependencies, and finally DOSBox Staging's direct dependencies), then the MSYS approach is certainly possible. 

Plus, adding such a nightmare fits with our present Halloween / Guy Fawkes holiday theme :bat: ! @dreamer mentioned another maintainer managed to do this; and it was indeed a non-trivial, multi-week effort. 

You mentioned wanting _to give a "second chance" to an old, but 100% functional, notebook._   The guaranteed successful way to do this would be installing a modern, supported, but memory-lite Linux (or BSD) on it.

Something like: https://www.linuxliteos.com/forums/release-announcements/linux-lite-5-2-final-released/

Unlike XP, installing a 64-bit Linux would also let you leverage the full 64-bit register space of your CPU, which can often double performance for CPU-bound tasks.

**Comment by dreamer** [comment]
Hey, I forgot about another possibility: cross-compile from Linux to Windows - *perhaps* it will work on Windows XP.

On Fedora, almost all dependencies we use are provided by Fedora repo (e.g. `mingw32-SDL2`); use `mingw32-configure` instead of `./configure` and `mingw32-make` instead of make. I did it once and needed to some some tiny adjustment for icon file or something.

I think this might be the most practical solution here - it's definitely much easier than building on Windows XP.

**Comment by tiagotarifa** [comment]
Thanks guys!
I'll give a try in this weekend, to build the binary for Windows XP using Linux. If it works, I'll post all steps here.

**Comment by kcgen** [comment]
If you can package it into a script, we'd be happy to add it to the existing helper tools in `./contrib`

**Comment by GranMinigun** [comment]
It's actually possible to build for WinXP in VS2019, but support for that is marked as deprecated and probably will be removed in VS2022. It requires installing "C++ Windows XP Support for VS 2017 (v141) tools" component, which includes Windows SDK v7.1, and solution should be retargeted to use that. Whether it's possible to build dosbox-staging that way, I don't know. Probably not. Probably not really worth it anyway. Just thought I'd mention it.

**Comment by LowLevelMahn** [comment]
> Whether it's possible to build dosbox-staging that way, I don't know. Probably not. Probably not really worth it anyway. Just thought I'd mention it.

vcpkg does not even fully work with Win7 - so i think that will be also a showstopper
