### ISSUE TITLE
Help with custom RetroPie build script on Pi4

### ISSUE THREAD

**Issue by jlopezvil** [dosbox-staging/dosbox-staging#733]
Related to   https://github.com/dosbox-staging/dosbox-staging/issues/646

Sorry. I have no success in compiling dosbox-stagin on pi4. Attempted all things readed on this post. Maybe some advice o post the compiled file for pi4?

**Comment by FeignInt** [comment]
Hi @jlopezvil , I do not have a rPi4 myself so I do not know if this there is a general problem with the current master and rpi4

The linked issue was due to "left over" libraries messing up the detection of fluidsynth, I doubt that is what is causing problems for you.

can you attach/link/paste the build log?

    ( ./configure 2>&1 && make -j1 2>&1 ) | tee buildlog.txt

The **tee** might be over doing it, I'm unsure if it is installed as standard on i386/amd64 let alone a pi4.

If **tee** appears to be missing just replace **| tee** with **>** 

also pass anything that you normally would to **./configure** (and tell us)

The **-j1** is just to limit jobs to *one* it slows the build but makes the log a little easier to read ( people often paste the last bit of a failed build and miss the actual error higher up in the log ;) )

We will also want info on the actual commit you are building off

paste output of 

    git describe

I can tell you that *v0.76.0-alpha-993-g8716a00b* builds fine on amd64 Debian/sid

I guess I should try buster, that is assuming your rPi4 similar to the setups on the linked issue in being based on Debian/buster

anyway, logs will help us work out what going wrong for you, along with any other information you can give, regarding Distro, installed build dependencies etc.

**Comment by nemo93** [comment]
hello @jlopezvil! As @FeignInt mentioned nothing can be done without you providing a minimum of information :) I do have a Pi4 and everything does compile fine here. What's your system specs and OS version? What command-line did you issue to start the compiling? I also second @FeignInt regarding Fluidsynth as the prime suspect. If you could give a try to the following that would be interesting:

```
./autogen.sh
./configure --disable-opengl --disable-fluidsynth CPPFLAGS="-DNDEBUG" CFLAGS="-O3 -march=native" CXXFLAGS="-O3 -march=native"
make clean
make -j2
```

Before that ensure that you have the latest system packages updated (sudo apt update && sudo apt full-upgrade -y). I'm on Buster standard.

**Comment by jlopezvil** [comment]
https://github.com/dosbox-staging/dosbox-staging/issues/733#issuecomment-733559342

It works ... Compiled ok.

Maybe was also a trouble with my script module for update, compile and install dosbox-stagin.

There some script file for include in my   retropie-setup?

Now Im using this but doesnt work fine in install the now compiled binaries ...   

[dosbox-stagin.sh.txt](https://github.com/dosbox-staging/dosbox-staging/files/5599463/dosbox-stagin.sh.txt)

**Comment by FeignInt** [comment]
@jlopezvil you should probably report this problem to the authors of the script and ask them to fix the typo **stagin => staging** when you do

When you report the problem please **include detail** of the problem

> but doesnt work fine

is little help ... sometimes I like guessing games, sometimes they just frustrate.

The script looks a little odd, it appears to setup the fluidsynth dependencies , but as far as I know buster does not have fluidsynth2
I'm going to assume you added the **--disable-fluidsynth**, which is why it compiled fine. 
Now my next assumption is *"Install fail"* is due to the configuration step

    iniSet "fluid.soundfont" "/usr/share/sounds/sf2/FluidR3_GM.sf2"
    iniSet "fullresolution" "desktop"
    iniSet "fullscreen" "true"
    iniSet "mididevice" "fluidsynth"

lots of mention of fluidsynth, which has been disabled, maybe that is spitting out an error which in turn marks install as failed.

Like I said, best to get in touch with the script author(s)

or maybe @nemo93 can help with it, pi4/retropi is alien to me

either:

- drop fluidsynth support
- re-work script to use the fluidsynth2 in *contrib/*
 I haven't looked at this, my debian/rules disables fluidsynth if version not at least 2
- backport fluidsynth2 from **unstable** to **buster**

I don't think hacking the **~/.config/dosbox** location is required, DOSBox Staging already adds a suffix to the .conf files, so won't conflict (unless other files are a problem.. phonebook, keymapper?). c1445526410d96c9feaad580b2ce3ab186c47b16 also made some of the sed redundant.

@nemo93 I'm interested in the **--disable-opengl** flag, is that something that is required for the pi4?  I can have Launchpad PPA build for arm64, which *might* work on retropi.

**Comment by jlopezvil** [comment]
Script was made for me copying from dosbox script..... I dont know if somebody has made a script. Bit this i am asking for helo with my bad script

**Comment by nemo93** [comment]
@jlopezvil please find the script I've made to be integrated within Retrope. 
**Note**: it's not perfect at this stage. Feel free to adapt it to your needs. I'll provide no support for it at this stage. Also it will compile a specific branch of this repository kindly provided (and maintained) by @kcgen which is `kc/fps-pacing-1` (master+some tweaks for pi4).

https://pastebin.com/EJkP3iss

Just copy/paste the above in a script named after `dosbox-staging.sh` that you must store there:

```
<home>/RetroPie-Setup/scriptmodules/emulators/
```

Then launch Retropie Setup as usual with the following command from your `<home>` directory:
```
$ sudo ./RetroPie-Setup/retropie_setup.sh
```

Update the script and once done, navigate to `Manage Packages > Manage Experimental`. There you should see a `dosbox-staging` entry. Go there and choose to `Install/Update from Source`. Compilation should go smooth (~7-8mn) and you'll have Fluidsynth enabled as well.

@FeignInt the **--disable-opengl** flag is there to match another script from Retropie which is the one to compile DOSBox SVN. I wanted to keep close match between scripts to perhaps merge code at some point. I'm no expert so please take the following with a pinch of salt but Raspberry PIs today do not really support OpenGL (only ES). Progress are being made on the GL driver but still not there yet.

**Comment by FeignInt** [comment]
This is why it is important to provide detail @jlopezvil 

some problems
- needlessly pulling in incompatible (and unused) fluidsynth
- it appears be pulling in redundant depends from dosbox ( sdl1 etc.)
- needlessly hacking the *~/.config/dosbox* location
- configuring for unsupported fluidsynth

I still do not know where it fails, you have not given us an real detail on the "install error"

Is this script something that *"worked"* in the past?  The sed in the attached [dosbox-stagin.sh.txt](https://github.com/dosbox-staging/dosbox-staging/files/5599463/dosbox-stagin.sh.txt) seems to target a version prior to 2020-04-18

But lets walk back to the original problem, *unable to compile*

It seems you have managed to compile it after @nemo93 hinted **--disable-fluidsynth** which I must admit surprised me as you said in the first post :

>Sorry. I have no success in compiling dosbox-stagin on pi4. **Attempted all things readed on this post**. Maybe some advice o post the compiled file for pi4?

Since compilation is no longer a problem ( unless you really want/need fluidsynth ) all you need to do is install to some suitable location, it does not need  to be complicated

```bash
#!/bin/bash
./autogen.sh &&
./configure \
    --prefix="${HOME}/dosbox-staging \
    --disable-opengl \
    --disable-fluidsynth \
    CPPFLAGS="-DNDEBUG" \
    CFLAGS="-O3 -march=native" \
    CXXFLAGS="-O3 -march=native"
make clean
make && make install
``` 

and set PATH

    export PATH="${HOME}/dosbox-staging/bin:$PATH"

or configure the retropie UI ( I assume it has one )

It is crude, but should work. The correct way would be to use the existing package manager, but It doesn't look like I'm going to get any detail to be able to diagnose/fix that.

:D @nemo93 just posted

**Comment by FeignInt** [comment]
@nemo93 I started fixing the provided script, but yours is complete ;)
pretty much the same, I was missing *build-essential automake*

I did come up with this:

```bash
while read -r
do
    export "$REPLY"
done < <( make -C contrib/static-fluidsynth 2>/dev/null \
                 | grep -oE "FLUIDSYNTH.+" )
```

which is a little less hardcoded

also do you need :

    depends_dosbox "${depends[@]}"

I'm guessing that will call in the legacy dosbox depends

**Comment by nemo93** [comment]
> ```
> depends_dosbox "${depends[@]}"
> ```
> 
> I'm guessing that will call in the legacy dosbox depends

@FeignInt you're correct. I kept it for compatibility and I might remove it at some point. In fact when I have time I'll review the script once again to see if there's some tweak that could be done (also I really do not like to EXPORT). Also Retropie maintainers will have their words to say so this script is all but definitive :)

**Comment by FeignInt** [comment]
They need not be exported, they can be passed to configure in the same way as CPPFLAGS

I did the while loop as it was a cheap way of avoiding word splitting

terrible for logs/diagnostics

maybe modify the Makefile to write a file which can be sourced to set the FLUIDSYNTH vars

**Comment by jlopezvil** [comment]
https://github.com/dosbox-staging/dosbox-staging/issues/733#issuecomment-734183326

Works perfectly. Thanks again.
Where could find it when you update it?

**Comment by kcgen** [comment]
@nemo93, if we packaged this in `./contrib`, could Pi users directly run it? Or would they have to do other stuff, like copy it into their `~/retropie-setup/modules/..` add it to the menu system, etc?

Given all of the content has been authored by @jlopezvil and @nemo93, I would say you are the authors and thus it's in your right to license it to something like GPL2 or 3 (or whatever you like); which would make packaging easier here.

Just a suggestion! Hopeful we can package it so all Pi users can benefit.

**Comment by jlopezvil** [comment]
I think authory must be for @nemo93 .....

**Comment by nemo93** [comment]
@kcgen The script is only to be used with Retropie. Therefore I'd advise against any inclusion in `contrib`. At least at this stage. My goal remains the same: to include Staging directly in Retropie (assuming you and @dreamer are fine with it of course). Yet after chatting with Retropie maintainers lack of MT-32 is an issue as the other forks included do come with full Fluidsynth and MT-32 support.

Also to be fair I've done almost nothing on that script. I just adapted the [existing one](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/emulators/dosbox.sh) for Dosbox SVN included with Retropie. Credits can go to Retropie Maintainers :) 

What I'm able to offer for the time being is an entry to the Wiki where I'll include the script posted above. Script then just have to be copied over the `<home>/RetroPie-Setup/scriptmodules/emulators/` directory.

Let me know if that's fine?

**Comment by kcgen** [comment]
All sounds good @nemo93! 

I guess the only remaining hurdle is achieving MT-32 parity with:

![2020-11-27_08-04](https://user-images.githubusercontent.com/1557255/100467494-63eb1100-3087-11eb-8140-68a7e587b400.png)

I've been a RetroPie users for years, but didn't realize this SDL2 patched version also provided FluidSynth or MT-32 support! (so adding a description for Staging's features will be a nice touch too).

A wiki article sounds like the best option for interim period.

**Comment by nemo93** [comment]
@kcgen I do have to apologize as my previous statement was incorrect. I was indeed referring to the "Duganchen" DOSBox [fork](https://github.com/duganchen/dosbox). It's a good fork to use on Pi and one I've used for several months. Development has stopped as it seems and it does come with Fluidsynth and SDL2 support. _No MT-32_. As far as I know in Retropie only SVN does support MT-32. All to say that to have MT-32 support in Staging would be a great way to push for its inclusion in Retropie. I don't want to look too pushy (I'm afraid it's too late!) about this MT-32 integration, I just try to explain the reason why Staging is not included in Retropie as of yet.

I'm interested by your last sentence. Do you mind my asking to elaborate a bit please? I do manually change stuff in `~/RetroPie-Setup/` without issue. Here I modify scripts or add ones to bring more emus to Retropie. I never ran into issue in the GUI while running the `update setup script`. For instance adding my script above to the right location and updating Retropie from GUI shouldn't cause any issue.

**Comment by dreamer** [comment]
> All to say that to have MT-32 support in Staging would be a great way to push for its inclusion in Retropie. I don't want to look too pushy (I'm afraid it's too late!) about that MT-32 integration. I'm just trying to explain the reason why Staging is not included with Retropie as of yet.

No worries :) 

As for now, you can use updated MT-32 patch: https://github.com/dosbox-staging/dosbox-staging/issues/257#issuecomment-735369446 This patch needs some important improvements before we can merge it to master, but I think we'll do it for 0.77.0 (or maybe even for 0.76.1 - but only as a feature to opt-in during compilation time).

Does Retropie DOSBox SVN builds it's own version of Munt mt32emu library, or is the library distributed on the OS?

As for **duganchen**'s fork - yes, it seems abandoned (we asked if Dugan Chen wants to contribute to dosbox-staging, but he/she respectfully declined). There's some important work that I plan to port from that fork into dosbox-staging (namely: GLEW support to replace some shitty code we inherited from SVN and probably some fixes).

**Comment by nemo93** [comment]
> Does Retropie DOSBox SVN builds it's own version of Munt mt32emu library, or is the library distributed on the OS?

You have to compile [Munt](https://github.com/munt/munt) by yourself. I understand there's some legal issues around the Roland MT-32 ROMs and as such can't be freely distributed. Keep me honest! I'd love to have a `static-munt` under `contrib` coming along with Staging though (without ROMs).

Let me reinstate that I have no authority whatsoever either about Retropie of course! I mean I'm just trying to be a humble contributor to the projects I love and care about. If anyone else is trying to integrate Staging with Retropie please keep on doing that. I'll be happy to assist.

**Comment by dreamer** [comment]
> I understand there's some legal issues around the Roland MT-32 ROMs (…)

Yup :( Not so much issues as in "it's illegal", but rather legal uncertainty. Roland Corporation is quick to request takedowns / threaten to sue, but when they were requested to produce paperwork they actually own the copyright of samples in MT-32 ROM files they suddenly "lost paperwork".

I hope that long-term we'll be able to modify mt32emu lib to use Free replacement for those ROM files (e.g. with samples based on the new freepats project), but that's a topic to start later, and to be continued in #257 thread.

**Comment by kcgen** [comment]
>  I'd love to have a static-munt under contrib coming along with Staging though

With almost no repository including Munt, I suggest we go one step further than an optional `contrib` builder and instead include it into the default build as an always-on feature (similar to the audio CD-DA codecs); perhaps with an opt-out config switch just in rare cases where Munt doesn't build on one's platform. 

How we pull or include the sources (git sub-project, dynamic downloader, etc..), I will defer to @dreamer's recommendation.

**Comment by nemo93** [comment]
I've added script to the Wiki. I'm closing that issue then. Let's continue discussion about mt32 on the other thread.
