### ISSUE TITLE
Fluidsynth is not actually bundled with the Linux version?

### ISSUE THREAD

**Issue by JKjakay** [dosbox-staging/dosbox-staging#752]
**Describe the bug**
Maybe I dont get it - but is it possible that you forgot to include the fluidsynth libraries in the Linux version?

**To Reproduce**
Three reasons:
a) I cant find them (may be my fault...)
b) dosbox-staging 0.76 does not accept the midi option "fluidsynth"
c) the linux archive is only about 1/3 the size of the windows and mac archives

**Expected behaviour**
startup with the bundled fluidsynth enabled (it works if I enable fluidsynth as a system service)

**Environment (please complete the following information):**
Ubuntu 20.10

**Version of dosbox-staging:**
0.76, archive name is: dosbox-staging-linux-v0.76.0.tar.xz

**Comment by dreamer** [comment]
This is not a bug. I left this warning in our download page: https://dosbox-staging.github.io/downloads/linux/

> ⚠️ Tarball builds have FluidSynth 2.x feature disabled.

That's because distributions are slow to adopt FluidSynth 2.x and it's only now starting to be available - if we turned it *on*, then we would throw out compatibility with following distros:

- All Ubuntu versions before 20.04
- All Fedora versions before 33
- All Debians (period)
- All Mint versions

etc, etc…

Unfortunately, maintainer of Snap package has not enabled FluidSynth 2.x in there yet… I just tested it and found this and yet another bug...

So options you have for now:

- compile it yourself
- wait until we'll contact Snap package maintainer and resolve the issues (which most likely means we will take over the package)
- wait until our Debian package will be accepted (it's in Debian review - we track it in - #664)
- wait until someone willing to maintain Flatpak package for Flathub will show up (#351)
- or we wait for will just bite the bullet and provide AppImage packages ourselves because we'll be too tired of dealing with this…

(We *really* don't want to enable FluidSynth the same way we did for Windows and macOS - in both cases bundling FluidSynth caused a lot of issues and is a very brittle solution due to all FluidSynth 2.x dependencies :( ).

I will keep this issue open until we will have at least one viable solution to recommend for users who want pre-built package with FluidSynth support on Ubuntu.

**Comment by kcgen** [comment]
> (We really don't want to enable FluidSynth the same way we did for Windows and macOS - in both cases bundling FluidSynth caused a lot of issues and is a very brittle solution due to all FluidSynth 2.x dependencies :(

This is of-course the worst fallback, but something we could consider until *any* alternatives present themselves.

I believe the latest Glib + FluidSynth static builders now eliminate the brittle dependency issues:  https://github.com/dosbox-staging/dosbox-staging/pull/748 (pending), however as of a couple minutes ago, I confirmed zero-dependencies exist on a clean installation of MacOS.

I was able put that Glib builder together because I similarly stripped down my Linux system (renaming shared libraries in /usr/lib :-) ) after linking the binary, and similarly confirmed it runs when the system is deprived of any possible links to system libs.

Anyway.. not ideal, but I worry we're in a waiting game right now, and this approach is simply "better than nothing".

**Comment by JKjakay** [comment]
Thank you! I missed the warning on the download page. 

I went for the compilation solution, worked without problems. However, since fluidsynth is already installed system-wide on my rig, I wonder whether using the bundled version has any advantages for Linux users? Except for having to start a fluidsynth server before starting dosbox-staging, the old way seems to sound and work the same, more or less.

**Comment by FeignInt** [comment]
@JKjakay 

Another option
https://launchpad.net/~feignint/+archive/ubuntu/dosbox-staging

Weekly snapshots,
https://launchpad.net/~feignint/+archive/ubuntu/dosbox-staging-weekly
They are pushed to Launchpad PPA around 04:10 UTC , takes a while to get built and published, usually available 6-7 am Fridays

Both should have FluidSynth, even Bionic (which should work for Debian/Buster) since commit Feignint/dosbox-staging-deb@d98489c9fdf3d4027a08ae9238699165440ef5b6

Groovy and Hirsute work on current Debian Sid, which has had FluidSynth2 since Sat, 14 Dec 2019

Or,
dig around on
https://salsa.debian.org/Feignint/dosbox-staging/-/jobs/

**Comment by dreamer** [comment]
That's correct @FeignInt's package is solid choice - I added a note about it in: https://dosbox-staging.github.io/downloads/linux/

@FeignInt can you push `fluid-soundfont-gm` to be an actual dependency and not merely a suggestion? I doubt 5.6MB TimGM6mb is good enough to be the default choice… (is that soundfont installed by default by Ubuntu? I don't see it in dosbox-staging dependency list)

**Comment by FeignInt** [comment]
> @FeignInt can you push `fluid-soundfont-gm` to be an actual dependency and not merely a suggestion? I doubt 5.6MB TimGM6mb is good enough to be the default choice… (is that soundfont installed by default by Ubuntu? I don't see it in dosbox-staging dependency list)

yeap, I can bump it to a **recommends**,  They are pulled in by default, unless the user overrides either by system wide config, or passing **--install-recommends=no**

The TimGM6mb is pulled in by libfluidsynth2, 
> Depends: <snip> timgm6mb-soundfont (>= 1.3-3~) | sf3-soundfont-gm

The fluid-soundfont-gm is a little odd, at least on Debian, it isn't included as a default-GM.sf2, I couldn't find a VCS for it, just the source via apt

When I thought I was using fluid-soundfont-gm I was actually using [musescore-general-soundfont-lossless](https://packages.debian.org/sid/musescore-general-soundfont-lossless)
~~But as far as I can see, no Ubuntu package~~ [in ubuntu since Focal](https://packages.ubuntu.com/focal/musescore-general-soundfont-lossless)

[same maintainer for all three](https://qa.debian.org/developer.php?login=tsmithe%40ubuntu.com)

I'm thinking of filling a bug report, with patch, against fluid-soundfont  to have it use alternatives.

I think it would make sense to have its Priority between TimGM6mb and MuseScore
```
There are 2 choices for the alternative default-GM.sf2 (providing /usr/share/sounds/sf2/default-GM.sf2).

  Selection    Path                                              Priority   Status
------------------------------------------------------------
* 0            /usr/share/sounds/sf2/MuseScore_General_Full.sf2   70        auto mode
  1            /usr/share/sounds/sf2/MuseScore_General_Full.sf2   70        manual mode
  2            /usr/share/sounds/sf2/TimGM6mb.sf2                 20        manual mode
```

I'll have to check the Priority of the other MuseScore soundfonts

**Comment by grapeli** [comment]
How is linux different, including windows, macos, etc?

You can include **all** libraries statically linked. Even OpenGL.
You can link fluidsynth statically, include a dynamic library, or build with dynamically linked using dlopen().

Somehow google chrome has no problems distributing its monster on linux. They statically link a whole range of libraries. They join dynamically linked (libwidevinecdm.so and swiftshader) And with the use of dlopen() (pipewire).
https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/modules/desktop_capture/linux/base_capturer_pipewire.cc;l=59

**Comment by dreamer** [comment]
We don't do static linking on Linux unless there's absolutely no other choice. EOT.

**Comment by grapeli** [comment]
I am going over it. It is completely indifferent to me.
I watch this spectacle with amusement.
Do yours.

**Comment by kcgen** [comment]
> I watch this spectacle with amusement.

My feeling aren't hurt, but no one comes here to have their work made fun of.

I value your prior input and technical contributions @grapeli, so please either delete or update your comment to contribute to the discussion.

**Comment by grapeli** [comment]
Censor, delete, ban. Do what you want!
