### ISSUE TITLE
System clipboard support

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#767]
I don't know how difficult this would be to implement, but it would be a nice quality of life feature to have for various contexts.

**Comment by dreamer** [comment]
Idea is good and SDL2 provides most of the functionality - the problem lies designing user interaction. We can't use the following shortcuts:

- Ctrl+C (it's Cancel / Abort task in DOS)
- Ctrl+V / Ctrl+X - will clash with shortcuts inside DOS games

We could implement Unix terminal / Powershell style shortcuts:

- Ctrl+Insert (Copy - but how user would select text?)
- Shift+Insert (Paste)

But these might clash with DOS software as well…

Perhaps we could limit ourselves to paste only? Adding a new option for mouse (`middlepaste`?) could work very well when mouse is `seamless` mode. I'll think about the solution... (I do have some ideas how to handle it, but suggestions are welcome).

**Comment by kcgen** [comment]
Middlepaste sounds very nice, and fits perfectly with the mouse settings.

Another option to simply "grab console text buffer" (all of it), would satisfy the desire (and users could sift through it in a host-side editor),  without the complexity of introducing selection mechanics.

**Comment by Draky50110** [comment]
Same as Linux' Terminal ?

CTRL+SHIFT+C/X/V ?

**Comment by kcgen** [comment]
Although this is nice to have, I'm not sure how it can be implemented in a way that doesn't conflict with Staging's non-goals.

 If someone wants to PR this - and it proves to be a small, understandable, and elegant amount of code, that doesn't add a moving-target target burden (ie: keeping up with different operating systems' clipboard APIs); then great!
Closing this for now, as it's outside the scope of the project.
