### ISSUE TITLE
French translation / traduction française

### ISSUE THREAD

**Issue by Draky50110** [dosbox-staging/dosbox-staging#776]
Hello.
I'm using english by default because french language file is only made for official DOSBox 0.74-3.

So I created a new language file to translate it from beginning but it is full of strange character, most of them used for coloring.

So which editor should be used and which encoding is supported ? UTF-8 I hope...

**Comment by dreamer** [comment]
Codepage 858 / ISO-8859-1 (but actually it depends on… keyboard layout selected by user :( - CP858 is for `fr` and other western languages).

@Draky50110 I am aware that translation files and whole current translation system is pretty terrible - I have a plan for replacing it with a better one (gettext-based, so translators shouldn't need to worry about technical details like encoding and could use good software like https://poedit.net/).

Are you interested with helping with this transition? Even if you don't want to wait for it to be implemented, we will still be able use your translation file - I would need both versions: UTF-8 and CP858 (I would store both versions in `contrib/translations/` - CP858 for current users, UTF-8 for conversion into a new system later).

What OS do you use?

**Comment by Draky50110** [comment]
Wow, what a mess.

Yes, I'd like to re-translate from scratch in fact.
I' used to POedit, I'm on Ubuntu 20.10, using weekly PPA for DB-staging.

I can use nano, gedit or notepadqqq.

Here is default file created without "keyb fr" at start,so default codepage.

[default.txt](https://github.com/dosbox-staging/dosbox-staging/files/5718140/default.txt)

There are a lot of strange char inside and I don't know how to edit it properly.

**Comment by dreamer** [comment]
@Draky50110 yup, it's a mess :(

Anyway - you're using Linux so that makes everything easier for us :)

I just pushed an update to master branch - it should make working with translations bearable…

In directory `contrib/tranlations/` there are several more files and dirs now:

- `contrib/translations/utf-8/en/` - in this directory there's up-to date english language file, encoded in UTF-8 - this can serve as base for translations in new languages
- For testing purpose, I copied this file to prepare basis for `fr` and `pl` translations, and translated few messages inside
- For translating I suggest using Meld program and opening both English and French files side-by-side
- After updating a string, run `make` (e.g. like this: `make -C contrib/translations`). It will invoke `iconv` program with appropriate parameters (you probably have `iconv` already installed)
- Generated language file will be `contrib/translations/fr/français.lng` (when testing I created a symlink in `~/.config/dosbox/` to avoid copying it over and over again)
- I suggest changing DOSBox Staging setting: `startup_verbosity = medium` (to avoid wait times for splash screen)

I translated several french messages to start (Meld will show which ones) - once you will have a nice update you can submit it (preferably as PR) :).

I am open to suggestions on how to improve this workflow. Once we will have gettext system ready, I will write a script to convert utf-8 .lng files to .po files.

**Comment by Draky50110** [comment]
Ok,will work with meld :) 

Will tell you when it will be ok with french UTF-8 file.

Some suggestions, bad or good I don't know.
What about naming files like fr_FR.lng in directory "fr" ?
There might be en_US, en_EN, in their directory.
I don't know about polish if there are pl_XX...
Maybe later ;)

What about a "changelog" with future keys in contrib/translations/utf-8/en ?
With a GitHub "commit ID" before each new key.
Why ? Because if someone wants to see if his translated language file is up to date it might help seeing this.
I know .po files can have authors, date and version so it might help also.

Anyway, let's translate.

**Comment by dreamer** [comment]
> What about naming files like fr_FR.lng in directory "fr" ?

Right :) I did rename all generated files to gettext scheme, so `contrib/translations/fr/français.lng` is now `contrib/translations/fr/fr_FR.lng`. I noticed `iconv` has an option for transliteration, so following gettext scheme allows me to have `contrib/translations/pl/pl_PL.CP437.lng` as well :)

I kept filenames in `utf-8` dir as they were, to avoid disrupting any work that might've started already.

I also noticed that converting french utf-8 file to CP437 and CP858 generates exactly the same file - so it will work for people using `keyb us` and `keyb fr`.

> What about a "changelog" with future keys in contrib/translations/utf-8/en ?

In a month or two I'll create a new version of english utf-8 file and summarize changes. When major features for 0.77.0 will be ready I will do it again, create 0.77.0-beta tag and we'll announce string freeze: I will not be merging any new code that modifies source strings - translators will have some time to make the final adjustments.

> With a GitHub "commit ID" before each new key.

This would be too much burden to me, sorry. I hope changelog will be enough.

> I know .po files can have authors, date and version so it might help also.

For now I will record your authorship as commit author (we do that for all code, so it makes sense for translations as well). After migrating to gettext we'll include all normal metadata and tags.

**Comment by Draky50110** [comment]
Ok, nearly done.
Some things need to be spcified.

':CONFIG_DISPLAY' : what is this value for ?
What is an "overlay" (in path/mount things) ?

**Comment by dreamer** [comment]
Thanks @Draky50110!

For commit authorship (640e651f20b5fb08eb97e7a89e92bb4d64b6f9a6) I used a mail you used in one of your repos: `Gilles <gilles at w...e.fr>` - it's only on a branch, so I can change it still if you prefer to use a different one (GitHub anonymizes emails, so you won't see it via GitHub page). You can download converted file here: https://github.com/dosbox-staging/dosbox-staging/blob/po/fr-1/contrib/translations/fr/fr_FR.lng

(Once you'll confirm mail, I will push this update to the master branch)

- `CONFIG_DISPLAY` - it's an option in .conf file in sdl section - users who have more than 1 monitor can select which one should be used by default. Values are 0, 1, 2, ... - the meaning depends on user's OS and setup (so 1 might be left monitor or right monitor, depending on user setup)
- overlay - https://dosbox-staging.github.io/v0-75-0/#overlay

I noticed some adjustments are needed (e.g. to blue intro banner), but that's normal - for gettext I will need to fix it, so graphical characters are not part of the translation.

@kcgen Having translation uncovered few issues we have:

- autotype command is not hooked into old translation system (do we want to hook it up?)
- our help messages to `mount` and `imgmount` need to be trimmed again - we barely fit them in English, translators won't be able to stick to a single 80x24 screen. Maybe we should remove the note line about case-sensitivity?

**Comment by Draky50110** [comment]
Just tested, it works :) 

For authoring, ok to use this e-mail :) 
What about putting a README (text file) in the same dir that fr_FR.lng to have some credits/install instructions ?
[README.txt](https://github.com/dosbox-staging/dosbox-staging/files/5723151/README.txt)

I changed some strings thanks to your explanations (mainly OVERLAY related) so I attach a new (and last) version which is fully usable with 077 GIT version of DOSBox-Staging.
[fr-0.77.0-alpha.lng.txt](https://github.com/dosbox-staging/dosbox-staging/files/5723059/fr-0.77.0-alpha.lng.txt)

**Comment by kcgen** [comment]
@dreamer , yes, feel free to snip the note about case, and anything else a tad redundant.  I'll also try to condense any wording too.

For autotype- which ever way you feel is worth while. I guess we don't have any existing translations anyway, so perhaps waiting for the new system is the easiest/laziest approach.  Unless there things I could do now to prep it for translation using the new system?

**Comment by Draky50110** [comment]
mmmm "Intro" command is weird with no border...

**Comment by dreamer** [comment]
@Draky50110 Thank you!

- I pushed your latest translation to master: ed1855a9552ca91dcd6022975998328f2070ac91
- Renamed utf-8 files to use extension .txt to avoid problem with uploading to GitHub comments
- Renamed your README.txt to traduction-lisez-moi.txt - otherwise I am quite sure packagers would be confused about multiple README files
- I generated updated version of unicode english file (includes new strings for MT-32 feature and some adjustments to old messages). See the diff here: d7b84eb7381304c1346861882004be7d9506bcc7
- I removed version info from README.txt file - I can't keep this information up-to-date manually. When done, we will bundle the translations with the program (so users won't need to worry about this version anyway).

In particular about help messages to `mount` and `imgmount` commands - can you try to fit them neatly into max 80x24 screen? It's quite important for them to display properly with default settings. I removed one note from the english text for both messages, that should help a little.

**Comment by kcgen** [comment]
Excellent progress @Draky50110 and @dreamer !
Getting the wording just right and bounding it to fit visual limits isn't easy, so I pass on my thanks!

**Comment by Draky50110** [comment]
Ok, some news from today :
- I figure how `iconv` works, thanks to your script :) so I can now test my own work
- I managed to reduce translation for IMG/MOUNT so they fit in 80x24 now
- I translated all new strings and made spell corrections on previous work

Two questions now : 
- with CPU cycles option : it says you can have a number for fixed cyles. Is the word "fixed" mandatory in the option or does it only requires a number ?
- when booting DOSBox, intro "Welcome to xxx" is missing the first letter when using French : it displays "ienvenue" instead of "Bienvenue". Can't see why.

So now the last .txt UTF-8 file
[fr-0.77.0-alpha.txt](https://github.com/dosbox-staging/dosbox-staging/files/5728747/fr-0.77.0-alpha.txt)

**Comment by dreamer** [comment]
French punctuation rules require a space before ":" - today I learned :)

I made a correction to fix "Bienvenue" (the preceding ANSI escape code was not delimited) and few whitespace issues. I noticed few more, but most of them require a fix in code rather than in translation - I'll look into that.

`fixed` is a keyword, that is non-mandatory - it can be ommitted and only number used.

I hope during 0.77.0 development cycle we'll make extensive help messages for few more built-in commands (we track this work here: #729). When new changes will land in translation, I'll leave a comment in here :)

**Comment by Draky50110** [comment]
Thanks for fixing spaces and setting shorter sentences.

So here is the "final" version, with "fixed" word... fixed in translations.
[fr-0.77.0-alpha.txt](https://github.com/dosbox-staging/dosbox-staging/files/5730530/fr-0.77.0-alpha.txt)

**Comment by dreamer** [comment]
Upstream merged a patch from 2014 in SVN trunk; the change introduced some changes to translations. I updated the english file in master branch. Changes: 4f9ac9fa1b16bb183402aa7d750750dafcfd04b7

**Comment by Draky50110** [comment]
Done, sorry for the delay.
[fr-0.77.0-alpha.txt](https://github.com/dosbox-staging/dosbox-staging/files/5933448/fr-0.77.0-alpha.txt)

**Comment by dreamer** [comment]
@Draky50110 not a problem at all :) we're still somewhat far away from the release.

I totally forgot to mention another two changes to translation strings:

- Removed `PROGRAM_MOUNT_STATUS_FORMAT` - it is now generated automatically - it should've never existed in the first place, it was impossible for translators to handle this correctly; this string was causing a bug when user changed DOS console mode to e.g. 132x50.
- Added two new translation strings (they are being shown as errors for `mount -z <drive>` command): 12d4116593290556d6f2650dfdd498c9b948b744

**Comment by Draky50110** [comment]
Ok, added two strings and removed one :)
[fr-0.77.0-alpha.txt](https://github.com/dosbox-staging/dosbox-staging/files/5936482/fr-0.77.0-alpha.txt)

**Comment by dreamer** [comment]
Thanks to @Wengier we now have `ver` command updated to the new help style - it's ready for translation :)

Change: 9a379a552adc79436bbf4ef6f76ee82b60ae469e

Here's how it looks in English:

![2021-02-10-125846_700x575_scrot](https://user-images.githubusercontent.com/3967/107512260-db204380-6ba6-11eb-8f79-37a2923ce3f6.png)

**Comment by dreamer** [comment]
Closing if favour of #884

**Comment by Draky50110** [comment]
Just to point : ver command translated (and correctly wraped)
