### ISSUE TITLE
MT32 messages from the device displayed while playing

### ISSUE THREAD

**Issue by mikesk8** [dosbox-staging/dosbox-staging#794]
I have seen you are planing to integrate MT32 emulation. 

Are you also planning to add possibility to display messages from the device while playing? There were some few funny messages appearing on physical MT32 LCD display especially while playing Sierra games. Are you planning to add the option to display those back on the computer screen while playing the game with MT32 emulation on? 

Thanks,
Michael

**Comment by dreamer** [comment]
At this point these messages are only written to log / stdout.

Option to display them in GUI overlay would quite cool and very welcome considering this is part of the game :) Unfortunately, we don't have good system for displaying overlay messages yet - with each release I am gradually cleaning up and simplifying graphics pipeline so we could eventually add this feature without introducing ugly hacks.

Related to #447 #315 #274

**Comment by johnnovak** [comment]
I'm also interested in making this happen -- alongside with in-game volume controls operated by hotkeys that should given an indication of the current value in a HUD, just like on a TV, for example.

**Comment by kcgen** [comment]
> I'm also interested in making this happen -- alongside with in-game volume controls operated by hotkeys that should given an indication of the current value in a HUD, just like on a TV, for example.

I like the sounds of that!

Came across this little font cacher for Sdl2 ; might be handy: https://github.com/grimfang4/SDL_FontCache

**Comment by johnnovak** [comment]
I've been thinking about this a bit this morning, and I was actually thinking of introducing [NanoVG](https://github.com/memononen/nanovg) into the project. It's basically a 2D vector-graphics library, a loose HTML5 canvas implementation, actually quite similar to Cairo.

I've been using it with great success in some desktop app of mine I'm working on, and I know people are using it successfully in many mobile apps as it has good OpenGL ES support, and there have been a lot of optimisation efforts to make it performant on mobile devices.

_"Currently there is an OpenGL back-end for NanoVG: [nanovg_gl.h](https://github.com/memononen/nanovg/blob/master/src/nanovg_gl.h) for OpenGL 2.0, OpenGL ES 2.0, OpenGL 3.2 core profile and OpenGL ES 3. The implementation can be chosen using a define as in above example. See the header file and examples for further info."_

The state-of-the-art free & open-source modular synth environment [VCV Rack](https://vcvrack.com/) also uses it for all its rendering. If it's good enough for that, it will be surely good enough for DOSBox.

It has support for high-quality antialiased text via freetype, and of course it maintains its own glyph cache. It's very simple to make it render to an FBO, I'm using that in my own app for all sort of things, then composite the result into the framebuffer.

So the rendering loop I have in mind would be like this (pretty standard for all modern games to use this deferred rendering approach):

- Render standard graphics card output into a texture (currently happening)
- Render HUD overlay into a texture **(new)**
- Write standard graphics output into the framebuffer (currently happening)
- Write HUD overlay into the framebuffer with alpha-blending **(new)**

And that's it! Technically that won't be very difficult, I think the most complicated part will be to design a nice API to make the whole HUD overlay thing flexible and extensible enough for all kinds of future uses.

But this would only work on OpenGL backends; frankly, I don't really care about the legacy backends much, probably they should be eventually removed... The nice thing about introducing such a 2D drawing library is that you can draw all sorts of shapes as well (rounded rectangles, circles, Bezier paths, etc.), which will be very handy for drawing simple overlay UIs/HUDs. We'll eventually need such drawing ability, and even for the simple text overlays I proposed, I'd like to draw the text on top of a nice rounded rectangle with some opacity.

One complication would be the VFR mode. But I guess VFR could do the rendering at whatever pace, then the overlay rendering could always happen at least at 30 FPS or something (e.g. when you set the volume, the overlay text displays, then gradually fades away after a second or two; for that you need constant frame updates at min. 30 FPS or something).

**Comment by shermp** [comment]
I think someone (can't remember who, was it @kklobe ?) was also thinking of implementing ImGUI to provide some GUI control to dosbox-staging, maybe something to think about?

**Comment by johnnovak** [comment]
I personally think that while ImGUI is useful for technical debug UIs and stuff like that, it's what-you-see-is-what-you-get, pretty much. It doesn't support themes or anything, everything is hardcoded. So I don't think it's fit for purpose for what we want to do. 

If the endgoals is to support nice HUDs like on a TV and some simple console-like overlay UI perhaps so the user can change a few parameters or remap keys, etc (via a controller, preferably), ImGUI is simply not fit for purpose. You can't  change it's appearance easily, for a start, and the behaviour of all widgets is fixed and it's really meant as a "coder's debug UI". For that purpose, it's great; for any other purpose, I wouldn't even consider it.

Yes, ReShade uses it, but that's a bad example because that's not really a "HUD"; it's just a clever way to give access to shader parameters in a very barebones (and quite ugly looking) UI.

**Comment by Burrito78** [comment]
The macOS DOSBox app Boxer had a beautiful way of displaying MT-32 messages.

![Bildschirmfoto 2022-05-10 um 15 29 19](https://user-images.githubusercontent.com/61995128/167641470-9bc232f9-b22e-427e-9317-a1e1d031f21c.png)

http://blog.boxerapp.com/2011/10/31/the-hills-are-alive-with-the-sound-of-music/

**Comment by GranMinigun** [comment]
ImGUI supports theming. But yes, some prettier alternative is quite welcome, at least for consideration. Just remember that Staging has SDL renderer backend, not just (optional!) OpenGL, and someday someone will definitely bring Vulkan as well.

Related: #315, #447, #997.

**Comment by LowLevelMahn** [comment]
> I've been thinking about this a bit this morning, and I was actually thinking of introducing [NanoVG](https://github.com/memononen/nanovg) into the project. It

from the github page: This project is not actively maintained.

and i personally think that ImGUI is the better choice here - there is a SDL2, OpenGL etc. backend for it and
the immediate mode style will help to keep also the debugger responsive if we ever start to port the debugger

**Comment by johnnovak** [comment]
Thanks for you comments guys. I think this is an important decision, the pros of cons of various approaches should be examined carefully, and you've brought up some interesting points to think about. As I'm particularly interested in this topic, I intend to write up a proposal in the coming weeks, addressing the points you mentioned as well.

I'm hoping you will join in discussing my proposal, and that we'll come up with a plan in the end that's forward-looking and satisfies all criteria we think is important for Staging! 😄

**Comment by johnnovak** [comment]
I'm not in favour of using system notifications for this purpose. In the case of Munt it's actually a good solution because usually you're using it in conjunction with an emulator. So for Munt (a separate process) to display these messages while you're playing a game fullscreen, notifications are pretty much the only viable way.

Whereas in DOSBox with Munt integrated, we have a lot more flexibility and much better options at our disposal that could look a lot prettier. Equally important, we wouldn't be dependent on notification settings perhaps configured at the system level, and could offer a unified experience across the supported platforms.

What I envision is integrating resolution-independent, vector-based OSD functionality into DOSBox which would enable us to implement cool OSD stuff like the Munt messages, and also sleek console/set-top-box style on-screen menus with transparency and whatnot.

I have the proposal in my head just need some time to type it out, and now I'm busy with the audio enhancements stuff 😄  In any case, I've made some mockups already; this is one for the MT-32 messages:

![insert-buckazoid](https://user-images.githubusercontent.com/698770/175181772-2a0f51dc-f4b0-4024-b284-265f8e688f41.png)

Like I said, this would be vector-based, so any resolution or window size could be supported very easily. Here's a zoomed version; it's just a few rectangles, a vertical gradient overlay, and some simple blur. All these are supported in GPU accelerated canvas-like vector graphics libraries (Skia, NanoVG, bgfx, etc.)

![insert-buckazoid-large](https://user-images.githubusercontent.com/698770/175180759-01f63445-0507-4db4-ae3e-78c07dc191e5.png)

**Comment by kcgen** [comment]
That mock up sure is easy on the eyes, @johnnovak!

**Comment by Burrito78** [comment]
It looks EVEN BETTER than the Boxer App example above! Thanks for the mokup, @johnnovak!

**Comment by johnnovak** [comment]
See main discussion & plans about the OSD feature here:
https://github.com/dosbox-staging/dosbox-staging/discussions/1953

**Comment by Burrito78** [comment]
Continued in #447 .
