### ISSUE TITLE
FluidSynth: Add more parameters inside of the config file

### ISSUE THREAD

**Issue by fbaier** [dosbox-staging/dosbox-staging#843]
Hello Dosbox-Staging team,
I would like to add the idea of more parameters at the [fluidsynth] part inside the configuration file.
Like ScummVM, I just think that the major features should be add inside the configuration.

Basic:
soundfont = /path/to/the/sf2/file
midi-bank-select = gm (gs is default)
sample-rate = 44100
midi-channels = 16 (default)
gain = 20 (default)
interpolation = 4th (default)

Reverb:
reverb.active = 1 (default)
reverb.room-size = 20 (default)
reverb.width = 1 (default)
reverb.damp = 0 (default)
reverb.level = 90 (default)

Chorus:
chorus.active = 1 (default)
chorus.nr = 3 (default)
chorus.level = 20 (default)
chorus.speed = 30 (default)
chorus.depth = 80 (default)

Source: 
https://www.fluidsynth.org/api/fluidsettings.xml
https://github.com/scummvm/scummvm/blob/master/audio/softsynth/fluidsynth.cpp

**Comment by dreamer** [comment]
@fbaier Thank you for creating the issue - let's investigate these settings one-by-one to learn which ones will be beneficial. Some of them were included in original version of FluidSynth patch and we *removed them* for various reasons (usually one of 3 reasons: setting might be harmful / unnecessary / nobody asked for it). With this issue I think we get rid of 3rd reason :)

### soundfont
`soundfont = /path/to/the/sf2/file` - implemented already, as well as simply "file.sf2" which will be looked up in default locations where soundfonts are stored. Also, relative paths (for storing soundfonts with the game and ~ expansion works as well) :)

### midi-bank-select
`midi-bank-select = gm (gs is default)` - uh, this might be a bug in DOSBox Staging… I think this option was not there last time I looked at available FluidSynth settings? I presume it should be GM (only, without option for change). I don't know any DOS games using GS (if we have confirmation about any single game expecting MIDI GS then we'll need to make this an option of course). So, do we know any game expecting GS? Perhaps I am wrong in my assumption that all DOS software expected GM from MIDI hardware available at the time? Or is it a soundfont-related setting?

Someone who knows MIDI standard better than me needs to answer these questions :)

### sample-rate
`sample-rate = 44100` - this value is tied to DOSBox Staging internal mixer sample rate to avoid accidental resampling of music output. So you'll need to change `rate` in section `[mixer]`. However, I don't think this is advisable - keep it at 44.1kHz or up to 48kHz. ATM I don't think there's any reason to expose this setting to users.

### midi-channels
`midi-channels = 16 (default)`

I will quote the FluidSynth documentation here:

> The MIDI standard defines 16 channels, so MIDI hardware is limited to this number. Internally FluidSynth can use more channels which can be mapped to different MIDI sources.

Based on this description, I think this option is irrelevant to DOSBox Staging. We have a single MIDI source, always.

### gain
`gain = 20 (default)`
Implemented already - it's a soundfont-specific option (because different sf2 files will require different gain value). Described in https://dosbox-staging.github.io/v0-76-0/#2-3-add-built-in-midi-support-via-fluidsynth (and in .conf file). You can write:

```ini
soundfont = timbres_of_heaven.sf2 20
```
Perhaps we need to describe it better in the documentation? :)

### interpolation
`interpolation = 4th (default)`

DOSBox Staging uses "7th" (highest quality available via FluidSynth 2.x). This is a technical detail and I see no reason for exposing this option to end-users.

### Reverb
DOSBox Staging uses following values here - we use different values than FluidSynth lib defaults (based on ScummVM defaults IIRC):
```
           FS default | DOSBox Staging value
reverb.active =     1 | 1
reverb.room-size = 20 | 0.61
reverb.width =      1 | 0.76
reverb.damp =       0 | 0.23
reverb.level =     90 | 0.56
```

### Chorus
Same story with Chorus; we picked different defaults, less relevant to music creation and more for DOS game music playback:
```
           FS default | DOSBox Staging value
chorus.active =     1 | 1
chorus.nr =         3 | 3
chorus.level =     20 | 1.2
chorus.speed =     30 | 0.3
chorus.depth =     80 | 8.0
```

Do we really need to expose reverb and chorus options to the users? Are they more relevant per-game or per-soundfont?

**Comment by kcgen** [comment]
I agree with all of your assessments @dreamer.

FluidSynth and QSynth use their own scaled-up value ranges versus the actual value fed into libFluidSynth.  So for example, we see room size of 20 here:

![qsynth](https://user-images.githubusercontent.com/1557255/106053144-4e05c680-609f-11eb-921f-68b722c7a100.png)

However rhe value accepted by libFluidSynth is 0.0 to 1.0; therefore QSynth divides the knob value by 100 and passes 0.2 into libFluidSynth.  

This 'knob-val divided by knob-max' is often how all these "defaults" map into libFluidSynth, which is why our (DOSBox Staging) values appear small in comparison.. but we're actually making extensive use of these effects.

The value ranges accepted by libFluidSynth are:

``` text
Parameters
synth	FluidSynth instance
roomsize	Reverb room size value (0.0-1.0)
damping	Reverb damping value (0.0-1.0)
width	Reverb width value (0.0-100.0)
level	Reverb level value (0.0-1.0)
```
(And roughly the same for Chorus). 

The values we're using do make use of both effects without negative or runaway behavior, and were extensively tuned by the scummVM team and tested (without complaint) by their user-base over several years.  

On scrolling through our conf file, I'm already uneasy with its size. I also think our midi sounds pretty darn good (thanks to the scummVM team!) Compared to when I previously ran timidity externally, so these two "forces" conspire to leave them as such.  

If someone wanted to embark on finding even better defaults, then we could expose some settings to help them explore this. But the evidence to change would need a vote by users, and we could also have a shoot-out w/ the scummVM community. Ultimately, everyone could benefit from this undertaking.

**Comment by kcgen** [comment]
ScummVM default values are set by their GUI here:
https://github.com/scummvm/scummvm/blob/5b0938b0a7e39145baad79a2b75c99c4d75d385b/gui/fluidsynth-dialog.cpp#L63

And then divided down to ratios and applied to libFluidSynth here:

https://github.com/scummvm/scummvm/blob/5b0938b0a7e39145baad79a2b75c99c4d75d385b/audio/softsynth/fluidsynth.cpp#L200

And the setting we used came from:

https://github.com/scummvm/scummvm/pull/1858

https://forums.scummvm.org/viewtopic.php?t=11632

**Comment by kcgen** [comment]
Latest sources support adjusting chorus and reverb. 
Grab the latest build (0.78-alpha), and run `config -wc` inside the DOS prompt to update your config file.
