### ISSUE TITLE
Git master can't save mapper file (bisected)

### ISSUE THREAD

**Issue by BPaden** [dosbox-staging/dosbox-staging#873]
**Describe the bug**
Trying to save a mapper file results in the error message: `MAPPER: Can't open  for saving the key bindings`

**To Reproduce**
I've tested this with an empty config. Open up the mapper, make a change and click save.

**Environment (please complete the following information):**
Arch Linux

**Version of dosbox-staging:**

`v0.77.0-alpha-334-g77862ab8`

**Configuration parameters:**
Confirmed with the default/empty config file and no existing mapper.

**Additional context**
Git bisect points to b0ef7b34adcb5e104be39fae04482b62c8b5242d introducing this issue. Reverting the commit seems to resolve the issue.

**Comment by kcgen** [comment]
Thanks for finding and bisecting this @BPaden!

The changes was put in to address[ this assert crash on Windows](https://github.com/dosbox-staging/dosbox-staging/issues/852), assuming a debug build, on a clean-slate launch (ie: no initial config file yet).

In theory the PR does the same thing, but was able to protect against the assert.  That said, it's now (somehow) negatively impacting saving.

@dreamer - do you see how the oiriginal vs. prior implementations are functionally different?

@BPaden , just to double check, is this on Linux or Windows?

**Comment by BPaden** [comment]
I originally tested on Linux, but looks like it effects both.

**Comment by dreamer** [comment]
@BPaden Thank you so much for report and bisect!

Uhhh, ok - I think I figured out what's happening…

My **hypothesis** is: this code was buggy for some time and was working only due to a coincidence…

- in `sdlmain.cpp:2834` we have `sdl_sec->AddInitFunction(&MAPPER_StartUp);`
- when some function calls `ExecuteInit` to iterate over `initfunctions` and call `MAPPER_Startup`, we are at the same time adding new functions to `initfunctions` - because `MAPPER_Startup` calls `section->AddInitFunction(&MAPPER_ConfigureBindings, true);`. So our iterator is probably invalidated and we are in UB behaviour from this point forward.
- Function `MAPPER_ConfigureBindings` is the one that's actually setting the name of mapper file to be used. Due to invalidated iterator, the function object wrapping this function is either overwritten or removed immediately (or leaks, or whatever tricks caused by [nasal demons](http://www.catb.org/jargon/html/N/nasal-demons.html)) - either way it's missing from the `initfunctions` container. It's not called, so mapper file name stays in default (empty string), hence message: `MAPPER: Can't open<space><empty string><space>for saving the key bindings`.

I am only ~70% certain that this is indeed caused by iterator invalidation - maybe the root cause is different. Reverting the commit might cause a different bug - UB can be manifesting in a different way (Windows STL throws assert message at us for a reason).

*Now my side-rambling. This is why I hate C++. In Rust it's impossible to have iterator invalidation in safe code - a bug like this would be caught at **compilation time**. In C++ we have this facade of STL containers that **pretend** to be safe, when in fact they are not that much safer than using plain C.*

I need to investigate more on how to fix this, but not today… @kcgen additional ideas and investigations will be very welcome.

**Comment by kcgen** [comment]
Tentative fix inbound on [`kc/get-mapperfile-fix-1`](https://github.com/dosbox-staging/dosbox-staging/tree/kc/get-mapperfile-fix-1).

@BPaden , when you have a chance can you give it a go? 

I'm unsure of all the ways to exercise the mapper - but I do know we can `ctrl+F1`, `dosbox -startmapper`, and we can also trigger a (reload?) via command-line `config -set ... `. Hopefully you can put all of these through the paces :running_man:

**Comment by BPaden** [comment]
I left a comment on the commit about a build error. Otherwise it does seem to fix the issue. I tried with both ctrl+f1 and dosbox -startmapper. Running `config -set mapperfile` to change the mapperfile at runtime worked as well.

**Comment by kcgen** [comment]
Thanks for the testing @BPaden 👍
You got the adjustment right as well (sdl_sec). 
Will update and put this forward for PR.
