### ISSUE TITLE
Segmentation fault when pcspeaker is disabled while its dos-application (SafeEyes.com) is in use.

### ISSUE THREAD

**Issue by IlyaIndigo** [dosbox-staging/dosbox-staging#876]
**Describe the bug**
I have a dos application Safe Eyes http://old-dos.ru/files/file_1662.html.
I run it with renderer and sound (pcspeaker) disabled.
dosbox-staging -exit -c 'config -set render scaler=none' -c 'config -set speaker pcspeaker=false' SafeEyes.com
And in most cases, when you get to the point in the program where pcspeaker makes a nasty squeak, the application ends with a segmentation error.
But not always! Sometimes it keeps working.
This is definitely affected by the "pcspeaker=false" option and it always happens at the moment when the sound should be played.
When pcspeaker=true the sound plays, it is kind of hoarse compared to dosbox 0.74-3 but the application continues to work.
In dosbox 0.74-3 it always works as expected without crashing.
I have attached the config and different stdout.

**To Reproduce**
1 Preferably use my config.
2 Download the program from http://old-dos.ru/dl.php?id=17094 or from the attachment.
3 In the config pcspeaker=true.
4 Run dosbox-staging -exit -c 'config -set render scaler=none' -c 'config -set speaker pcspeaker=false' SafeEyes.com
5 Press the down key, select the 2nd item 'Полный тренинг', press Enter, then press the down key 2 times to start the training.

**Expected behaviour**
The training should start on the blue square with no sound at the beginning.

**Environment (please complete the following information):**
- OS and version openSUSE Tumbleweed
- Relevant hardware info: Notebook HP Pavilion DV6 with intel i3 M380 and intel HD Graphics. 

**Version of dosbox-staging:**
0.76.0
[bad.log](https://github.com/dosbox-staging/dosbox-staging/files/5964096/bad.log)
[dosbox-0.74.3-good.log](https://github.com/dosbox-staging/dosbox-staging/files/5964097/dosbox-0.74.3-good.log)
[good.log](https://github.com/dosbox-staging/dosbox-staging/files/5964098/good.log)
[pcspeaker-true-good.log](https://github.com/dosbox-staging/dosbox-staging/files/5964099/pcspeaker-true-good.log)
[SafeEyes.com.zip](https://github.com/dosbox-staging/dosbox-staging/files/5964100/SafeEyes.com.zip)
[dosbox-staging.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5964125/dosbox-staging.conf.txt)

**Comment by kcgen** [comment]
Interesting program @IlyaIndigo! (maybe I will start using it :eyes: )

The cause of the crash is due to a read of an uninitialized leading channel pointer in the Disney sound-source. On entry into the training session, the program writes a control value to the Disney's IO port that in turn enables the mixer callback prior to the Disney performing it's analysis (when it would normally set the leading channel pointer). 

---

The problem of visual fatigue and diseases associated with it among personnel working on VDT ​​was officially confirmed in the report of the Working Group of Experts of the World Health Organization "VDT and user health" (Geneva, 1989). We propose a software tool developed by us for relieving visual fatigue in persons employed in VDT. The methodology is based on the discovery of the English neurophysiologist F. Campbell (Campbell.F) to improve visual functions when showing certain geometric images. There are specialized devices that use the Campbell effect for therapeutic purposes in a clinical setting.

The developed software tool contains know-how and includes:
- display of certain dynamic graphic images based on the Campbell effect;
- feedback "user (patient) - computer" in the process of treatment;
- test tasks for the user (patient) evaluating the therapeutic effect.

The duration of the procedure is 8 - 10 minutes.

The systematic use of the software during breaks and (or) at the end of work allows to increase the efficiency of personnel and to prevent eye diseases that occur during constant work at the VDT. This program has no analogues and is offered for inclusion in the basic software package for each of the computers supplied by DEC. 

The program works in DOS or Windows environment. If necessary, it can be easily adapted for another operating environment and requires a processor not higher than I486 and an SVGA video monitor with a resolution of at least 600x800 pixels. A high level of sales is likely, with a relatively low cost of the program. The presence of such a program in the basic set of software will increase the level of sales of computers, as it will provide greater comfort in work, reduce fatigue and preserve the health of the staff for a long time.

**Comment by kcgen** [comment]
@IlyaIndigo, 
 -  Can you try building the `kc/fix-safeeyes-1` branch?
 - Or using the Linux release binary currently built here: https://github.com/dosbox-staging/dosbox-staging/actions/runs/557624371

**Comment by dreamer** [comment]
@IlyaIndigo Issue got closed automatically with the PR - please confirm if it works on your side as well though (on master) - if it doesn't we'll re-open this issue. Thanks!

**Comment by kcgen** [comment]
@IlyaIndigo , regarding the audio, for clean-sounding "tones" like those produced in this safeeyes, crank up your `pcrate = 48000` to match that of your `[mixer] rate = `.  It's not as realistic sounds for games that play music and such, but it works good for mono-tones.

**Comment by IlyaIndigo** [comment]
@kcgen Sorry, I only got a chance to check and write now.
I am glad that the problem was reproduced and fixed so quickly, I was afraid that there would be problems with reproduction.
Now 10 out of 10 runs are stable. :-)
Also glad that you liked the program. It's the only non game DOS program I haven't found.
I would be glad to get a patch for the stable version.

Another problem is that when sound is not turned off, it sounds slower and sounds hoarse compared to dosbox. This may be due to the lowered frequency in the default config.

Translated with www.DeepL.com/Translator (free version)

**Comment by IlyaIndigo** [comment]
I remembered a game that works only with pcspeaker - ChipDale and checked it, the difference between the default setting and 48000 is not very noticeable, although I thought it would be more noticeable than on SafeEyes, but subjectively it sounds at 48000 more pleasant.
I think lowering the default for pcrate is not a good idea.

**Comment by IlyaIndigo** [comment]
@kcgen My patch is correct?
https://build.opensuse.org/package/view_file/home:13ilya/dosbox-staging/dosbox-staging-0.76.0-disney.patch?expand=1

**Comment by kcgen** [comment]
> Now 10 out of 10 runs are stable. :-)

@IlyaIndigo , thanks you for confirming all is well.

Regarding the patch:
> I would be glad to get a patch for the stable version
> @kcgen My patch is correct?

Yes, your patch[ matches the backport pull request](https://github.com/dosbox-staging/dosbox-staging/pull/879) in progress for the next 0.76 fix release.

> I remembered a game that works only with pcspeaker - ChipDale and checked it, the difference between the default setting and 48000 is not very noticeable, although I thought it would be more noticeable than on SafeEyes, but subjectively it sounds at 48000 more pleasant.

The justification for the PC speaker's ~18 KHz playback rate is that it matches the original PC speaker's output frequency and also acts like a low-pass filter.  You can hear some samples here and see some visuals: 

 - https://github.com/dosbox-staging/dosbox-staging/pull/413

And a couple other visuals of another notable PC Speaker change:

 - https://github.com/dosbox-staging/dosbox-staging/pull/482

The trouble is we have overlapping sampling rates: the speaker is producing 18939 samples per second, which is up-sampled in DOSBox's mixer (typically to 44,100 samples per second) and passed to SDL2, whose output is typically up-sampled to 48000 samples per second in the audio driver or physical audio chip. 

Overlapping and differing sampling rates can cause harmonics, new tones either at higher or lower volumes depending how they accumulate, for some frequencies - exactly as you've experienced for SafeEyes.

An even better solution would be to run the PC speaker at exactly our mixer's negotiated rate to eliminate risk of harmonics (which is what you're now doing with `pcrate = 48000`), and additionally apply a low-pass filter to the PC speakers samples.  This would provide the best of both worlds. I'll add it as an enhancement request!

**Comment by IlyaIndigo** [comment]
Thank you! :-)

If you know about rumhacking and how DOS applications work, could you help me some more?
In SafeEyes there is a choice of background colors, and the default is blue (0), but I would like green (1).
Selecting a color creates a SOFTVISN.CNF file with a number from 0 to 5 that corresponds to the selected color.
If there is no file, it just defaults to 0(blue).

I hex-edited. found the code to load the file, but make the default green(1) I failed.

It may even be easier to swap the colors, so that the green is first (0), followed by blue.

**Comment by kcgen** [comment]
> If you know about romhacking and how DOS applications work, could you help me some more?

Unfortunately I'm just a simple high-level programmer :sweat_smile: 

The vogons forums are visited by many talented folks in this regard, and perhaps your question there would pique one of their interests enough to help! Best regards in finding a solution. :+1:

**Comment by IlyaIndigo** [comment]
That's okay, thank you very much for your help anyway!
