### ISSUE TITLE
De-duplicate hardcoded version strings

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#891]
**The problem**

Right now, by my counting, we have **9** places in code where version string is hardcoded. This causes friction for certain tasks - also for me, as I need to remember about updating all of them during every release.

Meson migration #854 allows us to start cleaning up this mess :) In #890 first two hardcoded versions are being removed (both in CI). As for other strings:

https://github.com/dosbox-staging/dosbox-staging/pull/890#issuecomment-778864800
> - `README` - I consider it not in scope of Meson migration (but to be resolved)
> - `src/platform/visualc/config.h` - definitely in scope of Meson migration part 2 (VS replacement)
> - `src/winres.rc` - in scope of Meson migration part 2
> - `.github/workflows/macos.yml` - in scope of Meson migration part 1
> - `contrib/macos/create-app-bundle.sh` - in scope of Meson migration part 1
> - `contrib/fedora/dosbox-staging.spec` - not in scope of Meson migration, BUT it's a task for me later, as a Fedora packager - I will probably do it while writing PACKAGING.md file
> - `contrib/linux/dosbox-staging.metainfo.xml` - in the scope of Meson migration, but I need to discuss it with FlatHub maintainers (probably in flathub/io.github.dosbox-staging#2) - converting this file to be auto-generated will address a serious issue for Flatpak packaging for me. I would strongly prefer it to be a separate task, not part of this PR.
>
> So, before Meson we had 9 places with duplicated version info. This PR takes it down to 7; after removing macOS stuff it will go down to 5, other Meson (part 1) tasks will take it down to 4, after Meson (part 2) migration it will be down to 2, and after revamping documentation (not sure what's the best way to do it yet) we'll finally end up with 1 place :)

This issue is a tracker for removal of this duplication :)

**Comment by Burrito78** [comment]
@kcgen update on this plz.

**Comment by kcgen** [comment]
I made some progress de-duping metadata (one example:   42ad1026cf8f11c6c2b4e83ad060cf832e28771d)

during reviews, we would also be unlikely to allow more duplication of metadata to proliferate.

Something like Jinja2 would let us hold a YAML of the project's metadata (once and for all), and then let it populate tags in all the files that need it..  but this approach (or something like Jinja) is another layer to understand and maintain - and I don't think our templating problem is "big enough" to warrant that yet.

I'll tentatively close this, because I was the last one to work on it.
