### ISSUE TITLE
"Critical error" in Chessmaster 3000

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#902]
*This is an unconfirmed report.*

User complained about inability to run Chessmaster 3000, but went silent when asked to create a bug report, so the details are sparse…

> (…) it launches and exits after a few seconds with a "Critical Error! Hardware configuration has changed, please reinstall." message.
>
> Plain DosBox runs the same installation with no issue.
(…)
> Just tried DOSBox Staging as per your suggestion. The same thing happens. It crashes after a few seconds while on DOSBox 0.74-3 it runs flawlessly.

If someone has a moment, please investigate. I would say it's somewhat probable that this is a regression on SVN trunk.

**Comment by kcgen** [comment]
Also confirmed SVN is affected.

I can't remember which games did it, but I've seen some games record "the state of the system" in a config file at the time of installation -- and that "state" literally can change with different builds of DOSBox.

To test this (just with SVN), we would need the installer files (or disk images). Right now I can only find post-installed files though.

**Comment by nemo93** [comment]
I've tested with 2 different versions of this game. 

* One is the original disks with installer => after properly installing and configuring the game it will crash as stated above (Critical Error!) after just a few seconds. 
* Second is just a backup of game files found online. Please note it's exactly the **v1.02a** of the game. In that case, game works flawless.

The "working" version does contain more files than the one with installer. Please see screenshot below (total 57 files).
![chess3k](https://user-images.githubusercontent.com/8100500/108634951-a6e93480-747c-11eb-9a45-9a17b2e1ea2e.png)

Setup options are being saved in file named `CONFIG.CM`. For the record I'm copy/pasting the contents of the 2 versions hereafter.
* Non-working version
```
VIDEO=EGA
SOUND=sblaster.com
PRINTER=NONE
MEDIA=4
DRIVES=CC
HASH=8
ANALYSIS=48456
```

* Working version (note: sound can still be heard even if set to NONE)
```
VIDEO=EGA
SOUND=NONE
PRINTER=IBM
MEDIA=4
DRIVES=CC
HASH=8
ANALYSIS=19751
```

I haven't tried to move the `CONFIG.CM` of the working version with the non-working one. My mistake.

**Comment by kcgen** [comment]
Great find @nemo93 !
I'm glad the issue appears to be game-side, and not DOSBox (SVN/Staging/.. )-side.

I wonder if the game is  computing some kind of hash in the `analysis`, and comparing that to the one in `config.cm`?

**Comment by nemo93** [comment]
That's my reasoning as well of some hash being computed at some point. Yet I'd have expected the outcome to be different than the above. Where the post-installed files version wouldn't work if the hash was calculated based on some hardware or mem value for instance. I'm puzzled. 

What's weird too is that you get a small info screen at the end of install process stating something like "it's ok to copy the installed files to another computer but the disks can't (eg. with DISKCOPY) due to some special formatting and compression formats". There's nothing interesting in the manual of the game and I couldn't find anything useful online.

For the record, there is a similar thread with same issue on [Vogons](https://www.vogons.org/viewtopic.php?t=29689). Solution is the same as above: to find the version that works.

**Comment by nemo93** [comment]
@dreamer @kcgen 
I've created an [entry ](https://github.com/dosbox-staging/dosbox-staging/wiki/Games-issues#chessmaster-3000) into the wiki and thus recommend this ticket to be closed off.
