### ISSUE TITLE
OpenGLES support for shaders

### ISSUE THREAD

**Issue by SupervisedThinking** [dosbox-staging/dosbox-staging#926]
**Describe the solution you'd like**
Since DOSBox always nags about `CONFIG: Unknown option glshader` on my SBCs... how about adopting those patches in a somewhat similar way to add an OpenGLES renderer which allows to use shaders on ARM builds which mostly lack support of the OpenGL API.

https://www.raspberrypi.org/forums/viewtopic.php?t=110957
https://www.vogons.org/viewtopic.php?f=41&t=48303#p500777

The average GPU of SBCs is fast enough to render such stuff & scanlines would add a nice retro touch.

**Comment by dreamer** [comment]
@SupervisedThinking these patches predate SDL2 and OpenGL glshader support, so they won't apply to our code :(

When we started work on importing SDL2 patch, it had OpenGLES bits for Android inside, but IIRC it was broken and unfinished - I removed those OpenGLES bits to speed up SDL2 migration back in the day (SDL2 texture with opengles gives equivalent level of support as those old bits).

OpenGLES will need to be reimplemented (perhaps some code from that patch can be salvaged, but I'm not sure how much - maybe 50%).

**Comment by SupervisedThinking** [comment]
>edit There's https://github.com/aqualung99/dosbox-0.74-ES though - it claims to be SDL2 based, so that's promising, maybe we can salvage work from there.

That's the reason why I've pointed you there & looks like the changes are somewhat "recent":
https://github.com/aqualung99/dosbox-0.74-ES/commits/master?after=fb071dd58b47df3d244462e8fe65f3ef731f3837+34&branch=master

**Comment by GranMinigun** [comment]
Slang and GL ES context are separate things, but yeah, both are on my roadmap.

**Comment by johnnovak** [comment]
Now my view is that we'll target a subset of the intersection of OpenGL ES 3.1 and OpenGL core profile 4.1 in the upcoming reworked OpenGL renderer, so removing the "won't do" and "out of scope" labels to avoid confusion.

**Comment by Grounded0** [comment]
@johnnovak 

What's the minimum OpenGL feature level required to run upcoming 0.83.0? Is it still OpenGL 2.1+ or has that been bumped up?

**Comment by johnnovak** [comment]
> [@johnnovak](https://github.com/johnnovak)
> 
> What's the minimum OpenGL feature level required to run upcoming 0.83.0? Is it still OpenGL 2.1+ or has that been bumped up?

Nothing has been changed yet in that regard, but I'm planning to target OpenGL core profile 3.3 when I'll modernise the OpenGL backend. macOS supports up to core profile 4.1, and Raspberry Pi 4 or later OpenGL ES 3.1 which corresponds to OpenGL core profile 4.3 (those versions introduce compute shaders).

Basically all GPUs on Windows released in the last 10-12 years support core profile 4.6, so macOS is the "bottleneck". That's in quotes because our usage of OpenGL is extremely minimal, so OpenGL core profile 3.3 / OpenGL ES 2.0+ will be sufficient for our needs in practice.

Besides, if one really needs 4.6 functionality, one's better off with DirectX 12 or Vulkan. But that's AAA game territory, not us.

Just created a ticket for the work:

- https://github.com/dosbox-staging/dosbox-staging/issues/4514
