### ISSUE TITLE
ROM packages support

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#939]
A ROM package holds the game's files and metadata inside it.

In order to elegantly support this, DOSBox's existing file IO calls should be wrapped on a 1-to-1 basis, sending them through an IO backend.

The IO backend can then operate on files on the host (as the calls current do), in the writable overlay area, or held in the ROM package.

DOSBox has thousands of IO calls, So this issue tracks the effort of simply wrapping such calls, so when we finalize the ROM package's container and compression format we will be ready to simply drop it into this IO backend.

IO calls also exist inside 3rd party code (such as the audio codecs, MT32, and FluidSynth) that we currently use when we pass those libraries a filename and let them perform IO calls themselves. To avoid those, we will need to use load-from-memory type API calls (allowing us to perform the file read beforehand), or pass them IO callbacks, which some libraries provide, such as the CD-DA codecs.

This issue allows us to discuss details of how we want to go about this.

**Comment by shermp** [comment]
So, I've been thinking about this today, and was thinking one idea might be to take inspiration from how EPUB files are packaged as a conceptual model.

As a background, I'm heavily involved in ebooks, so I'm rather familiar with the basics of EPUB packaging.

The EPUB format is a standard zip archive. There is one standard, uncompressed file stored in `META-INF/container.xml`. This contents of this file specifies the location of the default OPF file, and any additional OPF files (although I've never seen an EPYB in the while that actually *has* multiple OPF files).

The OPF file is a combined ebook metadata, file manifest and (because it matters for ebooks) xhtml file order. Any files not listed in the manifest are ignored. Apart from the mandatory `META-INF/container.xml` file, there is no mandatory file/directory structure.

Obviously, any potential Dosbox format would probably be quite different technically. For example, much more aggressive compression. I notice that ZStandard is now an official compression algorithm allowed in ZIP archives for example. And Dosbox would probably use it's own metadata and manifest formats.
