### ISSUE TITLE
PC speaker performance in macOS

### ISSUE THREAD

**Issue by almeath** [dosbox-staging/dosbox-staging#951]
The PC speaker emulation in standard DOSBox SVN and also DOSBox Staging, blends certain notes in some games, most notably Sierra AGI titles such as King's Quest and King's Quest II. I do not recall ever experiencing that issue with original PC hardware.

I overcame this issue by applying an old patch I found on VOGONS to my own customized SVN build. The details of the patch are here:

https://github.com/almeath/DOSBox-SVN-64-bit-for-macOS/commit/2ca3a60d59b7e7bb05dec29931a52b21f3b3e224

Unfortunately, with the extensive changes to the pcspeaker.cpp, this patch will not apply to DOSBox Staging.

To illustrate the issue, I have linked to two MP3s of the title music sequence in King's Quest, first the "corrected" version from the patch, and then the uncorrected version from DOSBox Staging.

I made sure game settings were suited to an old AGI title and were identical in both the SVN and Staging tests.

**Patched DOSBox SVN 4442:**
https://www.dropbox.com/s/w62q1ylayqhz16v/patched%20svn.mp3?dl=0

**DOSBox Staging 0.76:**
https://www.dropbox.com/s/7tcevklvffww636/staging.mp3?dl=0

Given that the PC speaker emulation was apparently improved in Staging, I am wondering why the changes from the above patch were not introduced? Could they be? Having the notes strangely blend like that kind of ruins the retro experience for me.

I have only labelled this as a bug because I do not know if it is a Mac-specific issue, or expected behavior on all systems.

**Comment by dreamer** [comment]
@almeath Thanks for reporting/working on this! :)

Can you try setting `zero_offset=false` (in `[speaker]` section) - just to confirm this is not the root cause of the problem?

I resolved the conflicts and imported the patch: f6e9ff1c0aa98c7c28d7cf1c4d6d04bedb0f8db6 - you can test it on branch `po/pc-speaker-patch-1` and confirm if it fixes the problem on your side? Was this patch authored by you or was it imported from some Vogons thread? (I would like to know if author explain the reasoning behind the change).

>  I am wondering why the changes from the above patch were not introduced? Could they be?

We are certainly eager to keep improving PC speaker emulation, although not very happy to introduce "exp" mode just to turn on single "if" statement in code (this part of patch will probably be removed). Anyway - as for sound samples you uploaded - can you point me to second where the difference can be heard? I cannot pinpoint it - to me both samples sound the same.

@kcgen The implementation difference is in `PCSPEAKER_SetCounter` function, lines 296, 297:
```C++
        if (spkr.type == 1 && spkr.mode==SPKR_PIT_ON && cntr<10000)
            spkr.pit_index=spkr.pit_max;
```
What do you think about this change?

**Comment by kcgen** [comment]
This change does significantly fix a bunch of effects in games like Keen, Duke Nukem, and adjacent iD software games (and surely others). Comparisons:
https://www.vogons.org/viewtopic.php?f=32&t=29603

ripsaw8080 and others note halfway through the 2nd page that some games suffer regressions (therefore, requiring this patch be configurable).

They suggest the long-term solution is a deeper rewrite to modelling the voltage and speaker position.  That was circa 2011.  

Since then, improving the accuracy of the speaker's waveform has been done by @ripa, and is without compromises (that's why ECE uses ripa's patch and doesn't need a conf toggle). 

Given ripa is reworking the patch into a merge-able state, I believe the best path is to wait for that to happen and use ripa's implementation.

**Comment by almeath** [comment]
Thanks for looking into this. Yes, that is the same thread I found on Vogons. I was going to post some extra sound samples from Space Quest, but it looks like you have already been able to verify the issue in numerous games.

I tested the patched branch you linked to, and it works great as long as I set the PC speaker to "exp". 

I was not aware of further developments in this area - can you point me to the relevant thread on Vogons?

**Comment by kcgen** [comment]
@almeath ; can I suggest we close this?

Not to ignore this work - we certainly do want @ripa's PC speaker audio work; however we're currently tracking it in a project task (as opposed to an issue).

**Comment by almeath** [comment]
Sure, no problem. I can't wait to hear the results ;-)
