### ISSUE TITLE
Is there a gui way to change settings and mount drives?

### ISSUE THREAD

**Issue by Toadfield** [dosbox-staging/dosbox-staging#998]
I don't want to use commands and any other modern emulator supports a gui.

**Comment by kcgen** [comment]
There are front-ends that can help configure many configuration setting common to many DOSBox forks, such as Staging. 

You can also run DOSBox Staging inside RetroPie; we have an extensive wiki page discussing that.  RetroPie acts as the front end, without any command-line actions needed to launch your games.  That said, you do need to pre-configure your games as a one-time activity. 

The wiki also discusses best practices like applying common setting in your main conf file, and then only using a handful of per-game settings.

It's important to understand that the DOS gaming era spanned almost 5 generations of console.. so the DOS games and hardware used in the early 80s differs wildly from the hardware in the late 90s.. so that's why DOSBox needs to be highly configurable.  (Where as a console emulator only has a single hardware profile to emulate).

**Comment by Toadfield** [comment]
Okay,I will try dbgl.

**Comment by kcgen** [comment]
Longer term, @dreamer does have plans for a GUI: https://github.com/dosbox-staging/dosbox-staging/issues/315
